	Title	'TRSDOS 2.3 Backup Utility'
;
;
; TRSDOS OPERATING SYSTEM, VERSION 2.3 - BACKUP UTILITY
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON, 03.01.2022
;
;
; ASCII EQUATES
;
CC	Equ	  3		;CONTROL-C (END-OF-MESSAGE)
LF	Equ	 10		;LINE FEED
CR	Equ	 13		;CARRIAGE RETURN
WI	Equ	 23		;SWITCH WIDE CHARACTERS
HO	Equ	 28		;HOME DISPLAY CURSOR
BL	Equ	 29		;TO LINE START
EE	Equ	 30		;ERASE TO END OF LINE
CE	Equ	 31		;CLEAR TO SCREEN END
CO	Equ	192		;SPACE COMPRESSION (0 TO 63)
;
;
; DEFAULT FLOPPY DISK CONSTANTS
;
NUMDRV	Equ	4		;DRIVES PER SYSTEM
LASDRV	Equ	NUMDRV - 1	;LAST DRIVE NUMBER
NUMTRK	Equ	40		;TRACKS PER DISK
LASTRK	Equ	NUMTRK-1	;LAST TRACK NUMBER
NUMSEC	Equ	10		;SECTORS PER TRACK
LASSEC	Equ	NUMSEC-1	;LAST SECTOR NUMBER
FIRSEC	Equ	0		;FIRST SECTOR NUMBER
DIRECT	Equ	17		;DIRECTORY TRACK
;
;
; DEFINE LAST DISK TRACK IN EIGHT MSB'S OF WORD
;
LASTHI	Equ	LASTRK Shl 8	;DEFINE THE WORD
;
;
; DEFINE LAST DISK TRACK IN MSB AND FIRST SECTOR IN LSB
;
LATFIS	Equ	LASTHI+FIRSEC	;DEFINE THE WORD
;
;
; CONTROL BYTES FOR INITIALIZATION (FORMATTING)
;
FILMRK	Equ	0E5H		;SECTOR FILL BYTE
CRCMRK	Equ	0F7H		;WRITE CRC ADDRESS MARK
LOKMRK	Equ	0F9H		;LOCKED TRACK ADDRESS MARK
DIRMRK	Equ	0FAH		;DIRECTORY ADDRESS MARK
DTAMRK	Equ	0FBH		;DATA ADDRESS MARK
IDXMRK	Equ	0FCH		;INDEX ADDRESS MARK
IDAMRK	Equ	0FEH		;IDENTITY ADDRESS MARK
;
;
; WD1771 FLOPPY DISK CONTROLLER COMMAND CODES
;
WDHOME	Equ	00001011B	;RESTORE TO TRACK ZERO
WDSEEK	Equ	00011011B	;SEEK TO TRACK
WDSTIN	Equ	01011011B	;STEP IN TO TRACK
WDREAD	Equ	10001000B	;READ SECTOR
WDWRIT	Equ	10101000B	;WRITE DATA SECTOR
WDWRID	Equ	10101001B	;WRITE DIRECTORY SECTOR
WDFORC	Equ	11010000B	;FORCE INTERRUPT
WDWTRK	Equ	11110100B	;WRITE TRACK
;
;
; HARDWARE PORT ADDRESSES
;
MDRVRE	Equ	037B6H		;MANGLED DRIVE SELECT REGISTER
DRVREG	Equ	037E1H		;FLOPPY DRIVE SELECT REGISTER
CSTREG	Equ	037ECH		;FLOPPY STATUS/COMMAND REGISTER
TRKREG	Equ	037EDH		;FLOPPY TRACK REGISTER
SCTREG	Equ	037EEH		;FLOPPY SECTOR REGISTER
DTAREG	Equ	037EFH		;FLOPPY DATA REGISTER
KROSEV	Equ	03840H		;KEYBOARD <BREAK> KEY ROW
;
;
; LEVEL II BASIC ROM ROUTINE ADDRESSES
;
VDCHAR	Equ	00033H		;VIDEO DRIVER ENTRY
KBLINE	Equ	00040H		;INPUT AND FILL INPUT BUFFER
DELAYL	Equ	00060H		;DELAY ROUTINE
VIDRVR	Equ	00458H		;ROM VIDEO DISPLAY DRIVER
PRDRVR	Equ	0058DH		;ROM PRINTER DRIVER
;
;
; STORAGE LOCATIONS IN TRSDOS NUCLEUS (SYS0/SYS)
;
CLKMON	Equ	04046H		;MONTH
STACKT	Equ	041FCH		;TOP OF SYSTEM STACK
SYSBUF	Equ	04200H		;BOOT LOADER LOCATION
SYSCON	Equ	0430FH		;SYSTEM CONDITION FLAGS
SCTBUF	Equ	04D00H		;SYSTEM SECTOR BUFFER
;
;
; FUNCTIONS ADDRESSES IN TRSDOS NUCLEUS (SYS0/SYS)
;
ERRENT	Equ	04030H		;ERROR ENTRY
DOPMSG	Equ	04467H		;DISPLAY MESSAGE STRING
GETDTE	Equ	04470H		;GET SYSTEM DATE STRING
;
;
; DEFINE SECTOR SIZE AND FORMATTED TRACK SIZE
;
SCTSIZ	Equ	256		;DISK SECTOR SIZE IN BYTES
SIZTRK	Equ	SCTSIZ*NUMSEC	;SIZE OF A TRACK OF SECTORS
TRKSIZ	Equ	3053		;TRACK SIZE IN BYTES
TRKOSI	Equ	TRKSIZ+124	;MAXIMUM TRACK OVERFLOW SIZE
;
;
; PROGRAM MODULE NAME STRING
;
	Nam	'BACKUP'
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING
;
	Rem	CR
	Rem	'* * * N O T I C E * * *',CR
	Rem	'* PROPRIETARY PROGRAM *',CR
	Rem	'* COPYRIGHT (c) 1979  *',CR
	Rem	'* BY TANDY CORPORATION*',CR
	Rem	'*  FORT WORTH, TEXAS  *',CR
	Rem	'* ALL RIGHTS RESERVED *',CR
	Rem	'* * * N O T I C E * * *',CR
;
;
	Org	05200H
;
BACKUP:	DI			;DISABLE INTERRUPTS
	LD	SP,STACKT	;LOAD TOP OF STACK
	PUSH	HL		;SAVE COMMAND LINE POINTER
	LD	A,(ERRENT)	;BYTE FROM ERROR HANDLER START
	CP	0C7H		;TEST IF 'RST 00H' - BOOT
	JR	Z,BACKCO	;THEN CONTINUE IF IT IS
	LD	A,(SYSCON)	;GET SYSTEM CONDITION FLAGS
	BIT	5,A		;TEST PROGRAM CHAINING ACTIVE
	JR	Z,BACKCO	;CONTINUE IF INACTIVE
	LD	HL,INVDCM	;POINT AT INVALID MESSAGE
	CALL	DOPMSG		;DISPLAY THE MESSAGE STRING
	JP	ERRENT		;THEN ABORT TO DOS ERROR
BACKCO:	LD	HL,SIGNOM	;POINT AT SIGN-ON STRING
	CALL	DOPMSG		;DISPLAY THE MESSAGE
	POP	HL		;RECOVER COMMAND LINE POINTER
	LD	A,(ERRENT)	;BYTE FROM ERROR HANDLER START
	CP	0C7H		;TEST IF 'RST 00H' - BOOT
	JR	Z,PMTSRC	;THEN WE PROMPT FOR DRIVE
	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	':'		;TEST IF DRIVE DELIMITER
	JR	NZ,PMTSRC	;SKIP IF NOT THE DELIMITER
	INC	HL		;ELSE BUMP COMMAND POINTER
	JR	GETSRC		;THEN SKIP DRIVE PROMPT
PMTSRC:	LD	HL,WHICSM	;POINT AT SOURCE DRIVE PROMPT
	CALL	DOPMSG		;DISPLAY PROMPT STRING
	LD	HL,HITBUF-O	;POINT AT INPUT BUFFER
	LD	B,1		;LOAD INPUT LINE LENGTH
	CALL	KBLINE		;READ KEYBOARD LINE
GETSRC:	LD	A,(HL)		;GET DRIVE CODE TO A
	SUB	'0'		;REMOVE ASCII BIAS
	JP	C,PMTSRC	;PROMPT AGAIN IF INVALID
	CP	NUMDRV		;TEST IF DRIVE IN RANGE
	JP	NC,PMTSRC	;PROMPT AGAIN IF INVALID
	INC	HL		;BUMP BUFFER POINTER
	RLCA			;ROTATE THREE
	RLCA			; BITS TO
	RLCA			;  THE LEFT
	OR	11000111B	;MAKE INTO A 'SET' OP-CODE
	LD	(SRCDRB),A	;STORE THE BIT SET VALUE
	XOR	A		;ZERO ACCUMULATOR
	SET	0,A		;SET DRIVE SELECT BIT
;
;
; SOURCE DRIVE SELECT BIT MASK STORAGE
;5256
SRCDRB	Equ	$-1		;DRIVE SELECT CODE
;
;
; STORE SOURCE DRIVE BIT SELECT MASK AND CONTINUE
;
	LD	(SRCCOD),A	;SAVE SOURCE DRIVE CODE
	LD	A,(ERRENT)	;BYTE FROM ERROR HANDLER START
	CP	0C7H		;TEST IF 'RST 00H' - BOOT
	JR	Z,PMTDST	;THEN WE PROMPT FOR DRIVE
GETDSL:	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	INC	HL		;BUMP COMMAND POINTER
	CP	CR		;TEST IF END OF LINE
	JR	Z,PMTDST	;THEN PROMPT FOR DRIVE
	CP	':'		;TEST IF DRIVE DELIMITER
	JR	NZ,GETDSL	;SKIP IF NOT THE DELIMITER
	JR	GETDST		;ELSE SKIP DRIVE PROMPT
PMTDST:	LD	HL,WHICDM	;POINT AT DESTINATION PROMPT
	CALL	DOPMSG		;DISPLAY PROMPT STRING
	LD	HL,HITBUF-O	;POINT AT INPUT BUFFER
	LD	B,1		;LOAD INPUT LINE LENGTH
	CALL	KBLINE		;READ KEYBOARD LINE
GETDST:	LD	A,(HL)		;GET DRIVE CODE TO A
	SUB	'0'		;REMOVE ASCII BIAS
	JP	C,PMTDST	;PROMPT AGAIN IF INVALID
	CP	4		;TEST IF DRIVE IN RANGE
	JP	NC,PMTDST	;PROMPT AGAIN IF INVALID
	RLCA			;ROTATE THREE
	RLCA			; BITS TO
	RLCA			;  THE LEFT
	OR	11000111B	;MAKE INTO A 'SET' OPCODE
	LD	(DSTDRB),A	;STORE THE BIT SET VALUE
	XOR	A		;ZERO ACCUMULATOR
	SET	0,A		;SET DRIVE SELECT BIT
;
;
; DESTINATION DRIVE BIT SELECT MASK STORAGE
;5290
DSTDRB	Equ	$-1		;DRIVE SELECT CODE
;
;
; STORE DESTINATION DRIVE BIT SELECT MASK AND CONTINUE
;
	LD	(DSTCOD),A	;SAVE DESTINATION DRIVE CODE
	LD	A,(ERRENT)	;BYTE FROM ERROR HANDLER START
	CP	0C7H		;TEST IF 'RST 00H' - BOOT
	JR	Z,PMTDTE	;THEN WE PROMPT FOR DATE
	LD	A,(CLKMON)	;GET MONTH NUMBER FROM DOS
	OR	A		;TEST IF NON-ZERO
	JR	Z,PMTDTE	;PROMPT IF MONTH NOT SET
	LD	HL,DTEBUF	;POINT AT DATE STRING BUFFER
	CALL	GETDTE		;GET DATE STRING FROM DOS
	JR	SKIPDA		;THEN SKIP DATE PROMPT
PMTDTE:	LD	HL,BACKDM	;POINT AT BACKUP DATE PROMPT
	CALL	DOPMSG		;DISPLAY PROMPT STRING
	LD	HL,DTEBUF	;POINT AT DATE STRING BUFFER
	LD	B,8		;LOAD MAXIMUM LINE LENGTH
	CALL	KBLINE		;READ A LINE OF INPUT
	LD	A,B		;GET INPUT LINE SIZE
	CP	8		;TEST IF CORRECT LENGTH
	JR	NZ,PMTDTE	;PROMPT AGAIN IF NOT CORRECT
	LD	A,(DTEBUF+2)	;GET DELIMITER TO A
	CP	'/'		;TEST IF CORRECT DELIMITER
	JR	NZ,PMTDTE	;PROMPT AGAIN IF INCORRECT
	LD	A,(DTEBUF+5)	;GET DELIMITER TO A
	CP	'/'		;TEST IF CORRECT DELIMITER
	JR	NZ,PMTDTE	;PROMPT AGAIN IF INCORRECT
SKIPDA:	LD	HL,BACKIT	;POINT AT CODE TO RELOCATE
	LD	DE,SYSBUF	;POINT AT DESTINATION ADDRESS
	LD	BC,LENREL	;LOAD LENGTH OF CODE
	LDIR			;RELOCATE THE CODE
	XOR	A		;ZERO ACCUMULATOR
	LD	(CURDRN-O),A	;ZERO CURRENT DRIVE NUMBER
	LD	A,(SRCCOD-O)	;GET SOURCE DRIVE CODE TO A
	LD	HL,DSTCOD-O	;POINT AT DESTINATION CODE
	SUB	(HL)		;TEST IF SAME DRIVE NUMBER
	LD	(SGLDRV-O),A	;SAVE ONE DRIVE BACKUP FLAG
	CALL	SELSRC-O	;SELECT SOURCE DRIVE
	CALL	HOMHED-O	;HOME DRIVE HEAD TO TRACK ZERO
	LD	A,(CSTREG)	;GET CONTROLLER STATUS TO A
	LD	HL,SDNRDM	;SOURCE NOT READY MESSAGE
	BIT	7,A		;TEST IF DRIVE NOT READY
	JP	NZ,ABORTM-O	;THEN WE ABORT THE BACKUP
	LD	HL,SDNISM	;SOURCE NOT IN SYSTEM
	BIT	2,A		;TEST IF AT TRACK ZERO
	JP	Z,ABORTM-O	;ABORT THE BACKUP IF NOT
	LD	DE,0		;LOAD TRACK AND SECTOR ZERO
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	CALL	RDSECT-O	;READ BOOT SECTOR TO BUFFER
	LD	HL,SRCRDM-O	;SOURCE DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT IF READ ERROR
	LD	A,(BOOTDT-O)	;DIRECTORY TRACK IN BOOT SECTOR
	LD	(DIRTRK-O),A	;SAVE DIRECTORY TRACK NUMBER
	LD	A,(DIRTRK-O)	;LOAD DIRECTORY TRACK TO A
	LD	D,A		;COPY TRACK NUMBER TO A
	LD	E,0		;ZERO SECTOR NUMBER
	LD	BC,GATSEC-O	;POINT AT GAT SECTOR BUFFER
	CALL	RDSECT-O	;READ THE GAT SECTOR
	LD	HL,SRCRDM-O	;SOURCE DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT IF READ ERROR
	CALL	SELDST-O	;SELECT DESTINATION DRIVE
	CALL	HOMHED-O	;HOME DRIVE HEAD TO TRACK ZERO
	LD	A,(CSTREG)	;GET CONTROLLER STATUS TO A
	LD	HL,DDNRDM	;DESTINATION NOT READY MESSAGE
	BIT	7,A		;TEST IF DRIVE NOT READY
	JP	NZ,ABORTM-O	;THEN WE ABORT THE BACKUP
	LD	HL,DDNISM	;DESTINATION NOT IN SYSTEM
	BIT	2,A		;TEST IF AT DRIVE ZERO
	JP	Z,ABORTM-O	;ABORT THE BACKUP IF NOT
	LD	HL,WRPROM-O	;DESTINATION WRITE PROTECTED
	BIT	6,A		;TEST IF WRITE PROTECTED
	JP	NZ,ABORTM-O	;ABORT BACKUP IF IT IS
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	LD	DE,LATFIS	;LAST TRACK FIRST SECTOR
	CALL	RDSECT-O	;READ SECTOR ON LAST TRACK
	JP	NZ,DSTNOF	;SKIP IF READ ERROR
	LD	A,(DIRTRK-O)	;GET DIRECTORY TRACK TO A
	LD	D,A		;COPY TRACK TO D REGISTER
	LD	E,FIRSEC	;GET STARTING SECTOR TO E
	LD	BC,GATBUF-O	;POINT AT GAT SECTOR BUFFER
	CALL	RDSECT-O	;READ GAT SECTOR TO BUFFER
	LD	HL,DSTRDM-O	;DESTINATION DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT BACKUP IF READ ERROR
	LD	HL,GASMPW-O	;POINT AT GAT MASTER PASSWORD
	LD	DE,MASTPW-O	;POINT AT DESTINATION GAT
	LD	B,10		;PASSWORD AND DISK NAME LENGTH
TESTID:	LD	A,(DE)		;GET BYTE FROM DESTINATION
	CP	(HL)		;TEST IF MATCHING SOURCE BYTE
	JR	NZ,FOREQU	;ABORT IF MISMATCH
	INC	DE		;BUMP DESTINATION OFFSET
	INC	HL		;BUMP SOURCE OFFSET
	DJNZ	TESTID		;LOOP FOR NEXT TEST BYTE
	LD	HL,LOCKTB-O	;POINT AT LOCK TABLE IN GAT
	LD	DE,GATBUF-O	;POINT AT GAT BUFFER
	LD	BC,NUMTRK	;LOAD ENTRY COUNT TO BC
	LDIR			;COPY LOCK TABLE TO GAT
	JP	NOFORM		;THEN SKIP FORMATTING CODE
;
;
; FORMAT REQUIRED, DISKETTES CONTAIN DIFFERENT PACK IDS!
;5380
FOREQU:	LD	HL,FORMRM	;FORMAT REQUIRED MESSAGE
;
;
; DESTINATION DISK NOT FORMATTED
;5383
DSTNOF:	CALL	HOMHED-O	;HOME DRIVE HEAD TO TRACK ZERO
	LD	HL,GATBUF-O	;POINT TO GAT SECTOR
	XOR	A		;ZERO TRACK COUNTER
CLRGAL:	LD	(HL),11111100B	;LOAD UNUSED ENTRY BYTE
	INC	HL		;BUMP BUFFER POINTER
	INC	A		;BUMP ENTRY COUNTER
	CP	NUMTRK		;TEST IF DONE WITH ENTRIES
	JR	NZ,CLRGAL	;LOOP UNTIL ALL DONE
CLRGAB:	CP	Low DOSVER-O	;TEST IF AT VERSION BYTE
	JR	Z,ERRTST	;THEN GO TEST FOR ERRORS
	LD	(HL),11111111B	;PAD OUT WITH ALL BITS SET
	INC	HL		;BUMP BUFFER POINTER
	INC	A		;BUMP ENTRY COUNTER
	JR	CLRGAB		;LOOP UNTIL ALL DONE
ERRTST:	LD	BC,410		;LOAD TEST LOOP COUNTER
	LD	HL,NODSKM	;NO DISK IN DRIVE MESSAGE
IDXONE:	DEC	BC		;DECREMENT LOOP COUNTER
	LD	A,B		;GET MSB TO A FOR TEST
	OR	C		;TEST IF END OF LOOP
	JP	Z,ABORTM-O	;THEN WE ABORT TEST LOOP
	LD	A,(CSTREG)	;GET FLOPPY CONTROLLER STATUS
	AND	00000010B	;TEST IF INDEX HOLE REACHED
	JR	NZ,IDXONE	;LOOP IF NOT THERE YET
	LD	BC,13114	;LOAD TEST LOOP COUNTER
	LD	HL,OPDORM	;DOOR NOT CLOSED MESSAGE
IDXTWO:	DEC	BC		;DECREMENT LOOP COUNTER
	LD	A,B		;GET MSB TO A FOR TEST
	OR	C		;TEST IF END OF LOOP
	JP	Z,ABORTM-O	;THEN WE ABORT TEST LOOP
	LD	A,(CSTREG)	;GET FLOPPY CONTROLLER STATUS
	AND	00000010B	;TEST IF PAST INDEX HOLE
	JR	Z,IDXTWO	;LOOP IF NOT THERE YET
	LD	DE,0		;ZERO DE REGISTER FOR COUNT
	LD	BC,372		;LOAD TEST LOOP COUNTER
	LD	HL,NODSKM	;NO DISK IN DRIVE MESSAGE
IDXTRI:	DEC	BC		;DECREMENT LOOP COUNTER
	LD	A,B		;GET MSB TO A FOR TEST
	OR	C		;TEST IF END OF LOOP
	JP	Z,ABORTM-O	;THEN WE ABORT TEST LOOP
	INC	DE		;BUMP COUNTER
	LD	A,(CSTREG)	;GET FLOPPY CONTROLLER STATUS
	AND	00000010B	;TEST IF INDEX HOLE REACHED
	JR	NZ,IDXTRI	;LOOP IF NOT THERE YET
	LD	BC,13120	;LOAD TEST LOOP COUNTER
	LD	HL,OPDORM	;DOOR NOT CLOSED MESSAGE
IDXFOU:	DEC	BC		;DECREMENT LOOP COUNTER
	LD	A,B		;GET MSB TO A FOR TEST
	OR	C		;TEST IF END OF LOOP
	JP	Z,ABORTM-O	;THEN WE ABORT TEST LOOP
	INC	DE		;BUMP COUNTER
	LD	A,(CSTREG)	;GET FLOPPY CONTROLLER STATUS
	AND	00000010B	;TEST IF PAST INDEX HOLE
	JR	Z,IDXFOU	;LOOP IF NOT THERE YET
	LD	HL,-5429	;GET NEGATED INDEX HOLE COUNT
	ADD	HL,DE		;TEST IF TOO MANY HOLES
	LD	HL,HASECM	;HARD SECTORED DISK MESSAGE
	JP	NC,ABORTM-O	;ABORT IF HARD SECTORED
;
;
; INITIALIZE FOR FORMATTING TRACKS
;
	XOR	A		;ZERO ACCUMULATOR
	LD	(TRKNUM),A	;SET TRACK NUMBER TO ZERO
;
;
; FORMAT DISK TRACKS LOOP
;53FB
FORMDL:	LD	A,(TRKNUM)	;GET TRACK NUMBER TO A
	CALL	BINASC-O	;CONVERT NUMBER TO ASCII
	LD	(FMTTKT),BC	;STORE ASCII NUMBER IN STRING
	LD	HL,FMTTKM	;POINT AT PROGRESS STRING
	CALL	MSGOUT-O	;DISPLAY THE STRING
	LD	A,(TRKNUM)	;LOAD TRACK NUMBER TO A
	LD	B,A		;COPY TRACK NUMBER TO B
	LD	A,(DIRTRK-O)	;GET DIRECTORY TRACK TO A
	CP	B		;TEST IF ON DIRECTORY TRACK
	LD	B,DIRMRK	;LOAD DIRECTORY ADDRESS MARK
	JR	Z,FORLOK	;SKIP IF DIRECTORY TRACK
	LD	B,DTAMRK	;LOAD DATA ADDRESS MARK
FORLOK:	LD	A,B		;GET ADDRESS MARK TO A
	LD	(THEMRK),A	;SAVE THE ADDRESS MARK
	LD	HL,TRKBUF	;POINT AT TRACK IMAGE BUFFER
	LD	DE,SKEWTB	;POINT AT SECTOR SKEW TABLE
	LD	B,14		;LOAD BYTE COUNTER TO B
	CALL	STOBAS-O	;STORE ALL BITS SET BYTE
;
;
; FORMAT DISK SECTORS LOOP
;5428
FORMDS:	LD	B,6		;LOAD BYTE COUNTER TO B
	LD	C,00000000B	;LOAD ALL BITS RESET BYTE
	CALL	STOBNB-O	;STORE THE BYTES IN BUFFER
	LD	C,IDAMRK	;LOAD IDENTITY ADDRESS MARK
	CALL	STOBTB-O	;STORE THE ADDRESS MARK
	LD	C,0		;LOAD TRACK NUMBER TO C
TRKNUM	Equ	$-1		;TRACK NUMBER STORAGE
	CALL	STOBTB-O	;STORE THE TRACK NUMBER
	LD	C,0		;LOAD HEAD NUMBER TO C
	CALL	STOBTB-O	;STORE HEAD NUMBER IN BUFFER
	LD	A,(DE)		;GET SECTOR NUMBER TO A
	LD	C,A		;COPY THE NUMBER TO C
	CALL	STOBTB-O	;STORE SECTOR NUMBER IN BUFFER
	LD	C,1		;LOAD SECTOR SIZE (256 BYTES)
	CALL	STOBTB-O	;STORE SECTOR SIZE CODE
	LD	C,CRCMRK	;LOAD CRC ADDRESS MARK
	CALL	STOBTB-O	;STORE THE ADDRESS MARK
	LD	C,11111111B	;LOAD ALL BITS SET BYTE
	CALL	STOBTB-O	;STORE THE BYTE IN BUFFER
	LD	B,11		;LOAD BYTE COUNTER TO B
	CALL	STOBAS-O	;STORE ALL BITS SET BYTES
	LD	B,6		;LOAD BYTE COUNTER TO B
	LD	C,00000000B	;LOAD ALL BITS RESET BYTE
	CALL	STOBNB-O	;STORE BYTE IN BUFFER
	LD	C,0		;GET ADDRESS MARK TO C
THEMRK	Equ	$-1		;DATA/DIRECTORY/LOCKED MARK
	CALL	STOBTB-O	;STORE ADDRESS MARK IN BUFFER
	LD	B,0		;LOAD BYTE COUNTER (256)
	LD	C,FILMRK	;LOAD SECTOR FILL BYTE
	CALL	STOBNB-O	;FILL THE SECTOR DATA FIELD
	LD	C,CRCMRK	;LOAD CRC ADDRESS MARK
	CALL	STOBTB-O	;STORE THE ADDRESS MARK
	LD	C,11111111B	;LOAD ALL BITS SET BYTE
	CALL	STOBTB-O	;STORE THE BYTE IN BUFFER
	LD	B,11		;LOAD BYTE COUNTER TO B
	CALL	STOBAS-O	;STORE ALL BITS SET BYTES
	INC	DE		;BUMP SKEW TABLE INDEX
	LD	A,(DE)		;GET SECTOR NUMBER FROM TABLE
	INC	A		;BUMP THE SECTOR NUMBER
	JR	NZ,FORMDS	;LOOP FOR NEXT IF MORE SECTORS
	LD	B,91		;LOAD BYTE COUNTER TO B
	CALL	STOBAS-O	;STORE ALL BITS SET BYTES
	CALL	WRTRAK		;WRITE THE TRACK TO DISK
;
;
; NOT FORMATTING TRACK - SKIP TO NEXT TRACK
;5486
	LD	A,(TRKNUM)	;GET TRACK NUMBER TO A
	INC	A		;BUMP THE TRACK NUMBER
	LD	(TRKNUM),A	;RE-SAVE TRACK NUMBER
	CP	NUMTRK		;TEST IF DONE LAST TRACK
	JR	Z,INISYS	;THEN WE ARE DONE FORMATTING
	LD	A,WDSTIN	;STEP IN DRIVE HEAD COMMAND
	LD	(CSTREG),A	;OUTPUT THE COMMAND
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
FORMWL:	LD	A,(CSTREG)	;GET CONTROLLER STATUS TO A
	RRCA			;COPY BUSY BIT TO CARRY
	JR	C,FORMWL	;LOOP UNTIL NOT BUSY
	JP	FORMDL		;THEN FORMAT NEXT TRACK
;
;
; WRITE A TRACK FROM TRACK BUFFER TO DISK - RETRY ONCE
;54A3
WRTRAK:	CALL	TRAKWR		;WRITE TRACK TO DISK
	RET	Z		;DONE IF SUCCESSFUL WRITE
;
;
; WRITE A TRACK FROM TRACK BUFFER TO DISK
;54A7
TRAKWR:	CALL	SELDST-O	;SELECT DISK DRIVE
	LD	BC,TRKBUF	;POINT AT TRACK BUFFER
	LD	HL,CSTREG	;COMMAND/STATUS REGISTER
	LD	(HL),WDWTRK	;WRITE TRACK COMMAND
	LD	DE,DTAREG	;POINT AT DATA REGISTER
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	DI			;DISABLE INTERRUPTS
	JR	TRAKWL		;THEN ENTER WRITE TRACK LOOP
;
;
; TEST IF NOT BUSY - IF SO, THEN WE ARE DONE WRITING
;54BC
TRAKWN:	RRCA			;COPY BUSY BIT TO CARRY
	JR	NC,TRAKWX	;ALL DONE IF NOT BUSY
;
;
; TEST IF CONTROLLER READY - LOOP IF NOT, ELSE LOAD AND WRITE
;54BF
TRAKWL:	LD	A,(HL)		;GET CONTROLLER STATUS TO A
	BIT	1,A		;TEST IF CONTROLLER IS READY
	JR	Z,TRAKWN	;TEST IF DONE IF IT ISN'T
	LD	A,(BC)		;GET DATA BYTE FROM BUFFER
	LD	(DE),A		;OUTPUT BYTE TO CONTROLLER
	INC	BC		;BUMP BUFFER POINTER
	JP	TRAKWL		;LOOP BACK FOR NEXT BYTE
;
;
; DONE WRITING TRACK - TEST FOR ANY ERRORS
; ENTRY:  BC      - CURRENT TRACK BUFFER OFFSET
;54CA
TRAKWX:	LD	A,(HL)		;GET FINAL STATUS TO A
	LD	HL,TRFASM	;TRANSFER RATE TOO FAST
	BIT	2,A		;TEST IF LOST DATA ERROR
	JP	NZ,ABORTM-O	;DISPLAY MESSAGE AND ABORT
	LD	HL,-TRKBUF	;NEGATED TRACK BUFFER OFFSET
	ADD	HL,BC		;ADD TO BUFFER OFFSET
	EX	DE,HL		;SWAP RESULT TO DE
	LD	HL,-TRKSIZ	;NEGATED TRACK BUFFER SIZE
	ADD	HL,DE		;ADD TO BUFFER OFFSET
	LD	HL,MSLOWM	;MOTOR SPEED TOO SLOW
	JP	NC,ABORTM-O	;DISPLAY MESSAGE AND ABORT
	LD	HL,-TRKOSI	;NEGATED MAXIMUM OVERFLOW SIZE
	ADD	HL,DE		;ADD TO BUFFER OFFSET
	LD	HL,MFASTM	;MOTOR SPEED TO FAST
	JP	C,ABORTM-O	;DISPLAY MESSAGE AND ABORT
	RET
;
;
; DONE FORMATTING - INITIALIZE THE DISK SYSTEM
;54ED
INISYS:	LD	A,CR		;LOAD NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	LD	D,0		;START AT TRACK ZERO
INISYN:	LD	L,D		;GET TRACK NUMBER TO L
	LD	H,High GATBUF-O	;INDEX INTO GAT SECTOR
	LD	A,(HL)		;GET ALLOCATION BYTE
	INC	A		;TEST IF TRACK LOCKED OUT
	JP	Z,NEXTIN	;THEN SKIP READING THE TRACK
	LD	A,D		;GET TRACK NUMBER TO A
	CALL	BINASC-O	;CONVERT TO ASCII DECIMAL
	LD	(VFYTKT-O),BC	;STORE IN VERIFY STRING
	LD	E,0		;ZERO SECTOR NUMBER
INISNS:	PUSH	DE		;SAVE TRACK AND SECTOR
	LD	A,D		;GET TRACK NUMBER TO A
	LD	A,E		;GET SECTOR NUMBER TO A
	CALL	BINASC-O	;CONVERT TO DECIMAL ASCII
	LD	(VFYTKS-O),BC	;STORE IN VERIFY STRING
	LD	HL,VFYTKM-O	;POINT AT VERIFY STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	POP	DE		;RECOVER TRACK AND SECTOR
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	CALL	RDSECT-O	;READ SECTOR INTO BUFFER
	LD	HL,NOTFOM	;POINT AT NOT FOUND MESSAGE
	BIT	4,A		;TEST IF RECORD NOT FOUND
	JP	NZ,LOCKTK-O	;THEN LOCK OUT THE TRACK
	LD	HL,CRCERM	;POINT AT CRC ERROR MESSAGE
	BIT	3,A		;TEST IF CRC ERROR
	JP	NZ,LOCKTK-O	;THEN LOCK OUT THE TRACK
	LD	HL,VFYSLM	;TRANSFER RATE TOO FAST
	BIT	2,A		;TEST IF LOST DATA
	JP	NZ,ABORTM-O	;THEN ABORT THE FORMAT
	INC	E		;BUMP SECTOR NUMBER
	LD	A,E		;GET SECTOR NUMBER TO A
	CP	NUMSEC		;TEST IF LAST SECTOR READ
	JP	NZ,INISNS	;LOOP FOR NEXT IF NOT
;
;
; LOOP FOR NEXT TRACK INITIALIZING
;553C
NEXTIN:	INC	D		;BUMP TRACK NUMBER
	LD	A,D		;GET TRACK NUMBER TO A
	CP	NUMTRK		;TEST IF LAST TRACK DONE
	JP	NZ,INISYN	;LOOP FOR NEXT IF NOT
	LD	A,CR		;LOAD NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	LD	HL,GATBUF-O	;POINT AT GAT BUFFER
	LD	DE,LOCKTB-O	;POINT AT LOCK-OUT TABLE
	LD	BC,NUMTRK	;LOAD ENTRY COUNT
	LDIR			;STORE LOCKED ENTRIES
;
;
; CONTINUATION IF NO FORMATTING NEEDED
;5553
NOFORM:	LD	HL,LOCKTB-O	;POINT AT TRACK LOCK-OUT TABLE
	LD	DE,GASLOT-O	;POINT AT THE OTHER TABLE
	LD	B,NUMTRK	;LOAD ENTRY COUNT
MEDIAT:	LD	A,(DE)		;GET LOCK-OUT TABLE BYTE
	CPL			;COMPLEMENT THE BYTE
	LD	C,A		;SAVE THE RESULT IN C
	PUSH	DE		;SAVE OTHER TABLE POINTER
	LD	A,E		;LOAD TABLE POINTER LSB
	SUB	Low GASLOT-O	;INDEX INTO ALLOCATION TABLE
	LD	E,A		;UPDATE TABLE POINTER
	LD	A,(DE)		;GET ALLOCATION BYTE
	POP	DE		;RECOVER OTHER TABLE POINTER
	AND	C		;AND WITH LOCK-OUT TABLE BYTE
	AND	(HL)		;AND WITH LOCK-OUT TABLE BYTE
	PUSH	HL		;SAVE LOCK-OUT TABLE POINTER
	LD	HL,REJECM	;DISK IS BAD AND REJECTED
	JP	NZ,ABORTM-O	;ABORT IF FLAWED DISKETTE
	POP	HL		;RECOVER SAVED TABLE POINTER
	INC	DE		;BUMP SECOND TABLE POINTER
	INC	HL		;BUMP FIRST TABLE POINTER
	DJNZ	MEDIAT		;LOOP UNTIL ALL ENTRIES DONE
	LD	A,(SGLDRV-O)	;GET SINGLE DRIVE BACKUP FLAG
	OR	A		;TEST IF ONLY ONE DRIVE
	JP	NZ,BACKIT-O	;THEN GO DO THE BACKUP
	LD	HL,4095		;INIT FOR MEMORY TEST LOOP
RAMTST:	LD	A,H		;GET ADDRESS MSB TO A
	SUB	High 4096	;SUBTRACT ONE MEMORY BLOCK
	LD	H,A		;UPDATE MEMORY POINTER MSB
	LD	A,(HL)		;GET BYTE FROM MEMORY
	LD	B,A		;SAVE THE BYTE IN B
	CPL			;COMPLEMENT THE BYTE
	LD	(HL),A		;STORE BYTE IN MEMORY
	CP	(HL)		;TEST IF WE HAVE RAM THERE
	LD	(HL),B		;RESTORE PREVIOUS BYTE
	JR	NZ,RAMTST	;LOOP UNTIL RAM IS FOUND
	LD	A,H		;GET TOP OF RAM MSB TO A
	SUB	High SCTBUF	;COMPUTE FREE MEMORY MSB
	LD	B,0		;INIT FOR COPY BUFFER SIZE
GETBUS:	INC	B		;BUMP BUFFER SIZE IN TRACKS
	SUB	High SIZTRK	;SUBTRACT TRACK OF SECTORS
	JR	NC,GETBUS	;LOOP UNTIL BUFFER UNDERFLOW
	LD	A,B		;GET TRACK COUNT TO A
	DEC	A		;COMPUTE BUFFER SIZE IN TRACKS
	LD	(COPYBS-O),A	;SAVE THE COPY BUFFER SIZE
	JP	BACKIT-O	;EXECUTE RELOCATED CODE
;
;
; DEFINE OFFSET FROM OUR LOCATION TO RELOCATED CODE
;
O	Equ	$-SYSBUF	;DEFINE THE OFFSET
;
;
; CODE COPIED TO 'SYSBUF' AND ABOVE, OVERLAYING TRSDOS
;559B (4200)
BACKIT:	CALL	SELDST-O	;SELECT DESTINATION DRIVE
	CALL	HOMHED-O	;HOME DISK DRIVE HEAD
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	LD	DE,0		;TRACK ZERO, SECTOR ZERO
	CALL	RDSECT-O	;READ BOOT SECTOR INTO BUFFER
	LD	HL,DSTRDM-O	;DESTINATION DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT IF READ ERROR
	LD	A,76H		;LOAD HALT OP-CODE
	LD	(HITBUF-O),A	;STORE AT BOOT SECTOR START
	LD	A,WDWRIT	;WRITE DATA SECTOR COMMAND
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	CALL	WRSECT-O	;WRITE THE BOOT SECTOR BACK
	LD	HL,DSTWRM-O	;DESTINATION DISK WRITE ERROR
	JP	NZ,ABORTM-O	;ABORT IF WRITE ERROR
	CALL	SELSWP-O	;SELECT DRIVE OR SWAP DISK
	CALL	HOMHED-O	;HOME DISK DRIVE HEAD
	XOR	A		;ZERO ACCUMULATOR
	LD	(XFRCNT-O),A	;ZERO TRACKS TRANSFERED COUNT
	LD	D,0		;ZERO THE TRACK NUMBER
REFILL:	LD	BC,SCTBUF	;POINT AT SECTOR BUFFER
	LD	A,(TRKREG)	;GET TRACK FROM CONTROLLER
	LD	(CTLTRK-O),A	;SAVE THE TRACK NUMBER
	LD	A,D		;GET TRACK NUMBER TO A
	LD	(CURTRK-O),A	;SAVE THE TRACK NUMBER
NEXTRK:	PUSH	BC		;SAVE SECTOR BUFFER POINTER
	LD	H,High GATSEC-O	;SECTOR BUFFER POINTER MSB
	LD	L,D		;INDEX INTO GAT SECTOR
	LD	C,(HL)		;GET ALLOCATION BYTE TO C
	LD	A,D		;GET TRACK NUMBER TO A
	ADD	A,Low GASLOT-O	;INDEX TO LOCK-OUT TABLE
	LD	L,A		;POINT AT LOCK-OUT TABLE
	LD	A,(HL)		;GET LOCK_OUT TABLE VALUE
	CPL			;COMPLEMENT THE BYTE
	AND	C		;MASK WITH ALLOCATION BYTE
	LD	H,High GATBUF-O	;CORRESPONDING GAT ADDRESS
	LD	C,(HL)		;GET LOCK-OUT BYTE TO C
	OR	C		;MERGE WITH LOCK-OUT BYTE
	CP	C		;TEST IF MATCHING VALUE
	POP	BC		;RECOVER SECTOR BUFFER POINTER
	JP	Z,LMATCH-O	;CONTINUE IF VALUES MATCH
	CALL	SELSWP-O	;SELECT DRIVE OR SWAP DISK
	LD	E,0		;ZERO SECTOR NUMBER
NEXSEC:	PUSH	BC		;SAVE BUFFER POINTER
	LD	A,D		;GET TRACK NUMBER TO A
	CALL	BINASC-O	;CONVERT TO DECIMAL ASCII
	LD	(LODTKT-O),BC	;STORE IN LOADING MESSAGE
	LD	A,E		;GET SECTOR NUMBER TO A
	CALL	BINASC-O	;CONVERT TO DECIMAL ASCII
	LD	(LODTKS-O),BC	;STORE IN LOADING MESSAGE
	POP	BC		;RECOVER BUFFER POINTER
	PUSH	DE		;SAVE TRACK AND SECTOR
	LD	HL,LODTKM-O	;POINT AT LOADING MESSAGE
	CALL	MSGOUT-O	;DISPLAY PROGRESS STRING
	POP	DE		;RECOVER TRACK AND SECTOR
	CALL	RDSECT-O	;READ SECTOR INTO BUFFER
	LD	HL,SRCRDM-O	;SOURCE DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT IF READ ERROR
	INC	E		;BUMP SECTOR NUMBER
	LD	A,E		;GET SECTOR TO A FOR TEST
	CP	NUMSEC		;TEST IF DONE WITH TRACK
	JR	NZ,NEXSEC	;LOOP FOR NEXT SECTOR IF NOT
	LD	A,(CSTREG)	;GET CONTROLLER STATUS TO A
	LD	L,D		;GET TRACK NUMBER TO L
	LD	H,High TRKTYP-O	;TRACK FORMAT TYPE BUFFER MSB
	LD	(HL),A		;STORE TRACK FORMAT TYPE
	LD	HL,XFRCNT-O	;POINT AT TRACK COUNTER
	INC	(HL)		;BUMP TRACKS LOADED COUNT
	LD	A,(SGLDRV-O)	;GET SINGLE DRIVE BACKUP FLAG
	OR	A		;TEST IF SINGLE DRIVE BACKUP
	JR	NZ,BUFULL	;SKIP IF NOT SINGLE DRIVE
	LD	A,(COPYBS-O)	;GET COPY BUFFER SIZE TO A
	CP	(HL)		;TEST IF COPY BUFFER FULL
	JR	Z,BUFULL	;WRITE OUT THE BUFFER IF SO
LMATCH:	INC	D		;BUMP TRACK NUMBER
	LD	A,D		;GET TRACK TO A FOR TEST
	CP	NUMTRK		;TEST IF DONE WITH DISK
	JP	NZ,NEXTRK-O	;LOOP FOR NEXT TRACK IF NOT
	LD	A,(XFRCNT-O)	;GET TRACKS TRANSFERED COUNT
	OR	A		;TEST IF NO TRACKS TO TRANSFER
	JP	Z,WRTINF-O	;THEN COPY THE INFORMATION
BUFULL:	LD	BC,SCTBUF	;POINT AT SECTOR BUFFER
	LD	A,0		;GET TRACK NUMBER TO A
;
;
; STORAGE FOR CURRENT TRACK FOR COPY PROGRESS
;5648
CTLTRK	Equ	$-1		;STORAGE FOR TRACK
;
;
; CONTINUATION OF TRACK COPY ROUTINE
;
	LD	(TRKREG),A	;SET UP TRACK REGISTER
	LD	D,0		;GET TRACK NUMBER TO D
;
;
; STORAGE FOR CURRENT TRACK
;564D
CURTRK	Equ	$-1		;STORAGE FOR TRACK
;
;
; CONTINUATION OF TRACK COPY ROUTINE
;564E
TRKNXT:	PUSH	BC		;SAVE BUFFER POINTER
	LD	H,High GATSEC-O	;LOAD BUFFER POINTER MSB
	LD	L,D		;GET TRACK NUMBER TO L
	LD	C,(HL)		;GET ALLOCATION TABLE BYTE
	LD	A,D		;GET TRACK NUMBER TO A
	ADD	A,Low GASLOT-O	;INDEX INTO LOCK-OUT TABLE
	LD	L,A		;POINT INTO LOCK-OUT TABLE
	LD	A,(HL)		;GET BYTE FROM THE TABLE
	CPL			;COMPLEMENT THE BYTE
	AND	C		;MASK WITH ALLOCATION BYTE
	LD	H,High GATBUF-O	;GET BUFFER POINTER MSB
	LD	C,(HL)		;GET ALLOCATION BYTE TO C
	OR	C		;MERGE WITH OTHER TABLE BYTE
	LD	L,D		;GET TRACK NUMBER TO L
	LD	(HL),A		;STORE BYTE IN THE TABLE
	CP	C		;TEST IF BYTES MATCH
	POP	BC		;RECOVER BUFFER POINTER
	JP	Z,SKIPTK-O	;SKIP TRACK IF MATCH
	CALL	RESELD-O	;RE-SELECT DISKETTE DRIVE
	LD	E,0		;ZERO SECTOR NUMBER
	LD	A,D		;GET TRACK NUMBER TO A
	OR	E		;TEST IF BOOT SECTOR
	JR	NZ,NOTBOT	;SKIP IF IT ISN'T
	LD	A,(BC)		;GET BOOT SECTOR BYTE TO A
	LD	(BOOTSA-O),A	;SAVE THE SECTOR BYTE
	LD	A,76H		;LOAD 'HALT' OP-CODE
	LD	(BC),A		;STORE IN BOOT SECTOR
NOTBOT:	PUSH	BC		;SAVE BUFFER POINTER
WRNEXS:	PUSH	BC		;SAVE BUFFER POINTER AGAIN
	LD	A,D		;GET TRACK NUMBER TO A
	CALL	BINASC-O	;CONVERT TO DECIMAL ASCII
	LD	(COPTKT-O),BC	;STORE IN COPYING MESSAGE
	LD	A,E		;GET SECTOR NUMBER TO A
	CALL	BINASC-O	;CONVERT TO DECIMAL ASCII
	LD	(COPTKS-O),BC	;STORE IN COPYING MESSAGE
	POP	BC		;RECOVER BUFFER POINTER
	PUSH	DE		;SAVE TRACK AND SECTOR
	LD	HL,COPTKM-O	;POINT AT COPYING MESSAGE
	CALL	MSGOUT-O	;DISPLAY PROGRESS STRING
	POP	DE		;RECOVER TRACK AND SECTOR
	LD	L,D		;GET TRACK NUMBER TO L
	LD	H,High TRKTYP-O	;TRACK FORMAT TYPE BUFFER MSB
	LD	A,(HL)		;GET FORMAT TYPE TO A
	AND	01100000B	;MASK TO FORMAT TYPE BITS
	RLCA			;ROTATE
	RLCA			; TO TWO
	RLCA			;  LS BITS
	OR	WDWRIT		;MAKE INTO WRITE SECTOR CODE
	CALL	WRSECT-O	;WRITE OUT THE SECTOR
	LD	HL,DSTWRM-O	;DESTINATION DISK WRITE ERROR
	JP	NZ,ABORTM-O	;ABORT IF WRITE ERROR
	INC	E		;BUMP SECTOR NUMBER
	LD	A,E		;GET SECTOR NUMBER TO A
	CP	NUMSEC		;TEST IF DONE WITH TRACK
	JR	NZ,WRNEXS	;LOOP FOR NEXT SECTOR IF NOT
	POP	BC		;RECOVER BUFFER POINTER
	LD	E,0		;ZERO SECTOR NUMBER
SCTNXT:	PUSH	BC		;SAVE BUFFER POINTER
	LD	A,D		;GET TRACK NUMBER TO A
	CALL	BINASC-O	;CONVERT TO ASCII DECIMAL
	LD	(VFYTKT-O),BC	;STORE IN VERIFYING MESSAGE
	LD	A,E		;GET SECTOR NUMBER TO A
	CALL	BINASC-O	;CONVERT TO ASCII DECIMAL
	LD	(VFYTKS-O),BC	;STORE IN VERIFYING MESSAGE
	POP	BC		;RECOVER BUFFER POINTER
	PUSH	DE		;SAVE TRACK AND SECTOR
	LD	HL,VFYTKM-O	;POINT AT VERIFYING MESSAGE
	CALL	MSGOUT-O	;DISPLAY PROGRESS STRING
	POP	DE		;RECOVER TRACK AND SECTOR
	CALL	RDSECT-O	;READ THE SECTOR TO STORE
	LD	HL,DSTRDM-O	;DESTINATION DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT IF READ ERROR
	INC	E		;BUMP SECTOR NUMBER
	LD	A,E		;GET SECTOR TO A FOR TEST
	CP	NUMSEC		;TEST IF DONE LAST SECTOR
	JR	NZ,SCTNXT	;LOOP FOR NEXT ONE IF NOT
	LD	HL,XFRCNT-O	;POINT AT TRACK TRANSFER COUNT
	DEC	(HL)		;DECREMENT THE COUNT
SKIPTK:	INC	D		;BUMP TRACK NUMBER
	LD	A,D		;GET TRACK TO A FOR TEST
	CP	NUMTRK		;TEST IF DONE LAST TRACK
	JR	Z,WRTINF	;THEN WE SKIP THE FOLLOWING
	LD	A,(XFRCNT-O)	;GET TRACK TRANSFER COUNT TO A
	OR	A		;TEST IF TRANSFER BUFFER EMPTY
	JP	NZ,TRKNXT-O	;LOOP FOR NEXT TRACK IF NOT
	JP	REFILL-O	;ELSE REFILL THE BUFFER
;
;
; COPY DONE - WRITE OUT INFORMATION
;56EA
WRTINF:	LD	HL,DTEBUF-O	;POINT AT BACKUP DATE STRING
	LD	DE,GASCRD-O	;POINT AT DATE LOCATION IN GAT
	LD	BC,8		;NUMBER OF BYTES TO COPY
	LDIR			;COPY BACKUP DATE TO GAT
	CALL	RESELD-O	;RE-SELECT DISKETTE DRIVE
	LD	A,(DIRTRK-O)	;GET DIRECTORY TRACK TO A
	LD	D,A		;GET DIRECTORY TRACK TO D
	LD	E,0		;LOAD GAT SECTOR NUMBER
	LD	BC,GATSEC-O	;POINT AT GAT SECTOR BUFFER
	LD	A,WDWRID	;WRITE DIRECTORY SECTOR COMMAND
	CALL	WRSECT-O	;WRITE OUT THE GAT SECTOR
	LD	HL,DSTWRM-O	;DESTINATION DISK WRITE ERROR
	JP	NZ,ABORTM-O	;ABORT IF WRITE ERROR
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	CALL	RDSECT-O	;READ GAT SECTOR TO BUFFER
	LD	HL,DSTRDM-O	;DESTINATION DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT IF READ ERROR
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	LD	DE,0		;TRACK ZERO, SECTOR ZERO
	CALL	RDSECT-O	;READ BOOT SECTOR TO BUFFER
	LD	HL,DSTRDM-O	;DESTINATION DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT IF READ ERROR
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	LD	A,0		;GET SAVED BOOT SECTOR BYTE
;
;
; STORAGE FOR SAVED BOOT SECTOR BYTE
;572B
BOOTSA	Equ	$-1		;SAVED BYTE STORAGE
;
;
; CONTINUATION OF BACKUP OPERATION
;
	LD	(BC),A		;RESTORE SAVED BYTE
	LD	A,WDWRIT	;WRITE DATA SECTOR COMMAND
	CALL	WRSECT-O	;WRITE OUT BOOT SECTOR
	LD	HL,DSTWRM-O	;DESTINATION DISK WRITE ERROR
	JP	NZ,ABORTM-O	;ABORT IF WRITE ERROR
	CALL	HOMHED-O	;HOME THE DRIVE HEAD
	LD	HL,BAKCOM-O	;BACKUP COMPLETE MESSAGE
;
;
; DISPLAY MESSAGE, PROMPT FOR <ENTER> AND RE-BOOT SYSTEM
; ENTRY:  HL      - POINTER TO MESSAGE STRING
;573E (43A3)
ABORTM:	CALL	MSGOUT-O	;DISPLAY ERROR MESSAGE
;
;
; PROMPT FOR <ENTER> KEY PRESS - THEN REBOOT SYSTEM
;5741 (43A6)
	LD	HL,HITENM-O	;POINT AT PROMPT STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
PREENW:	LD	A,(KROSEV)	;READ KEYBOARD ROW
	RRCA			;ROTATE <ENTER> BIT TO CARRY
	JR	NC,PREENW	;LOOP UNTIL KEY PRESSED
	RST	00H		;THEN RE-BOOT SYSTEM
;
;
; WRITE A SECTOR FROM SECTOR BUFFER TO DISK - RETRY ONCE
; ENTRY:  A       - DISK CONTROLLER COMMAND CODE
;         BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL WRITE
;574E (43B3)
WRSECT:	LD	(SECTWC-O),A	;STORE COMMAND CODE
;
;
; WRITE A SECTOR FROM SECTOR BUFFER TO DISK - RETRY ONCE
; ENTRY:  BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL WRITE
;
	PUSH	BC		;SAVE BUFFER POINTER
	CALL	SECTWR-O	;WRITE SECTOR TO DISK
	POP	HL		;RECOVER BUFFER POINTER
	RET	Z		;DONE IF SUCCESSFUL WRITE
	LD	B,H		;BUFFER POINTER MSB TO B
	LD	C,L		;BUFFER POINTER LSB TO C
;
;
; WRITE A SECTOR FROM SECTOR BUFFER TO DISK
; ENTRY:  BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL WRITE
;5759 (43BE)
SECTWR:	LD	(SCTREG),DE	;STORE TRACK AND SECTOR
	PUSH	DE		;SAVE TRACK AND SECTOR
	CALL	SELDRV-O	;SELECT DISKETTE DRIVE
	LD	HL,CSTREG	;COMMAND/STATUS REGISTER
	LD	(HL),WDSEEK	;SEEK TO TRACK COMMAND
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
SECTWB:	LD	A,(HL)		;GET FLOPPY STATUS
	RRCA			;TEST IF CONTROLLER BUSY
	JR	C,SECTWB	;LOOP WHILE IT IS
	LD	(HL),0		;ELSE OUTPUT COMMAND CODE
SECTWC	Equ	$-1		;FLOPPY COMMAND CODE
	LD	DE,DTAREG	;POINT AT DATA REGISTER
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	DI			;DISABLE INTERRUPTS
	JR	SECTWL		;THEN ENTER READ LOOP
;
;
;TEST IF NOT BUSY - IF SO, THEN WE ARE DONE WRITING
;577A
SECTWN:	RRCA			;COPY BUSY BIT TO CARRY
	JR	NC,SECTWX	;ALL DONE IF NOT BUSY
;
;
; TEST IF CONTROLLER READY - LOOP IF NOT, ELSE LOAD AND WRITE
;577D (43E2)
SECTWL:	LD	A,(HL)		;GET CONTROLLER STATUS TO A
	BIT	1,A		;TEST IF CONTROLLER IS READY
	JR	Z,SECTWN	;TEST IF DONE IF IT ISN'T
	LD	A,(BC)		;GET DATA BYTE FROM BUFFER
	LD	(DE),A		;OUTPUT BYTE TO CONTROLLER
	INC	BC		;BUMP BUFFER POINTER
	JP	SECTWL-O	;LOOP BACK FOR NEXT BYTE
;
;
; DONE WRITING - GET FINAL STATUS AND RETURN
;57B8
SECTWX:	LD	A,(HL)		;GET FINAL STATUS TO A
	AND	01111100B	;MASK TO ERROR BITS
	POP	DE		;RECOVER TRACK AND SECTOR
	RET	Z		;RETURN IF NO ERRORS
	LD	(HL),WDFORC	;ELSE FORCE INTERRUPT
	RET
;
;
; TRACK UNUSABLE - DISPLAY MESSAGE AND LOCK OUT THE TRACK
; ENTRY:  D       - TRACK NUMBER
;         HL      - MESSAGE STRING POINTER
;5790 (43F5)
LOCKTK:	PUSH	DE		;SAVE TRACK AND SECTOR
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	POP	DE		;RECOVER TRACK AND SECTOR
	LD	L,D		;GET TRACK NUMBER TO L
	LD	H,High GATBUF-O	;INDEX INTO GAT SECTOR
	LD	(HL),11111111B	;LOCK OUT THE TRACK
	JP	NEXTIN		;RE-ENTER SYSTEM INITIALIZE
;
;
; CONVERT A BINARY NUMBER TO ASCII DECIMAL
; ENTRY:  A       - BINARY NUMBER
; EXIT:   B       - DECIMAL ASCII NUMBER LSB
;         C       - DECIMAL ASCII NUMBER MSB
;579D (4402)
BINASC:	LD	C,'0'		;LOAD INITIAL ASCII ZERO
BINASL:	SUB	10		;SUBTRACT DECIMAL TEN
	JR	C,BINASX	;ALL DONE IF UNDERFLOW
	INC	C		;ELSE BUMP ASCII NUMBER MSB
	JR	BINASL		;LOOP FOR NEXT SUBTRACTION
BINASX:	ADD	A,'9'+1		;ADD REMAINDER TO LSB
	LD	B,A		;COPY ASCII RESULT LSB TO B
	RET
;
;
; STORE A NUMBER OF 'ALL BITS SET' BYTES IN TRACK BUFFER
; ENTRY:  B       - BYTE COUNTER
;         HL      - BUFFER POINTER
; EXIT:   B       - ZERO
;         C       - 11111111B
;         HL      - INCREMENTED BY B BYTES
;57AA (440F)
STOBAS:	LD	C,11111111B	;LOAD ALL BITS SET
;
;
; STORE A NUMBER OF BYTES IN TRACK BUFFER
; ENTRY:  B       - BYTE COUNTER
;         C       - BYTE TO STORE
;         HL      - BUFFER POINTER
; EXIT:   B       - ZERO
;         HL      - INCREMENTED BY B BYTES
;57AC (4411)
STOBNB:	CALL	STOBTB-O	;STORE THE BYTE IN BUFFER
	DJNZ	STOBNB		;LOOP UNTIL ALL BYTES STORED
	RET
;
;
; STORE A BYTE IN TRACK BUFFER
; ENTRY:  C       - BYTE TO STORE
;         HL      - BUFFER POINTER
; EXIT:   HL      - INCREMENTED
;57B2 (4417)
STOBTB:	LD	(HL),C		;STORE BYTE IN BUFFER
	INC	HL		;BUMP BUFFER POINTER
	RET
;
;
; HOME DRIVE HEAD TO TRACK ZERO
;57B5 (441A)
HOMHED:	LD	A,WDHOME	;HOME DRIVE HEAD COMMAND
	LD	(CSTREG),A	;OUTPUT TO FLOPPY CONTROLLER
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
HOMHEW:	LD	A,(CSTREG)	;GET CONTROLLER STATUS TO A
	RRCA			;ROTATE BUSY BIT TO CARRY
	JR	C,HOMHEW	;LOOP UNTIL NOT BUSY
	RET
;
;
; SELECT SOURCE DRIVE FOR BACKUP
; ENTRY:  HL      - POINTER TO PROMPT STRING
;         SRCCOD  - DRIVE CODE WITH BIT SEVEN SET IF SELECTED
;57C5 (442A)
SELSRC:	LD	A,0		;GET SOURCE DRIVE CODE TO A
;
;
; COURCE DRIVE CODE STORAGE
;
SRCCOD	Equ	$-1		;SOURCE DRIVE CODE
;
;
; CONTINUATION TO PROMPT FOR AND SELECT SOURCE DRIVE
;
	OR	10000000B	;SET SOURCE SELECTED BIT
	PUSH	HL		;SAVE HL REGISTER
	LD	HL,INSSDM-O	;SOURCE DISK PROMPT STRING
	CALL	PMTSEL-O	;PROMPT AND SELECT DRIVE
	POP	HL		;RECOVER HL REGISTER
	RET
;
;
; SELECT A DRIVE AND SWAP DISK IF NEEDED ROUTINE
;57D2 (4437)
SELSWP:	LD	A,(CURDRN-O)	;GET CURRENT DRIVE NUMBER
	BIT	7,A		;TEST IF SOURCE SELECTED
	JR	NZ,SELSRC	;THEN RE-SELECT THE DRIVE
	CALL	SELSRC-O	;SELECT SOURCE DRIVE
	LD	A,(SGLDRV-O)	;GET SINGLE DRIVE BACKUP FLAG
	OR	A		;TEST IF SINGLE DRIVE
	RET	NZ		;ALL DONE IF IT ISN'T
	CALL	HOMHED-O	;ELSE HOME DISK DRIVE HEAD
	PUSH	BC		;SAVE BC REGISTER
	PUSH	DE		;SAVE DE REGISTER
	PUSH	HL		;SAVE HL REGISTER
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	LD	DE,0		;TRACK ZERO, SECTOR ZERO
	CALL	RDSECT-O	;READ BOOT SECTOR TO BUFFER
	LD	HL,SRCRDM-O	;SOURCE DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT IF READ ERROR
	POP	HL		;RECOVER HL REGISTER
	POP	DE		;RECOVER DE REGISTER
	POP	BC		;RECOVER BC REGISTER
	LD	A,(HITBUF-O)	;GET FIRST BOOT SECTOR BYTE
	OR	A		;TEST IF BYTE IS ZERO
	JR	NZ,ZEROCD	;ZERO DRIVE CODE AND RETRY
	PUSH	BC		;SAVE BC REGISTER
	PUSH	DE		;SAVE DE REGISTER
	PUSH	HL		;SAVE HL REGISTER
	LD	A,(DIRTRK-O)	;GET DIRECTORY TRACK TO A
	LD	D,A		;COPY TRACK NUMBER TO D
	LD	E,0		;GET HIT SECTOR NUMBER TO E
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	CALL	RDSECT-O	;READ HIT SECTOR TO BUFFER
	LD	HL,SRCRDM-O	;SOURCE DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT IF READ ERROR
	LD	HL,GASMPW-O	;POINT AT GAT MASTER PASSWORD
	LD	DE,HISMPW-O	;POINT AT MASTER PASSWORD
	LD	B,10		;LOAD COMPARE LENGTH
TSTSAM:	LD	A,(DE)		;GET BYTE FROM SECTOR
	CP	(HL)		;TEST IF A MATCH
	JR	NZ,SNARKY	;ABORT IF MISMATCH
	INC	DE		;BUMP DESTINATION POINTER
	INC	HL		;BUMP SOURCE POINTER
	DJNZ	TSTSAM		;LOOP UNTIL ALL COMPARED
	POP	HL		;RECOVER HL REGISTER
	POP	DE		;RECOVER DE REGISTER
	POP	BC		;RECOVER BC REGISTER
	RET
;
;
; SNARKY REMARK DISPLAYED WHEN WRONG DISK INSERTED
;5828
SNARKY:	LD	HL,WAKUPM-O	;POINT AT WAKE-UP MESSAGE
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE STRING
	POP	HL		;RECOVER HL REGISTER
	POP	DE		;RECOVER DE REGISTER
	POP	BC		;RECOVER BC REGISTER
;
;
; ZERO CURRENT DRIVE NUMBER AND TRY AGAIN
;5831
ZEROCD:	XOR	A		;ZERO ACCUMULATOR
	LD	(CURDRN-O),A	;SET CURRENT DRIVE NUMBER
	JR	SELSWP		;THEN TRY AGAIN
;
;
; SELECT DESTINATION DRIVE FOR BACKUP
; ENTRY:  HL      - POINTER TO PROMPT STRING
;         DSTCOD  - DRIVE CODE WITH BIT SIX SET IF SELECTED
;5837 (449C)
SELDST:	LD	A,0		;GET DESTINATION DRIVE CODE
;
;
; DESTINATION DRIVE CODE STORAGE
;
DSTCOD	Equ	$-1		;DESTINATION  DRIVE CODE
;
;
; CONTINUATION TO PROMPT FOR AND SELECT DESTINATION DRIVE
;
	OR	01000000B	;SET DESTINATION SELECT BIT
	PUSH	HL		;SAVE HL REGISTER
	LD	HL,INSDDM-O	;DESTINATION DISK PROMPT STRING
	CALL	PMTSEL-O	;PROMPT AND SELECT DRIVE
	LD	A,(CSTREG)	;GET CONTROLLER STATUS TO A
	LD	HL,WRPROM-O	;DESTINATION WRITE PROTECTED
	BIT	6,A		;TEST IF WRITE PROTECTED
	JP	NZ,ABORTM-O	;ABORT BACKUP IF SO
	POP	HL		;RECOVER HL REGISTER
	RET
;
;
; RE-SELECT DISKETTE DRIVE
;584F (44B4)
RESELD:	LD	A,(CURDRN-O)	;GET CURRENT DRIVE NUMBER
	BIT	6,A		;TEST IF ALREADY SELECTED
	JR	NZ,SELDST	;THEN NO NEED TO RE-SELECT
	CALL	SELDST-O	;SELECT DESTINATION DRIVE
	LD	A,(SGLDRV-O)	;GET SINGLE DRIVE BACKUP FLAG
	OR	A		;TEST IF SINGLE DRIVE
	RET	NZ		;THEN WE JUST RETURN
	CALL	HOMHED-O	;HOME DISK DRIVE HEAD
	PUSH	BC		;SAVE BUFFER POINTER
	PUSH	DE		;SAVE TRACK AND SECTOR
	PUSH	HL		;SAVE HL REGISTER
	LD	BC,HITBUF-O	;POINT AT SECTOR BUFFER
	LD	DE,0		;TRACK ZERO, SECTOR ZERO
	CALL	RDSECT-O	;READ BOOT SECTOR INTO BUFFER
	POP	HL		;RECOVER HL REGISTER
	POP	DE		;RECOVER TRACK AND SECTOR
	POP	BC		;RECOVER BUFFER POINTER
	LD	HL,DSTRDM-O	;DESTINATION DISK READ ERROR
	JP	NZ,ABORTM-O	;ABORT IF READ ERROR
	LD	A,(HITBUF-O)	;GET BOOT SECTOR BYTE
	CP	76H		;TEST IF 'HALT' OP-CODE
	RET	Z		;DONE IF ALREADY WRITTEN
	XOR	A		;ELSE ZERO ACCUMULATOR
	LD	(CURDRN-O),A	;SET CURRENT DRIVE TO ZERO
	JR	RESELD		;THEN SELECT THE DRIVE
;
;
; SELECT DRIVE - PROMPT FOR DISKETTE CHANGE IF ONLY ONE DRIVE
; ENTRY:  A       - DRIVE CODE FOR NEW DRIVE SELECT
;         BC      - BUFFER POINTER
;         DE      - TRACK AND SECTOR
;         HL      - DRIVE CHANGE PROMPT STRING POINTER
;         CURDRN  - CURRENT DRIVE NUMBER
;         SGLDRV  - SINGLE DRIVE BACKUP FLAG
;5882 (44E7)
PMTSEL:	CP	0		;TEST IF DRIVE IS CURRENT
;
;
; CURRENT DRIVE NUMBER
;
CURDRN	Equ	$-1		;CURRENT DRIVE NUMBER STORAGE
;
;
; CONTINUATION OF DRIVE SELECT CODE

	JR	Z,SELDRV	;THEN RE-SELECT THE DRIVE
	LD	(CURDRN-O),A	;SET NEW CURRENT DRIVE NUMBER
	LD	A,0		;GET SINGLE DRIVE BACKUP FLAG
;
;
; SINGLE DRIVE BACKUP FLAG - NON ZERO IF DOUBLE DRIVE
;
SGLDRV	Equ	$-1		;SINGLE DRIVE BACKUP FLAG
;
;
; CONTINUATION OF DRIVE SELECT CODE
;
	OR	A		;TEST IF SINGLE DRIVE
	JR	NZ,SELDRV	;THEN JUST RE-SELECT DRIVE
	PUSH	BC		;SAVE BUFFER POINTER
	PUSH	DE		;SAVE TRACK AND SECTOR
	PUSH	HL		;SAVE PROMPT STRING POINTER
	LD	A,CR		;LOAD NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
WENTER:	CALL	MSGOUT-O	;DISPLAY PROMPT STRING
WRELEA:	LD	A,(KROSEV)	;READ KEYBOARD ROW
	RRCA			;ROTATE <ENTER> BIT TO CARRY
	JR	C,WRELEA	;LOOP UNTIL KEY RELEASED
	LD	BC,16384	;LOAD LOOP COUNTER
WAITLP:	LD	A,(KROSEV)	;READ KEYBOARD ROW
	RRCA			;ROTATE <ENTER> BIT TO CARRY
	JR	C,ISRELE	;DONE IF KEY RELEASED
	DEC	BC		;DECREMENT LOOP COUNTER
	LD	A,B		;GET VALUE TO A FOR TEST
	OR	C		;TEST IF LOOP EXHAUSTED
	JR	NZ,WAITLP	;LOOP UNTIL LOOP DONE
	LD	A,EE		;END OF LINE ERASE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	LD	BC,13107	;LOAD DELAY VALUE
	CALL	DELAYL		;DELAY FOR 192 MILLISECONDS
	JR	WENTER		;THEN LOOP UNTIL <ENTER> KEY
ISRELE:	LD	A,EE		;END OF LINE ERASE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	POP	HL		;RECOVER PROMPT STRING POINTER
	POP	DE		;RECOVER TRACK AND SECTOR
	POP	BC		;RECOVER BUFFER POINTER
;
;
; RE-SELECT CURRENT DRIVE
; ENTRY:  CURDRN  - CURRENT DRIVE NUMBER
;58C2 (4527)
SELDRV:	LD	A,(CSTREG)	;GET CONTROLLER STATUS
	PUSH	AF		;SAVE THE STATUS
	LD	A,(CURDRN-O)	;GET DRIVE NUMBER TO A
	LD	(DRVREG),A	;RE-SELECT CURRENT DRIVE
	POP	AF		;RECOVER SAVED STATUS
	RLCA			;COPY NOT READY BIT TO CARRY
	PUSH	BC		;SAVE BUFFER POINTER
	LD	BC,0		;LOAD DELAY VALUE
	CALL	C,DELAYL	;DELAY FOR 960 MILLISECONDS
	POP	BC		;RECOVER BUFFER POINTER
	RET
;
;
; READ A DISK SECTOR INTO SECTOR BUFFER - RETRY ONCE
; ENTRY:  BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL READ
;58D7 (453C)
RDSECT:	PUSH	BC		;SAVE BUFFER POINTER
	CALL	SECTRD-O	;READ SECTOR INTO BUFFER
	POP	HL		;RECOVER BUFFER POINTER
	RET	Z		;DONE IF SUCCESSFUL READ
	LD	B,H		;BUFFER POINTER MSB TO B
	LD	C,L		;BUFFER POINTER LSB TO C
;
;
; READ A DISK SECTOR INTO SECTOR BUFFER
; ENTRY:  BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL READ
;58DF (4544)
SECTRD:	CALL	SELDRV-O	;RE-SELECT CURRENT DRIVE
	LD	(SCTREG),DE	;STORE TRACK AND SECTOR
	PUSH	DE		;SAVE TRACK AND SECTOR VALUES
	LD	HL,CSTREG	;COMMAND/STATUS REGISTER
	LD	(HL),WDSEEK	;SEEK TO TRACK COMMAND
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
SECTRB:	LD	A,(HL)		;GET FLOPPY CONTROLLER STATUS
	RRCA			;COPY BUSY BIT TO CARRY
	JR	C,SECTRB	;LOOP IF CONTROLLER BUSY
	LD	(HL),WDREAD	;READ SECTOR COMMAND
	LD	DE,DTAREG	;POINT AT DATA REGISTER
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	DI			;DISABLE INTERRUPTS
	JR	SECTRL		;THEN ENTER READ LOOP
;
;
; TEST IF NOT BUSY - IF SO, THEN WE ARE DONE READING
;5900 (4565)
SECTRN:	RRCA			;COPY BUSY BIT TO CARRY
	JR	NC,SECTRX	;ALL DONE IF NOT BUSY
;
;
; TEST IF DATA BYTE READY - LOOP IF NOT, ELSE READ AND STORE
;5903 (4568)
SECTRL:	LD	A,(HL)		;GET CONTROLLER STATUS TO A
	BIT	1,A		;TEST IF DATA BYTE IS READY
	JR	Z,SECTRN	;TEST IF DONE IF IT ISN'T
	LD	A,(DE)		;GET DATA BYTE FROM DISK
	LD	(BC),A		;STORE BYTE IN BUFFER
	INC	BC		;BUMP BUFFER POINTER
	JP	SECTRL-O	;LOOP BACK FOR NEXT BYTE
;
;
; DONE READING - GET FINAL STATUS AND RETURN
;590E (4573)
SECTRX:	LD	A,(HL)		;GET FINAL STATUS TO A
	AND	01011100B	;MASK TO ERROR BITS
	POP	DE		;RECOVER TRACK AND SECTOR
	RET	Z		;RETURN IF NO ERRORS
	LD	(HL),WDFORC	;ELSE FORCE INTERRUPT
	RET
;
;
; DISPLAY A MESSAGE STRING
; ENTRY:  HL      - POINTER TO STRING
;5916 (457B)
MSGOUT:	PUSH	HL		;SAVE MESSAGE POINTER
MSGOUL:	LD	A,(HL)		;GET CHARACTER FROM STRING
	CP	CC		;TEST IF MESSAGE END
	JR	Z,MSGOUX	;EXIT IF END OF STRING
	CALL	VDCHAR		;ELSE DISPLAY THE CHARACTER
	INC	HL		;BUMP MESSAGE POINTER
	CP	CR		;TEST IF MESSAGE END
	JR	NZ,MSGOUL	;LOOP FOR NEXT CHARACTER
MSGOUX:	POP	HL		;RECOVER MESSAGE POINTER
	RET
;
;
; PROGRAM MESSAGE STRINGS
;5926 (458B)
COPTKM	Db	BL,'COPYING   TRACK 00, SECTOR 00',CC
;
;
; DEFINE OFFSET TO TRACK IN COPY STRING
;5937 (459C)
COPTKT	Equ	$-14		;DEFINE THE OFFSET
;
;
; DEFINE OFFSET TO SECTOR IN COPY STRING
;5942 (45A7)
COPTKS	Equ	$-3		;DEFINE THE OFFSET
;
;
; MORE MESSAGES
;5945 (45AA)
VFYTKM	Db	BL,'VERIFYING TRACK 00, SECTOR 00',CC
;
;
; DEFINE OFFSET TO TRACK IN VERIFY STRING
;5956 (45BB)
VFYTKT	Equ	$-14		;DEFINE THE OFFSET
;
;
; DEFINE OFFSET TO SECTOR IN VERIFY STRING
;5961 (45C6)
VFYTKS	Equ	$-3		;DEFINE THE OFFSET
;
;
; MORE MESSAGES
;5964 (45C9)
LODTKM	Db	BL,'LOADING   TRACK 00, SECTOR 00',CC
;
;
; DEFINE OFFSET TO TRACK IN LOAD STRING
;5975 (45DA)
LODTKT	Equ	$-14		;DEFINE THE OFFSET
;
;
; DEFINE OFFSET TO SECTOR IN LOAD STRING
;5980 (45E5)
LODTKS	Equ	$-3		;DEFINE THE OFFSET
;
;
; MORE MESSAGES
;5983 (45E8)
SRCRDM	Db	LF,'SOURCE DISK READ ERROR!',CR
DSTRDM	Db	LF,'DESTINATION DISK READ ERROR!',CR
DSTWRM	Db	LF,'DESTINATION DISK WRITE ERROR!',CR
WRPROM	Db	LF,'DESTINATION DISK IS WRITE PROTECTED!',CR
INSSDM	Db	BL,EE,'INSERT SOURCE DISK  (ENTER)',BL,CC
INSDDM	Db	BL,EE,'INSERT DESTINATION DISK  (ENTER)',BL,CC
WAKUPM	Db	BL,EE,"W A K E   U P !!!  THAT'S NOT THE SAME SOURCE DISK !",CR
BAKCOM	Db	LF,'BACKUP COMPLETE',CR
HITENM	Db	LF,LF,"HIT 'ENTER' TO BOOT DOS",CR
;
;
; STORAGE FOR DIRECTORY TRACK NUMBER 139b
;5AA4 (4709)
DIRTRK	Ds	1		;RESERVE THE SPACE
;
;
; INPUT BUFFER FOR BACKUP DATE STRING
;5AA5 (470A)
DTEBUF	Ds	2		;DECIMAL ASCII MONTH STORAGE
	Ds	1		;ASCII DELIMITER
	Ds	2		;DECIMAL ASCII DAY STORAGE
	Ds	1		;ASCII DELIMITER
	Ds	2		;DECIMAL ASCII YEAR STORAGE
;
;
; STORAGE LOCATIONS FOR SECTOR COPY
;5AAE (4713)
	Org	5AAEH
;
COPYBS	Db	0		;COPY BUFFER SIZE IN TRACKS
XFRCNT	Db	0		;NUMBER OF TRACKS TRANSFERED
;
;
; RESERVE SPACE UPTO BUFFERS
;
	Ds	235		;RESERVE THE SPACE
;
;
; STORAGE BUFFER FOR TRACK FORMAT TYPES
;5B9B (4800)
TRKTYP	Ds	256		;RESERVE THE SPACE
;
;
; GRANULE ALLOCATION TABLE (GAT) SECTOR BUFFER
;5C9B (4900)
GATSEC	Ds	256		;RESERVE THE SPACE
;
;
; DEFINE TRACK LOCK-OUT TABLE OFFSET
;5CFB (4960)
GASLOT	Equ	GATSEC+060H	;DEFINE THE OFFSET
;
;
; DEFINE DISK MASTER PASSWORD OFFSET
;5D69 (49CE)
GASMPW	Equ	GATSEC+0CEH	;DEFINE THE OFFSET
;
;
;DEFINE CREATION DATE STRING OFFSET
;5D73 (49D8)
GASCRD	Equ	GATSEC+0D8H	;DEFINE THE OFFSET
;
;
; GRANULE ALLOCATION TABLE (GAT) SECTOR BUFFER
;5D9B (4A00)
GATBUF	Ds	256		;RESERVE THE SPACE
;
;
; DEFINE TRACK LOCK-OUT TABLE OFFSET
;5DFB (4A60)
LOCKTB	Equ	GATBUF+060H	;DEFINE THE OFFSET
;
;
; DEFINE BCD DOS VERSION NUMBER OFFSET
;5E66 (4ACB)
DOSVER	Equ	GATBUF+0CBH	;DEFINE THE OFFSET
;
;
; DEFINE DISK MASTER PASSWORD OFFSET
;5E69 (4ACE)
MASTPW	Equ	GATBUF+0CEH	;DEFINE THE OFFSET
;
;
; HASH INDEX TABLE (HIT) SECTOR BUFFER
;5E9B (4B00)
HITBUF	Ds	256		;RESERVE THE SPACE
;
;
; DEFINE OFFSET INTO BOOT SECTOR TO DIRECTORY TRACK NUMBER
;5E9D (4B02)
BOOTDT	Equ	HITBUF+002H	;DEFINE THE OFFSET
;
;
; DEFINE MASTER PASSWORD OFFSET
;5F69 (4BCE)
HISMPW	Equ	HITBUF+0CEH	;DEFINE THE OFFSET
;
;
; DEFINE LENGTH OF CODE TO BE MOVED TO 'SYSBUF' AND UP
;
LENREL	Equ	$+SCTSIZ-BACKIT	;DEFINE THE LENGTH
;
;
; PROGRAM MESSAGE STRINGS
;
	Org	5F9BH
;
INVDCM	Db	'SINGLE DRIVE BACKUP INVALID DURING PROGRAM CHAINING!',CR
SIGNOM	Db	HO,CE,'TRSDOS DISK BACKUP UTILITY   VER 2.3',LF,CR
WHICSM	Db	'SOURCE DRIVE NUMBER ? ',CC
WHICDM	Db	'DESTINATION DRIVE NUMBER ? ',CC
BACKDM	Db	'BACKUP DATE (DD/MM/YY) ? ',CC
SDNRDM	Db	'SOURCE DRIVE NOT READY!',CR
SDNISM	Db	'SOURCE DRIVE NOT IN SYSTEM!',CR
DDNRDM	Db	'DESTINATION DRIVE NOT READY!',CR
DDNISM	Db	'DESTINATION DRIVE NOT IN SYSTEM!',CR
NODSKM	Db	'NO DISKETTE IN DESTINATION DRIVE!',CR
OPDORM	Db	'DOOR NOT CLOSED ON DESTINATION DRIVE!',CR
HASECM	Db	'DESTINATION DISKETTE UNUSABLE! HARD-SECTORED!',CR
FORMRM	Db	'FORMAT REQUIRED, DISKETTES CONTAIN DIFFERENT PACK IDS!',CR
FMTTKM	Db	BL,'FORMATTING TRACK 00',CC
;
;
; DEFINE OFFSET TO TRACK IN FORMAT STRING
;6176
FMTTKT	Equ	$-3		;ASCII TRACK NUMBER
;
;
; FURTHER MESSAGES
;6179
TRFASM	Db	LF,"CAN'T FORMAT, DISK TRANSFER RATE TOO FAST!",CR
MSLOWM	Db	LF,"CAN'T FORMAT, MOTOR SPEED TOO SLOW!",CR
MFASTM	Db	LF,"CAN'T FORMAT, MOTOR SPEED TOO FAST!",CR
NOTFOM	Db	': NOT FOUND! TRACK LOCKED OUT!',CR
CRCERM	Db	': CRC ERROR! TRACK LOCKED OUT!',CR
REJECM	Db	LF,'BACKUP REJECTED DUE TO FLAWS ON DESTINATION DISK!',CR
VFYSLM	Db	LF,"CAN'T VERIFY FORMAT, DISK TRANSFER RATE TOO FAST!",CR
;
;
; SECTOR SKEW TABLE (SKEW OF 5)
;6293
SKEWTB	Db	0,5,1,6,2,7,3,8,4,9,-1
;
;
; ALIGN TRACK IMAGE BUFFER ON A PAGE BOUNDARY
;629E
	Ds	256 - $ And 255	;RESERVE THE SPACE
;
;
; WRITE TRACK (FORMAT BUFFER)
;6300
TRKBUF	Ds	TRKSIZ		;RESERVE THE SPACE
;
;
; DEFAULT VIDEO DRIVER ENTRY ADDRESS
;
	Org	0401EH
;
	Dw	VIDRVR		;SET THE DEFAULT
;
;
; DEFAULT PRINTER DRIVER ENTRY ADDRESS
;
	Org	04026H
;
	Dw	PRDRVR		;SET THE DEFAULT
;
	End	BACKUP
