	Title	'TRSDOS 2.3 Boot Record'
;
;
; TRSDOS OPERATING SYSTEM, VERSION 2.3 - BOOT RECORD
;
; COPYRIGHT BY TANDY CORPORATION
;
; MUST BY LOCATED ON TRACK ZERO, SECTOR ZERO
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON, 04.01.2022
;
;
; ASCII EQUATES
;
CC	Equ	  3		;CONTROL-C (END-OF-MESSAGE)
CR	Equ	 13		;CARRIAGE RETURN
NA	Equ	 23		;SWITCH TO NARROW SCREEN
HO	Equ	 28		;HOME DISPLAY CURSOR
CE	Equ	 31		;CLEAR TO SCREEN END
CO	Equ	192		;SPACE COMPRESSION (0 TO 63)
;
;
; DEFAULT FLOPPY DISK CONSTANTS
;
NUMSEC	Equ	10		;SECTORS PER TRACK
DIRECT	Equ	17		;DIRECTORY TRACK
SYSZER	Equ	4		;SYS0/SYS DIR ENTRY SECTOR
RECSIZ	Equ	256		;SECTOR SIZE IN BYTES
;
;
; DEFINE INDICES INTO SECTOR BUFFER
;
LAS	Equ	RECSIZ-1	;LAST BYTE OF BUFFER
GAP	Equ	22		;INDEX TO FIRST 'GAP'
;
;
; WD1771 FLOPPY DISK CONTROLLER COMMAND CODES
;
WDSEEK	Equ	00011011B	;SEEK TO TRACK
WDREAD	Equ	10001000B	;READ SECTOR
WDFORC	Equ	11010000B	;FORCE INTERRUPT
;
;
; HARDWARE PORT ADDRESSES
;
DRVREG	Equ	037E1H		;FLOPPY DRIVE SELECT REGISTER
CSTREG	Equ	037ECH		;FLOPPY STATUS/COMMAND REGISTER
SCTREG	Equ	037EEH		;FLOPPY SECTOR REGISTER
DTAREG	Equ	037EFH		;FLOPPY DATA REGISTER
;
;
; LEVEL II BASIC ROM ROUTINE ADDRESSES
;
VDCHAR	Equ	00033H		;VIDEO DRIVER ENTRY
KBLINE	Equ	00040H		;GET KEYBOARD LINE
;
;
; STORAGE LOCATIONS IN TRSDOS NUCLEUS (SYS0/SYS)
;
STACKT	Equ	041FCH		;TOP OF STACK
GATBUF	Equ	04D00H		;SECTOR BUFFER
;
;
	Org	04200H
;
BOOTLD:	Db	000H		;SIGNATURE/RECORD TYPE (NOP)
	Db	0FEH		;SIGNATURE/RECORD SIZE (CP)
DIRTRK	Db	DIRECT		;DIRECTORY TRACK NUMBER
;
;
; START OF MAIN BOOT LOADER CODE
;
	DI			;DISABLE INTERRUPTS
	LD	SP,STACKT	;LOAD TOP OF STACK
	LD	HL,CLRSCM	;SCREEN CLEAR MESSAGE POINTER
	CALL	DISMES		;CLEAR THE TERMINAL SCREEN
	LD	A,00000001B	;LOAD DRIVE SELECT CODE
	LD	(DRVREG),A	;SELECT DRIVE ZERO
	LD	A,(DIRTRK)	;GET DIRECTORY TRACK TO A
	LD	D,A		;COPY THE TRACK TO D
	LD	E,SYSZER	;SYS0/SYS DIR ENTRY SECTOR
	LD	BC,GATBUF	;POINT AT SYSTEM BUFFER
	CALL	READSE		;READ THE DIRECTORY SECTOR
	JR	NZ,DERROR	;ABORT IF READ ERROR
	LD	A,(GATBUF)	;GET FIRST ENTRY BYTE
	AND	00010000B	;ISOLATE ENTRY OCCUPIED BIT
	LD	HL,NOSYSM	;ASSUME NO SYSTEM INSTALLED
	JR	Z,MSGHLT	;ABORT IF NOT A SYSTEM DISK
	EXX			;SWAP TO ALTERNATE REGISTERS
	LD	HL,(GATBUF+GAP)	;GET FIRST 'GAP' FOR SYS0/SYS
	LD	D,L		;GET TRACK NUMBER TO D
	LD	A,H		;BYTE COUNT AND SECTOR OFFSET
	RLCA			;COPY SECTOR OFFSET
	RLCA			; IN BITS SEVEN TO FIVE
	RLCA			;  INTO BITS THREE TO ONE
	AND	00000111B	;ISOLATE OFFSET BITS
	LD	H,A		;SAVE RESULT FOR LATER
	RLCA			;MULTIPLY BY TWO
	RLCA			;MULTIPLY BY FOUR
	ADD	A,H		;MULTIPLY BY FIVE = 0 to x5
	LD	E,A		;GET SECTOR NUMBER TO E'
	LD	BC,GATBUF+LAS	;END OF BUFFER TO FORCE READ
	EXX			;SWAP TO MAIN REGISTERS
;
;
; READ A LOAD FORMAT FILE INTO MEMORY AND EXECUTE
;
READLF:	CALL	BYTINP		;GET BYTE FROM INPUT FILE
	DEC	A		;TEST IF DATA RECORD HEADER
	JR	NZ,TSTEXE	;IF NOT TEST FOR OTHER TYPES
;
;
; WE HAVE A DATA RECORD - LOAD THE DATA BLOCK
;
	CALL	BYTINP		;LOAD RECORD SIZE TO A
	LD	B,A		;COPY BLOCK SIZE TO B
	CALL	BYTINP		;GET LOAD ADDRESS LSB TO A
	LD	L,A		;COPY ADDRESS BYTE TO L
	DEC	B		;DECREMENT BYTE COUNT
	CALL	BYTINP		;GET LOAD ADDRESS MSB TO A
	LD	H,A		;COPY ADDRESS BYTE TO H
READAT:	DEC	B		;DECREMENT BYTE COUNT
	JR	Z,READLF	;GET NEXT RECORD IF DONE
	CALL	BYTINP		;READ DATA BYTE FROM FILE
	LD	(HL),A		;STORE THE BYTE IN MEMORY
	INC	HL		;BUMP MEMORY POINTER
	JR	READAT		;THEN LOOP FOR NEXT BYTE
;
;
; TEST IF RECORD TYPE IS EXECUTION HEADER
;425B
TSTEXE:	DEC	A		;TEST IF EXECUTION HEADER
	JR	Z,RUNFIL	;THEN EXECUTE LOADED FILE
;
;
; ALL OTHER RECORD TYPES ARE ASSUMED A COMMENT
;
	CALL	BYTINP		;LOAD RECORD SIZE TO A
	LD	B,A		;COPY BLOCK SIZE TO B
SKIPCO:	CALL	BYTINP		;READ AND DISCARD THE BYTE
	DJNZ	SKIPCO		;LOOP UNTIL ALL READ
	JR	READLF		;GET NEXT RECORD IF DONE
;
;
; WE HAVE AN EXECUTION ADDRESS RECORD - EXECUTE LOADED FILE
;4269
RUNFIL:	CALL	BYTINP		;READ AND DISCARD BYTE COUNT
	CALL	BYTINP		;READ EXECUTION ADDRESS LSB
	LD	L,A		;COPY ADDRESS BYTE TO L
	CALL	BYTINP		;READ EXECUTION ADDRESS MSB
	LD	H,A		;COPY ADDRESS BYTE TO H
	JP	(HL)		;EXECUTE THE LOADED FILE
;
;
; GET NEXT CHARACTER FROM BUFFER - REFILL BUFFER IF NEEDED
; ENTRY:  BC'     - BUFFER POINTER
;         D'      - TRACK NUMBER
;         E'      - SECTOR NUMBER
; EXIT:   BC'     - INCREMENTED MODULO 256
;         D'      - INCREMENTED IF LAST SECTOR DONE
;         E'      - INCREMENTED MODULO 10
;4275
BYTINP:	EXX			;SWAP TO ALTERNATE REGISTERS
	INC	C		;BUMP BUFFER POINTER LSB
	JR	NZ,BYTINX	;SKIP IF NOT TIME TO READ
	PUSH	BC		;ELSE SAVE BUFFER POINTER
	LD	A,00000001B	;LOAD DRIVE SELECT CODE
	LD	(DRVREG),A	;SELECT THE DISK DRIVE
	CALL	READSE		;READ NEXT SECTOR
	JR	NZ,DERROR	;ABORT IF READ ERROR
	POP	BC		;RECOVER BUFFER POINTER
	INC	E		;BUMP SECTOR NUMBER
	LD	A,E		;GET SECTOR NUMBER TO A
	SUB	NUMSEC		;TEST IF DONE WITH TRACK
	JR	NZ,BYTINX	;SKIP IF MORE SECTORS TO GO
	LD	E,A		;ELSE SET TO SECTOR ZERO
	INC	D		;AND BUMP TRACK NUMBER
BYTINX:	LD	A,(BC)		;LOAD A BYTE FROM THE BUFFER
	EXX			;SWAP BACK TO MAIN REGISTERS
	RET
;
;
; A DISK ERROR OCCURRED _ DISPLAY MESSAGE AND HALT
;4290
DERROR:	LD	HL,DERROM	;POINT AT ERROR MESSAGE
;
;
; DISPLAY A MESSAGE STRING AND HALT THE COMPUTER
; ENTRY:  HL      - POINTER TO MESSAGE
;4293
MSGHLT:	CALL	DISMES		;DISPLAY THE STRING
	CALL	KBLINE		;GET A KEYBOARD LINE
	HALT			;THEN HALT THE COMPUTER
;
;
; DISPLAY A MESSAGE STRING
; TERMINATOR IS EITHER CONTROL-C OR CARRIAGE RETURN
; ENTRY:  HL      - POINTER TO THE STRING
;429A
DISMES:	PUSH	HL		;SAVE MESSAGE POINTER
DISMEL:	LD	A,(HL)		;GET CHARACTER FROM STRING
	CP	CC		;TEST IF MESSAGE TERMINATOR
	JR	Z,DISMEX	;THEN WE EXIT PROMPTLY
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	INC	HL		;BUMP STRING POINTER
	CP	CR		;TEST IF MESSAGE TERMINATOR
	JR	NZ,DISMEL	;LOOP FOR NEXT IF NOT
DISMEX:	POP	HL		;RECOVER MESSAGE POINTER
	RET
;
;
; READ A DISK SECTOR - RETRY ONCE
; ENTRY:  BC      - BUFFER POINTER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - RESULT FLAGS
;         BC      - POINTER AT BYTE AFTER BUFFER
;         D       - UNCHANGED TRACK NUMBER
;         E       - UNCHANGED SECTOR NUMBER
;         HL      - PREVIOUS BUFFER POINTER
;         ZF      - SET IF SUCCESSFULE READ, ELSE RESET
;42AA
READSE:	PUSH	BC		;SAVE BUFFER POINTER
	CALL	SEREAD		;TRY READING THE SECTOR
	POP	HL		;RECOVER BUFFER POINTER
	RET	Z		;DONE IF SUCCESSFUL READ
	LD	B,H		;BUFFER POINTER MSB TO B
	LD	C,L		;BUFFER POINTER LSB TO C
;
;
; READ A DISK SECTOR
; ENTRY:  BC      - BUFFER POINTER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - RESULT FLAGS
;         BC      - POINTER AT BYTE AFTER BUFFER
;         D       - UNCHANGED TRACK NUMBER
;         E       - UNCHANGED SECTOR NUMBER
;         HL      - POINTER TO FLOPPY COMMAND/STATUS REGISTER
;         ZF      - SET IF SUCCESSFULE READ, ELSE RESET
;42B2
SEREAD:	LD	(SCTREG),DE	;STORE TRACK AND SECTOR
	LD	HL,CSTREG	;COMMAND/STATUS REGISTER
	LD	(HL),WDSEEK	;STORE SEEK TO TRACK COMMAND
	PUSH	AF		;DELAY FOR A BIT
	POP	AF		;DELAY SOME MORE
	PUSH	AF		;DELAY A LITTLE LONGER
	POP	AF		;DO THE LAST DELAY
WAITNB:	LD	A,(HL)		;GET CONTROLLER STATUS TO A
	RRCA			;COPY BUSY BIT TO CARRY
	JR	C,WAITNB	;LOOP UNTIL CONTROLLER NOT BUSY
	LD	(HL),WDREAD	;STORE READ SECTOR COMMAND
	PUSH	DE		;SAVE TRACK AND SECTOR
	LD	DE,DTAREG	;POINT AT DATA REGISTER
	PUSH	BC		;DELAY A LITTLE BIT
	POP	BC		;DELAY SOME MORE
	JR	RLUPEN		;THEN ENTER READ LOOP
WAIRDY:	RRCA			;COPY BUSY BIT TO CARRY
	JR	NC,DONERD	;EXIT IF ALL DONE READING
NXTBYT:	LD	A,(HL)		;GET CONTROLLER STATUS TO A
	BIT	1,A		;TEST DATA READY BIT
	JR	Z,WAIRDY	;TEST IF DONE IF NO DATA
	LD	A,(DE)		;ELSE READ THE DATA BYTE
	LD	(BC),A		;STORE BYTE IN BUFFER
	INC	BC		;BUMP BUFFER POINTER
RLUPEN:	JR	NXTBYT		;THEN LOOP FOR NEXT BYTE
;
;
; DONE READING - TEST FOR ERRORS
; EXIT;   A       - FLOPPY CONTROLLER STATUS FLAGS
;         ZF      - RESET IF SUCCESS, RESET IF ERROR
;42DA
DONERD:	LD	A,(HL)		;GET FINAL STATUS TO A
	AND	01011100B	;MASK TO ERROR BITS
	POP	DE		;RECOVER TRACK AND SECTOR
	RET	Z		;DONE IF SUCCESSFUL READ
	LD	(HL),WDFORC	;RESET FLOPPY CONTROLLER
	RET
;
;
; CLEAR THE SCREEN MESSAGE
;42E2
CLRSCM	Db	HO		;HOME DISPLAY CURSOR
	Db	CE		;CLEAR TO SCREEN END
	Db	CC		;MESSAGE TERMINATOR
;
;
; OPERATING SYSTEM NOT FOUND MESSAGE
;42E5
NOSYSM	Db	NA		;SWITCH TO NARROW SCREEN
	Db	CO+40		;OUTPUT FOURTY SPACES
	Db	'NO SYSTEM'
	Db	CR		;MESSAGE TERMINATOR
;
;
; SOME SORT OF UNSPECIFIED DISK ERROR OCCURRED
;42F1
DERROM	Db	NA		;SWITCH TO NARROW SCREEN
	Db	CO+40		;OUTPUT FOURTY SPACES
	Db	'DISK ERROR'
	Db	CR		;MESSAGE TERMINATOR
;
;
; UNUSED OR UNKNOWN BYTES
;
	Db	0EBH,05FH	;DEFINE THE BYTES
;
	End	BOOTLD
