	Title	'TRSDOS 2.3 Format Utility'
;
;
; TRSDOS OPERATING SYSTEM, VERSION 2.3 - FORMAT UTILITY
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON, 27.12.2021
;
;
; ASCII EQUATES
;
CC	Equ	  3		;CONTROL-C (END-OF-MESSAGE)
LF	Equ	 10		;LINE FEED
CR	Equ	 13		;CARRIAGE RETURN
NA	Equ	 23		;SWITCH TO NARROW SCREEN
HO	Equ	 28		;HOME DISPLAY CURSOR
BL	Equ	 29		;TO LINE START
EE	Equ	 30		;ERASE TO END OF LINE
CE	Equ	 31		;CLEAR TO SCREEN END
CO	Equ	192		;SPACE COMPRESSION (0 TO 63)
;
;
; DEFAULT FLOPPY DISK CONSTANTS
;
NUMDRV	Equ	4		;DRIVES PER SYSTEM
LASDRV	Equ	NUMDRV - 1	;LAST DRIVE NUMBER
NUMTRK	Equ	40		;TRACKS PER DISK
LASTRK	Equ	NUMTRK - 1	;LAST TRACK NUMBER
NUMSEC	Equ	10		;SECTORS PER TRACK
LASSEC	Equ	NUMSEC - 1	;LAST SECTOR NUMBER
FIRSEC	Equ	0		;FIRST SECTOR NUMBER
DIRECT	Equ	17		;DIRECTORY TRACK
;
;
; DEFINE LAST DISK TRACK IN EIGHT MSB'S OF WORD
;
LASTHI	Equ	LASTRK Shl 8	;DEFINE THE WORD
;
;
; DEFINE LAST DISK TRACK IN MSB AND FIRST SECTOR IN LSB
;
LATFIS	Equ	LASTHI+FIRSEC	;DEFINE THE WORD
;
;
; CONTROL BYTES FOR INITIALIZATION (FORMATTING)
;
FILMRK	Equ	0E5H		;SECTOR FILL BYTE
CRCMRK	Equ	0F7H		;WRITE CRC ADDRESS MARK
LOKMRK	Equ	0F9H		;LOCKED TRACK ADDRESS MARK
DIRMRK	Equ	0FAH		;DIRECTORY ADDRESS MARK
DTAMRK	Equ	0FBH		;DATA ADDRESS MARK
IDXMRK	Equ	0FCH		;INDEX ADDRESS MARK
IDAMRK	Equ	0FEH		;IDENTITY ADDRESS MARK
;
;
; WD1771 FLOPPY DISK CONTROLLER COMMAND CODES
;
WDHOME	Equ	00001011B	;RESTORE TO TRACK ZERO
WDSEEK	Equ	00011011B	;SEEK TO TRACK
WDSTIN	Equ	01011011B	;STEP IN TO TRACK
WDREAD	Equ	10001000B	;READ SECTOR
WDWRIT	Equ	10101000B	;WRITE DATA SECTOR
WDWRID	Equ	10101001B	;WRITE DIRECTORY SECTOR
WDFORC	Equ	11010000B	;FORCE INTERRUPT
WDWTRK	Equ	11110100B	;WRITE TRACK
;
;
; HARDWARE PORT ADDRESSES
;
MDRVRE	EQU	037B6H		;MANGLED DRIVE SELECT REGISTER
DRVREG	Equ	037E1H		;FLOPPY DRIVE SELECT REGISTER
CSTREG	Equ	037ECH		;FLOPPY STATUS/COMMAND REGISTER
TRKREG	Equ	037EDH		;FLOPPY TRACK REGISTER
SCTREG	Equ	037EEH		;FLOPPY SECTOR REGISTER
DTAREG	Equ	037EFH		;FLOPPY DATA REGISTER
KROSEV	Equ	03840H		;KEYBOARD <BREAK> KEY ROW
;
;
; LEVEL II BASIC ROM ROUTINE ADDRESSES
;
VDCHAR	Equ	00033H		;VIDEO DRIVER ENTRY
KBLINE	Equ	00040H		;INPUT AND FILL INPUT BUFFER
DELAYL	Equ	00060H		;DELAY ROUTINE
VIDRVR	Equ	00458H		;ROM VIDEO DISPLAY DRIVER
PRDRVR	Equ	0058DH		;ROM PRINTER DRIVER
;
;
; STORAGE LOCATIONS IN TRSDOS NUCLEUS (SYS0/SYS)
;
CLKMON	EQU	04046H		;MONTH
STACKT	EQU	041FCH		;TOP OF SYSTEM STACK
SYSBUF	Equ	04200H		;BOOT LOADER LOCATION
SYSCON	Equ	0430FH		;SYSTEM CONDITION FLAGS
SCTBUF	Equ	04D00H		;SYSTEM SECTOR BUFFER
;
;
; FUNCTIONS ADDRESSES IN TRSDOS NUCLEUS (SYS0/SYS)
;
ERRENT	Equ	04030H		;ERROR ENTRY
DOPMSG	Equ	04467H		;DISPLAY MESSAGE STRING
GETDTE	Equ	04470H		;GET SYSTEM DATE STRING
;
;
; DEFINE SECTOR SIZE AND FORMATTED TRACK SIZE
;
SCTSIZ	Equ	256		;DISK SECTOR SIZE IN BYTES
SIZTRK	Equ	SCTSIZ*NUMSEC	;SIZE OF A TRACK OF SECTORS
TRKSIZ	Equ	3053		;TRACK SIZE IN BYTES
TRKOSI	Equ	TRKSIZ+124	;MAXIMUM TRACK OVERFLOW SIZE
;
;
; PROGRAM MODULE NAME STRING
;
	Nam	'FORMAT'
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING
;
	Rem	CR
	Rem	'* * * N O T I C E * * *',CR
	Rem	'* PROPRIETARY PROGRAM *',CR
	Rem	'* COPYRIGHT (c) 1979  *',CR
	Rem	'* BY TANDY CORPORATION*',CR
	Rem	'*  FORT WORTH, TEXAS  *',CR
	Rem	'* ALL RIGHTS RESERVED *',CR
	Rem	'* * * N O T I C E * * *',CR
;
;
	Org	05200H
;
FORMAT:	DI			;DISABLE INTERRUPTS
	LD	SP,STACKT	;LOAD TOP OF STACK
	PUSH	HL		;SAVE HL REGISTER
	LD	A,(ERRENT)	;BYTE FROM ERROR HANDLER START
	CP	0C7H		;TEST IF 'RST 00H' - BOOT
	JR	Z,FORMCO	;THEN CONTINUE IF IT IS
	LD	A,(SYSCON)	;GET SYSTEM CONDITION FLAGS
	BIT	5,A		;TEST PROGRAM CHAINING ACTIVE
	JR	Z,FORMCO	;CONTINUE IF INACTIVE
	LD	HL,INVDCM	;POINT AT INVALID MESSAGE
	CALL	DOPMSG		;DISPLAY THE MESSAGE STRING
	JP	ERRENT		;THEN ABORT TO DOS ERROR
FORMCO:	LD	HL,BOOTSE	;POINT AT BOOT SECTOR IMAGE
	LD	DE,SYSBUF	;POINT AT SYSTEM BUFFER
	LD	BC,SCTSIZ	;LOAD SECTOR BYTE COUNT
	LDIR			;COPY BOOT SECTOR TO BUFFER
	LD	HL,SIGNOM	;POINT AT SIGN-ON STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	POP	HL		;CLEAN UP THE STACK
FORMDP:	LD	HL,WHICDM	;POINT AT DRIVE PROMPT
	CALL	MSGOUT-O	;DISPLAY THE PROMPT
	LD	HL,HITBUF	;POINT AT INPUT BUFFER
	LD	B,1		;LOAD INPUT LINE LENGTH
	CALL	KBLINE		;READ KEYBOARD LINE
	LD	A,(HL)		;GET DRIVE CODE TO A
	SUB	'0'		;REMOVE ASCII BIAS
	JP	C,FORMDP	;PROMPT AGAIN IF INVALID
	CP	NUMDRV		;TEST IF DRIVE IN RANGE
	JP	NC,FORMDP	;PROMPT AGAIN IF INVALID
	RLCA			;ROTATE THREE
	RLCA			; BITS TO
	RLCA			;  THE LEFT
	OR	11000111B	;MAKE INTO A 'SET' OP-CODE
	LD	(FORMBS),A	;STORE THE BIT SET VALUE
	XOR	A		;ZERO ACCUMULATOR
	SET	0,A		;SET  DRIVE SELECT BIT
FORMBS	Equ	$-1		;DRIVE SELECT OP-CODE
	LD	(SELDRN),A	;SAVE FORMAT DRIVE CODE
	CALL	SELDRV		;SELECT DISKETTE DRIVE
	CALL	HOMHED		;HOME DISK DRIVE HEAD
	LD	BC,0		;LOAD ONE SECOND DELAY VALUE
	CALL	DELAYL		;CALL BASIC ROM TO DELAY
FORMBU:	LD	A,(CSTREG)	;GET DISK CONTROLLER STATUS
	BIT	0,A		;TEST IF CONTROLLER BUSY
	JR	NZ,FORMBU	;LOOP UNTIL NOT BUSY
	LD	HL,DNRDYM	;DRIVE NOT READY MESSAGE
	BIT	7,A		;TEST IF CONTROLLER READY
	JP	NZ,ABORTM	;ABORT IF DRIVE NOT READY
	LD	HL,DRNISM	;DRIVE NOT IN SYSTEM MESSAGE
	BIT	2,A		;TEST IF AT TRACK ZERO
	JP	Z,ABORTM	;NO DRIVE IF NOT THERE
FORMDN:	LD	HL,DNAMEM	;POINT AT DISK NAME PROMPT
	CALL	MSGOUT-O	;DISPLAY PROMPT STRING
	LD	HL,DNAMIM	;GET POINTER TO DISK NAME
	LD	DE,DSKNAM	;POINT AT GAT NAME LOCATION
	LD	BC,8		;LOAD LENGTH OF EMPTY NAME
	LDIR			;COPY INTO GAT SECTOR IMAGE
	LD	HL,HITBUF	;POINT AT INPUT BUFFER
	LD	B,8		;LOAD MAXIMUM STRING LENGTH
	CALL	KBLINE		;READ KEYBOARD LINE
	LD	A,B		;GET LENGTH OF INPUT STRING
	OR	A		;TEST IF EMPTY STRING
	JR	Z,FORMDN	;PROMPT AGAIN IF EMPTY
	LD	C,B		;GET STRING LENGTH TO C
	LD	B,0		;NOW BC HAS THE LENGTH
	LD	DE,DSKNAM	;POINT AT DISK NAME LOCATION
	LDIR			;COPY DISK NAME TO GAT SECTOR
FORMCD:	LD	HL,CREADM	;POINT AT CREATION DATE PROMPT
	CALL	MSGOUT-O	;DISPLAY PROMPT STRING
	LD	HL,HITBUF	;POINT AT INPUT BUFFER
	LD	B,8		;LOAD MAXIMUM LINE LENGTH
	CALL	KBLINE		;READ A LINE OF INPUT
	LD	A,B		;GET INPUT LINE SIZE
	CP	8		;TEST IF CORRECT LENGTH
	JP	NZ,FORMCD	;PROMPT AGAIN IF NOT CORRECT
	LD	A,(HITBUF+2)	;GET DELIMITER TO A
	CP	'/'		;TEST IF CORRECT DELIMITER
	JP	NZ,FORMCD	;PROMPT AGAIN IF INCORRECT
	LD	A,(HITBUF+5)	;GET DELIMITER TO A
	CP	'/'		;TEST IF CORRECT DELIMITER
	JP	NZ,FORMCD	;PROMPT AGAIN IF INCORRECT
	LD	C,B		;GET STRING LENGTH TO C
	LD	B,0		;NOW BC HAS THE LENGTH
	LD	DE,DSKDAT	;POINT AT CREATION DATE IN GAT
	LD	HL,HITBUF	;POINT AT INPUT LINE BUFFER
	LDIR			;COPY DATE STRING TO GAT
FORMPW:	LD	HL,MASPWM	;MASTER PASSWORD PROMPT STRING
	CALL	MSGOUT-O	;DISPLAY THE PROMPT STRING
	LD	HL,HITBUF	;POINT TO INPUT BUFFER
	LD	B,8		;LOAD MAXIMUM LINE LENGTH
	CALL	KBLINE		;READ A LINE OF INPUT
	LD	A,B		;GET INPUT LINE SIZE
	OR	A		;TEST IF EMPTY STRING
	JR	Z,FORMPW	;PROMPT AGAIN IF EMPTY
	EX	DE,HL		;SWAP STRING POINTER TO DE
	ADD	A,E		;INDEX TO PASSWORD END
	LD	L,A		;COPY RESULT TO L
	LD	A,D		;GET POINTER MSB TO A
	ADC	A,0		;ADD ANY CARRY TO MSB
	LD	H,A		;HL POINTS AT STRING END
	LD	A,8		;LOAD MAXIMUM LINE LENGTH
	SUB	B		;SUBTRACT PASSSWORD LENGTH
	LD	B,A		;REMAINING CHARACTER COUNT TO B
FORMPS:	LD	(HL),' '	;PAD OUT WITH SPACES
	INC	HL		;BUMP STRING POINTER
	DJNZ	FORMPS		;LOOP UNTIL ALL PADDED
	CALL	PWHASH		;COMPUTE MASTER PASSWORD HASH
	LD	(DISKPW),HL	;STORE THE MASTER PASSWORD
	JR	CLRGAT		;THEN GO SETUP GAT SECTOR
;
;
; COMPUTE MASTER PASSWORD HASH CODE
; ENTRY:  DE      - POINTER TO PASSWORD BUFFER
; EXIT:   HL      - ENCODED PASSWORD
;52F6
PWHASH:	LD	HL,-1		;MASK VALUE USED FOR ENCODE
	LD	B,8		;MAXIMUM CHARACTER COUNT
	LD	A,E		;PASSWORD BUFFER POINTER LSB
	ADD	A,7		;POSITION AT END OF BUFFER
	LD	E,A		;COPY RESULT BACK TO E
	JR	NC,PWHASL	;SKIP IF NOT OVERFLOW
	INC	D		;ELSE BUMP MSB OF POINTER
PWHASL:	LD	A,(DE)		;GET CHARACTER FROM BUFFER
	PUSH	DE		;SAVE BUFFER POINTER
	LD	D,A		;SAVE THE CHARACTER IN D
	LD	E,H		;LOAD FIRST MARK VALUE TO E
	LD	A,L		;LOAD SECOND MARK VALUE TO A
	AND	00000111B	;MASK TO LOWER THREE BITS
	RRCA			;ROTATE THREE
	RRCA			; LS BITS
	RRCA			;  INTO THREE MS BITS
	XOR	L		;EXCLUSIVE OR WITH SECOND MARK
	LD	L,A		;SAVE AS SECOND MARK
	LD	H,0		;ZERO H FOR MULTIPLICATION
	ADD	HL,HL		;MULTIPLY BY TWO
	ADD	HL,HL		;MULTIPLY BY FOUR
	ADD	HL,HL		;MULTIPLY BY EIGHT
	ADD	HL,HL		;MULTIPLY BY SIXTEEN
	XOR	H		;EXCLUSIVE OR WITH UPPER BYTE
	XOR	D		;EXCLUSIVE OR WITH CHARACTER
	LD	D,A		;SAVE UPPER EIGHT BITS
	LD	A,L		;GET LOWER BYTE TO A
	ADD	HL,HL		;MULTIPLY BY THIRTY TWO
	XOR	H		;EXCLUSIVE OR WITH UPPER BYTE
	XOR	E		;EXCLUSIVE OR WITH FIRST MARK
	LD	E,A		;SAVE LOWER EIGHT BITS
	EX	DE,HL		;SWAP HASH CODE TO HL
	POP	DE		;RECOVER BUFFER POINTER
	DEC	DE		;BACKUP THE POINTER
	DJNZ	PWHASL		;LOOP FOR ALL CHARACTERS
	RET
;
;
; CLEAR OUT GAT SECTOR IMAGE
;5322
CLRGAT:	LD	HL,GATBUF	;POINT AT GAT BUFFER
	XOR	A		;ZERO COUNTER
CLRGAL:	LD	(HL),11111100B	;LOAD UNUSED ENTRY BYTE
	INC	HL		;BUMP BUFFER POINTER
	INC	A		;BUMP ENTRY COUNTER
	CP	NUMTRK		;TEST IF DONE WITH ENTRIES
	JR	NZ,CLRGAL	;LOOP UNTIL ALL DONE
CLRGAB:	CP	Low DOSVER	;TEST IF AT VERSION BYTE
	JR	Z,TSTLOK	;THEN TEST FOR LOCKED TRACKS
	LD	(HL),11111111B	;PAD OUT WITH ALL BITS SET
	INC	HL		;BUMP BUFFER POINTER
	INC	A		;BUMP ENTRY COUNTER
	JR	CLRGAB		;LOOP UNTIL ALL DONE
;
;
; INVALID TRACK NUMBER ENTERED
;5338
TRKBAD:	LD	HL,INVATM	;INVALID TRACK MESSAGE
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
;
;
; TEST IF USER WANTS TO LOCK OUT ANY TRACKS
;533E
TSTLOK:	LD	HL,WANTLM	;LOCK OUT TRACKS MESSAGE
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	LD	HL,HITBUF	;POINT AT INPUT BUFFER
	LD	B,3		;LOAD MAXIMUM INPUT LENGTH
	CALL	KBLINE		;GO GET INPUT LINE
	LD	A,(HL)		;GET CHARACTER FROM BUFFER
	CP	'Y'		;TEST IF AFFIRMATIVE
	JR	NZ,NOTLOK	;SKIP IF NEGATIVE RESPONSE
	LD	HL,WHICTM	;POINT AT WHICH TRACKS MESSAGE
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE STRING
	LD	HL,HITBUF	;POINT AT INPUT BUFFER
	LD	B,30		;LOAD MAXIMUM INPUT LENGTH
	CALL	KBLINE		;READ A LINE OF INPUT
LOKNXT:	CALL	ASCBIN		;CONVERT NUMBER TO BINARY
	LD	D,E		;COPY TRACK NUMBER TO D
	CP	'-'		;TEST IF TRACK RANGE
	JR	NZ,LOKSGL	;SKIP IF SINGLE TRACK
	CALL	ASCBIN		;ELSE CONVERT NUMBER TO BINARY
LOKSGL:	EX	AF,AF'		;SWAP TO ALTERNATE AF
	LD	A,D		;GET STARTING TRACK TO A
	OR	A		;TEST IF TRACK ZERO
	JR	Z,TRKBAD	;INVALID TRACK IF IT IS
	CP	NUMTRK		;TEST IF ABOVE RANGE
	JR	NC,TRKBAD	;INVALID TRACK IF IT IS
	LD	A,E		;GET ENDING TRACK TO A
	CP	NUMTRK		;TEST IF ABOVE RANGE
	JR	NC,TRKBAD	;INVALID TRACK IF IT IS
	SUB	D		;COMPUTE NUMBER OF TRACKS
	JR	C,TRKBAD	;INVALID TRACK IF NEGATIVE
	INC	A		;BUMP THE TRACK COUNT
	LD	B,A		;COPY COUNT TO B REGISTER
	PUSH	HL		;SAVE HL REGISTER
	LD	L,D		;INDEX INTO GAT BUFFER
	LD	H,High GATBUF	;POINTER INTO GAT BUFFER
MRKUSD:	LD	(HL),11111111B	;MARK TRACK AS USED
	INC	HL		;BUMP BUFFER POINTER
	DJNZ	MRKUSD		;LOOP UNTIL TRACK(S) LOCKED
	POP	HL		;RECOVER HL REGISTER
	EX	AF,AF'		;SWAP TO PRIMARY AF
	CP	CR		;TEST IF END OF LINE
	JR	NZ,LOKNXT	;LOOP FOR NEXT TRACK IF NOT
	LD	HL,FMTLTM	;FORMAT LOCKED TRACKS PROMPT
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE STRING
	LD	HL,HITBUF	;POINT AT HIT BUFFER
	LD	B,3		;LOAD MAXIMUM LINE LENGTH
	CALL	KBLINE		;READ A LINE OF INPUT
	LD	A,(HL)		;GET CHARACTER FROM INPUT
	LD	(FMTLTK),A	;SAVE LOCKED FORMAT FLAG
NOTLOK:	CALL	SELDRV		;SELECT DISKETTE DRIVE
	LD	BC,0		;LOAD ONE SECOND DELAY
	CALL	DELAYL		;GO DO THE DELAY
	LD	A,(CSTREG)	;GET FLOPPY CONTROLLER STATUS
	LD	HL,DNRDYM	;DRIVE NOT READY MESSAGE
	BIT	7,A		;TEST IF DRIVE NOT READY
	JP	NZ,ABORTM	;THEN ABORT THE FORMAT
	LD	HL,DRNISM	;DRIVE NOT IN SYSTEM MESSAGE
	BIT	2,A		;TEST IF TRACK ZERO FLAG
	JP	Z,ABORTM	;ABORT IF THE FLAG IS RESET
	LD	HL,WRPROM	;WRITE PROTECTED MESSAGE
	BIT	6,A		;TEST IF WRITE PROTECTED
	JP	NZ,ABORTM	;ABORT IF PROTECTED
	LD	BC,410		;LOAD TEST LOOP COUNTER
	LD	HL,NODSKM	;NO DISK IN DRIVE MESSAGE
IDXONE:	DEC	BC		;DECREMENT LOOP COUNTER
	LD	A,B		;GET MSB TO A FOR TEST
	OR	C		;TEST IF END OF LOOP
	JP	Z,ABORTM	;THEN WE ABORT TEST LOOP
	LD	A,(CSTREG)	;GET FLOPPY CONTROLLER STATUS
	AND	00000010B	;TEST IF INDEX HOLE REACHED
	JR	NZ,IDXONE	;LOOP IF NOT THERE YET
	LD	BC,13114	;LOAD TEST LOOP COUNTER
	LD	HL,OPDORM	;DOOR NOT CLOSED MESSAGE
IDXTWO:	DEC	BC		;DECREMENT LOOP COUNTER
	LD	A,B		;GET MSB TO A FOR TEST
	OR	C		;TEST IF END OF LOOP
	JP	Z,ABORTM	;THEN WE ABORT TEST LOOP
	LD	A,(CSTREG)	;GET FLOPPY CONTROLLER STATUS
	AND	00000010B	;TEST IF PAST INDEX HOLE
	JR	Z,IDXTWO	;LOOP IF NOT THERE YET
	LD	DE,0		;ZERO DE REGISTER FOR COUNT
	LD	BC,372		;LOAD TEST LOOP COUNTER
	LD	HL,NODSKM	;NO DISK IN DRIVE MESSAGE
IDXTRI:	DEC	BC		;DECREMENT LOOP COUNTER
	LD	A,B		;GET MSB TO A FOR TEST
	OR	C		;TEST IF END OF LOOP
	JP	Z,ABORTM	;THEN WE ABORT TEST LOOP
	INC	DE		;BUMP COUNTER
	LD	A,(CSTREG)	;GET FLOPPY CONTROLLER STATUS
	AND	00000010B	;TEST IF INDEX HOLE REACHED
	JR	NZ,IDXTRI	;LOOP IF NOT THERE YET
	LD	BC,13120	;LOAD TEST LOOP COUNTER
	LD	HL,OPDORM	;DOOR NOT CLOSED MESSAGE
IDXFOU:	DEC	BC		;DECREMENT LOOP COUNTER
	LD	A,B		;GET MSB TO A FOR TEST
	OR	C		;TEST IF END OF LOOP
	JP	Z,ABORTM	;THEN WE ABORT TEST LOOP
	INC	DE		;BUMP COUNTER
	LD	A,(CSTREG)	;GET FLOPPY CONTROLLER STATUS
	AND	00000010B	;TEST IF PAST INDEX HOLE
	JR	Z,IDXFOU	;LOOP IF NOT THERE YET
	LD	HL,-5429	;GET NEGATED INDEX HOLE COUNT
	ADD	HL,DE		;TEST IF TOO MANY HOLES
	LD	HL,HASECM	;HARD SECTORED DISK MESSAGE
	JP	NC,ABORTM	;ABORT IF HARD SECTORED
	CALL	SELDRV		;SELECT DISKETTE DRIVE
	LD	BC,HITBUF	;POINT AT HIT BUFFER
	LD	DE,0		;LOAD TRACK AND SECTOR NUMBERS
	CALL	RDSECT-O	;READ BOOT SECTOR TO BUFFER
	CALL	Z,HASDTA	;PROMPT IF FORMAT WANTED
	NOP			;DO
	NOP			; ABSOLUTELY
	NOP			;  NOTHING
	LD	H,High GATBUF	;LOAD GAT BUFFER MSB
	LD	L,DIRECT	;INDEX INTO GAT SECTOR
	LD	C,0		;ZERO TRACK COUNTER
FINDDS:	LD	A,(HL)		;GET GAT ENTRY TO A
	CP	11111100B	;TEST IF ENTRY AVAILABLE
	JR	Z,ENTRAV	;DONE IF ENTRY FOUND
	INC	C		;BUMP TRACK NUMBER
	LD	A,C		;GET TRACK NUMBER TO A
	RRCA			;SHIFT ODD BIT TO CARRY
	LD	A,L		;COPY TRACK NUMBER TO A
	JR	NC,NOTCOG	;NOT CONSECUTIVE GRANULES
	ADD	A,C		;INDEX TO NEXT TRACK
	LD	L,A		;INDEX INTO GAT SECTOR
	CP	NUMTRK		;TEST IF LAST TRACK DONE
	JR	NZ,FINDDS	;LOOP IF MORE TO TEST
	JR	NOTDIR		;ABORT FORMAT IF NO TRACKS
NOTCOG:	SUB	C		;INDEX TO PREVIOS TRACK
	LD	L,A		;INDEX INTO GAT SECTOR
	JR	NZ,FINDDS	;NOT TWO CONSECUTIVE GRANULES
;
;
; NO TRACK AVAILABLE FOR DIRECTORY - DISPLAY MESSAGE AND ABORT
;544C
NOTDIR:	LD	HL,NOTAVM	;NO TRACK FOR DIRECTORY MESSAGE
	JP	ABORTM		;SHOW STRING AND ABORT FORMAT
;
;
; A TRACK IS AVAILABLE FOR DIRECTORY
; ENTRY:  L       - FIRST AVAILABLE TRACK
;5452
ENTRAV:	LD	A,L		;GET DIRECTORY TRACK TO A
	LD	(DIRTRK-O),A	;STORE DIRECTORY TRACK NUMBER
	CALL	BINASC		;CONVERT TRACK NUMBER TO ASCII
	LD	(DIRTKT),BC	;STORE ASCII DIRECTORY TRACK
	LD	HL,DIRTKM	;DIRECTORY TRACK STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
;
;
; INIATILIZE FOR FORMATTING TRACKS
:
	XOR	A		;ZERO ACCUMULATOR
	LD	(TRKNUM),A	;SET TRACK NUMBER TO ZERO
;
;
; FORMAT DISK TRACKS LOOP
;5467
FORMDL:	LD	A,(TRKNUM)	;GET TRACK NUMBER TO A
	CALL	BINASC		;CONVERT NUMBER TO ASCII
	LD	(FMTTKT),BC	;STORE ASCII NUMBER IN STRING
	LD	HL,FMTTKM	;POINT AT PROGRESS STRING
	CALL	MSGOUT-O	;DISPLAY THE STRING
	LD	A,(TRKNUM)	;LOAD TRACK NUMBER TO A
	LD	B,A		;COPY TRACK NUMBER TO B
	LD	A,(DIRTRK-O)	;GET DIRECTORY TRACK TO A
	CP	B		;TEST IF ON DIRECTORY TRACK
	LD	B,DIRMRK	;LOAD DIRECTORY ADDRESS MARK
	JR	Z,FORLOK	;SKIP IF DIRECTORY TRACK
	LD	L,A		;GET GAT OFFSET TO L
	LD	H,High GATBUF	;INDEX INTO GAT SECTOR
	LD	A,(HL)		;GET ALLOCATION BYTE TO A
	INC	A		;BUMP THE ALLOCATION BYTE
	LD	B,DTAMRK	;LOAD DATA ADDRESS MARK
	JR	NZ,FORLOK	;SKIP IF TRACK LOCKED
	LD	A,0		;GET FORMAT LOCKED TRACKS FLAG
FMTLTK	Equ	$-1		;FORMAT LOCKED TRACKS FLAG
	CP	'Y'		;TEST IF WE SHOULD FORMAT
	JP	NZ,SKIPFO	;SKIP IF NOT FORMATTING TRACKS
	LD	B,LOKMRK	;LOAD LOCKED ADDRESS MARK
FORLOK:	LD	A,B		;GET ADDRESS MARK TO A
	LD	(THEMRK),A	;SAVE THE ADDRESS MARK
	LD	HL,TRKBUF	;POINT AT TRACK IMAGE BUFFER
	LD	DE,SKEWTB	;POINT AT SECTOR SKEW TABLE
	LD	B,14		;LOAD BYTE COUNTER TO B
	CALL	STOBAS		;STORE ALL BITS SET BYTE
;
;
; FORMAT DISK SECTORS LOOP
;54A4
FORMDS:	LD	B,6		;LOAD BYTE COUNTER TO B
	LD	C,00000000B	;LOAD ALL BITS RESET BYTE
	CALL	STOBNB		;STORE THE BYTES IN BUFFER
	LD	C,IDAMRK	;LOAD IDENTITY ADDRESS MARK
	CALL	STOBTB		;STORE THE ADDRESS MARK
	LD	C,0		;LOAD TRACK NUMBER TO C
TRKNUM	Equ	$-1		;TRACK NUMBER STORAGE
	CALL	STOBTB		;STORE THE TRACK NUMBER
	LD	C,0		;LOAD HEAD NUMBER TO C
	CALL	STOBTB		;STORE HEAD NUMBER IN BUFFER
	LD	A,(DE)		;GET SECTOR NUMBER TO A
	LD	C,A		;COPY THE NUMBER TO C
	CALL	STOBTB		;STORE SECTOR NUMBER IN BUFFER
	LD	C,1		;LOAD SECTOR SIZE (256 BYTES)
	CALL	STOBTB		;STORE SECTOR SIZE CODE
	LD	C,CRCMRK	;LOAD CRC ADDRESS MARK
	CALL	STOBTB		;STORE THE ADDRESS MARK
	LD	C,11111111B	;LOAD ALL BITS SET BYTE
	CALL	STOBTB		;STORE THE BYTE IN BUFFER
	LD	B,11		;LOAD BYTE COUNTER TO B
	CALL	STOBAS		;STORE ALL BITS SET BYTES
	LD	B,6		;LOAD BYTE COUNTER TO B
	LD	C,00000000B	;LOAD ALL BITS RESET BYTE
	CALL	STOBNB		;STORE BYTE IN BUFFER
	LD	C,0		;GET ADDRESS MARK TO C
THEMRK	Equ	$-1		;DATA/DIRECTORY/LOCKED MARK
	CALL	STOBTB		;STORE ADDRESS MARK IN BUFFER
	LD	B,0		;LOAD BYTE COUNTER (256)
	LD	C,FILMRK	;LOAD SECTOR FILL BYTE
	CALL	STOBNB		;FILL THE SECTOR DATA FIELD
	LD	C,CRCMRK	;LOAD CRC ADDRESS MARK
	CALL	STOBTB		;STORE THE ADDRESS MARK
	LD	C,11111111B	;LOAD ALL BITS SET BYTE
	CALL	STOBTB		;STORE THE BYTE IN BUFFER
	LD	B,11		;LOAD BYTE COUNTER TO B
	CALL	STOBAS		;STORE ALL BITS SET BYTES
	INC	DE		;BUMP SKEW TABLE INDEX
	LD	A,(DE)		;GET SECTOR NUMBER FROM TABLE
	INC	A		;BUMP THE SECTOR NUMBER
	JR	NZ,FORMDS	;LOOP FOR NEXT IF MORE SECTORS
	LD	B,91		;LOAD BYTE COUNTER TO B
	CALL	STOBAS		;STORE ALL BITS SET BYTES
	CALL	WRTRAK		;WRITE THE TRACK TO DISK
;
;
; NOT FORMATTING TRACK - SKIP TO NEXT TRACK
;5502
SKIPFO:	LD	A,(TRKNUM)	;GET TRACK NUMBER TO A
	INC	A		;BUMP THE TRACK NUMBER
	LD	(TRKNUM),A	;RE-SAVE TRACK NUMBER
	CP	NUMTRK		;TEST IF DONE LAST TRACK
	JR	Z,INISYS	;THEN WE ARE DONE FORMATTING
	LD	A,WDSTIN	;STEP IN DRIVE HEAD COMMAND
	LD	(CSTREG),A	;OUTPUT THE COMMAND
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
FORMWL:	LD	A,(CSTREG)	;GET CONTROLLER STATUS TO A
	RRCA			;COPY BUSY BIT TO CARRY
	JR	C,FORMWL	;LOOP UNTIL NOT BUSY
	JP	FORMDL		;THEN FORMAT NEXT TRACK
;
;
; WRITE A TRACK FROM TRACK BUFFER TO DISK - RETRY ONCE
;551F
WRTRAK:	CALL	TRAKWR		;WRITE TRACK TO DISK
	RET	Z		;DONE IF SUCCESSFUL WRITE
;
;
; WRITE A TRACK FROM TRACK BUFFER TO DISK
;5523
TRAKWR:	CALL	SELDRV		;SELECT DISK DRIVE
	LD	BC,TRKBUF	;POINT AT TRACK BUFFER
	LD	HL,CSTREG	;COMMAND/STATUS REGISTER
	LD	(HL),WDWTRK	;WRITE TRACK COMMAND
	LD	DE,DTAREG	;POINT AT DATA REGISTER
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	DI			;DISABLE INTERRUPTS
	JR	TRAKWL		;THEN ENTER WRITE TRACK LOOP
;
;
; TEST IF NOT BUSY - IF SO, THEN WE ARE DONE WRITING
;5538
TRAKWN:	RRCA			;COPY BUSY BIT TO CARRY
	JR	NC,TRAKWX	;ALL DONE IF NOT BUSY
;
;
; TEST IF CONTROLLER READY - LOOP IF NOT, ELSE LOAD AND WRITE
;553B
TRAKWL:	LD	A,(HL)		;GET CONTROLLER STATUS TO A
	BIT	1,A		;TEST IF CONTROLLER IS READY
	JR	Z,TRAKWN	;TEST IF DONE IF IT ISN'T
	LD	A,(BC)		;GET DATA BYTE FROM BUFFER
	LD	(DE),A		;OUTPUT BYTE TO CONTROLLER
	INC	BC		;BUMP BUFFER POINTER
	JP	TRAKWL		;LOOP BACK FOR NEXT BYTE
;
;
; DONE WRITING TRACK - TEST FOR ANY ERRORS
; ENTRY:  BC      - CURRENT TRACK BUFFER OFFSET
;5546
TRAKWX:	LD	A,(HL)		;GET FINAL STATUS TO A
	LD	(HL),WDFORC	;FORCE INTERRUPT COMMAND
	LD	HL,TRFASM	;TRANSFER RATE TOO FAST
	BIT	2,A		;TEST IF LOST DATA ERROR
	JP	NZ,ABORTM	;DISPLAY MESSAGE AND ABORT
	LD	HL,-TRKBUF	;NEGATED TRACK BUFFER OFFSET
	ADD	HL,BC		;ADD TO BUFFER OFFSET
	EX	DE,HL		;SWAP RESULT TO DE
	LD	HL,-TRKSIZ	;NEGATED TRACK BUFFER SIZE
	ADD	HL,DE		;ADD TO BUFFER OFFSET
	LD	HL,MSLOWM	;MOTOR SPEED TOO SLOW
	JP	NC,ABORTM	;DISPLAY MESSAGE AND ABORT
	LD	HL,-TRKOSI	;NEGATED MAXIMUM OVERFLOW SIZE
	ADD	HL,DE		;ADD TO BUFFER OFFSET
	LD	HL,MFASTM	;MOTOR SPEED TOO FAST
	JP	C,ABORTM	;DISPLAY MESSAGE AND ABORT
	RET
;
;
; DONE FORMATTING - INITIALIZE THE DISK SYSTEM
;556B
INISYS:	LD	A,CR		;LOAD A NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	LD	D,0		;START AT TRACK ZERO
INISYN:	LD	L,D		;GET TRACK NUMBER TO L
	LD	H,High GATBUF	;INDEX INTO GAT SECTOR
	LD	A,(HL)		;GET ALLOCATION BYTE
	INC	A		;TEST IF TRACK LOCKED OUT
	JP	Z,NEXTIN	;THEN SKIP READING THE TRACK
	LD	A,D		;GET TRACK NUMBER TO A
	CALL	BINASC		;CONVERT TO ASCII DECIMAL
	LD	(VFYTKT),BC	;STORE IN VERIFY STRING
	LD	E,0		;ZERO SECTOR NUMBER
INISNS:	PUSH	DE		;SAVE TRACK AND SECTOR
	LD	A,D		;GET TRACK NUMBER TO A
	CALL	SELDRV		;SELECT DISKETTE DRIVE
	LD	A,E		;GET SECTOR NUMBER TO A
	CALL	BINASC		;CONVERT TO DECIMAL ASCII
	LD	(VFYTKS),BC	;STORE IN VERIFY STRING
	LD	HL,VFYTKM	;POINT AT VERIFY STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	POP	DE		;RECOVER TRACK AND SECTOR
	LD	BC,HITBUF	;POINT AT SECTOR BUFFER
	CALL	RDSECT-O	;READ SECTOR INTO BUFFER
	LD	HL,NOTFOM	;POINT AT NOT FOUND MESSAGE
	BIT	4,A		;TEST IF RECORD NOT FOUND
	JP	NZ,LOCKTK	;THEN LOCK OUT THE TRACK
	LD	HL,CRCERM	;POINT AT CRC ERROR MESSAGE
	BIT	3,A		;TEST IF CRC ERROR
	JP	NZ,LOCKTK	;THEN LOCK OUT THE TRACK
	LD	HL,XFRFAM	;TRANSFER RATE TOO FAST
	BIT	2,A		;TEST IF LOST DATA
	JP	NZ,ABORTM	;THEN ABORT THE FORMAT
	INC	E		;BUMP SECTOR NUMBER
	LD	A,E		;GET SECTOR NUMBER TO A
	CP	NUMSEC		;TEST IF LAST SECTOR READ
	JP	NZ,INISNS	;LOOP FOR NEXT IF NOT
;
;
; LOOP FOR NEXT TRACK INITIALIZING
;55BD
NEXTIN:	INC	D		;BUMP TRACK NUMBER
	LD	A,D		;GET TRACK NUMBER TO A
	CP	NUMTRK		;TEST IF LAST TRACK DONE
	JP	NZ,INISYN	;LOOP FOR NEXT IF NOT
	LD	HL,GATBUF	;POINT AT GAT BUFFER
	LD	DE,LOCKTB	;POINT AT LOCK-OUT TABLE
	LD	BC,NUMTRK	;LOAD ENTRY COUNT
	LDIR			;STORE LOCKED ENTRIES
	LD	HL,INISYM	;POINT AT SYSTEM INIT STRING
	CALL	MSGOUT-O	;DISPLAY PROGRESS STRING
	LD	HL,GATBUF	;POINT AT GAT SECTOR BUFFER
	LD	A,(HL)		;GET ENTRY BYTE FROM GAT
	OR	00000001B	;SET FIRST ENTRY AS USED
	LD	(HL),A		;RE-SAVE ENTRY BYTE
	LD	A,(DIRTRK-O)	;GET DIRECTORY TRACK TO A
	LD	(DSECOF),A	;STORE IN 'DIR/SYS' ENTRY
	LD	L,A		;COPY DIRECTORY TRACK TO L
	LD	H,High GATBUF	;HL HAS INDEX TO GAT ENTRY
	LD	A,(HL)		;GET ENTRY TO A
	INC	A		;TEST IF TRACK IS USED
	JP	Z,FMTERR	;THEN FORMAT ERROR
	LD	(HL),11111111B	;FLAG TWO GRANULES USED
	LD	DE,0		;LOAD TRACK TO D, SECTOR TO E
	LD	BC,SYSBUF	;POINT AT SECTOR BUFFER
	LD	A,WDWRIT	;WRITE DATA SECTOR COMMAND
	CALL	WSECTR		;GO WRITE 'BOOT/SYS' SECTOR
	LD	A,(CSTREG)	;GET FINAL STATUS TO A
	AND	01100000B	;MASK TO RECORD TYPE BITS
	JP	NZ,INIERR	;ABORT IF NOT DATA ADDRESS MARK
	LD	BC,GATBUF	;POINT AT GAT SECTOR BUFFER
	LD	A,(DIRTRK-O)	;GET DIRECTORY TRACK TO A
	LD	D,A		;D HOLDS THE TRACK NUMBER
	LD	E,0		;DIRECTORY SECTOR NUMBER (GAT)
	LD	A,WDWRID	;WRITE DIRECTORY SECTOR COMMAND
	CALL	WSECTR		;WRITE GRANULE ALLOCATION TABLE
	LD	A,(CSTREG)	;GET FINAL STATUS TO A
	AND	01100000B	;MASK TO RECORD TYPE BITS
	CP	00100000B	;TEST IF DIRECTORY ADDRESS MARK
	JP	NZ,INIERR	;ABORT IF NOT THE ADDRESS MARK
	LD	HL,HITBUF	;POINT AT HIT SECTOR BUFFER
CLRHIT:	LD	(HL),0		;ZERO HIT SECTOR BYTE
	INC	L		;BUMP SECTOR LOCATION
	JR	NZ,CLRHIT	;LOOP UNTIL ALL CLEARED
	LD	(HL),0A2H	;HASH CODE FOR 'BOOT/SYS'
	INC	HL		;BUMP HIT INDEX
	LD	(HL),02CH	;HASH CODE FOR 'DIR/SYS'
	DEC	HL		;POINT BACK AT SECTOR START
	LD	E,1		;DIRECTORY SECTOR NUMBER (HIT)
	LD	BC,HITBUF	;POINT AT HIT SECTOR BUFFER
	LD	A,WDWRID	;WRITE DIRECTORY SECTOR COMMAND
	CALL	WSECTR		;WRITE HASH INDEX TABLE
	LD	A,(CSTREG)	;GET FINAL STATUS TO A
	AND	01100000B	;MASK TO RECORD TYPE BITS
	CP	00100000B	;TEST IF DIRECTORY ADDRESS MARK
	JP	NZ,INIERR	;ABORT IF NOT THE ADDRESS MARK
	LD	DE,HITBUF	;POINT AT HIT SECTOR BUFFER
	LD	HL,BSYSIM	;POINT AT 'BOOT/SYS' ENTRY
	LD	BC,32		;LOAD ENTRY LENGTH
	LDIR			;COPY INTO SECTOR BUFFER
	LD	A,(DIRTRK-O)	;GET DIRECTORY TRACK TO A
	LD	D,A		;COPY TRACK NUMBER TO D
	LD	E,2		;DIRECTORY SECTOR NUMBER (DIR)
	LD	BC,HITBUF	;POINT AT SECTOR BUFFER
	LD	A,WDWRID	;WRITE DIRECTORY SECTOR COMMAND
	CALL	WSECTR		;WRITE DIRECTORY SECTOR
	LD	A,(CSTREG)	;GET FINAL STATUS TO A
	AND	01100000B	;MASK TO RECORD TYPE BITS
	CP	00100000B	;TEST IF DIRECTORY ADDRESS MARK
	JP	NZ,INIERR	;ABORT IF NOT THE ADDRESS MARK
	LD	HL,DSYSIM	;POINT AT 'DIR/SYS' ENTRY
	LD	DE,HITBUF	;POINT AT HIT SECTOR BUFFER
	LD	BC,32		;LOAD ENTRY LENGTH
	LDIR			;COPY INTO SECTOR BUFFER
	LD	A,(DIRTRK-O)	;GET DIRECTORY TRACK TO A
	LD	D,A		;COPY TRACK NUMBER TO A
	LD	E,3		;DIRECTORY SECTOR NUMBER (DIR)
	LD	BC,HITBUF	;POINT AT HIT SECTOR BUFFER
	LD	A,WDWRID	;WRITE DIRECTORY SECTOR COMMAND
	CALL	WSECTR		;WRITE DIRECTORY SECTOR
	LD	A,(CSTREG)	;GET FINAL STATUS TO A
	AND	01100000B	;MASK TO RECORD TYPE BITS
	CP	00100000B	;TEST IF DIRECTORY ADDRESS MARK
	JP	NZ,INIERR	;ABORT IF NOT THE ADDRESS MARK
	LD	HL,HITBUF	;POINT AT SECTOR BUFFER
	LD	B,32		;NUMBER OF BYTES PER ENTRY
CLRENT:	LD	(HL),0		;ZERO OUT A ENTRY BYTE
	INC	HL		;BUMP BUFFER POINTER
	DJNZ	CLRENT		;LOOP UNTIL ENTRY CLEARED
	LD	A,(DIRTRK-O)	;GET DIRECTORY TRACK TO A
	LD	D,A		;D HOLDS THE TRACK NUMBER
	LD	E,4		;DIRECTORY SECTOR NUMBER
CLRDIR:	LD	BC,HITBUF	;POINT AT SECTOR BUFFER
	LD	A,WDWRID	;WRITE DIRECTORY SECTOR COMMAND
	CALL	WSECTR		;WRITE EMPTY DIRECTORY SECTOR
	LD	A,(CSTREG)	;GET FINAL STATUS TO A
	AND	01100000B	;MASK TO RECORD TYPE BITS
	CP	00100000B	;TEST IF DIRECTORY ADDRESS MARK
	JP	NZ,INIERR	;ABORT IF NOT THE ADDRESS MARK
	INC	E		;BUMP DIRECTORY SECTOR NUMBER
	LD	A,E		;GET NUMBER TO A FOR TESTING
	CP	NUMSEC		;TEST IF DIRECTORY ALL FILLED
	JR	NZ,CLRDIR	;LOOP UNTIL IT IS
	CALL	HOMHED		;HOME THE DRIVE HEAD
	LD	HL,FMTCOM	;POINT AT FORMAT COMPLETE
;
;
; DISPLAY MESSAGE, PROMPT FOR <ENTER> AND RE-BOOT SYSTEM
; ENTRY:  HL      - POINTER TO MESSAGE STRING
;56AD
ABORTM:	CALL	MSGOUT-O	;DISPLAY ERROR MESSAGE
;
;
; PROMPT FOR <ENTER> KEY PRESS - THEN REBOOT SYSTEM
;56B0
PREENT:	LD	HL,HITENM	;POINT AT PROMPT STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
PREENW:	LD	A,(KROSEV)	;READ KEYBOARD ROW
	RRCA			;ROTATE <ENTER> BIT TO CARRY
	JR	NC,PREENW	;LOOP UNTIL KEY PRESSED
	RST	00H		;THEN RE-BOOT SYSTEM
;
;
; WRITE A SECTOR TO DISK - READ THE SECTOR BACK AFTER WRITING
; ENTRY:  A       - DISK CONTROLLER COMMAND CODE
;         BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL WRITE
;56BD
WSECTR:	CALL	WRSECT		;WRITE THE SECTOR TO DISK
	JR	NZ,INIERR	;ABORT IF WRITE ERROR
	PUSH	BC		;SAVE BUFFER POINTER
	LD	BC,HITBUF	;POINT AT SECTOR BUFFER
	CALL	RDSECT-O	;READ THE SECTOR TO BUFFER
	POP	BC		;RECOVER BUFFER POINTER
	RET	Z		;ALL DONE IF SUCCESSFUL
;
;
; CAN'T INITIALIZE SYSTEM INFORMATION
;56CB
INIERR:	LD	HL,CANTIM	;POINT AT ERROR STRING
	JP	ABORTM		;DISPLAY MESSAGE AND ABORT
;
;
; CAN'T FORMAT TRACK
;56D1
FMTERR:	LD	HL,CANTFO	;POINT AT ERROR STRING
	JP	ABORTM		;DISPLAY MESSAGE AND ABORT
;
;
; WRITE A SECTOR FROM SECTOR BUFFER TO DISK - RETRY ONCE
; ENTRY:  A       - DISK CONTROLLER COMMAND CODE
;         BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL WRITE
;56D7
WRSECT:	LD	(SECTWC),A	;STORE COMMAND CODE
;
;
;  WRITE A SECTOR FROM SECTOR BUFFER TO DISK - RETRY ONCE
; ENTRY:  BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL WRITE
;56DA
	PUSH	BC		;SAVE BUFFER POINTER
	CALL	SECTWR		;WRITE SECTOR TO DISK
	POP	HL		;RECOVER BUFFER POINTER
	RET	Z		;DONE IF SUCCESSFUL WRITE
	LD	B,H		;BUFFER POINTER MSB TO B
	LD	C,L		;BUFFER POINTER LSB TO C
;
;
;  WRITE A SECTOR FROM SECTOR BUFFER TO DISK
; ENTRY:  BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL WRITE
;56E2
SECTWR:	LD	(SCTREG),DE	;STORE TRACK AND SECTOR
	PUSH	DE		;SAVE TRACK AND SECTOR
	CALL	SELDRV		;SELECT DISKETTE DRIVE
	LD	HL,CSTREG	;COMMAND/STATUS REGISTER
	LD	(HL),WDSEEK	;SEEK TO TRACK COMMAND
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
SECTWB:	LD	A,(HL)		;GET FLOPPY STATUS
	RRCA			;TEST IF CONTROLLER BUSY
	JR	C,SECTWB	;LOOP WHILE IT IS
	LD	(HL),0		;ELSE OUTPUT COMMAND CODE
SECTWC	Equ	$-1		;FLOPPY COMMAND CODE
	LD	DE,DTAREG	;POINT AT DATA REGISTER
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	DI			;DISABLE INTERRUPTS
	JR	SECTWL		;THEN ENTER WRITE LOOP
;
;
;TEST IF NOT BUSY - IF SO, THEN WE ARE DONE WRITING
;5703
SECTWN:	RRCA			;COPY BUSY BIT TO CARRY
	JR	NC,SECTWX	;ALL DONE IF NOT BUSY
;
;
; TEST IF CONTROLLER READY - LOOP IF NOT, ELSE LOAD AND WRITE
;5706
SECTWL:	LD	A,(HL)		;GET CONTROLLER STATUS TO A
	BIT	1,A		;TEST IF CONTROLLER IS READY
	JR	Z,SECTWN	;TEST IF DONE IF IT ISN'T
	LD	A,(BC)		;GET DATA BYTE FROM BUFFER
	LD	(DE),A		;OUTPUT BYTE TO CONTROLLER
	INC	BC		;BUMP BUFFER POINTER
	JP	SECTWL		;LOOP BACK FOR NEXT BYTE
;
;
; DONE WRITING - GET FINAL STATUS AND RETURN
;5711
SECTWX:	LD	A,(HL)		;GET FINAL STATUS TO A
	AND	01111100B	;MASK TO ERROR BITS
	POP	DE		;RECOVER TRACK AND SECTOR
	RET	Z		;RETURN IF NO ERRORS
	LD	(HL),WDFORC	;ELSE FORCE INTERRUPT
	RET
;
;
; TRACK UNUSABLE - DISPLAY MESSAGE AND LOCK OUT THE TRACK
; ENTRY:  D       - TRACK NUMBER
;         HL      - MESSAGE STRING POINTER
;5719
LOCKTK:	PUSH	DE		;SAVE TRACK AND SECTOR
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	POP	DE		;RECOVER TRACK AND SECTOR
	LD	L,D		;GET TRACK NUMBER TO L
	LD	H,High GATBUF	;INDEX INTO GAT SECTOR
	LD	(HL),11111111B	;LOCK OUT THE TRACK
	JP	NEXTIN		;RE-ENTER SYSTEM INITIALIZE
;
;
; CONVERT A BINARY NUMBER TO ASCII DECIMAL
; ENTRY:  A       - BINARY NUMBER
; EXIT:   B       - DECIMAL ASCII NUMBER LSB
;         C       - DECIMAL ASCII NUMBER MSB
;5726
BINASC:	LD	C,'0'		;LOAD INITIAL ASCII ZERO
BINASL:	SUB	10		;SUBTRACT DECIMAL TEN
	JR	C,BINASX	;ALL DONE IF UNDERFLOW
	INC	C		;ELSE BUMP ASCII NUMBER MSB
	JR	BINASL		;LOOP FOR NEXT SUBTRACTION
BINASX:	ADD	A,'9'+1		;ADD REMAINDER TO LSB
	LD	B,A		;COPY ASCII RESULT LSB TO B
	RET
;
;
; CONVERT ASCII DECIMAL NUMBER TO BINARY
; ENTRY:  HL      - POINTER TO THE ASCII STRING
; EXIT:   E       - BINARY NUMBER
;         HL      - INCREMENTED PAST THE NUMBER
;5733
ASCBIN:	LD	E,0		;INITIALIZE RESULT REGISTER
ASCBIL:	LD	A,(HL)		;GET CHARACTER FROM STRING
	INC	HL		;BUMP STRING POINTER
	CP	'0'		;TEST IF DECIMAL ASCII DIGIT
	RET	C		;DONE IF NOT DECIMAL DIGIT
	CP	'9'+1		;TEST IF DECIMAL ASCII DIGIT
	RET	NC		;DONE IF NOT DECIMAL DIGIT
	SUB	'0'		;SUBTRACT DECIMAL ASCII BIAS
	LD	B,A		;COPY RESULT TO B REGISTER
	LD	A,E		;GET PREVIOUS RESULT TO A
	ADD	A,A		;MULTIPLY BY TWO
	ADD	A,A		;MULTIPLY BY FOUR
	ADD	A,E		;MULTIPLY BY FIVE
	ADD	A,A		;MULTIPLY BY TEN
	ADD	A,B		;ADD IN NEW ONES DIGIT
	LD	E,A		;SAVE RESULT IN E REGISTER
	JR	ASCBIL		;THEN LOOP FOR NEXT DIGIT
;
;
; STORE A NUMBER OF 'ALL BITS SET' BYTES IN TRACK BUFFER
; ENTRY:  B       - BYTE COUNTER
;         HL      - BUFFER POINTER
; EXIT:   B       - ZERO
;         C       - 11111111B
;         HL      - INCREMENTED BY B BYTES
;5749
STOBAS:	LD	C,11111111B	;LOAD ALL BITS SET
;
;
; STORE A NUMBER OF BYTES IN TRACK BUFFER
; ENTRY:  B       - BYTE COUNTER
;         C       - BYTE TO STORE
;         HL      - BUFFER POINTER
; EXIT:   B       - ZERO
;         HL      - INCREMENTED BY B BYTES
;574B
STOBNB:	CALL	STOBTB		;STORE THE BYTE IN BUFFER
	DJNZ	STOBNB		;LOOP UNTIL ALL BYTES STORED
	RET
;
;
; STORE A BYTE IN TRACK BUFFER
; ENTRY:  C       - BYTE TO STORE
;         HL      - BUFFER POINTER
; EXIT:   HL      - INCREMENTED
;5751
STOBTB:	LD	(HL),C		;STORE BYTE IN BUFFER
	INC	HL		;BUMP BUFFER POINTER
	RET
;
;
; HOME DRIVE HEAD TO TRACK ZERO
;5754
HOMHED:	CALL	SELDRV		;SELECT DISK DRIVE
	LD	A,WDHOME	;HOME DRIVE HEAD COMMAND
	LD	(CSTREG),A	;OUTPUT TO FLOPPY CONTROLLER
	PUSH	AF		;DELAY FOR I/O
	POP	AF		;DELAY FOR I/O
	PUSH	AF		;DELAY FOR I/O
	POP	AF		;DELAY FOR I/O
HOMHEW:	LD	A,(CSTREG)	;GET CONTROLLER STATUS
	RRCA			;ROTATE BUSY BIT TO CARRY
	JR	C,HOMHEW	;LOOP UNTIL NOT BUSY
	RET
;
;
; SELECT A DISK DRIVE
; ENTRY:  SELDRN  - DRIVE NUMBER TO SELECT
;5767
SELDRV:	LD	A,0		;LOAD DRIVE NUMBER TO A
SELDRN	Equ	$-1		;DRIVE NUMBER STORAGE
	LD	(DRVREG),A	;SELECT THE DRIVE
	RET
;
;
; SECTOR SKEW TABLE (SKEW OF 5)
;575D
SKEWTB	Db	0,5,1,6,2,7,3,8,4,9,-1
;
;
; DISK NAME STRING IMAGE
;5778
DNAMIM	Db	'        '
;
;
; DIRECTORY ENTRY IMAGE FOR 'BOOT/SYS'
;5780
BSYSIM	Db	05EH,000H,000H,000H,000H
	Db	'BOOT    SYS'
	Db	060H,07FH,01FH,0B2H,005H,000H,000H,000H
	Db	0FFH,0FFH,000H,000H,000H,000H,000H,000H
;
;
; DIRECTORY ENTRY IMAGE FOR 'DIR/SYS'
;57A0
DSYSIM	Db	05DH,000H,000H,000H,000H
	Db	'DIR     SYS'
	Db	0A7H,01DH,0F9H,0E5H,00AH,000H,011H,001H
	Db	0FFH,0FFH,000H,000H,000H,000H,000H,000H
;
;
; OFFSET TO DIRECTORY SECTOR IN ABOVE IMAGE
;57B6
DSECOF	Equ	$-10		;DEFINE THE OFFSET
;
;
; PROGRAM MESSAGE STRINGS
;57C0
INVDCM	Db	'FORMAT INVALID DURING PROGRAM CHAINING!',CR
SIGNOM	Db	HO,CE,'TRSDOS DISK FORMATTER PROGRAM  2.3',LF,CR
WHICDM	Db	'WHICH DRIVE IS TO BE USED ? ',CC
DNAMEM	Db	'DISKETTE NAME ? ',CC
CREADM	Db	'CREATION DATE (DD/MM/YY) ? ',CC
MASPWM	Db	'MASTER PASSWORD ? ',CC
DNRDYM	Db	'DRIVE NOT READY!',CR
WRPROM	Db	'WRITE PROTECTED DISKETTE!',CR
DRNISM	Db	'DRIVE NOT IN SYSTEM!',CR
NODSKM	Db	'NO DISKETTE IN DRIVE!',CR
OPDORM	Db	'DOOR NOT CLOSED ON DRIVE!',CR
HASECM	Db	'DISKETTE UNUSABLE! HARD-SECTORED!',CR
HASDAM	Db	'DISKETTE CONTAINS DATA, FORMAT OR NOT ? ',CC
WANTLM	Db	'DO YOU WANT TO LOCK OUT ANY TRACKS ? ',CC
WHICTM	Db	'WHICH TRACKS (1-39) ? ',CC
INVATM	Db	'INVALID TRACK NUMBER!',CR
FMTLTM	Db	'FORMAT THE LOCKED OUT TRACKS? ',CC
NOTAVM	Db	"CAN'T FORMAT, NO TRACKS AVAILABLE FOR DIRECTORY!",CR
DIRTKM	Db	'DIRECTORY WILL BE PLACED ON TRACK 00',CR
;
;
; DEFINE OFFSET TO TRACK IN DIRECTORY PLACEMENT STRING
;59EB
DIRTKT	Equ	$-3		;ASCII DIRECTORY TRACK NUMBER
;
;
; MORE PROGRAM MESSAGE STRINGS
;5A29
CANTFO	Db	"CAN'T FORMAT, DIRECTORY TRACK FLAWED!",CR
;
;
; MORE MESSAGES
;
FMTTKM	Db	BL,'FORMATTING TRACK 00',CC
;
;
; DEFINE OFFSET TO TRACK IN FORMAT STRING
;5A26
FMTTKT	Equ	$-3		;ASCII TRACK NUMBER
;
;
; MORE PROGRAM MESSAGE STRINGS
;5A29
TRFASM	Db	LF,"CAN'T FORMAT, DISK TRANSFER RATE TOO FAST!",CR
MSLOWM	Db	LF,"CAN'T FORMAT, MOTOR SPEED TOO SLOW!",CR
MFASTM	Db	LF,"CAN'T FORMAT, MOTOR SPEED TOO FAST!",CR
VFYTKM	Db	BL,'VERIFYING TRACK 00, SECTOR 00',CC
;
;
; DEFINE OFFSET TO TRACK IN VERIFY STRING
;5AB0
VFYTKT	Equ	$-14		;ASCII TRACK NUMBER
;
;
; DEFINE OFFSET TO SECTOR IN VERIFY STRING
;5ABB
VFYTKS	Equ	$-3		;ASCII SECTOR NUMBER
;
;
; MORE PROGRAM MESSAGE STRINGS
;5ABE
NOTFOM	Db	': NOT FOUND! TRACK LOCKED OUT!',CR
CRCERM	Db	': CRC ERROR! TRACK LOCKED OUT!',CR
XFRFAM	Db	LF,"CAN'T VERIFY, DISK TRANSFER RATE TOO FAST!",CR
INISYM	Db	LF,'INITIALIZING SYSTEM INFORMATION',CR
CANTIM	Db	"CAN'T INITIALIZE SYSTEM INFORMATION",CR
FMTCOM	Db	LF,'FORMATTING COMPLETE',CR
HITENM	Db	LF,LF,"HIT 'ENTER' TO BOOT DOS",CR
;
;
; DEFINE LOCATIONS IN GAT FOR DISKETTE INFORMATION
;
	Org	05CCBH
;
;
; DOS VERSION NUMBER IN BINARY CODED DECIMAL
;5CCB
DOSVER	Db	021H		;DOS VERSION NUMBER
;
;
; UNUSED BYTES (AS FAR AS I KNOW)
;
	Db	0,0		;RESERVE THE BYTES
;
;
; ENCODED (HASHED) DISK PASSWORD
;5CCE
DISKPW	DW	0		;DEFINE LOCATION
;
;
; DISK NAME STRING
;5CD0
DSKNAM	Db	'        '	;EMPTY FOR NOW
;
;
; DISK CREATION DATE STRING
;5CD8
DSKDAT	Db	'MM/DD/YY'	;DUMMY ENTRIES
;
;
; AUTO PROCEDURE STRING TERMINATED BY CARRIAGE RETURN
;5CE0
AUTOEX	Db	CR,'                               '
;
;
; RE-DEFINE ORIGIN TO BOOT SECTOR IMAGE
;
	Org	05E00H
;
;
; DEFINE OFFSET FROM OUR LOCATION TO BOOT LOADER ADDRESS
;
O	Equ	$-SYSBUF	;DEFINE THE DIFFERENCE
;
;
; BOOT SECTOR IMAGE
;5E00
BOOTSE	Db	000H		;SIGNATURE/RECORD TYPE (NOP)
	Db	0FEH		;SIGNATURE/RECORD SIZE (CP)
DIRTRK	Db	000H		;DIRECTORY TRACK NUMBER
;
;
; START OF MAIN BOOT LOADER CODE
;
	DI			;DISABLE INTERRUPTS
	LD	SP,STACKT	;SET TOP OF STACK FOR BOOT
	LD	HL,CLRSCR-O	;POINT AT SCREEN CLEAR STRING
	CALL	MSGOUT-O	;CLEAR THE VIDEO SCREEN
	LD	A,00000001B	;CODE FOR SELECTING DRIVE 0
	LD	(DRVREG),A	;SELECT THE DRIVE
	LD	A,(DIRTRK-O)	;LOAD DIRECTORY TRACK TO A
	LD	D,A		;SAVE THE TRACK IN D
	LD	E,4		;SECTOR FOR SYS0/SYS ENTRY
	LD	BC,SCTBUF	;POINT AT SECTOR BUFFER
	CALL	RDSECT-O	;READ THE DIRECTORY SECTOR
	JR	NZ,RDEROR	;ABORT IF READ ERROR
	LD	A,(SCTBUF)	;GET FIRST BUFFER BYTE
	AND	00010000B	;ISOLATE ENTRY OCCUPIED BIT
	LD	HL,NOSYST-O	;POINT AT ERROR MESSAGE
	JR	Z,MSGHLT	;ABORT IF UNOCCUPIED ENTRY
	EXX			;SWAP TO ALTERNATE REGISTERS
	LD	HL,(SCTBUF+22)	;GET FIRST GAP FOR 'SYS0/SYS'
	LD	D,L		;TRACK NUMBER TO D
	LD	A,H		;BYTE COUNT, SECTOR OFFSET TO A
	RLCA			;SHIFT BIT
	RLCA			; FIVE TO
	RLCA			;  BIT TWO
	AND	00000111B	;MASK TO GRANULE NUMBER (0/1)
	LD	H,A		;SAVE RESULT IN H REGISTER
	RLCA			;MULTIPLY BY TWO
	RLCA			;MULTIPLY BY FOUR
	ADD	A,H		;MULTIPLY BY FIVE
	LD	E,A		;GET SECTOR NUMBER TO E
	LD	BC,SCTBUF+255	;AT BUFFER END TO FORCE READ
	EXX			;SWAP TO PRIMARY REGISTERS
BOOTLL:	CALL	BOOTRB-O	;READ A BYTE FROM DISK
	DEC	A		;TEST IF LOAD ADDRESS CODE
	JR	NZ,BOOTTR	;TEST NEXT IF NOT
	CALL	BOOTRB-O	;READ A BYTE FROM DISK
	LD	B,A		;SET AS THE BYTE COUNTER
	CALL	BOOTRB-O	;READ A BYTE FROM DISK
	LD	L,A		;SET AS LOAD ADDRESS LSB
	DEC	B		;DECREMENT BYTE COUNTER
	CALL	BOOTRB-O	;READ A BYTE FROM DISK
	LD	H,A		;SET AS LOAD ADDRESS MSB
BOOTNB:	DEC	B		;DECREMENT BYTE COUNTER
	JR	Z,BOOTLL	;LOOP FOR NEXT RECORD IF ZERO
	CALL	BOOTRB-O	;READ A BYTE FROM DISK
	LD	(HL),A		;STORE THE BYTE IN MEMORY
	INC	HL		;BUMP MEMORY POINTER
	JR	BOOTNB		;THEN GO FOR NEXT BYTE
BOOTTR:	DEC	A		;TEST IF RUN ADDRESS CODE
	JR	Z,BOOTEX	;THEN GO EXECUTE LOADED CODE
	CALL	BOOTRB-O	;READ A BYTE FROM DISK
	LD	B,A		;SET AS THE BYTE COUNTER
BOOTCO:	CALL	BOOTRB-O	;READ A BYTE FROM DISK
	DJNZ	BOOTCO		;LOOP AND DISCARD BYTES
	JR	BOOTLL		;THEN GO FOR NEXT RECORD
BOOTEX:	CALL	BOOTRB-O	;READ AND DISCARD COUNT BYTE
	CALL	BOOTRB-O	;READ A BYTE FROM DISK
	LD	L,A		;SET AS RUN ADDRESS LSB
	CALL	BOOTRB-O	;READ A BYTE FROM DISK
	LD	H,A		;SET AS RUN ADDRESS MSB
	JP	(HL)		;THEN EXECUTE LOADED CODE
;
;
; READ A BYTE FROM SECTOR BUFFER - REFILL IF EMPTY
; ENTRY:  BC      - BUFFER POINTER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - BYTE FROM BUFFER
;         BC      - LSB IS INCREMENTED MODULO 256
;         D       - INCREMENTED IF SECTOR HITS 10
;         E       - INCREMENTED MODULO 10
;5E75
BOOTRB:	EXX			;SWAP TO ALTERNATE REGISTERS
	INC	C		;BUMP BUFFER POINTER
	JR	NZ,BOOTGB	;GET BUFFER BYTE IF NOT EMPTY
	PUSH	BC		;SAVE BUFFER POINTER
	LD	A,00000001B	;LOAD DRIVE SELECT CODE
	LD	(MDRVRE),A	;WAS RESELECT CURRENT DRIVE
	CALL	RDSECT-O	;READ NEXT SECTOR
	JR	NZ,RDEROR	;ABORT IF READ ERROR
	POP	BC		;RECOVER BUFFER POINTER
	INC	E		;BUMP SECTOR NUMBER
	LD	A,E		;GET NUMBER TO A
	SUB	NUMSEC		;TEST IF DONE WITH TRACK
	JR	NZ,BOOTGB	;GET BUFFER BYTE IF NOT
	LD	E,A		;ZERO SECTOR NUMBER
	INC	D		;BUMP TO NEXT TRACK
BOOTGB:	LD	A,(BC)		;GET A BYTE FROM BUFFER
	EXX			;SWAP TO PRIMARY REGISTERS
	RET
;
;
; A DISK READ ERROR OCCURRED
;5E90
RDEROR:	LD	HL,DSKERR-O	;POINT AT ERROR MESSAGE
;
;
; DISPLAY A MESSAGE, GET KEYBOARD INPUT AND REBOOT
;5E93
MSGHLT:	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	CALL	KBLINE		;GET A KEYBOARD LINE
	HALT			;RE-BOOT THE SYSTEM
;
;
; DISPLAY A MESSAGE STRING ON THE DISPLAY OUTPUT DEVICE
; MESSAGE TERMINATOR IS 'CC' (NOT OUTPUT) OR 'CR' (OUTPUT)
; ENTRY:  HL      - POINTER TO STRING
; EXIT:   HL      - PRESERVED
;5E9A
MSGOUT:	PUSH	HL		;SAVE STRING POINTER
MSGOUL:	LD	A,(HL)		;GET CHARACTER FROM STRING
	CP	CC		;TEST IF MESSAGE TERMINATOR
	JR	Z,MSGOUX	;THEN WE ARE ALL DONE
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	INC	HL		;BUMP STRING POINTER
	CP	CR		;TEST IF MESSAGE TERMINATOR
	JR	NZ,MSGOUL	;LOOP UNTIL IT IS
MSGOUX:	POP	HL		;RECOVER STRING POINTER
	RET
;
;
; READ A DISK SECTOR INTO SECTOR BUFFER - RETRY ONCE
; ENTRY:  BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL READ
;5EAA
RDSECT:	PUSH	BC		;SAVE BUFFER POINTER
	CALL	SECTRD-O	;READ SECTOR INTO BUFFER
	POP	HL		;RECOVER BUFFER POINTER
	RET	Z		;DONE IF SUCCESSFUL READ
	LD	B,H		;BUFFER POINTER MSB TO B
	LD	C,L		;BUFFER POINTER LSB TO C
;
;
; READ A DISK SECTOR INTO SECTOR BUFFER
; ENTRY:  BC      - POINTER TO BUFFER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - DISK CONTROLLER STATUS FLAGS
;         D       - UNCHANGED
;         E       - UNCHANGED
;         ZF      - SET IF SUCCESSFUL READ
;5EB2
SECTRD:	LD	(SCTREG),DE	;STORE TRACK AND SECTOR
	LD	HL,CSTREG	;COMMAND/STATUS REGISTER
	LD	(HL),WDSEEK	;SEEK TO TRACK COMMAND
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
SECTRB:	LD	A,(HL)		;GET FLOPPY CONTROLLER STATUS
	RRCA			;COPY BUSY BIT TO CARRY
	JR	C,SECTRB	;LOOP IF CONTROLLER BUSY
	LD	(HL),WDREAD	;READ SECTOR COMMAND
	PUSH	DE		;SAVE TRACK AND SECTOR VALUES
	LD	DE,DTAREG	;POINT AT DATA REGISTER
	EX	(SP),HL		;DELAY FOR I/O
	EX	(SP),HL		;DELAY FOR I/O
	JR	SECTRE		;THEN ENTER READ LOOP
;
;
; TEST IF NOT BUSY - IF SO, THEN WE ARE DONE READING
;5ECD
SECTRN:	RRCA			;COPY BUSY BIT TO CARRY
	JR	NC,SECTRX	;ALL DONE IF NOT BUSY
;
;
; TEST IF DATA BYTE READY - LOOP IF NOT, ELSE READ AND STORE
;5ED0
SECTRL:	LD	A,(HL)		;GET CONTROLLER STATUS TO A
	BIT	1,A		;TEST IF DATA BYTE IS READY
	JR	Z,SECTRN	;TEST IF DONE IF IT ISN'T
	LD	A,(DE)		;GET DATA BYTE FROM DISK
	LD	(BC),A		;STORE BYTE IN BUFFER
	INC	BC		;BUMP BUFFER POINTER
SECTRE:	JR	SECTRL		;LOOP BACK FOR NEXT BYTE
;
;
; DONE READING - GET FINAL STATUS AND RETURN
;5EDA
SECTRX:	LD	A,(HL)		;GET FINAL STATUS TO A
	AND	01011100B	;MASK TO ERROR BITS
	POP	DE		;RECOVER TRACK AND SECTOR
	RET	Z		;RETURN IF NO ERRORS
	LD	(HL),WDFORC	;ELSE FORCE INTERRUPT
	RET
;
;
; BOOT LOADER MESSAGES
;5EE2
CLRSCR	Db	HO,CE,CC
NOSYST	Db	NA,CO+40,'NO SYSTEM',CR
DSKERR	Db	NA,CO+40,'DISK ERROR',CR
;
;
; RESIDUAL BYTE (AS FAR AS I KNOW)
;
	Db	0EBH		;DEFINE THE BYTE
;
;
; DISKETTE CONTAINS DATA - ASK WHAT TO DO
;
	Org	05B9CH
;
HASDTA:	LD	HL,HASDAM	;POINT AT PROMPT STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	LD	HL,HITBUF	;POINT AT INPUT BUFFER
	LD	B,1		;GET BUFFER SIZE TO B
	CALL	KBLINE		;INPUT AND FILL BUFFER
	LD	A,(HL)		;GET CHARACTER FROM LINE
	CP	'N'		;TEST IF FORMAT NOT WANTED
	JP	Z,HASDRB	;THEN WE ABORT THE FORMAT
	CP	'Y'		;TEST IF FORMAT WANTED
	JP	NZ,HASDTA	;LOOP UNTIL EITHER KEY
	NOP			;DO NOTHING AT ALL
	CALL	SELDRV		;RE-SELECT DISKETTE DRIVE
	LD	BC,32768	;HALF SECOND DELAY
	CALL	DELAYL		;CALL ROUTINE IN BASIC ROM
	RET
;
;
; WAIT FOR SIXTY MILLISECONDS, THEN PROMPT FOR REBOOT
;5BC0
HASDRB:	LD	BC,4096		;LOAD DELAY VALUE
	CALL	DELAYL		;CALL ROUTINE IN BASIC ROM
	JP	PREENT		;THEN GO PROMPT FOR RE-BOOT
;
;
; ALIGN BUFFERS ON A PAGE BOUNDARY
;
	Ds	256 - $ And 255	;RESERVE THE SPACE
;
;
; GRANULE ALLOCATION TABLE (GAT) SECTOR BUFFER
;5C00
GATBUF	Ds	SCTSIZ		;RESERVE THE SPACE
;
;
; DEFINE TRACK LOCK-OUT TABLE OFFSET
;5C60
LOCKTB	Equ	GATBUF+060H	;DEFINE THE OFFSET
;
;
; MULTI PURPOSE OR HASH INDEX TABLE (HIT) SECTOR BUFFER
;5D00
HITBUF	Ds	SCTSIZ		;RESERVE THE SPACE
;
;
; BOOT SECTOR BUFFER
;5E00
	Ds	SCTSIZ		;RESERVE THE SPACE
;
;
; WRITE TRACK (FORMAT BUFFER)
;5F00
TRKBUF	Ds	TRKSIZ		;RESERVE THE SPACE
;
	End	FORMAT
