	Title	'TRSDOS 2.3 Disk Operating System'
;
;
; TRSDOS DISK OPERATING SYSTEM, VERSION 2.3
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON 28.01.2022
;
; PART 0 - NUCLEUS
;
;
; DEFINE IF PATCHES ARE ACTIVE
;
PATCHG	Equ	  0		;PATCHES ACTIVE
;
;
; ASCII EQUATES
;
CC	Equ	  3		;CONTROL-C (END-OF-MESSAGE)
LF	Equ	 10		;LINE FEED
CR	Equ	 13		;CARRIAGE RETURN
HO	Equ	 28		;HOME DISPLAY CURSOR
EE	Equ	 30		;ERASE TO END OF LINE
CE	Equ	 31		;CLEAR TO SCREEN END
CO	Equ	192		;SPACE COMPRESSION (0 TO 63)
;
;
; FLOPPY DISK CONSTANTS
;
MAXDRV	Equ	  4		;MAX NUMBER OF DRIVES
NUMTRK	Equ	 35+(5*PATCHG)	;DEFINE THE COUNT
NUMSEC	Equ	 10		;SECTORS PER TRACK
FIRSEC	Equ	  0		;FIRST SECTOR NUMBER
LASSEC	Equ	NUMSEC-1+FIRSEC	;LAST SECTOR NUMBER
;
;
; WESTERN DIGITAL WD1771 DISK CONTROLLER COMMAND CODES
;
	If	PATCHG		;PATCHES ACTIVE
WDREST	 Equ	00001000B	;RESTORE HEAD
WDSEEK	 Equ	00011100B	;SEEK TO HEAD
WDREAD	 Equ	10001000B	;READ SECTOR
WDWRDB	 Equ	10101000B	;WRITE SECTOR 'FB' DATA MARK
WDWRDA	 Equ	10101001B	;WRITE SECTOR 'FA' DATA MARK
	Else			;ORIGINAL
WDREST	 Equ	00001011B	;RESTORE HEAD
WDSEEK	 Equ	00011111B	;SEEK TO HEAD
WDREAD	 Equ	10001000B	;READ SECTOR
WDWRDB	 Equ	10101000B	;WRITE SECTOR 'FB' DATA MARK
WDWRDA	 Equ	10101001B	;WRITE SECTOR 'FA' DATA MARK
	EndIf			;ALL DONE
;
;
; HARDWARE PORT ADDRESSES
;
INTREG	Equ	037E0H		;INTERRUPT STATUS BYTE
DRVREG	Equ	037E1H		;FLOPPY DRIVE SELECT REGISTER
CSTREG	Equ	037ECH		;FLOPPY STATUS/COMMAND REGISTER
TRKREG	Equ	037EDH		;FLOPPY TRACK REGISTER
SCTREG	Equ	037EEH		;FLOPPY SECTOR REGISTER
DTAREG	Equ	037EFH		;FLOPPY DATA REGISTER
KROONE	Equ	03801H		;KEYBOARD ROW 1
KROSEV	Equ	03840H		;KEYBOARD <BREAK> KEY ROW
TRAPOS	Equ	03C2EH		;DOS PROGRAM TRACE DISPLAY POS
TIMPOS	Equ	03C35H		;DOS TIME DISPLAY POSITION
;
;
; ROM ROUTINE ADDRESSES
;
KBCHAR	Equ	0002BH		;KEYBOARD DRIVER ENTRY
VDCHAR	Equ	00033H		;VIDEO DRIVER ENTRY
PRCHAR	Equ	0003BH		;PRINTER DRIVER ENTRY
DELAYL	Equ	00060H		;DELAY ROUTINE
KYDRVR	Equ	003E3H		;KEYBOARD DRIVER
KYDRAJ	Equ	003FBH		;RE-ENTRY TO KEYBOARD ROUTINE
VIDRAU	Equ	0047DH		;ADD CHARACTER TO VIDEO
VIDRCH	Equ	0049AH		;RETURN LAST VIDEO CHARACTER
VIDRCO	Equ	004AAH		;PROCESS COMPRESSION CODE
VIDRCC	Equ	00506H		;PROCESS VIDEO CONTROL CHARS
PRDRCF	Equ	005B4H		;PRINTER DRIVER RE-ENTRY
;
;
; VECTORS, VARIABLES AND BUFFERS
;
INTVEC	Equ	04012H		;INTERRUPT VECTOR
KEYDCB	Equ	04015H		;KEYBOARD DCB
VDUDCB	Equ	0401DH		;VIDEO DCB
PRNDCB	Equ	04025H		;PRINTER DCB
KBDWRK	Equ	04036H		;KEYBOARD WORK AREA
CLKSEC	Equ	04041H		;SECOND
CLKMIN	Equ	04042H		;MINUTE
CLKHOU	Equ	04043H		;HOUR
CLKDAY	Equ	04044H		;DAY
CLKYEA	Equ	04045H		;YEAR
CLKMON	Equ	04046H		;MONTH
ULOADA	Equ	04047H		;UTILITY LOAD ADDRESS
MEMSIZ	Equ	04049H		;SYSTEM MEMORY SIZE
UTAREA	Equ	05200H		;SYSTEM UTILITY AREA
;
;
; PROGRAM MODULE NAME STRING
;
	Nam	'SYS0  '
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING
;
	Rem	CR
	Rem	'* * * N O T I C E * * *',CR
	Rem	'* PROPRIETARY PROGRAM *',CR
	Rem	'* COPYRIGHT (c) 1979  *',CR
	Rem	'* BY TANDY CORPORATION*',CR
	Rem	'*  FORT WORTH, TEXAS  *',CR
	Rem	'* ALL RIGHTS RESERVED *',CR
	Rem	'* * * N O T I C E * * *',CR
;
;
; DEFAULT SYSTEM PARAMETERS
;
	Org	0404BH
;404B
INTSTS	Db	0		;CURRENT INTERRUPT STATUS
INTMSK	Db	0		;INTERRUPT SUBROUTINE MASK
;
;
; INTERRUPT BIT ROUTINE HANDLER LIST
;404D
	Dw	INTSRR		;INTERRUPT BIT 0
	Dw	INTSRR		;INTERRUPT BIT 1
	Dw	INTSRR		;INTERRUPT BIT 2
	Dw	INTSRR		;INTERRUPT BIT 3
	Dw	INTSRR		;INTERRUPT BIT 4
	Dw	INTSRR		;INTERRUPT BIT 5
DSKINT	Dw	INTSRR		;INTERRUPT BIT 6 - DISK
CLKINT	Dw	INTSRR		;INTERRUPT BIT 7 - CLOCK
;
;
; RESERVE SPACE UPTO STACK AREA
;
	Ds	512 - Low $	;RESERVE THE SPACE
;
;
; SYSTEM STACK AREA
;41FC
STACKT	Equ	$-4		;DEFINE STACK TOP
;
;
; SYSTEM SECTOR BUFFER
;4200
SYSBUF	Ds	256		;RESERVE THE SPACE
;
;
; INTERRUPT TASK LIST ADDRESSES
;
	Org	04500H
;4500
ITASKL	Dw	DEFLTI		;ADDRESS OF TASK 0
	Dw	DEFLTI		;ADDRESS OF TASK 1
	Dw	DEFLTI		;ADDRESS OF TASK 2
	Dw	DEFLTI		;ADDRESS OF TASK 3
	Dw	DEFLTI		;ADDRESS OF TASK 4
	Dw	DEFLTI		;ADDRESS OF TASK 5
	Dw	DEFLTI		;ADDRESS OF TASK 6
	Dw	DEFLTI		;ADDRESS OF TASK 7
	Dw	DEFLTI		;ADDRESS OF TASK 8
	Dw	DEFLTI		;ADDRESS OF TASK 9
	Dw	DEFLTI		;ADDRESS OF TASK 10
	Dw	DEFLTI		;ADDRESS OF TASK 11
;
;
; INTERRUPT SERVICE ROUTINE
;4518
INTSRV:	PUSH	HL		;SAVE HL REGISTER
	PUSH	AF		;SAVE AF REGISTER
	LD	A,(INTREG)	;GET INTERRUPT STATUS BYTE
	LD	HL,INTSTS	;POINT TO INTERRUPT SAVE AREA
	LD	(HL),A		;SAVE INTERRUPT STATUS
	INC	L		;POINT TO MASK BYTE
	AND	(HL)		;COMPARE TO INTERRUPT STATUS
	JR	Z,INTSRI	;IGNORE INTERRUPT IF NO MATCH
INTSRB:	INC	L		;BUMP TO ADDRESS LIST
	RRA			;TEST FOR A MATCH
	JR	C,DOTASK	;JUMP IF ON BIT FOUND
INTSRN:	INC	L		;BUMP TO NEXT ADDRESS
	OR	A		;TEST IF MORE REMAINING
	JR	NZ,INTSRB	;TEST MORE IF SO
INTSRI:	LD	A,(KROSEV)	;LOAD <BREAK> KEY ROW
	AND	00000100B	;TEST IF <BREAK> PRESSED
	JR	NZ,DOBREK	;JUMP IF <BREAK> ACTIVE
INTSRX:	POP	AF		;RECOVER AF REGISTER
	POP	HL		;RECOVER HL REGISTER
	EI			;RE-ENABLE INTERRUPTS
INTSRR:	RET
;
;
; CALL INTERRUPT TASK ROUTINE
;4538
DOTASK:	PUSH	AF		;SAVE AF REGISTER
	PUSH	BC		;SAVE BC REGISTER
	PUSH	DE		;SAVE DE REGISTER
	PUSH	HL		;SAVE HL REGISTER
	PUSH	IX		;SAVE IX REGISTER
	LD	DE,DOTASR	;LOAD RETURN ADDRESS
	PUSH	DE		;SAVE IT ON STACK
	LD	E,(HL)		;LOAD LSB OF TASK ADDRESS
	INC	L		;BUMP TO MSB OF ADDRESS
	LD	D,(HL)		;LOAD MSB OF TASK ADDRESS
	EX	DE,HL		;MOVE ADDRESS TO HL
	JP	(HL)		;JUMP TO INTERRUPT HANDLER
;
;
; RETURN POINT FROM INTERRUPT TASK ROUTINES
;4547
DOTASR:	POP	IX		;RECOVER IX REGISTER
	POP	HL		;RECOVER HL REGISTER
	POP	DE		;RECOVER DE REGISTER
	POP	BC		;RECOVER BC REGISTER
	POP	AF		;RECOVER AF REGISTER
	JR	INTSRN		;LOOK FOR MORE INTERRUPTS
;
;
; ACTIVE <BREAK> KEY DETECTED DURING INTERRUPT PROCESSING
; TEST IF DEBUG IS ACTIVE - RETURN TO POINT OF INTERRUPT IF
; NOT, ELSE CLEAR ACTIVE FLAG, THEN LOAD AND EXECUTE DEBUG
;454F
DOBREK:	LD	HL,DEBUGF	;POINT TO DEBUG ACTIVE FLAG
	XOR	A		;LOAD COMPARISON VALUE
	CP	(HL)		;TEST IF DEBUG ACTIVE
	JR	Z,INTSRX	;JUMP IF INACTIVE
	LD	(HL),A		;RESET FLAG TO INACTIVE
	INC	L		;BUMP TO MSB OF LOAD REQ ADDR
	LD	A,(HL)		;LOAD LSB OF ADDRESS
	INC	L		;BUMP TO MSB OF ADDRESS
	LD	H,(HL)		;LOAD MSB OF ADDRESS
	LD	L,A		;ADDRESS NOW IN HL
	POP	AF		;RESTORE INTERRUPT CONTEXT
	EX	(SP),HL		;MOVE ADDRESS TO STACK
	EI			;RE-ENABLE INTERRUPTS
	RET
;
;
; SYSTEM CLOCK INTERRUPT ROUTINE
;4560
SYSCLI:	LD	A,8		;INDEX TO EIGHTH ENTRY
	CALL	SYSCLT		;GO EXECUTE TASK
	LD	A,9		;INDEX TO NINTH ENTRY
	CALL	SYSCLT		;GO EXECUTE TASK
	LD	A,10		;INDEX TO TENTH ENTRY
	CALL	SYSCLT		;GO EXECUTE TASK
	LD	A,11		;INDEX TO ELEVENTH ENTRY
	CALL	SYSCLT		;GO EXECUTE TASK
	LD	HL,CLINDX	;200 mS TASK INDEX
	INC	(HL)		;BUMP INDEX
	LD	A,(HL)		;GET INDEX TO A
	AND	00000111B	;RESTRICT TO 0-7
SYSCLT:	RLCA			;MAKE INTO A WORD INDEX
	LD	L,A		;MOVE INDEX TO L REGISTER
	LD	H,High ITASKL	;HL CONTAINS ADDRESS INDEX
	LD	(CURTSK),HL	;SAVE CURRENT TASK LIST ADDR
;
;
; LOAD ADDRESS FOR FIRST LEVEL OF INDIRECTION INTO DE
;
	LD	E,(HL)		;FETCH LSB OF ADDRESS
	INC	L		;BUMP TO MSB OF ADDRESS
	LD	D,(HL)		;FETCH MSB OF ADDRESS
	PUSH	DE		;PUSH ADDRESS ON STACK
	POP	IX		;MOVE ADDRESS TO IX REGISTER
	EX	DE,HL		;MOVE ADDRESS TO HL ALSO
;
;
; LOAD ADDRESS FOR SECOND LEVEL OF INDIRECTION
;
	LD	E,(HL)		;FETCH LSB OF ADDRESS
	INC	HL		;BUMP TO MSB OF ADDRESS
	LD	D,(HL)		;FETCH MSB OF ADDRESS
	EX	DE,HL		;MOVE THE ADDRESS TO HL
	JP	(HL)		;EXECUTE THE TASK
;
;
; JUMP TO 'REMOVE CURRENT TASK FROM LIST'
;
	Org	04419H
;
TSKREC:	JP	RECTSK		;REMOVE TASK FROM LIST
;
;
; REMOVE CURRENT TASK FROM LIST
;
	Org	0458EH
;458E
RECTSK:	POP	DE		;CLEAN UP THE STACK
	LD	A,(CURTSK)	;GET INTERRUPT TASK INDEX
	RRCA			;GET INDEX INTO TASK LIST
;
;
; JUMP TO 'REMOVE TASK FROM INTERRUPT TASK LIST'
;
	Org	04413H
;
TSKREM:	JP	REMTSK		;REMOVE TASK FROM LIST
;
;
; REMOVE TASK FROM INTERRUPT TASK LIST
;
	Org	04593H
;
REMTSK:	LD	DE,DEFLTI	;POINT TO INTERRUPT ADDRESS
;
;
; JUMP TO 'ADD ADDRESS TO INTERRUPT TASK LIST'
;
	Org	04410H
;
TSKADD:	JP	ADDTSK		;ADD ADDRESS TO TASK LIST
;
;
; ADD ADDRESS TO INTERRUPT TASK LIST
;
	Org	04596H
;
ADDTSK:	CP	12		;TEST IF LAST TASK
	RET	NC		;THEN WE ARE ALL DONE
	RLCA			;REFORM ADDRESS USING INDEX
	LD	L,A		;FORM ADDRESS
	LD	H,High ITASKL	; OF INTERRUPT TASK
;
;
; REPLACE INTERRUPT POINTER
; ENTRY:  HL      - INTERRUPT TASK LIST POINTER
;         DE      - INTERRUPT TASK HANDLER ADDRESS
;459D
CHGTSK:	DI			;KILL INTERRUPTS DURING ADJUST
	LD	(HL),E		;STORE LSB OF ADDRESS
	INC	L		;BUMP TO MSB OF POINTER
	LD	(HL),D		;STORE MSB OF ADDRESS
	EI			;WE MAY INTERRUPT NOW
;
;
; DEFAULT INTERRUPT TASK
;45A2
DFLTSK:	RET
;
;
; DEFAULT INTERRUPT SERVICE POINTER
;45A3
DEFLTI	Dw	DFLTSK		;POINT TO 'RET' OP-CODE
;
;
; JUMP TO 'REPLACE FIRST INTERRUPT POINTER'
; ENTRY:  DE      - ADDRESS TO REPLACE POINTER
;
	Org	04416H
;
RPLFIP:	JP	FIPRPL		;REPLACE FIRST POINTER
;
;
; REPLACE FIRST INTERRUPT POINTER
;
	Org	045A5H
;
FIPRPL:	LD	HL,0		;LOAD CURRENT TASK ADDRESS
CURTSK	Equ	$-2		;CURRENT INTERRUPT TASK ADDRESS
	LD	E,(HL)		;GET LSB OF TASK LIST ADDRESS
	INC	HL		;BUMP TO MSB OF ADDRESS
	LD	D,(HL)		;LOAD MSB OF TASK LIST ADDRESS
	EX	DE,HL		;MOVE TASK LIST ADDR TO HL
	POP	DE		;CLEAR THE STACK
	JR	CHGTSK		;GO STORE POINTER TO ADDRESS
;
;
; CLOCK MAINTENANCE INTERRUPT TASK
;45AF
CLKTSK	Dw	CLKHAN		;POINTER TO ROUTINE
	Db	5		;ENTRY COUNTER
CLKHAN:	DEC	(IX+02)		;DECREMENT ENTRY COUNTER
	RET	NZ		;EXIT IF MORE ENTRIES LEFT
	LD	(IX+02),5	;RESET ELAPSED TIME COUNTER
	LD	B,3		;NUMBER OF VALUES TO UPDATE
	LD	HL,CLKSEC	;STARTING ADDRESS FOR TIME
	LD	DE,MAXPER	;MAXIMUM PERIOD TABLE
CLKHAL:	INC	(HL)		;BUMP THE PERIOD
	LD	A,(DE)		;GET MAXIMUM PERIOD VALUE
	SUB	(HL)		;COMPARE TO MAX UNIT VALUE
	RET	NZ		;RETURN IF UNIT NOT MAX
	LD	(HL),A		;ELSE RESET PERIOD TO ZERO
	INC	L		;THEN BUMP TO NEXT VALUE
	INC	E		;BUMP TO NEXT TEST ADDRESS
	DJNZ	CLKHAL		;LOOP UNTIL ALL DONE
;
;
; UPDATE DATE IF 24 HOURS HAVE PASSED
;
	INC	L		;SKIP OVER YEAR VALUE
	INC	(HL)		;BUMP DAY VALUE
	INC	L		;SKIP TO MONTH VALUE
	LD	A,(HL)		;FETCH MONTH VALUE
	DEC	L		;BACKSPACE TO DAY VALUE
	DEC	A		;INDEX INTO MONTH TABLE
	ADD	A,E		;LSB OF MONTH TABLE ADDRESS
	LD	E,A		;FORM MONTH TABLE ADDRESS
	LD	A,(DE)		;FETCH DAYS FOR CURRENT MONTH
	CP	(HL)		;COMPARE WITH CURRENT DAYS
	RET	NC		;EXIT IF MONTH NOT ROLLED OVER
	LD	A,(HL)		;REFETCH CURRENT DAY NUMBER
	CP	30		;TEST IF FEBRUARY
	JR	NC,CLKHNF	;JUMP IF NOT FEBRUARY
	DEC	L		;BACKSPACE TO YEAR VALUE
	LD	A,(HL)		;FETCH YEAR
	INC	L		;SKIP FORWARD TO DAY
	AND	00000011B	;TEST IF LEAP YEAR
	RET	Z		;EXIT IF NOT LEAP YEAR
CLKHNF:	LD	(HL),1		;RESET DAY TO 1
	INC	L		;BUMP TO MONTH
	INC	(HL)		;INCREMENT MONTH VALUE
	LD	A,(HL)		;FETCH MONTH VALUE
	SUB	13		;TEST FOR YEAR ROLLOVER
	RET	C		;EXIT IF NOT END OF YEAR
	LD	(HL),1		;RESET MONTH TO 1
	DEC	L		;BACKSPACE OVER MONTH
	DEC	L		;THEN OVER DAY
	INC	(HL)		;THEN INCREMENT YEAR
	RET
;
;
; MAXIMUM VALUES FOR CLOCK PERIODS
;45EF
MAXPER	Db	60		;SECONDS
	Db	60		;MINUTES
	Db	24		;HOURS
;
;
; MONTH TABLE - NUMBER OF DAYS IN EACH MONTH
;
	Db	31		;JANUARY
	Db	28		;FEBRUARY
	Db	31		;MARCH
	Db	30		;APRIL
	Db	31		;MAY
	Db	30		;JUNE
	Db	31		;JULY
	Db	31		;AUGUST
	Db	30		;SEPTEMBER
	Db	31		;OCTOBER
	Db	30		;NOVEMBER
	Db	31		;DECEMBER
;
;
; SELECT DISK DRIVE
; ENTRY:  C       - DRIVE TO SELECT
;
	Org	04600H
;
SELDRV:	PUSH	HL		;SAVE CALLER'S HL
	LD	HL,LASDRV	;ADDRESS OF LAST DRIVE SELECTED
	LD	A,(HL)		;LOAD LAST DRIVE SELECTED
	CP	C		;COMPARE WITH DRIVE REQUESTED
	JR	NZ,SELDDI	;JUMP IF DIFFERENT DRIVE
	INC	L		;BUMP TO LAST DRIVE SELECT MASK
	LD	A,(HL)		;LOAD DRIVE SELECT MASK
	JR	SELDSA		;THEN GO SELECT DRIVE
SELDDI:	LD	(HL),C		;UPDATE LAST DRIVE SELECTED
	LD	H,High LASTRK	;FORM LAST TRACK TABLE ORIGIN
	LD	L,A		;FORM ORIGIN OF CURRENT DRIVE
	CALL	WAITNB		;WAIT FOR CONTROLLER NOT BUSY
	LD	A,(TRKREG)	;LOAD CURRENT TRACK
	LD	(HL),A		;SAVE LAST TRACK SELECTED
	LD	A,C		;GET DRIVE NUMBER TO A
	LD	L,A		;REFORM LAST TRACK ADDRESS
	LD	A,(HL)		;GET LAST TRACK SELECTED
	LD	(TRKREG),A	;UPDATE TRACK REGISTER
	LD	A,C		;GET DRIVE NUMBER TO A
	CALL	SELMSK		;CONSTRUCT DRIVE SELECT MASK
	LD	(DRVMSK),A	;SAVE FOR FUTURE USE
SELDSA:	LD	L,A		;SAVE MASK FOR LATER
	LD	A,(CSTREG)	;GET DRIVE STATUS
	RLCA			;TEST NOT READY BIT
	LD	A,L		;RESTORE DRIVE SELECT MASK
	LD	(DRVREG),A	;SELECT THE DRIVE
	JR	NC,SELDEX	;JUMP IF DRIVE READY
	LD	HL,0		;LOAD DELAY COUNTER
SELDDL:	DEC	HL		;DECREMENT THE COUNTER
	LD	A,H		;GET MSB TO A FOR TEST
	OR	L		;TEST IF COUNTER ZERO
	JR	NZ,SELDDL	;LOOP IF NOT ZERO
SELDEX:	POP	HL		;RESTORE CALLER'S HL
	RET
;
;
; CONSTRUCT A UNIT SELECT MASK FOR A DRIVE
; ENTRY:  A       - DRIVE NUMBER
; EXIT:   A       - UNIT SELECT MASK
;4639
SELMSK:	AND	00000111B	;RESTRICT DRIVE TO 0-7
	RLCA			;SHIFT DRIVE NUMBER LEFT
	RLCA			; THREE BIT POSITIONS
	RLCA			;  TO COMBINE WITH SET OP-CODE
	OR	11000111B	;SYNTHESIZE SET (A),A OP-CODE
	LD	(UNIMSK),A	;STORE SYNTHESIZED INSTRUCTION
	XOR	A		;ZERO ACCUMULATOR
	SET	0,A		;TURN ON DRIVE NUMBER BIT
UNIMSK	Equ	$-1		;UNIT SELECT MASK FOR 'SET'
	RET
;
;
; SELECT DRIVE AND ISSUE SEEK IF NOT ON TRACK
;4647
SELSEK:	CALL	SELDRV		;SELECT DISK DRIVE
	CALL	WAINBU		;WAIT FOR CONTROLLER NOT BUSY
	LD	A,(TRKREG)	;FETCH LAST TRACK SELECTED
	CP	D		;COMPARE WITH REQUIRED TRACK
	LD	(SCTREG),DE	;UPDATE TRACK/SECTOR REGISTERS
	RET	Z		;DONE IF AT REQUESTED TRACK
	LD	A,WDSEEK	;LOAD SEEK OP-CODE
;
;
; ISSUE COMMAND TO DISK CONTROLLER
; ENTRY:  A       - COMMAND TO ISSUE
;4658
ISSCMD:	PUSH	AF		;SAVE OP-CODE FOR LATER
	CALL	WAINBU		;WAIT FOR CONTROLLER NOT BUSY
	POP	AF		;RECOVER SAVED OP-CODE
	LD	(CSTREG),A	;SEND IT TO CONTROLLER
	RET
;
;
; SEND COMMAND TO DISK CONTROLLER - WAIT UNTIL PROCESSED
;
; -- APPARENTLY UNUSED CODE BLOCK --
;4661
CMDOUT:	CALL	ISSCMD		;SEND COMMAND TO CONTROLLER
;
	If	PATCHG		;PATCHES ACTIVE
	 EX	(SP),HL		;DELAY FOR I/O
	 EX	(SP),HL		;DELAY FOR I/O
	 EX	(SP),HL		;DELAY FOR I/O
	 EX	(SP),HL		;DELAY FOR I/O
	 NOP			;DELAY FOR I/O
	Else			;ORIGINAL
	 PUSH	AF		;DELAY FOR I/O
	 POP	AF		;DELAY FOR I/O
	 NOP			;DELAY FOR I/O
	 NOP			;DELAY FOR I/O
	 NOP			;DELAY FOR I/O
	EndIf			;DONE WITH IT
;
;
; WAIT UNTIL CONTROLLER NOT BUSY
;4669
WAINBU:	CALL	RESEUN		;RE-SELECT DRIVE, GET STATUS
	BIT	0,A		;TEST IF CONTROLLER BUSY
	RET	Z		;ALL DONE IF NOT BUSY
	JR	WAINBU		;LOOP UNTIL NOT BUSY
;
;
; MAIN DISK DRIVER FOR READ/WRITE OPERATIONS
; ENTRY:  A       - CONTROLLER READ/WRITE CODE
;         C       - UNIT NUMBER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
;         (SP+00) - POINTER TO PARAMETERS
;         SP+00   - ERROR RETRY COUNT
;         SP+01   - ERROR CODE BIAS VALUE
;         SP+02   - LD A,(BC) IF WRITE, LD A,(DE) IF READ
;         SP+03   - LD (DE),A IF WRITE, LD (BC),A IF READ
; EXIT:   CF      - SET IF ERROR, RESET OTHERWISE
;         A       - 0 IF NO ERROR, ERROR CODE OTHERWISE
;4671
DSKDRV:	LD	(RWCODE),A	;SAVE DISK CONTROLLER OP CODE
	EX	(SP),HL		;SAVE BUFFER PTR, GET PARM PTR
	PUSH	BC		;SAVE CALLER'S BC
	LD	B,(HL)		;FETCH RETRY COUNT
	INC	HL		;BUMP PARAMETER POINTER
	LD	A,(HL)		;GET BIAS COUNT
	INC	HL		;BUMP PARAMETER POINTER
	LD	(ERBIAS),A	;SAVE ERROR BIAS VALUE
	LD	A,(HL)		;GET FETCH/STORE INSTRUCTION
	INC	HL		;BUMP PARAMETER POINTER
	LD	H,(HL)		;GET FETCH/STORE INSTRUCTION
	LD	L,A		;ASSEMBLE TRANSFER CODES
;
	If	PATCHG		;PATCHES ACTIVE
	 LD	(DOXFER),HL	;STORE TRANSFER CODES
	Else			;ORIGINAL
	 LD	(DOXFER),HL	;STORE TRANSFER CODES
	EndIf			;DONE WITH IT
;
	POP	HL		;MOVE CALLERS BC TO HL
	EX	(SP),HL		;HL POINTS TO BUFFER
DSKDRR:	CALL	SELSEK		;SELECT UNIT, POSITION HEAD
	CALL	WAINBU		;WAIT FOR CONTROLLER TO DO IT
	PUSH	BC		;SAVE RETRY COUNT/UNIT NUMBER
	PUSH	DE		;SAVE TRACK/SECTOR NUMBER
	PUSH	HL		;SAVE BUFFER ADDRESS
	LD	HL,CSTREG	;CONTROLLER COMMAND/STATUS REG
	LD	(HL),0		;ISSUE READ/WRITE COMMAND
RWCODE	Equ	$-1		;DISK CONTROLLER COMMAND CODE
	LD	DE,DTAREG	;CONTROLLER DATA REGISTER
	POP	BC		;GET BUFFER ADDRESS TO BC
	PUSH	BC		;RE-SAVE THE ADDRESS
;
	If	PATCHG		;PATCHES ACTIVE
 	 EX	(SP),HL		;DELAY FOR I/O
	 EX	(SP),HL		;DELAY FOR I/O
	 EX	(SP),HL		;DELAY FOR I/O
	 EX	(SP),HL		;DELAY FOR I/O
	 DI			;NO INTERUPTIONS ALLOWED
	 JR	TSTRDY		;ENTER TRANSFER LOOP
TSTBSY:	 RRCA			;TEST IF CONTROLLER BUSY
	 JR	NC,XFRDON	;ALL DONE IF NOT BUSY
TSTRDY:	 LD	A,(HL)		;GET STATUS BYTE
	 BIT	1,A		;TEST IF BYTE IS READY
	 JR	Z,TSTBSY	;TEST CONTROLLER BUSY IF NOT
DOXFER:	 NOP			;ELSE DO
	 NOP			; THE TRANSFER
	 INC	BC		;BUMP BUFFER POINTER
	 JR	TSTRDY		;THEN LOOP FOR NEXT BYTE
	Else			;ORIGINAL
	 POP	BC		;DELAY FOR I/O
	 PUSH	BC		;DELAY FOR I/O
	 DI			;NO INTERRUPTIONS ALLOWED
	 JR	TSTRDY		;THEN ENTER TRANSFER LOOP
TSTBSY:	 RRCA			;ROTATE BUSY BIT TO CARRY
	 JR	NC,XFRDON	;ALL DONE IF NOT BUSY
TSTRDY:	 LD	A,(HL)		;GET STATUS BYTE
	 BIT	1,A		;TEST IF BYTE IS READY
	 JR	Z,TSTBSY	;CONTINUE TESTING IF NOT
	 DI			;NO INTERRUPTIONS ALLOWED
DOXFER:	 NOP			;DO THE
	 NOP			; TRANSFER
	 INC	BC		;BUMP BUFFER POINTER
	 JP	TSTRDY		;THEN LOOP FOR NEXT BYTE
	EndIf			;DONE WITH IT
;
XFRDON:	EI			;RE-ENABLE INTERRUPTS
	LD	A,(HL)		;GET CONTROLLER STATUS
	AND	01111100B	;MASK TO ERROR BITS
	LD	(HL),0D0H	;CLEAR DISK CONTROLLER
	POP	HL		;RECOVER BUFFER ADDRESS
	POP	DE		;RECOVER TRACK/SECTOR NUMBER
	POP	BC		;RECOVER RETRY COUNT/UNIT
	JR	Z,FONDBI	;EXIT IF NO ERRORS
	BIT	2,A		;TEST IF LOST DATA
	JR	NZ,LOSTDA	;JUMP IF LOST DATA
	CP	00100000B	;TEST IF WRITE FAULT
	JR	Z,WFAULT	;JUMP IF WRITE FAULT
	PUSH	AF		;SAVE ERROR STATUS
	LD	A,-1		;FORCE UNIT TO
	LD	(LASDRV),A	; BE RE-SELECTED
	CALL	SELDRV		;SELECT UNIT
	LD	A,WDREST	;RESTORE HEAD COMMAND
	CALL	ISSCMD		;ISSUE RESTORE COMMAND
	POP	AF		;RECOVER SAVED STATUS
LOSTDA:	DJNZ	DSKDRR		;LOOP FOR RETRY COUNT
WFAULT:	LD	B,A		;MOVE STATUS TO B
	LD	A,0		;MOVE BIAS VALUE TO A
ERBIAS	Equ	$-1		;ERROR CODE BIAS VALUE
FINDBI:	RRC	B		;RIGHT SHIFT ERROR STATUS
	JR	C,FONDBI	; UNTIL ERROR BIT FOUND
	INC	A		;INCREMENT BIAS VALUE
	JR	FINDBI		;LOOP UNTIL ERROR BIT FOUND
FONDBI:	POP	BC		;RECOVER RETRY COUNT/UNIT
	RET
;
;
; READ SUBROUTINE USED TO CALL DISK DRIVER
; ENTRY:  C       - UNIT NUMBER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - RETURN CODE
;         CF      - SET IF ERROR
;46DD
RDSECT:	LD	A,WDREAD	;LOAD READ COMMAND
	CALL	DSKDRV		;CALL DISK DRIVER
	Db	10		;RETRY COUNT IF ERROR
	Db	1		;BIAS TO BE ADDED TO ERROR
	LD	A,(DE)		;FETCH BYTE FROM CONTROLLER
	LD	(BC),A		;STORE IN CALLER'S BUFFER
;
;
; WRITE SUBROUTINE USED TO CALL DISK DRIVER - DATA
; ENTRY:  C       - UNIT NUMBER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - RETURN CODE
;         CF      - SET IF ERROR
;46E6
WRNSEC:	LD	A,WDWRDB	;LOAD WRITE OP CODE 'FB' DAM
;
;
; WRITE SUBROUTINE USED TO CALL DISK DRIVER
; ENTRY:  A       - DISK CONTROLLER COMMAND CODE
;         C       - UNIT NUMBER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - RETURN CODE
;         CF      - SET IF ERROR
;46E8
WRSECT:	CALL	DSKDRV		;CALL DISK DRIVER
	Db	5		;RETRY COUNT IF ERROR
	Db	9		;BIAS TO ADD TO ERROR CODE
	LD	A,(BC)		;FETCH BYTE FROM DATA BUFFER
	LD	(DE),A		;SEND BYTE TO CONTROLLER
;
;
; WRITE SUBROUTINE USED TO CALL DISK DRIVER - DIRECTORY
; ENTRY:  C       - UNIT NUMBER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - RETURN CODE
;         CF      - SET IF ERROR
;46EF
WRDSEC:	LD	A,WDWRDA	;LOAD WRITE OP CODE 'FA' DAM
	JR	WRSECT		;USE NORMAL WRITE DISK CALL
;
;
; READ SUBROUTINE USED TO CALL DISK DRIVER - VERIFY READ
; ENTRY:  C       - UNIT NUMBER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
; EXIT:   A       - RETURN CODE
;         CF      - SET IF ERROR
;46F3
RDSECV:	LD	A,WDREAD	;LOAD READ OP CODE
	CALL	DSKDRV		;CALL DISK DRIVER
	Db	5		;RETRY COUNT IF ERROR
	Db	1		;BIAS TO ADD TO ERROR CODE
	LD	A,(DE)		;FETCH BYTE FROM CONTROLLER
	NOP			;DO NOT STORE DATA IN BUFFER
;
;
; JUMP TO 'POSITION TO SPECIFIED RECORD' ROUTINE
;
	Org	04442H
;
POSREC:	JP	RECPOS		;GO POSITION TO RECORD
;
;
; POSITION FILE TO SPECIFIED RECORD NUMBER
;
	Org	04700H
;
RECPOS:	CALL	SAVREG		;SAVE CALLER'S REGISTERS
	SET	6,(IX+01)	;SIGNAL POSITION CALL
	BIT	7,(IX+01)	;TEST FOR PHYSICAL/LOGICAL I/O
	JR	Z,RECPOP	;JUMP IF PHYSICAL I/O
	LD	H,B		;MOVE RECORD NUMBER FROM BC
	LD	L,C		; TO HL SO IT CAN BE DIVIDED
	LD	A,(IX+09)	;FETCH RECORD SIZE
	CALL	RECTOS		;DIVIDE BY RECORD SIZE
	LD	B,H		;MOVE RELATIVE
	LD	C,L		; RECORD NUMBER TO BC
RECPOP:	LD	(IX+05),A	;SAVE OFFSET WITHIN SECTOR
	PUSH	BC		;SAVE RELATIVE RECORD NUMBER
	CALL	PURGEB		;FLUSH SECTOR BUFFER TO DISK
	POP	BC		;RECOVER RELATIVE RECORD
	RET	NZ		;ABORT IF ANY ERRORS
	LD	(IX+10),C	;MOVE RELATIVE SECTOR TO
	LD	(IX+11),B	; DCB AS NEXT RECORD NUMBER
	SET	5,(IX+01)	;FORCE READ ON NEXT ACCESS
	CALL	TSTEOF		;TEST FOR END OF FILE
	RET	NZ		;EXIT IF END OF FILE
	CALL	LCTGAP		;GET TRACK AND SECTOR FOR REC
	RET	NZ		;GO IF ERROR DURING TRANSLATION
	CALL	SELSEK		;SELECT DRIVE AND FIND TRACK
	XOR	A		;SIGNAL GOOD STATUS
	RET
;
;
; JUMP TO 'BACKSPACE ONE RECORD' ROUTINE
;
	Org	04445H
;
BACREC:	JP	RECBAC		;JUMP TO BACKSPACE ROUTINE
;
;
; BACKSPACE ONE RECORD OPERATION
;
	Org	04737H
;
RECBAC:	CALL	SAVREG		;SET UP EXIT SEQUENCE
	LD	C,(IX+10)	;LOAD BC WITH
	LD	B,(IX+11)	; NEXT SECTOR NUMBER
	BIT	7,(IX+01)	;TEST FOR LOGICAL VS PHY I/O
	JR	Z,RECFUL	;JUMP IF PHY I/O
	LD	A,(IX+09)	;GET RECORD SIZE FROM DCB
	OR	A		;TEST IF 256 BYTE RECORD
	JR	Z,RECFUL	;JUMP IF IT IS
	NEG			;ELSE NEGATE RECORD SIZE
	ADD	A,(IX+05)	;SUBTRACT LENGTH FROM POSITION
	JR	C,RECPOP	;GO IF IT CROSSES SECTOR LINE
RECFUL:	DEC	BC		;DECREMENT SECTOR NUMBER
	JR	RECPOP		;UPDATE BUFFER, FLUSH, RETURN
;
;
; JUMP TO 'REWIND' ROUTINE
;
	Org	0443FH
;
REWIND:	JP	REWINF		;REWIND THE FILE
;
;
; REWIND FILE
;
	Org	04756H
;
REWINF:	CALL	SAVREG		;SAVE CALLER'S REGISTERS
	LD	BC,0		;RECORD NUMBER FOR POSN CALL
	XOR	A		;ZERO OFFSET IN SECTOR BUFFER
	JR	RECPOP		;USE POSN TO REWIND FILE
;
;
; JUMP TO 'SKIP TO END OF FILE' ROUTINE
;
	Org	04448H
;
POSEOF:	JP	EOFPOS		;SKIP TO END OF FILE
;
;
; SKIP TO END OF FILE
;
	Org	0475FH
;
EOFPOS:	CALL	SAVREG		;SAVE CALLERS REGISTERS
	LD	C,(IX+12)	;LOAD NUMBER OF RECORDS
	LD	B,(IX+13)	; IN FILE INTO BC REGISTER
	LD	A,(IX+08)	;GET EOF BYTE IN LAST RECORD
	JR	RECPOP		;USE POSN TO UPDATE DCB
;
;
; JUMP ADDRESS TO READ RECORD ROUTINE
;
	Org	04436H
;
REDREC:	JP	RECRED		;READ THE RECORD
;
;
; READ RECORD PROCESSING
;
	Org	0476DH
;
RECRED:	CALL	SAVREG		;SAVE CALLER'S REGISTERS
	CALL	PURGEB		;PURGE BUFFER IF NECESSARY
	RET	NZ		;ABORT IF ANY ERRORS
	BIT	7,(IX+01)	;TEST FOR PHYSICAL I/O
	JP	Z,RDNXTS	;JUMP IF PHYSICAL READ
;
;
; LOGICAL READ
; TRANSFER RECORD FROM SECTOR BUFFER TO USER'S RECORD AREA,
; BYTE BY BYTE - THE SUBROUTINE AT READOP RETURNS THE NEXT BYTE
; FROM THE SECTOR BUFFER - IF THE BUFFER IS EXHAUSTED THE
; NEXT SECTOR WILL BE READ
;
	LD	B,(IX+09)	;GET RECORD SIZE
LOGIRD:	PUSH	HL		;SAVE USER'S RECORD AREA PTR
	PUSH	BC		;SAVE RECORD SIZE
	CALL	READOP		;GET A BYTE FROM SECTOR BUFFER
	POP	BC		;RECOVER RECORD SIZE
	POP	HL		;RECOVER RECORD AREA POINTER
	RET	NZ		;ABORT IF ANY READ ERRORS
	LD	(HL),A		;STORE BYTE IN USER'S BUFFER
	INC	HL		;BUMP BUFFER POINTER
	DJNZ	LOGIRD		;LOOP UNTIL RECORD MOVED
	RET
;
;
; JUMP TO WRITE RECORD ROUTINE
;
	Org	04439H
;
WRTREC:	JP	RECWRT		;GO WRITE THE RECORD
;
;
; WRITE RECORD PROCESSING
;
	Org	0478BH
;
RECWRT:	CALL	SAVREG		;SAVE CALLERS REGISTERS
;
;
; WRITE RECORD WITH OR WITHOUT VERIFY
; ENTRY:  A       - VERIFY FLAG
;478E
RECWRV:	LD	(VERIFL),A	;INITIALIZE VERIFY FLAG
	BIT	7,(IX+01)	;TEST IF PHYSICAL I/O
	JP	Z,PURGEL	;JUMP IF PHYSICAL
;
;
; LOGICAL WRITE
; TRANSFER RECORD FROM USER'S RECORD AREA TO SECTOR BUFFER,
; BYTE BY BYTE - THE SUBROUTINE AT WRITOP STORES THE NEXT BYTE
; IN THE SECTOR BUFFER - IF THE BUFFER IS FULL, IT IS WRITTEN
; TO DISK
;
	LD	B,(IX+09)	;GET RECORD SIZE
LOGWRT:	LD	A,(HL)		;GET BYTE FROM USER'S RECORD
	INC	HL		;BUMP TO NEXT DATA BYTE
	PUSH	HL		;SAVE USER'S RECORD AREA PTR
	PUSH	BC		;SAVE RECORD SIZE
	CALL	WRITOP		;STORE CHAR IN SECTOR BUFFER
	POP	BC		;RECOVER RECORD SIZE
	POP	HL		;RECOVER RECORD AREA POINTER
	RET	NZ		;ABORT IF ANY WRITE ERRORS
	DJNZ	LOGWRT		;LOOP UNTIL RECORD MOVED
	RET
;
;
; JUMP TO WRITE RECORD WITH VERIFY ROUTINE
;
	Org	0443CH
;
WRTREV:	JP	REVWRT		;GO DO THE VERIFY
;
;
; WRITE RECORD WITH VERIFY
;
	Org	047A8H
;
REVWRT:	CALL	SAVREG		;SAVE CALLER'S REGISTERS
	INC	A		;LOAD A 1 TO SHOW VERIFY
	JR	RECWRV		;THEN USE WRITE ROUTINE
;
;
; GENERAL PURPOSE DRIVER ENTRY
;47AE
GENDRV:	CALL	SAVREG		;SAVE CALLERS REGISTERS
	SET	7,(IX+01)	;SIGNAL LOGICAL I/O
	LD	A,B		;FETCH OPERATION CODE
	CP	2		;TEST FOR READ OR WRITE
	LD	A,C		;SAVE DATA FOR WRITE OP-CODE
	JR	NC,WRITOP	;GO IF WRITE OPERATION
;
;
; READ OPERATION REQUESTED
; EXIT:   A       - CHARACTER READ
;47BB
READOP:	CALL	TSTEOF		;TEST FOR END-OF-FILE
	RET	NZ		;RETURN IF EOF (A = 1CH OR 1DH)
	BIT	5,(IX+01)	;ANOTHER SECTOR FOR BUFFER?
	JR	Z,READON	;GET NEXT RECORD BYTE IF NOT
	CALL	RDNXTS		;READ NEXT SECTOR FROM FILE
	RET	NZ		;EXIT IF EOF OR OTHER ERROR
READON:	CALL	NEXTAD		;NEXT RECORD ADDRESS TO DE
	XOR	A		;CLEAR STATUS FLAGS
	LD	A,(DE)		;GET BYTE FROM SECTOR BUFFER
	PUSH	AF		;SAVE FETCHED CHARACTER
	INC	(IX+05)		;BUMP TO NEXT BUFFER BYTE
	JR	NZ,READOX	;JUMP IF BUFFER NOT EMPTY
	SET	5,(IX+01)	;SIGNAL READ REQUIRED
READOX:	POP	AF		;RESTORE FETCHED CHARACTER
	RET
;
;
; WRITE OPERATION REQUESTED
; ENTRY:  A       - BYTE TO BE WRITTEN
;47DA
WRITOP:	PUSH	AF		;SAVE BYTE TO BE WRITTEN
	BIT	5,(IX+01)	;TEST IF SECTOR BUFFER FULL
	JR	Z,WRITON	;JUMP IF ROOM IN SECTOR BUFFER
	CALL	NXTFIS		;READ NEXT FILE SECTOR
	JR	Z,WRITON	;GO IF NO READ ERRORS
	EX	(SP),HL		;CLEAR CHARACTER FROM STACK
	POP	HL		;CLEAN UP THE STACH
	RET
;
;
; CONTINUATION OF WRITE OPERATION
;47E9
WRITON:	CALL	NEXTAD		;GET NEXT POSITION TO DE
	POP	AF		;RECOVER SAVED CHARACTER
	LD	(DE),A		;STORE IT IN SECTOR BUFFER
	INC	DE		;BUMP BUFFER POSITION
	SET	4,(IX+01)	;FLAG BUFFER AS DIRTY
	INC	(IX+05)		;BUMP TO NEXT BUFFER POSITION
	CALL	TSTEOF		;TEST FOR EOF ACCESS PERMITTED
	JR	NZ,WRTNOP	;ABORT IF NOT PERMITTED
	BIT	6,(IX+01)	;RECORD NUMBER TO INCREMENT
	JR	NZ,WRITNU	;JUMP IF NOT UPDATING
WRTNOP:	LD	(IX+08),C	;UPDATE BUFFER EOF ADDRESS
WRITNU:	LD	A,C		;CURRENT SECTOR BUFFER OFFSET
	OR	A		;SET STATUS FLAGS FOR OFFSET
	JR	NZ,INCREX	;GO IF END NOT REACHED
	SET	5,(IX+01)	;FLAG BUFFER FULL, FORCE READ
	JR	PURGEL		;THEN GO PURGE THE BUFFER
;
;
; READ NEXT SECTOR FROM FILE
;480E
RDNXTS:	LD	A,(IX+01)	;FETCH ACCESS LEVEL TO A
	AND	00000111B	;ISOLATE PERMISSION FLAGS
	CP	00000110B	;TEST FOR READ/WRITE ACCESS
	JR	C,NOTRDP	;JUMP IF NO READ PROTECTION
	LD	A,25H		;PROTECTED FILE ILLEGAL ACCESS
	OR	A		;SET ERROR STATUS FLAGS
	RET
;
;
; NOT READ PROTECTED - TEST FOR END-OF-FILE
;481B
NOTRDP:	CALL	TSTEOF		;TEST FOR END-OF-FILE
	RET	NZ		;ABORT IF FILE END
	CALL	NXTFIS		;READ NEXT SECTOR FROM FILE
	RET	NZ		;EXIT IF ERROR DURING READ
;
;
; INCREMENT NEXT RECORD NUMBER
;4823
INCREC:	INC	(IX+10)		;BUMP NEXT RECORD NUMBER LSB
	JR	NZ,INCREX	;JUMP IF NOT OVERFLOW
	INC	(IX+11)		;BUMP NEXT RECORD NUMBER MSB
;
;
; PASS GOOD STATUS
; EXIT:   A       - ZERO
;         CF      - RESET
;         ZF      - SET
;482B
INCREX:	XOR	A		;SIGNAL GOOD STATUS - NO ERROR
	RET
;
;
; READ NEXT RECORD FROM FILE
;482D
NXTFIS:	CALL	LCTGAP		;GET NEXT SECTOR DISK ADDRESS
	RET	NZ		;EARLY RETURN IF ANY ERROR
	RES	5,(IX+01)	;CLEAR FORCE READ FLAG
	LD	L,(IX+03)	;SECTOR BUFFER ADDRESS LSB
	LD	H,(IX+04)	;SECTOR BUFFER ADDRESS MSB
	JP	RDSECT		;READ SECTOR AND RETURN
;
;
; PURGE LOGICAL SECTOR BUFFER IF NECESSARY
; ENTRY:  IX      - POINTER TO DEVICE CONTROL BLOCK
;483E
PURGEL:	LD	A,(IX+01)	;GET ACCESS FLAGS TO A
	AND	00000111B	;ISOLATE PERMISSIONS
	CP	00000101B	;TEST RUN ONLY OR RESTRICTED
	JR	C,PERMOK	;SKIP IF NEITHER
	LD	A,25H		;PROTECTED FILE ILLEGAL ACCESS
	OR	A		;RESET CARRY AND ZERO FLAGS
	RET
;
;
; FILE PERMISSIONS ARE NOT EXECUTE ONLY OR RESTRICTED ACCESS
;484B
PERMOK:	CALL	LCTGAP		;GET NEXT SECTOR DISK ADDRESS
	RET	NZ		;ABORT IF ANY ERRORS
	LD	L,(IX+03)	;SECTOR BUFFER ADDRESS LSB
	LD	H,(IX+04)	;SECTOR BUFFER ADDRESS MSB
	CALL	WRNSEC		;WRITE CURRENT SECTOR BUFFER
	RET	NZ		;ABORT IF WRITE ERROR
	RES	4,(IX+01)	;SIGNAL BUFFER AVAILABLE
	LD	A,0		;LOAD VERIFY FLAG TO A
VERIFL	Equ	$-1		;VERIFY WRITE FLAG STORAGE
	OR	A		;TEST IF VERIFY IS ON
	CALL	NZ,RDSECV	;READ AND VERIFY SECTOR
	RET	NZ		;ABORT IF READ ERROR
	CALL	TSTEOF		;TEST FOR END-OF-FILE
	JR	NZ,GOTEOF	;SKIP IF FILE END
	BIT	6,(IX+01)	;TEST IF POSITION CALL
	JR	NZ,INCREC	;THEN DO THE POSITIONING
GOTEOF:	INC	HL		;BUMP RECORD NUMBER
	LD	(IX+12),L	;UPDATE RECORD COUNT LSB
	LD	(IX+13),H	;UPDATE RECORD COUNT MSB
	JR	INCREC		;UPDATE THE COUNT AND EXIT
;
;
; PURGE SECTOR BUFFER IF NECESSARY
; ENTRY:  IX      - POINTER TO DEVICE CONTROL BLOCK
; EXIT:   A       - ZERO IF PHYSICAL ACCESS
;         ZF      - SET IF PHYSICAL ACCESS
;4878
PURGEB:	LD	A,(IX+01)	;FETCH ACCESS FLAGS TO A
	AND	10010000B	;MASK LOGICAL AND WRITE
	CP	10010000B	;TEST FOR LOGICAL ACCESS
	JR	Z,PURGEL	;GO IF LOGICAL
	XOR	A		;GOOD STATUS IF PHYSICAL
	RET
;
;
; GET ADDRESS OF NEXT RECORD IN SECTOR BUFFER, COMPUTE ADDRESS
; FOR NEXT BYTE TO BE FETCHED/STORED IN CURRENT LOGICAL RECORD
; EXIT:   DE      - NEXT RECORD ADDRESS
;4883
NEXTAD:	LD	A,(IX+05)	;GET CURRENT BYTE OFFSET
	LD	C,A		;SAVE THE BYTE IN C
	ADD	A,(IX+03)	;ADD IN BUFFER ADDRESS LSB
	LD	E,A		;COPY ADDRESS LSB TO E
	LD	A,(IX+04)	;GET BUFFER ADDRESS MSB
	ADC	A,0		;ADD ANY CARRY TO ADDRESS
	LD	D,A		;COPY ADDRESS MSB TO D
	RET
;
;
; SAVE CALLER'S REGISTERS AND SET UP EXIT PARAMETERS
; TEST IF THE CURRENT DEVICE IS OPEN AND ABORT IF IT IS CLOSED
; ENTRY:  DE      - POINTER TO DEVICE CONTROL BLOCK
;         (SP+00) - BUFFER ADDRESS
; EXIT:   IX      - POINTER TO DEVICE CONTROL BLOCK
;4892
SAVREG:	LD	A,(DE)		;GET DEVICE OPEN FLAG
	RLCA			;COPY OPEN BIT TO CARRY
	JR	NC,NOTOPN	;ABORT IF DEVICE NOT OPEN
;
;
; SAVE CALLER'S REGISTERS AND SET UP RESTORE ADDRESS
;4896
REGSAV:	POP	AF		;GET RETURN ADDRESS TO AF
	EX	(SP),HL		;SWAP BUFFER ADDRESS TO HL
	LD	(BUFADR),HL	;SAVE THE BUFFER ADDRESS
	LD	(DCBADR),DE	;SAVE THE DCB ADDRESS
	EX	(SP),HL		;SWAP BUFFER ADDRESS TO STACK
	PUSH	DE		;SAVE POINTER TO DCB
	EX	(SP),IX		;SWAP DCB POINTER AND IX
	PUSH	HL		;CALLER'S HL TO STACK
	PUSH	DE		;CALLER'S DE TO STACK
	PUSH	BC		;CALLER'S BC TO STACK
	PUSH	HL		;CREATE A HOLE ON THE STACK
	LD	HL,RSTREG	;POINT AT RESTORE SEQUENCE
	EX	(SP),HL		;SWAP ADDRESS AND HL REGISTER
	PUSH	AF		;PUT RETURN ADDRESS ON STACK
	XOR	A		;ZERO ACCUMULATOR AND FLAGS
	RET
;
;
; THE CURRENT DEVICE IS CLOSED, SO WE ABORT REGISTER SAVE
; EXIT:   A       - FILE NOT OPEN ERROR CODE
;         ZF      - CLEAR
;         CF      - CLEAR
;48AE
NOTOPN:	POP	AF		;REMOVE RETURN ADDRESS
	LD	A,26H		;LOAD ERROR CODE
	OR	A		;RESET ZERO AND CARRY FLAGS
	RET
;
;
; EXIT SEQUENCE TO RESTORE SAVED REGISTERS
; ENTRY:  (SP+00) - SAVED BC REGISTER
;         (SP+02) - SAVED DE REGISTER
;         (SP+04) - SAVED HL REGISTER
;         (SP+06) - SAVED IX REGISTER
;         (SP+08) - RETURN ADDRESS
; EXIT:   BC      - ORIGINAL BC REGISTER
;         DE      - ORIGINAL DE REGISTER
;         HL      - ORIGINAL HL REGISTER
;         IX      - ORIGINAL IX REGISTER
;48B3
RSTREG:	POP	BC		;RECOVER BC REGISTER
	POP	DE		;RECOVER DCB POINTER
	POP	HL		;RECOVER BUFFER POINTER
	POP	IX		;RECOVER IX REGISTER
	RET
;
;
; TEST FOR END-OF-FILE
; ENTRY:  IX      - POINTER TO DEVICE CONTROL BLOCK
; EXIT:   A       - 00H IF NOT AT THE END
;                 - 1CH IF AT THE END
;                 - 1DH IF BEYOND THE END
;48B9
TSTEOF:	LD	L,(IX+10)	;GET NEXT RECORD LSB
	LD	H,(IX+11)	;GET NEXT RECORD MSB
	LD	C,(IX+05)	;GET CURRENT RECORD OFFSET
	LD	A,H		;GET MSB OF NEXT RECORD
	CP	(IX+13)		;COMPARE TO END RECORD MSB
	JR	NZ,EOFLAG	;SKIP IF NOT THERE YET
	LD	A,L		;GET LSB OF NEXT RECORD
	CP	(IX+12)		;COMPARE TO END RECORD LSB
	JR	NZ,EOFLAG	;SKIP IF NOT THERE YET
	DEC	C		;ADJUST TO CURRENT RECORD
	CALL	TSTEOP		;TEST FOR SECTOR BUFFER EOF
	JR	NZ,EOFLAG	;SKIP IF NOT FILE END
	OR	00011100B	;SET END-OF-FILE FLAG
	RET
;
;
; BEYOND END-OF-FILE - RETURN THE STATUS
; ENTRY:  CF      - SET IF NOT EOF
;48D7
EOFLAG:	LD	A,1DH		;ASSUME BEYOND THE END
	RET	NC		;RETURN IF WE ARE
	XOR	A		;ELSE NOT THERE YET
	RET
;
;
; LOCATE 'GAP' FOR CURRENT RECORD NUMBER
;48DC
LCTGAP:	LD	L,(IX+10)	;GET NEXT RECORD NUMBER LSB
	LD	H,(IX+11)	;GET NEXT RECORD NUMBER MSB
	LD	A,5		;LOAD MODULO NUMBER
	CALL	DIVMOD		;COMPUTE RELATIVE GRANULE
	LD	(RELGRA),A	;SAVE THE GRANULE NUMBER
	PUSH	IX		;SAVE THE DCB POINTER
	EX	(SP),HL		;SWAP GRANULE AND DCB POINTER
	LD	BC,15		;OFFSET TO NEXT 'GAP' IN DCB
	ADD	HL,BC		;COMPUTE START OF 'GAP'S'
	POP	BC		;GET RELATIVE GRANULE NUMBER
	LD	A,5		;COUNT OF 'GAP' PAIRS TO SEARCH
	LD	DE,0		;STARTING GRANULE NUMBER
;
;
; TOP OF LOOP FOR TESTING "GAP'S"
;48F7
LCTGAL:	PUSH	AF		;SAVE COUNT OF "GAP'S" TESTED
	DEC	HL		;BACKSPACE FOR FIRST 'GAP' BYTE
	LD	A,(HL)		;LOAD FIRST BYTE OF EXTENT
	INC	HL		;BUMP TO SECOND EXTENT BYTE
	INC	A		;BUMP TRACK TO TEST FOR END
	JR	Z,ENDEXT	;GO IF END OF EXTENT
	PUSH	HL		;SAVE CURRENT 'GAP' ADDRESS
	LD	H,D		;GET CUMULATIVE GRANULES MSB
	LD	L,E		;GET CUMULATIVE GRANULES LSB
	XOR	A		;CLEAR THE CARRY FLAG
	SBC	HL,BC		;COMPARE REQUESTED TO TOTAL
	JR	C,BIGSUM	;SKIP IF OUT OF RANGE
	POP	HL		;RECOVER CURRENT 'GAP' ADDRESS
	JR	Z,COMPTS	;GO COMPUTE TRACK AND SECTOR
ENDEXT:	INC	HL		;BUMP TO THIRD EXTENT BYTE
	POP	AF		;GET COUNT OF "GAP'S" TESTED
	DEC	A		;COUNT ONE SET TESTED
	JR	Z,SEAREN	;SKIP IF ALL SETS TESTED
	LD	E,(HL)		;GET CUMULATIVE GRANULES LSB
	INC	HL		;BUMP TO GRANULE COUNT MSB
	LD	D,(HL)		;GET CUMULATIVE GRANULES MSB
	INC	HL		;BUMP TO NEXT 'GAP' FIRST BYTE
	INC	HL		;BUMP TO NEXT 'GAP' SECOND BYTE
	JR	LCTGAL		;THEN CONTINUE SCANNING "GAP'S"
;
;
; COME HERE IF THE RELATIVE GRANULE NUMBER IS
; GREATER THAN THE SUM OF ACCUMULATED GRANULES
;4915
BIGSUM:	INC	H		;IS DIFFERENC GREATER THAN 256
	LD	A,L		;NEGATIVE OF REQUESTED GRANULE
	POP	HL		;RECOVER POINTER TO GRANULE
	JR	NZ,ENDEXT	;GRANULE CAN'T BE IN THIS 'GAP'
;
;
; IF THE DIFFERENCE IS LESS THAN 256, COMPARE IT TO THE
; NUMBER OF GRANULES ASSIGNED TO THE CURRENT 'GAP' BECAUSE
; THE RELATIVE GRANULE MAY FALL WITHIN THE NEXT 'GAP'
;
	PUSH	DE		;SAVE GRANULE TOTAL TO FREE
	LD	E,A		;NEGATIVE OF REQUESTED GRANULE
	LD	A,(HL)		;GET TOTAL GRANULES - 1
	AND	00011111B	;ISOLATE GRANULE COUNT
	ADD	A,E		;COMPARE TO GRANULE COUNT
	LD	A,E		;RESTORE PREVIOUS COUNT
	POP	DE		;RECOVER TOTAL GRANULE COUNT
	JR	NC,ENDEXT	;IF GRANULE NOT IN THIS 'GAP'
	NEG			;CONVERT COUNT TO POSITIVE
	JR	COMPTS		;GO GOMPUTE TRACK AND SECTOR
;
;
; RELATIVE GRANULE NUMBER IS NOT IN CURRENT "GAP'S"
; SEARCH DIRECTORY ENTRIES BELONGING TO FILE FOR 'GAP'
; CONTAINING THE RELATIVE GRANULE NUMBER BEING SOUGHT
;4928
SEAREN:	CALL	FINGAP		;SEARCH FOR 'GAP' OWNING GRANULE
	RET	NZ		;ABORT IF DISK ERROR
	PUSH	HL		;SAVE GRANULE TRACK NUMBER
	LD	H,B		;REQUESTED RELATIVE GRANULE MSB
	LD	L,C		;REQUESTED RELATIVE GRANULE LSB
	XOR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;GRANULE SOUGHT MINUS TOTAL
	LD	A,L		;NUMBER OF GRANULES IN 'GAP'
	LD	(GRACNT),A	;TRACK ADDRESS UPDATE VALUE
	POP	HL		;RECOVER GRANULE TRACK NUMBER
	PUSH	DE		;SAVE CUMULATIVE GRANULE COUNT
	PUSH	IX		;SAVE DCB ADDRESS
	EX	(SP),HL		;SWAP DCB ADDRESS TO HL
	LD	DE,14		;START OF INDEX FOR "GAP'S"
	ADD	HL,DE		;INDEX INTO THE "GAP'S"
	POP	DE		;GET COUNT AND TRACK NUMBER
;
;
; SEARCH DCB FOR 'GAP' MATCHING NUMBER FROM 'FINGAP'
; WHEN CONTROL RETURNS, THE DCB IS SEARCHED FOR A MATCHING
; TRACK NUMBER AND GRANULE COUNT. IF ONE IS FOUND, CONTROL
; GOES TO 'ABSDAD' WHERE THE ABSOLUTE TRACK AND SECTOR NUMBER
; ARE COMPUTED. IF THE DCB DOES NOT CONTAIN THE TRACK NUMBER,
; THE "GAP'S" IN THE DCB ARE MOVED DOWN ONE ENTRY AND THE TRACK,
; COUNT AND CUMULATIVE TOTAL RETURNED FROM 'FINGAP' ARE COPIED
; TO THE FIRST 'GAP' ENTRY IN THE DCB
; EXIT:   HL      - TRACK AND GRANULE COUNT OWNING THE GRANULE
;         DE      - CUMULATIVE TRACK ADDRESSABLE GRANULE COUNT
;
	LD	B,5		;NUMBER OF "GAP'S" TO EXAMINE
DCBGAP:	LD	A,(HL)		;LOAD FIRST BYTE OF 'GAP'
	INC	HL		;BUMP THE FETCH ADDRESS
	CP	E		;DO TRACK NUMBERS MATCH?
	JR	NZ,DCBGAM	;JUMP IF THEY DON'T
	LD	A,(HL)		;ELSE FETCH THE COUNT
	XOR	D		;COMPARE WITH COUNT IN D
	AND	11100000B	;TEST IF COUNTS MATCH
	JR	Z,DCBGMA	;CONTINUE IF A MATCH
DCBGAM:	DEC	B		;DECREMENT THE 'GAP' COUNT
	JR	Z,DCBGMV	;MOVE "GAP'S" DOWN IF MISMATCH
	INC	HL		;BUMP ADDRESS TO NEXT 'GAP'
	INC	HL		;SKIP OVER THE TWO BYTE
	INC	HL		; TOTALS FOLLOWING EACH 'GAP'
	JR	DCBGAP		;THEN GO TEST NEXT 'GAP'
;
;
; MOVE "GAP'S" IN DCB DOWN ONE ENTRY
;4955
DCBGMV:	PUSH	DE		;SAVE CUMULATIVE GRANULE COUNT
	EX	DE,HL		;SWAP END OF "GAP'S" TO DE
	LD	HL,-4		;LOAD A MINUS FOUR
	ADD	HL,DE		;END ADDRESS OF "GAP'S" IN DCB
	LD	BC,12		;MOVE THREE SETS OF FOUR BYTES
	LDDR			;MOVE THE THREE SETS DOWN
	EX	DE,HL		;SWAP END OF "GAP'S" TO HL
	POP	BC		;GET CUMULATIVE GRANULE COUNT
	POP	DE		;GET REQUESTED GRANULE NUMBER
	JR	GETTRS		;UPDATE DCB GET TRACK/SECTOR
;
;
; GRANULE COUNTS MATCH
;4965
DCBGMA:	LD	(HL),D		;SAVE GRANULE COUNT IN DCB
	EX	DE,HL		;SWAP 'GAP' ENTRY AND DCB ADDR
	POP	AF		;CLEAN UP THE STACK
	JR	ABSDAD		;COMPUTE ABSOLUTE DISK ADDRESS
;
;
; CONVERT GRANULE NUMBER AND 'GAP' INTO ABSOLUTE TRACK AND SECTOR
;496A
COMPTS:	LD	(GRACNT),A	;SAVE GRANULE 'GAP' COUNT
	LD	B,(HL)		;NUMBER OF CONSECUTIVE SECTORS
	DEC	HL		;BACKSPACE TO TRACK NUMBER
	LD	C,(HL)		;GET TRACK NUMBER TO C
	INC	HL		;BACKUP TO SECTOR COUNT
	POP	AF		;GET EXTENT PAIRS COUNTED
	CPL			;MAKE COUNT NEGATIVE
	ADD	A,4		;SUBTRACT FOUR FROM IT
	JR	NC,FISEXT	;GO IF FIRST OR SECOND EXTENT
	INC	A		;GIVES FOUR, THREE, TWO, ONE
	RLCA			;MULTIPLY BY TWO
	RLCA			;MULTIPLY BY FOUR
	PUSH	BC		;SAVE TARGET 'GAP' (TRK, CNT)
	PUSH	DE		;SAVE CUMULATIVE GRANULE TOTAL
	EX	DE,HL		;SWAP 'GAP' ADDRESS TO DE
	LD	HL,-4		;LOAD A MINUS FOUR
	ADD	HL,DE		;BACKUP TO PREVIOUS EXTENT
	LD	B,0		;ZERO MSB OF BYTE COUNT
	LD	C,A		;BC HAS THE BYTE COUNT
	LDDR			;MOVE "GAP'S" AFTER TARGET DOWN
	EX	DE,HL		;TARGET 'GAP' END ADDRESS TO HL
	POP	DE		;CUMULATIVE GRANULE COUNT TO DE
	POP	BC		;TARGET 'GAP' (TRACK, COUNT)
	NOP			;DO NOTHING WHATSOEVER
GETTRS:	LD	(HL),B		;TARGET 'GAP' GRANULE COUNT
	DEC	HL		;BACKUP TO PREVIOUS ENTRY
	LD	(HL),C		;TARGET 'GAP' TRACK NUMBER
	DEC	HL		;BACKUP TO PREVIOUS ENTRY
	LD	(HL),D		;CUMULATIVE GRANULE COUNT MSB
	DEC	HL		;BACKUP TO PREVIOUS ENTRY
	LD	(HL),E		;CUMULATIVE GRANULE COUNT LSB
FISEXT:	LD	H,B		;GRANULE COUNT FOR THIS 'GAP'
	LD	L,C		;TRACK NUMBER FOR CURRENT 'GAP'
;
;
; BEGIN DISK ADDRESS TRANSLATION
; ENTRY:  H       - GRANULE COUNT FOR THIS 'GAP'
;         L       - TRACK NUMBER FOR CURRENT 'GAP'
; EXIT:   C       - DRIVE NUMBER FOR FILE
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
;         H       - UNCHANGED
;         L       - UNCHANGED
;4993
ABSDAD:	LD	A,H		;GET GRANULE COUNT TO A
	RLCA			;SHIFT FIRST
	RLCA			; GRANULE OFFSET
	RLCA			;  INTO THREE LS BITS
	AND	00000111B	;ISOLATE FIRST GRANULE OFFSET
	ADD	A,0		;ADD GRANULE COUNT TO OFFSET
GRACNT	Equ	$-1		;COUNT OF GRANULES IN 'GAP'
	LD	E,A		;SAVE GRANULE WITHIN 'GAP'
	AND	11111110B	;ADD OVERFLOW TO START TRACK
	RRCA			; ISOLATE AND RIGHT JUSTIFY
	LD	(TRKOFS),A	;SAVE FOR ADDING TO START TRACK
	LD	A,E		;REFETCH 'GAP' GRANULE NUMBER
	AND	00000001B	;ISOLATE ODD OR EVEN BIT
	LD	E,A		;COPY THE BIT TO E
	RLCA			;MULTIPLY BY TWO
	RLCA			;MULTIPLY BY FOUR
	ADD	A,E		;MULTIPLY BY FIVE
	ADD	A,0		;GET ABSOLUTE SECTOR ON TRACK
RELGRA	Equ	$-1		;STORAGE FOR RELATIVE GRANULE
	LD	E,A		;SAVE SECTOR NUMBER IN E
	LD	A,L		;GET TRACK NUMBER TO A
	ADD	A,0		;ADD TRACK INCREMENT IN 'GAP'
TRKOFS	Equ	$-1		;OFFSET FOR STARTING TRACK
	LD	D,A		;COPY TRACK NUMBER TO D
	LD	C,(IX+06)	;GET DRIVE NUMBER FOR FILE
	XOR	A		;THEN SIGNAL GOOD STATUS
	RET
;
;
; FIND 'GAP' FOR RELATIVE GRANULE NUMBER BY SEARCHING DIRECTORY
; ENTRIES BELONGING TO FILE. READ OVERFLOW ENTRIES IF NECESSARY
; ENTRY:  BC      - GRANULE NUMBER
; EXIT:   DE      - CUMULATIVE NUMBER OF GRANULES THRU THIS 'GAP'
;         H       - COUNT OF GRANULES ASSIGNED TO TRACK
;         L       - TRACK NUMBER
;49B5
FINGAP:	PUSH	BC		;SAVE REQUESTED GRANULE
	LD	DE,0		;INITIALIZE SKIPPED GRANULES
	LD	B,(IX+07)	;GET DIRECTORY SECTOR TO B
LOCOVE:	LD	A,B		;COPY DIRECTORY SECTOR TO A
	LD	(DIRIDX),A	;SAVE DIRECTORY SECTOR INDEX
	LD	C,(IX+06)	;GET UNIT NUMBER TO C
	CALL	REDDIR		;READ FILE DIRECTORY ENTRY
	LD	BC,22		;OFFSET TO EXTENT PAIRS
	ADD	HL,BC		;ADDRESS OF 'GAP' EXTENTS
	EX	DE,HL		;ADDRESS OF THE PAITS TO DE
	POP	BC		;REQUESTED GRANULE NUMBER
	RET	NZ		;ABORT IT DIRECTORY READ ERROR
FNDEOV:	LD	A,(DE)		;GET FIRST BYTE OF THE 'GAP'
	CP	11111110B	;TEST FOR OVERFLOW EXTENT PAIR
	JR	NC,LOCNEW	;SKIP IF END OR OVERFLOW
	INC	DE		;ELSE BUMP TO NEXT 'GAP' BYTE
	LD	A,(DE)		;THEN FETCH GRANULE COUNT
	PUSH	HL		;SAVE SKIPPED GRANULE COUNT
	AND	00011111B	;ISOLATE GRANULE COUNT - 1
	INC	A		;BUMP TO GET TRUE COUNT
	ADD	A,L		;ADD TO PASSED GRANULE COUNT
	LD	L,A		;UPDATE GRANULES SKIPPED LSB
	JR	NC,NOTOFL	;SKIP IF NOT OVERFLOW
	INC	H		;ELSE BUMP SKIPPED GRANULES MSB
NOTOFL:	PUSH	HL		;SAVE SKIPPED GRANULE COUNT
	DEC	HL		;ZERO BASE SKIPPED GRANULES
	XOR	A		;CLEAR CARRY FLAG
	SBC	HL,BC		;COMPARE THE GRANULE COUNTS
	POP	HL		;GET SKIPPED GRANULE COUNT
	JR	NC,GINGAP	;SKIP IF GRANULE IN THIS 'GAP'
	INC	DE		;BUMP TO NEXT 'GAP' SECOND BYTE
	POP	AF		;CLEAN UP THE STACK
	JR	FNDEOV		;UNTIL FOUND, END OR OVERFLOW
;
;
; GRANULE IS IN THIS 'GAP'
;
GINGAP:	POP	HL		;REQUESTED GRANULE NUMBER TO HL
	EX	DE,HL		;GAP ADDRESS TO HL, COUNT TO DE
	LD	A,(HL)		;COUNT OF ASSIGNED GRANULES
	DEC	HL		;BACKSPACE TO 'GAP' FIRST BYTE
	LD	L,(HL)		;GET TRACK NUMBER TO L
	LD	H,A		;ASSIGNED GRANULES COUNT
	XOR	A		;SIGNAL NO ERROR
	RET
;
;
; LOCATE OVERFLOW ENTRY OR ASSIGN A NEW 'GAP'
;49F1
LOCNEW:	PUSH	BC		;SAVE REQUESTED GRANULE NUMBER
	EX	DE,HL		;SWAP SECTOR ADDRESS, SKIPPED
	JR	NZ,ASSGAP	;SKIP IF 'GAP' ASSIGNED, WRITE
	INC	HL		;OVERFLOW ENTRY FOUND
	LD	B,(HL)		;OFFSET TO OVERFLOW ENTRY
	JR	LOCOVE		;GO LOCATE OVERFLOW "GAP'S"
;
;
; ASSIGN A 'GAP'
;49F9
ASSGAP:	CALL	ASSGRA		;ASSIGN NEXT 'GAP'
	POP	BC		;GET REQUESTED GRANULE
	RET	NZ		;ABORT IF ANY ERRORS
	JR	FINGAP		;ELSE RESTART THE SCAN
;
;
; GRANULE ASSIGNMENT
;
; THIS POINT IS REACHED WHEN A GRANULE NUMBER REQUIRED FOR A
; WRITE DOES NOT EXIST IN THE 'GAP' CHAIN FOR THE FILE. THIS
; SITUATION WILL OCCUR WHEN A FILE IS BEING CREATED, OR IF A
; FILE HAS FIFTY SECTORS ASSIGNED TO IT, AND A REQUEST TO WRITE
; SECTOR SIXTY WAS RECEIVED, FOR EXAMPLE, GRANULES FOR THE
; SPACE BETWEEN SECTORS FIFTY AND SIXTY WOULD BE ASSIGNED
;
; ASSIGNMENT CAN TAKE TWO FORMS. FIRST IS WHEN A GRANULE IS
; ASSIGNED TO AN EXISTING 'GAP'. THE SECOND OCCURS IF IT IS NOT
; POSSIBLE TO ADD GRANULES TO A 'GAP'. THIS CASE OCCURS WHEN A
; 'GAP' IS FULL, THIRTY-TWO GRANULES HAVE BEEN ASSIGNED, OR WHEN
; IT IS IMPOSSIBLE TO ASSIGN THE NEXT CONSECUTIVE GRANULE TO AN
; EXISTING 'GAP'. IN BOTH CASES, A NEW 'GAP' MUST BE CREATED AND
; ADDED TO THE DEVICE CONTROL BLOCK. IF THE 'GAP' AREA IN THE
; DCB IS FULL, AN OVERFLOW DIRECTORY ENTRY IS CREATED
; ENTRY:  BC      - REQUESTED GRANULE NUMBER (TARGET GRANULE)
;         DE      - NUMBER OF GRANULES PRESENTLY ASSIGNED
;         HL      - ADDRESS OF FILE ENTRY IN DIRECTORY SECTOR
;4A00
ASSGRA:	PUSH	BC		;SAVE TARGET GRANULE NUMBER
	LD	B,(IX+07)	;GET OVERFLOW ENTRY TO B
	LD	C,(IX+06)	;GET DRIVE NUMBER TO C
	CALL	REDGAT		;READ THE 'GAT' SECTOR
	POP	BC		;RECOVER TARGET GRANULE
	RET	NZ		;ABORT IF ERROR READING 'GAT'
	PUSH	HL		;SAVE DIRECTORY SECTOR ADDRESS
	LD	H,B		;GET TARGET GRANULE MSB TO H
	LD	L,C		;GET TARGET GRANULE LSB TO L
	XOR	A		;CLEAR THE CARRY FLAG
	SBC	HL,DE		;TARGET LESS ASSIGNED GRANULES
	LD	B,H		;DIFFERENCE BETWEEN REQUESTED
	LD	C,L		; AND CURRENT GRANULE NUMBER
	INC	BC		;GET TRUE COUNT TO BC
	POP	DE		;LOAD DIRECTORY SECTOR ENTRY
	INC	DE		;BUMP TO LAST 'GAP' SECOND BYTE
	INC	BC		;BUMP GRANULE COUNT TO ALLOCATE
	LD	A,(IX+07)	;DIRECTORY ENTRY SECTOR NUMBER
	AND	00000111B	;ISOLATE 'GAT' START POSITION
	RLCA			;MULTIPLY POSITION BY TWO
	RLCA			;MULTIPLY POSITION BY FOUR
	LD	L,A		;FORM 'GAT' SEARCH ADDRESS
	LD	H,High GATBUF	;POINTER INTO SECTOR BUFFER
	PUSH	BC		;GRANULES AND RELATIVE GRANULE
;
;
; TEST FOR INITIAL 'GAP' ASSIGNMENT, OR 'GAP' FULL
;
	LD	A,E		;CURRENT 'GAP' ADDRESS LSB
	AND	00011110B	;ISOLATE THE LOW BYTE
	CP	16H		;TEST FOR FIRST 'GAP' ADDRESS
	JR	Z,GRANAS	;SKIP IF FIRST 'GAP' ASSIGNMENT
	DEC	E		;BACKSPACE TO
	DEC	E		; TO PREVIOUS 'GAP'
ASSANO:	LD	A,(DE)		;CONSECUTIVE GRANULES - 1
	AND	00011111B	;ISOLATE GRANULE COUNT
	INC	A		;MAKE IT A TRUE COUNT
	LD	C,A		;COPY THE COUNT TO C REGISTER
	CP	32		;TEST GRANULE COUNT FIELD FULL
	JR	Z,GAPASG	;ASSIGN NEW 'GAP' IF FULL
;
;
; 'GAP' NOT FULL, TRY TO ASSIGN A GRANULE
;
	LD	A,(DE)		;CONSECUTIVE GRANS ASSIGNED
	AND	11100000B	;ISOLATE FIRST GRAN OFFSET
	RLCA			;ISOLATE STARTING
	RLCA			; SECTOR OFFSET AND
	RLCA			;  MOVE TO BIT ZERO
	ADD	A,C		;TOTAL GRANS ASSIGNED TO 'GAP'
	LD	B,A		;COPY THE GRANULE COUNT TO B
	SRL	B		;DIVIDE GRANULE COUNT BY TWO
	AND	00000001B	;ISOLATE GRANULE BIT
	LD	C,A		;SAVE BIT MASK FOR GRANULE
	DEC	DE		;BACKSPACE TO FIRST 'GAP' BYTE
	LD	A,(DE)		;LOAD STARTING TRACK NUMBER
	INC	DE		;BUMP TO SECOND 'GAP' BYTE
	ADD	A,B		;NUMBER OF CONSECUTIVE TRACKS
	LD	L,A		;FORM 'GAT' ADDRESS LSB
	LD	H,High GATBUF	;LOAD 'GAT' ADDRESS MSB
	CP	NUMTRK		;TEST IF END OF 'GAT' REACHED
	JR	NC,GAPASG	;THEN MUST START ANOTHER 'GAP'
;
;
; TEST IF REQUIRED GRANULE IS AVAILABLE
;
	LD	A,C		;BIT NEEDED IN 'GAT' ENTRY
	LD	B,(HL)		;GET TRACK AVAILABLE
	CALL	BITESB		;TEST NEEDED GRANULE AVAILABLE
	JR	Z,FIRASS	;SKIP IF IT IS
;
;
; ASSIGN A NEW 'GAP'
;4A54
GAPASG:	INC	E		;POINT AT SECOND BYTE
	INC	E		; OF NEXT 'GAP'
	LD	A,E		;COPY THE POINTER TO A
	AND	00011110B	;ISOLATE LSB OF ADDRESS
	CP	00011110B	;TEST FOR LAST PAIR IN ENTRY
	JR	NZ,GRANAS	;SKIP IF NOT LAST PAIR
;
;
; 'GAP' AREA IS FULL - CREATE AN OVERFLOW ENTRY
;
	CALL	GATWRT		;REWRITE 'GAT' AND DIR ENTRY
	POP	BC		;CLEAR STACK IN CASE OF ERROR
	RET	NZ		;ABORT IF WRITE ERROR
	PUSH	BC		;SAVE TRAGET GRANULE NUMBER
	CALL	BLDOVF		;BUILD OVERFLOW DIR ENTRY
	POP	BC		;GET TARGET GRANULE NUMBER
	RET	NZ		;ABORT IF ENTRY CREATE ERROR
	JP	FINGAP		;RESTART 'GAP' ASSIGNMENT
;
;
; CALL SYS2 TO BUILD OVERFLOW ENTRY
;4A6B
BLDOVF:	LD	A,0B4H		;LOAD REQUEST CODE 30
	RST	28H		;BUILD THE OVERFLOW ENTRY
;
;
; GRANULE ASSIGNMENT FOR NEW 'GAP'
;4A6E
GRANAS:	LD	B,2		;LOAD LOOP COUNT
GRANAL:	LD	A,L		;GET CURRENT TRACK TO A
	CP	NUMTRK		;TEST IF END OF 'GAT'
	JR	NC,GRANAR	;GO IF ALL TRACKS TESTED
	LD	A,(HL)		;ELSE FETCH A 'GAT' ENTRY
	INC	A		;TEST IF ANY GRANS AVAILABLE
	JR	NZ,SOMEAV	;SKIP IF SOME AVAILEBLE
	INC	L		;ELSE BUMP TO NEXT ENTRY
	JR	GRANAL		;LOOP UNTIL TABLE EXHAUSTED
GRANAR:	LD	L,Low GATBUF	;RESTART SCAN FROM BEGINNING
	DJNZ	GRANAL		;LOOP UNTIL DONE TWICE
	POP	BC		;GRANULES AND RELATIVE GRANULE
	CALL	GATWRT		;UPDATE 'GAT' AND DIRECTORY
	RET	NZ		;ABORT IF ERROR WRITING 'GAT'
	LD	A,1BH		;DISK SPACE FULL ERROR
	OR	A		;SET ERROR STATUS
	RET
;
;
; MAKE INITIAL 'GAP' BYTE TWO ASSIGNMENT
;4A89
SOMEAV:	LD	A,-1		;LOAD ALL BITS SET VALUE
	LD	(DE),A		;STORE IN SECOND BYTE OF 'GAP'
	LD	C,0		;LOAD BIT NUMBER TO C
	LD	B,(HL)		;LOAD 'GAT' ENTRY TO BIT TEST
RETEST:	LD	A,C		;LOAD BIT NUMBER TO A
	CALL	BITESB		;TEST BIT IN THE BYTE
	JR	Z,FIRASS	;GO IF FIRST GRANULE ASSIGNED
	LD	A,(DE)		;TRACK ASSIGNMENT SECOND GRAN
	ADD	A,00100000B	;SET BIT FIVE OF 'GAP' ENTRY
	LD	(DE),A		;SAVE SECOND BYTE OF 'GAP'
	INC	C		;BUMP TO NEXT BIT IN 'GAT'
	JR	RETEST		;LOOP BACK TO RETEST
FIRASS:	LD	A,C		;LOAD BIT NUMBER TO A
	CALL	SELMSK		;TURN ON BIT IN ACCUMULATOR
	OR	(HL)		;COMBINE WITH 'GAT' ENTRY
	LD	(HL),A		;SAVE UPDATED 'GAT' ENTRY
	DEC	E		;SKIP TO 'GAP' FIRST ENTRY
	LD	A,(DE)		;GET TRACK NUMBER FROM 'GAP'
	INC	A		;TEST NEW TRACK ASSIGNMENT
	JR	NZ,NEWTAS	;SKIP IF NEW TRACK ASSIGNMENT
	LD	A,L		;GET TRACK NUMBER TO A
	LD	(DE),A		;SAVE THE TRACK NUMBER
NEWTAS:	INC	E		;BUMP TO 'GAP' SECOND BYTE
	LD	A,(DE)		;GET SECOND BYTE OF 'GAP'
	INC	A		;BUMP ASSIGNED GRANULE COUNT
	LD	(DE),A		;RESTORE THE COUNT
	POP	BC		;COUNT OF GRANS TO ALLOCATE
	DEC	BC		;DECREMENT GRANULE COUNT
	PUSH	BC		;SAVE UPDATED COUNT
	LD	A,B		;GET MSB TO A FOR TEST
	OR	C		;TEST IF WE WE ARE DONE
	JP	NZ,ASSANO	;ALLOCATE ANOTHER IF MORE
	POP	BC		;CLEAR OUT THE STACK
;
;
; UPDATE 'GAT' AND DIRECTORY
;4AB6
GATWRT:	LD	C,(IX+06)	;GET DRIVE NUMBER TO C
	CALL	WRTGAT		;WRITE UPDATED 'GAT' SECTOR
	RET	NZ		;ABORT IF WRITE ERROR
	LD	B,0		;LOAD SECTOR AND OFFSET
DIRIDX	Equ	$-1		;DIRECTORY SECTOR INDEX
	JR	WRTDIR		;WRITE THE DIRECTORY
;
;
; READ DIRECTORY SECTOR ENTRY
; ENTRY:  B       - HASH INDEX TABLE INDEX
;         C       - UNIT NUMBER
; EXIT:   HL      - INDEX TO THE ENTRY
;4AC1
REDDIR:	PUSH	BC		;SAVE SECTOR AND UNIT
	PUSH	DE		;SAVE CALLER'S DE
	CALL	DIRIOR		;GET DIRECTORY I/O REGISTERSL
	JR	NZ,REDDIE	;ABORT IF SECTOR OUT OF RANGE
	PUSH	HL		;SAVE FILE ENTRY ADDRESS
	LD	L,0		;FORCE BUFFER ON PAGE BOUNDARY
	CALL	DDREAD		;READ DIRECTORY SECTOR
	POP	HL		;RECOVER ENTRY ADDRESS
	JR	Z,REDDIX	;EXIT IF NO ERRORS
REDDIE:	LD	A,11H		;SIGNAL DIRECTORY READ ERROR
REDDIX:	POP	DE		;RECOVER CALLER'S DE
	POP	BC		;RECOVER SECTOR AND UNIT
	RET
;
;
; WRITE DIRECTORY SECTOR ENTRY
; ENTRY:  B       - HASH INDEX TABLE INDEX
;         C       - UNIT NUMBER
;         HL      - INDEX TO THE ENTRY
;4AD6
WRTDIR:	PUSH	BC		;SAVE SECTOR AND UNIT
	PUSH	DE		;SAVE CALLER'S DE
	CALL	DIRIOR		;GET DIRECTORY I/O REGISTERS
	JR	NZ,WRTDIX	;ABORT IF SECTOR OUT OF RANGE
	LD	L,0		;FORCE BUFFER ON PAGE BOUNDARY
	CALL	WRDSEC		;WRITE DIRECTORY SECTOR
	JR	NZ,WRTDIE	;ABORT IF WRITE ERROR
	CALL	RDSECV		;READ AND VERIFY SECTOR
	CP	6		;TEST FOR GOOD READ
	JR	Z,WRTDIX	;ALL DONE IF IT IS
WRTDIE:	LD	A,12H		;SIGNAL DIRECTORY WRITE ERROR
WRTDIX:	POP	DE		;RECOVER CALLER'S DE
	POP	BC		;RECOVER SECTOR AND UNIT
	RET
;
;
; READ GRANULE ALLOCATION MAP SECTOR
;4AF0
REDGAT:	PUSH	DE		;SAVE CALLER'S DE
	PUSH	HL		;SAVE CALLER'S HL
	CALL	TRKDIR		;GET DIRECTORY TRACK NUMBER
	LD	E,0		;LOAD SECTOR NUMBER
	LD	HL,GATBUF	;POINT AT SECTOR BUFFER
	CALL	DDREAD		;READ THE 'GAT' SECTOR
	POP	HL		;RECOVER CALLER'S HL
	POP	DE		;RECOVER CALLER'S DE
	RET	Z		;ALL DONE IF SUCCESSFUL READ
	LD	A,14H		;SIGNAL 'GAT' READ ERROR
	RET
;
;
; WRITE GRANULE ALLOCATION MAP SECTOR
;4B03
WRTGAT:	PUSH	DE		;SAVE CALLER'S DE
	PUSH	HL		;SAVE CALLER'S HL
	CALL	TRKDIR		;GET DIRECTORY TRACK NUMBER
	LD	E,0		;LOAD SECTOR NUMBER
	LD	HL,GATBUF	;POINT AT SECTOR BUFFER
	CALL	WRDSEC		;WRITE A DIRECTORY SECTOR
	JR	NZ,WRTGAE	;ABORT IF WRITE ERROR
	CALL	RDSECV		;READ AND VERIFY SECTOR
	CP	6		;TEST FOR SUCCESSFUL READ
	JR	Z,WRTGAX	;ALL DONE IF IT IS
WRTGAE:	LD	A,15H		;SIGNAL 'GAT' WRITE ERROR
WRTGAX:	POP	HL		;RECOVER CALLER'S HL
	POP	DE		;RECOVER CALLER'S DE
	RET
;
;
; PREPARE REGISTER FOR DIRECTORY INPUT AND OUTPUT
; ENTRY:  B       - SYSTEM SECTOR NUMBER
;         C       - UNIT NUMBER
; EXIT:   AF      - NON-ZERO STATUS IF SECTOR OUT OF RANGE
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
;         HL      - SECTOR BUFFER ADDRESS FOR FILE ENTRY
;4B1E
DIRIOR:	CALL	TRKDIR		;GET DIRECTORY TRACK NUMBER
	LD	A,B		;GET SYSTEM SECTOR NUMBER TO A
	AND	11100000B	;ISOLATE FILE ENTRY NUMBER
	LD	L,A		;COPY BUFFER ADDRESS LSB TO L
	LD	H,High SYSBUF	;GET BUFFER ADDRESS MSB TO H
	XOR	B		;ISOLATE SECTOR NUMBER
	CP	NUMSEC-2	;TEST IF SECTOR OUT OF RANGE
	JR	NC,DIRIOE	;ABORT IF RANGE ERROR
	ADD	A,2		;FORM TRUE SECTOR NUMBER
	LD	E,A		;COPY THE NUMBER TO E
	XOR	A		;FLAG SUCCESSFUL STATUS
	RET
;
;
; WE HAVE A SECTOR OUT OF RANGE ERROR WHEN ACCESSING DISECTORY
;4B31
DIRIOE:	LD	A,10H		;SIGNAL SECTOR OUT OF RANGE
	OR	A		;FLAG ERROR STATUS
	RET
;
;
; READ A SECTOR TO BUFFER - DISK DRIVER READ SUBROUTINE
; ENTRY:  C       - UNIT NUMBER
;         D       - TRACK NUMBER
;         E       - SECTOR NUMBER
;         HL      - SECTOR BUFFER ADDRESS
; EXIT:   A       - ZERO IF SUCCESSFUL READ
;         ZF      - SET IF SUCCESSFUL READ
;4B35
DDREAD:	CALL	RDSECT		;READ SECTOR TO BUFFER
	SUB	6		;TEST IF NORMAL TERMINATION
	RET	Z		;ALL DONE IF IT IS
	ADD	A,6		;RESTORE COMPLETION CODE
	RET	NZ		;ALL DONE NORMAL COMPLETION
	PUSH	DE		;SAVE TRACK AND SECTOR
	LD	DE,0		;TRACK ZERO, SECTOR ZERO
	CALL	RDSECT		;READ BOOT SECTOR TO BUFFER
	POP	DE		;RECOVER TRACK AND SECTOR
	RET	NZ		;ABORT IF READ ERROR
	PUSH	HL		;SAVE ORIGINAL BUFFER ADDRESS
	INC	HL		;BUMP TO DIRECTORY
	INC	HL		; TRACK STORAGE LOCATION
	LD	D,(HL)		;GET DIRECTORY TRACK TO D
	LD	A,4		;OFFSET TO DIRECTORY TABLE
	ADD	A,C		;ADD DRIVE NUMBER TO OFFSET
	LD	L,A		;DIRECTORY TABLE ADDRESS LSB
	LD	H,High LASTRK	;DIRECTORY TABLE ADDRESS MSB
	LD	(HL),D		;SAVE DIRECTORY TRACK NUMBER
	POP	HL		;RECOVER OLD BUFFER ADDRESS
	JR	DDREAD		;THEN RETRY THE OPERATION
;
;
; GET DIRECTORY TRACK NUMBER FOR FOR DISK UNIT
; ENTRY:  C       - DISK DRIVE UNIT NUMBER
; EXIT:   D       - DIRECTORY TRACK NUMBER
;         HL      - DIRECTORY TABLE ADDRESS OFFSET
;4B55
TRKDIR:	LD	A,4		;OFFSET TO DIRECTORY TABLE
	ADD	A,C		;ADD DRIVE NUMBER TO OFFSET
	LD	L,A		;DIRECTORY TABLE ADDRESS LSB
	LD	H,High LASTRK	;DIRECTORY TABLE ADDRESS MSB
	LD	D,(HL)		;GET DIRECTORY TRACK NUMBER
	RET
;
;
; BUILD AND EXECUTE AN INSTRUCTION TO TEST A BIT ON A QUANTITY
; ENTRY:  A       - BIT TEST VALUE
;         B       - THE QUANTITY TO BIT TEST
; EXIT:   ZF      - SET IF THE GIVEN BIT IS SET, ELSE RESET
;4B5D
BITESB:	AND	00000111B	;ISOLATE BIT POSITION
	RLCA			;LEFT SHIFT
	RLCA			; THREE BITS
	RLCA			;  TO THE LEFT
	OR	01000000B	;FORM BIT TEST BYTE
	LD	(BITESV),A	;STORE BIT TEST BYTE
	BIT	0,B		;TEST THE BIT IN B REGISTER
BITESV	Equ	$-1		;STORAGE FOR BIT TEST BYTE
	RET
;
;
; COMPUTE A SECTOR NUMBER FOR A GIVEN RECORD
;   SECTOR NUMBER = RECORD SIZE * (RECORD NUMBER / 256)
; ENTRY:  A       - RECORD LENGTH
;         HL      - RECORD NUMBER
; EXIT:   A       - SECTOR OFFSET
;         DE      - RECORD NUMBER
;         HL      - SECTOR NUMBER
;4B6A
RECTOS:	PUSH	BC		;SAVE CALLER'S BC
	EX	DE,HL		;SWAP RECORD NUMBER TO DE
	LD	C,A		;COPY RECORD LENGTH TO C
	LD	HL,0		;CLEAR RESULT REGISTER
	LD	A,L		;INITIALIZE PRODUCT AS ZERO
	LD	B,8		;LOAD MAXIMUM SHIFT COUNT
RECTOL:	ADD	HL,HL		;SHIFT PRODUCT TO THE LEFT
	RLA			;SHIFT MS BIT OF A INTO CARRY
	RLC	C		;SHIFT BIT INTO LS BIT OF C
	JR	NC,RECTOO	;SKIP IF BIT IS OFF
	ADD	HL,DE		;ADD RECORD NUMBER TO PRODUCT
	ADC	A,0		;PICK UP ANY CARRY FROM L
RECTOO:	DJNZ	RECTOL		;UNTIL ALL RECORD BITS TESTED
	LD	C,A		;PRODUCT MSB TO C
	LD	A,L		;SECTOR OFFSET TO A (REMAINDER)
	LD	L,H		;LSB OF PRODUCT TO L
	LD	H,C		;MSB OF PRODUCT TO H
	POP	BC		;RECOVER CALLER'S BC
	RET
;
;
; MODULO DIVISION ROUTINE - SHIFT THE MOST SIGNIFICANT BIT
; OUT OF THE DIVIDEND INTO THE ACCUMULATOR, ONE BIT AT A TIME.
; WHENEVER THE ACCUMULATOR IS MORE THAN OR EQUAL TO THE MODULUS
; OR FULL, DECREMENT IT BY MODULO TIMES VALUE AND BUMP QUOTIENT
; ENTRY:  A       - DIVISOR
;         HL      - DIVIDEND
; EXIT:   A       - REMAINDER
;         HL      - QUOTIENT
;4B84
DIVMOD:	PUSH	DE		;SAVE THE DE REGISTER
	LD	D,A		;GET DIVISOR TO ACCUMULATOR
	LD	E,16		;LOAD MAXIMUM BIT COUNT
	XOR	A		;ZERO REMAINDER, CLEAR CARRY
DIVMOL:	ADD	HL,HL		;LEFT BIT SHIFT DIVIDEND
	RLA			;CARRY TO BIT 0, BIT 7 TO CARRY
	JR	C,DIVMOB	;SKIP IF REMAINDER IS LARGE
	CP	D		;ELSE COMPARE TO MODULUS
	JR	C,DIVMOG	;SKIP IF REMAINDER GREATER
DIVMOB:	SUB	D		;ELSE ADJUST REMAINDER
	INC	L		;THEN INCREMENT QUOTIENT
DIVMOG:	DEC	E		;TEST IF ALL BITS TESTED
	JR	NZ,DIVMOL	;CONTINUE IF MORE BITS
	POP	DE		;RESTORE CALLER'S DE
	RET
;
;
; STORAGE AREA FOR NUCLEUS
;
	Org	0403EH
;
DOSVER	Db	022H		;DOS BCD VERSION NUMBER
	Db	1		;RESERVED BYTE
CLINDX	Db	0		;CLOCK INTERRUPT INDEX
;
;
; TRACK HISTORY TABLE
;
	Org	04300H
;
LASTRK	Db	17		;LAST TRACK ACCESSED DRIVE 0
	Db	17		;LAST TRACK ACCESSED DRIVE 1
	Db	17		;LAST TRACK ACCESSED DRIVE 2
	Db	17		;LAST TRACK ACCESSED DRIVE 3
;
;
; DIRECTORY TRACK LIST
;
DIRTRK	Db	17		;DIRECTORY TRACK DRIVE 0
	Db	17		;DIRECTORY TRACK DRIVE 1
	Db	17		;DIRECTORY TRACK DRIVE 2
	Db	17		;DIRECTORY TRACK DRIVE 3
;
;
; UNIT FLAGS AND ADDRESSES
;
LASDRV	Db	0		;LAST UNIT SELECTED
DRVMSK	Db	00000001B	;SELECT MASK FOR LAST UNIT
DCBADR	Dw	0		;CURRENT OPERATION DCB
BUFADR	Dw	0		;CURRENT OPERATION BUFFER
LASTOR	Db	2		;LAST OVERLAY LOAD REQUEST
SYSCON	Db	0		;SYSTEM CONDITION FLAGS
	Dw	0		;RESERVED
	Ds	3		;BAD OVERLAY ERROR JUMP
DEBUGF	Ds	3		;DEBUG ON/OFF FLAG AND JUMP
CMLBUF	Ds	64		;DOS COMMAND LINE BUFFER
;
	If	PATCHG		;PATCHES ACTIVE
KIBDCB	 Ds	16		;ALTERNATE KEYBOARD DCB
DOTDCB	 Ds	16		;ALTERNATE VIDEO DCB
PRTDCB	 Ds	16		;ALTERNATE PRINTER DCB
;
;
; PATCH AREA
;
LOCACO	 Ds	48		;RESERVE THE SPACE
	Else			;ORIGINAL
KIBDCB	 Ds	32		;ALTERNATE KEYBOARD DCB
DOTDCB	 Ds	32		;ALTERNATE VIDEO DCB
PRTDCB	 Ds	32		;ALTERNATE PRINTER DCB
	EndIf			;DONE WITH IT
;
KIDRVA	Ds	2		;KEYBOARD DRIVER ADDRESS
DODRVA	Ds	2		;VIDEO DRIVER ADDRESS
PRDRVA	Ds	2		;PRINTER DRIVER ADDRESS
RSDRVA	Ds	2		;RESERVED
;
;
; DRIVER NAME AND ADDRESS TABLE (16 DRIVERS SUPPORTED)
;
KIDRNA	Ds	2		;KEYBOARD DRIVER NAME
KIDRAD	Ds	2		;KEYBOARD DRIVER ADDRESS
DODRNA	Ds	2		;VIDEO DRIVER NAME
DODRAD	Ds	2		;VIDEO DRIVER ADDRESS
PRDRNA	Ds	2		;PRINTER DRIVER NAME
PRDRAD	Ds	2		;PRINTER DRIVER ADDRESS
AEDRNA	Ds	(16-3)*4	;SPACE FOR ADDITIONAL ENTRIES
;
;
; SYSTEM DEVICE CONTROL BLOCK (32 BYTES)
;
	Org	04480H
;
SYSDCB	Db	'NAMENAME/EXT.PASSWORD:N         '
;
;
; SYSTEM OVERLAY DEVICE CONTROL BLOCK (16 BYTES)
;
OVLDCB	Db	10000000B	;OPEN FLAG
ACCFLG	Db	0		;ACCESS FLAGS
	Db	0		;RESERVED
	Dw	GATBUF		;SECTOR BUFFER ADDRESS
	Db	0		;OFFSET TO NEXT RECORD
	Db	0		;DRIVE NUMBER
OFLPTR	Db	0		;OVERFLOW POINTER
	Db	0		;EOF BYTE ADDRESS
	Db	0		;RECORD SIZE
NXTREC	Dw	0		;NEXT RECORD NUMBER
	Dw	65535		;NUMBER OF RECORDS
TRKNUM	Db	0		;TRACK NUMBER
	Db	0		;NUMBER OF GRANULES
;
;
; MAKE OVERLAY CALL TO LOAD SYS1/SYS REQUEST CODE 10
;
	Org	0402DH
;
DOSENT:	JP	NORENT		;GO LOAD THE OVERLAY
;
;
; MAKE OVERLAY CALL TO LOAD SYS1/SYS REQUEST CODE 20
;4030
ERRENT:	LD	A,0A3H		;CODE FOR SYS1/SYS OPTION 20
	RST	28H		;LOAD AND EXECUTE OVERLAY
;
;
; MAKE OVERLAY CALL TO LOAD SYS1/SYS REQUEST CODE 10
;
	Org	04400H
;
NORENT:	LD	A,093H		;CODE FOR SYS1/SYS OPTION 10
	RST	28H		;LOAD AND EXECUTE OVERLAY
;
;
; MAKE OVERLAY CALL TO LOAD SYS1/SYS REQUEST CODE 30
;
	Org	04405H
;
DOSCMD:	LD	A,0B3H		;CODE FOR SYS1/SYS OPTION 30
	RST	28H		;LOAD AND EXECUTE OVERLAY
;
;
; JUMP TO ROUTINE TO MAKE OVERLAY CALL TO ERROR PROCESSOR
;
	Org	04409H
;
DERROR:	JP	ERRORD		;LOAD AND EXECUTE OVERLAY
;
;
; LOAD ERROR MESSAGE PROCESSOR
;
	Org	044B0H
;
ERRORD:	PUSH	AF		;SAVE ERROR CODE
	LD	A,086H		;SYS4/SYS OVERLAY REQUEST CODE
	RST	28H		;LOAD AND EXECUTE OVERLAY
;
;
; JUMP TO ROUTINE TO MAKE OVERLAY CALL TO LOAD DEBUG
;
	Org	0400FH
;
LDEBUG:	JP	DEBUGR		;LOAD AND EXECUTE OVERLAY
;
;
; JUMP TO ROUTINE TO MAKE OVERLAY CALL TO LOAD DEBUG
;
	Org	0440DH
;
DEBUGL:	JP	DEBUGR		;LOAD AND EXECUTE OVERLAY
;
;
; MAKE OVERLAY CALL TO LOAD DEBUG
;
	Org	044B4H
;
DEBUGR:	PUSH	AF		;SAVE AF REGISTER
	LD	A,087H		;SYS5/SYS OVERLAY REQUEST CODE
	RST	28H		;LOAD AND EXECUTE DEBUG
;
;
; VALIDATE FILE NAME AND COPY TO DEVICE CONTROL BLOCK
;
	Org	0441CH
;
VALNAM:	LD	A,0C3H		;SYS1/SYS REQUEST CODE 40
	RST	28H		;LOAD AND VALIDATE FILENAME
;
;
; CREATE A NEW FILE
;
	Org	04420H
;
CREFIL:	LD	A,0A4H		;SYS2/SYS REQUEST CODE 20
	RST	28H		;LOAD OVERLAY AND CREATE
;
;
; OPEN AN EXISTING FILE
;
	Org	04424H
;
OPNFIL:	LD	A,094H		;SYS2/SYS REQUEST CODE 10
	RST	28H		;LOAD OVERLAY AND OPEN
;
;
; CLOSE A FILE
;
	Org	04428H
;
CLSFIL:	LD	A,095H		;SYS3/SYS REQUEST CODE 10
	RST	28H		;LOAD OVERLAY AND CLOSE
;
;
; KILL A FILE
;
	Org	0442CH
;
KILFIL:	LD	A,0A5H		;SYS3/SYS REQUEST CODE 20
	RST	28H		;LOAD OVERLAY AND KILL
;
;
; ADD FILE EXTENSION TO FILENAME
;
	Org	04473H
;
ADDEXT:	LD	A,0D3H		;SYS1/SYS REQUEST CODE 50
	RST	28H		;LOAD AND ADD EXTENSION
;
;
; PARSE COMMAND LINE PARAMETERS
;4476
PARSEC:	LD	A,0E3H		;SYS1/SYS REQUEST CODE 60
	RST	28H		;LOAD AND PARSE ARGUMENTS
;
;
; ENTER A DEVICE DRIVER
; ENTRY:  B       - DEVICE OP-CODE
;         HL      - DEVICE CONTROL BLOCK ADDRESS
;
	Org	04033H
;
DDRENT:	JP	ENTDDR		;GO AND ENTER THE DRIVER
;
;
; ENTER A DEVICE DRIVER LINK LOOP
; ENTRY:  B       - DEVICE OP-CODE
;         HL      - DEVICE CONTROL BLOCK ADDRESS
;
	Org	044B8H
;
ENTDDL:	PUSH	HL		;COPY DCB ADDRESS THROUGH
	POP	IX		; STACK INTO IX REGISTER
;
;
; ENTER A DEVICE DRIVER
; ENTRY:  B       - DEVICE OP-CODE
;         IX      - DEVICE CONTROL BLOCK ADDRESS
;44BB
ENTDDR:	LD	L,(IX+01)	;LOAD DRIVER ADDRESS LSB
	LD	H,(IX+02)	;LOAD DRIVER ADDRESS MSB
	LD	A,(IX+00)	;GET DEVICE CODE TO A
	CP	00010000B	;IS DCB LINKED TO ANOTHER?
	JR	Z,ENTDDL	;THEN LOOP FOR NEXT DCB
	JP	NC,GENDRV	;JUMP IF DISK DCB
	LD	A,B		;GET OP-CODE TO A
	CP	2		;COMPARE CODE TO WRITE
	JP	(HL)		;THEN ENTER THE DRIVER
;
;
; ENTRY POINT TO OUTPUT MESSAGE TO DISPLAY OUTPUT DEVICE
; MESSAGE TERMINATOR IS 'CC' (NOT OUTPUT) OR 'CR' (OUTPUT)
; ENTRY:  HL      - POINTER TO STRING
; EXIT:   HL      - PRESERVED
;
	Org	04467H
;
DOPMSG:	JP	DOMESS		;OUTPUT THE MESSAGE STRING
;
;
; ROUTINE TO OUTPUT MESSAGE TO DISPLAY OUTPUT DEVICE
; MESSAGE TERMINATOR IS 'CC' (NOT OUTPUT) OR 'CR' (OUTPUT)
; ENTRY:  HL      - POINTER TO STRING
; EXIT:   HL      - PRESERVED
;
	Org	044CFH
;
DOMESS:	PUSH	HL		;SAVE MESSAGE POINTER
DOMESL:	LD	A,(HL)		;GET CHARACTER FROM STRING
	CP	CC		;TEST IF TERMINATOR
	JR	Z,DOMESX	;EXIT IF ALL DONE
	CALL	VDCHAR		;OUTPUT THE CHARACTER
	INC	HL		;BUMP MESSAGE POINTER
	CP	CR		;TEST IF CARRIAGE RETURN
	JR	NZ,DOMESL	;LOOP UNTIL IT IS
DOMESX:	POP	HL		;RECOVER MESSAGE POINTER
	RET
;
;
; ENTRY POINT TO OUTPUT MESSAGE TO PRINTER OUTPUT DEVICE
; MESSAGE TERMINATOR IS 'CC' (NOT OUTPUT) OR 'CR' (OUTPUT)
; ENTRY:  HL      - POINTER TO STRING
; EXIT:   HL      - PRESERVED
;
	Org	0446AH
;
PRPMSG:	JP	PRMESS		;OUTPUT THE MESSAGE STRING
;
;
; ROUTINE TO OUTPUT MESSAGE TO PRINTER OUTPUT DEVICE
; MESSAGE TERMINATOR IS 'CC' (NOT OUTPUT) OR 'CR' (OUTPUT)
; ENTRY:  HL      - POINTER TO STRING
; EXIT:   HL      - PRESERVED
;
	Org	044DFH
;
PRMESS:	PUSH	HL		;SAVE MESSAGE POINTER
PRMESL:	LD	A,(HL)		;GET CHARACTER FROM STRING
	CP	CC		;TEST IF TERMINATOR
	JR	Z,PRMESX	;EXIT IF ALL DONE
	CALL	PRCHAR		;OUTPUT THE CHARACTER
	INC	HL		;BUMP MESSAGE POINTER
	CP	CR		;TEST IF CARRIAGE RETURN
	JR	NZ,PRMESL	;LOOP UNTIL IT IS
PRMESX:	POP	HL		;RECOVER MESSAGE POINTER
	RET
;
;
; BAD OVERLAY ERROR JUMP
;
	Org	04312H
;
BADOVJ:	JP	BADOVL		;JUMP TO ERROR HANDLER
;
;
; BAD OVERLAY ERROR HANDLER
;
	Org	04BA0H
;
BADOVL:	XOR	A		;ZERO A, CLEAR CF AND SET ZF
	RET
;
;
; SET UP JUMP TO SYSTEM OVERLAY LOADER
;
	Org	0400CH
;
LODOVR:	JP	OVRLOD		;LOAD SYSTEM OVERLAY
;
;
; LOAD A SYSTEM OVERLAY (NORMALLY A MAXIMUM OF 14 OVERLAYS)
; ENTRY:  A       - OVERLAY REQUEST BYTE
;
;  BIT 7 : =  MUST BE 1
;  BIT 6 : >
;  BIT 5 ;  > OVERLAY REQUEST OPTION (0 - 7)
;  BIT 4 : >
;  BIT 3 : =  OFFSET INTO DIRECTORY SECTOR FOR FILE ENTRY
;  BIT 2 : >
;  BIT 1 :  > DIRECTORY SECTOR - 2, HAS OVERLAY NAME (0 - 7)
;  BIT 0 : >
;
	Org	04BA2H
;
OVRLOD:	EX	(SP),HL		;SWAP RETURN ADDRESS TO HL
	POP	HL		;RECOVER HL REGISTER
	OR	A		;TEST IF REQUEST IS VALID
	JP	P,BADOVJ	;ABORT IF BAD OVERLAY REQUEST
	PUSH	HL		;SAVE HL REGISTER
	LD	H,A		;SAVE REQUEST BYTE IN H
	LD	A,(LASTOR)	;GET PREVIOUS SELECTION
	XOR	H		;FLIP PREVIOUS SELECTION
	AND	00001111B	;MASK TO DIRECTORY SECTOR BITS
	LD	A,H		;GET RESULT TO A
	LD	(LASTOR),A	;SAVE FOR NEXT TIME AROUND
	JR	Z,OVRLAL	;SKIP IF OVERLAY ALREADY LOADED
	PUSH	DE		;SAVE CALLER'S DE
	PUSH	BC		;SAVE CALLER'S BC
	AND	00001111B	;MASK TO SECTOR AND OFFSET BITS
	CP	00001000B	;TEST IF SECOND DIRECTORY ENTRY
	JR	C,OVRLOF	;CONTINUE IF FIRST ENTRY
	ADD	A,00011000B	;GET NEW FILE OFFSET (SECTOR)
OVRLOF:	LD	B,A		;COPY FILE OFFSET TO B
	LD	(OFLPTR),A	;STORE OFFSET IN DCB
	XOR	A		;CLEAR CARRY, ZERO A
	LD	(ACCFLG),A	;GRANT ALL PERMISSIONS
	SBC	HL,HL		;ZERO HL REGISTER
	LD	(NXTREC),HL	;SET NEXT RECORD NUMBER
	LD	C,A		;SET DRIVE NUMBER TO ZERO
	CALL	REDDIR		;READ THE DIRECTORY SECTOR
	JP	NZ,DERROR	;ABORT IF READ ERROR
	LD	A,L		;FILE ENTRY IN DIRECTORY LSB
	ADD	A,22		;POSITION TO FIRST 'GAP'
	LD	L,A		;FORM 'GAP' ADDRESS IN HL
	LD	A,(HL)		;FETCH OVERLAY TRACK NUMBER
	INC	L		;BUMP TO SECOND 'GAP' BYTE
	LD	H,(HL)		;SECTOR OFFSET AND GRANULES
	LD	L,A		;HL HAS FIRST OVERLAY 'GAP'
	LD	(TRKNUM),HL	;SAVE AS FIRST 'GAP' IN DCB
	LD	DE,OVLDCB	;POINT AT DEVICE CONTROL BLOCK
	CALL	SYSLDR		;LOAD FILE FROM OVERLAY DCB
	JP	NZ,DERROR	;ABORT IF OVERLAY READ ERROR
	LD	(OVRLAD),HL	;STORE EXECUTION ADDRESS
	POP	BC		;RESTORE CALLER'S BC
	POP	DE		;RESTORE CALLER'S DE
OVRLAL:	POP	HL		;RESTORE CALLER'S HL
	LD	A,(DEBUGF)	;GET DEBUG FLAG TO A
	LD	(OVRLDF),A	;SAVE THE FLAG FOR LATER
	XOR	A		;ZERO ACCUMULATOR
	LD	(DEBUGF),A	;DE-ACTIVATE DEBUG
	LD	A,(LASTOR)	;LOAD OVERLAY REQUEST CODE
	CALL	0		;EXECUTE THE OVERLAY
OVRLAD	Equ	$-2		;OVERLAY EXECUTION ADDRESS
	PUSH	AF		;SAVE OVERLAY EXIT STATUS
	LD	A,0		;GET SAVED DEBUG FLAG
OVRLDF	Equ	$-1		;STORAGE FOR DEBUG FLAG
	LD	(DEBUGF),A	;RESTORE THE FLAG
	POP	AF		;RECOVER OVERLAY EXIT STATUS
	RET
;
;
; LOAD AND EXECUTE A 'CMD' TYPE FILE
;
	Org	04433H
;
LODEXE:	JP	EXELOD		;LOAD AND EXECUTE THE FILE
;
;
; LOAD AND EXECUTE A 'CMD' TYPE FILE
;
	Org	04C06H
;
EXELOD:	PUSH	HL		;SAVE CALLER'S HL
	CALL	LODFIL		;LOAD FILE FROM SYSTEM DCB
	JP	NZ,DERROR	;ABORT IF ERROR DURING LOAD
	EX	(SP),HL		;SWAP RUN ADDRESS WITH HL
	LD	A,(SYSCON)	;GET SYSTEM CONDITION FLAGS
	OR	A		;TEST IF DEBUG FLAG SET
	JP	M,LDEBUG	;THEN GO LOAD DEBUG
	RET
;
;
; LOAD A FILE SPECIFIED BY A DEVICE CONTROL BLOCK
; ENTRY:  DE      - POINTER TO DEVICE CONTROL BLOCK
;
	Org	04430H
;
LODFIL:	JP	FILLOD		;LOAD THE SPECIFIED FILE
;
;
; LOAD A FILE SPECIFIED BY A DEVICE CONTROL BLOCK
; ENTRY:  DE      - POINTER TO DEVICE CONTROL BLOCK
;
	Org	04C16H
;
FILLOD:	LD	B,0		;SPECIFY PHYSICAL I/O
	LD	HL,GATBUF	;POINT AT FILE BUFFER
	CALL	OPNFIL		;OPEN THE SPECIFIED FILE
	JR	Z,GPFILO	;SKIP IF FILE OPENED OK
	SET	6,A		;SET ERROR CODE DISPLAY BIT
	CP	58H		;FILE NOT IN DIRECTORY?
	RET	NZ		;RETURN IF NOT
	LD	A,5FH		;ELSE PROGRAM NOT FOUND
	OR	A		;SET STATUS FLAGS
	RET
;
;
; GENERAL PURPOSE FILE LOADER
;4C29
GPFILO:	INC	DE		;BUMP TO DCB ACCESS FLAGS
	LD	A,(DE)		;GET ACCESS FLAGS TO A
	DEC	DE		;BACKUP TO DCB START
	AND	00000111B	;ISOLATE ACCESS PERMISSIONS
	CP	00000110B	;TEST FOR RESTRICTED FILE
	JR	C,SYSLDR	;SKIP IF NOT RESTRICTED
	LD	A,(SYSCON)	;GET SYSTEM CONDITION FLAGS
	RLCA			;DEBUG ACTIVE BIT TO CARRY
	LD	A,25H		;LOAD ILLEGAL ACCESS ERROR
	RET	C		;ABORT IF DEBUG ACTIVE
;
;
; SYSTEM LOADER
;4C39
SYSLDR:	LD	BC,GATBUF+255	;SET TO EMPTY BUFFER STATUS
SYSLLP:	CALL	SYSLGB		;GET A BYTE FROM LOAD FILE
	CP	01H		;TEST IF DATA RECORD
	JR	Z,SYSLDA	;THEN GO LOAD DATA BLOCK
	CP	02H		;TEST IF TRANSFER ADDRESS
	JR	Z,SYSLTR	;THEN EXECUTE LOADED CODE
	CP	1FH+1		;TEST IF COMMENT RECORD
	JR	C,SYSLCO	;THEN GO SKIP THE COMMENT
	LD	A,22H		;LOAD FILE FORMAT ERROR
	OR	A		;SET STATUS FOR ERROR CODE
	RET
;
;
; COMMENT RECORD - SKIP THE RECORD
;4C4F
SYSLCO:	CALL	SYSLGB		;GET BYTE COUNT TO A
	LD	B,A		;COPY THE BYTE COUNT TO B
SYSLCL:	CALL	SYSLGB		;READ A DATA BYTE
	DJNZ	SYSLCL		;LOOP UNTIL ALL BYTES READ
	JR	SYSLLP		;THEN LOOP FOR NEXT CODE
;
;
; TRANSFER ADDRESS RECORD - GET THE ADDRESS AND RETURN
; EXIT:   HL      - TRANSFER ADDRESS
;4C5A
SYSLTR:	CALL	SYSLGB		;GET AND DISCARD BYTE COUNT
	CALL	SYSLGB		;GET TRANSFER ADDRESS LSB
	LD	L,A		;COPY THE BYTE TO L
	CALL	SYSLGB		;GET TRANSFER ADDRESS MSB
	LD	H,A		;COPY THE BYTE TO H
	XOR	A		;SET STATUS FOR NO ERROR
	RET
;
;
; DATA RECORD - LOAD THE RECORD
;4C67
SYSLDA:	CALL	SYSLGB		;GET BYTE COUNT TO A
	LD	B,A		;COPY THE BYTE COUNT TO B
	CALL	SYSLGB		;GET LOAD ADDRESS LSB
	LD	L,A		;COPY THE BYTE TO L
	DEC	B		;DECREMENT BYTE COUNT
	CALL	SYSLGB		;GET LOAD ADDRESS MSB
	LD	H,A		;COPY THE BYTE TO H
	DEC	B		;DECREMENT BYTE COUNT
SYSLDL:	CALL	SYSLGB		;GET DATA BYTE TO A
	LD	(HL),A		;STORE DATA IN MEMORY
	CP	(HL)		;TEST IF BYTE STORED OK
	JR	NZ,SYSLER	;NO RAM THERE IF NOT
	INC	HL		;ELSE BUMP DATA ADDRESS
	DJNZ	SYSLDL		;LOOP UNTIL DATA STORED
	JR	SYSLLP		;THEN LOOP FOR NEXT CODE
;
;
; DETERMINE CAUSE OF STORAGE FAILURE
;4C81
SYSLER:	LD	A,(HL)		;FETCH MEMORY CONTENTS
	CPL			;COMPLEMENT THE BYTE
	LD	(HL),A		;STORE THE BYTE BACK
	CP	(HL)		;TEST IF BYTE STORED OK
	LD	A,63H		;MEMORY FAULT ERROR
	RET	NZ		;ABORT IF MISMATCH
	LD	A,64H		;ATTEMPT TO LOAD ROM
	OR	A		;SET ERROR STATUS
	RET
;
;
; GET NEXT BYTE OF LOAD DATA FROM SECTOR BUFFER
;4C8C
SYSLGB:	INC	C		;BUMP BUFFER POINTER LSB
	JR	NZ,SYSLNB	;SKIP IF BUFFER NOT EMPTY
	PUSH	DE		;SAVE DCB ADDRESS
	EX	(SP),IX		;SWAP DCB ADDRESS TO IX
	PUSH	HL		;SAVE CALLER'S HL
	PUSH	DE		;SAVE CALLER'S DE
	PUSH	BC		;SAVE BUFFER POINTER
	CALL	NOTRDP		;READ NEXT FILE RECORD
	POP	BC		;RECOVER BUFFER POINTER
	POP	DE		;RECOVER CALLER'S DE
	POP	HL		;RECOVER CALLER'S HL
	POP	IX		;RECOVER IX REGISTER
	JR	Z,SYSLNB	;SKIP IF NO ERROR
	POP	BC		;REMOVE RETURN ADDRESS
	OR	01000000B	;SIGNAL ERROR DURING LOAD
	RET
;
;
; GET A DATA BYTE FROM THE BUFFER
; ENTRY:  B       - CURRENT BYTE COUNT
;         C       - INDEX INTO DATA BUFFER
; EXIT:   A       - DATA BYTE FROM BUFFER
;4CA3
SYSLNB:	PUSH	BC		;SAVE COUNT AND INDEX
	LD	B,High GATBUF	;LOAD SECTOR BUFFER MSB
	LD	A,(BC)		;GET BYTE FROM BUFFER
	POP	BC		;RECOVER COUNT AND INDEX
	RET
;
;
; CLOCK DISPLAY AND MAINTENANCE INTERRUPT TASK HEADER
;4CA9
CLKTAS	Dw	CLKROU		;POINTER TO ROUTINE
	Db	5		;ENTRY COUNTER
CLKROU:	DEC	(IX+02)		;DECREMENT ENTRY COUNTER
	RET	NZ		;EXIT IF MORE ENTRIES LEFT
	LD	(IX+02),5	;RESET ELAPSED TIME COUNTER
	LD	HL,TIMPOS	;DISPLAY ADDRESS FOR TIME
;
;
; ENTRY POINT TO STORE SYSTEM TIME AS A STRING IN A BUFFER
; ENTRY:  HL      - POINTER TO STRING BUFFER
;
	Org	0446DH
;
GETTME:	JP	TMEGET		;GO STORE TIME STRING
;
;
; ROUTINE TO STORE SYSTEM TIME AS A STRING IN A BUFFER
; ENTRY:  HL      - POINTER TO STRING BUFFER
;
	Org	04CB7H
;
TMEGET:	LD	DE,CLKHOU	;POINT AT HOUR VALUE
	LD	C,':'		;LOAD TIME DELIMITER TO C
;
;
; COMMON ROUTINE TO STORE DATE OR TIME AS A STRING IN A BUFFER
; ENTRY:  C       - FIELD DELIMITER
;         HL      - POINTER TO STRING BUFFER
;4CBC
STORDT:	LD	B,3		;LOAD FIELD COUNTER TO B
STORDN:	LD	A,(DE)		;GET VALUE FROM STORAGE
	DEC	DE		;BACKUP TO PREVIOUS VALUE
	LD	(HL),'0'-1	;STORE STARTING TENS DIGIT
STORDU:	INC	(HL)		;BUMP THE TENS DIGIT
	SUB	10		;SUBTRACT DECIMAL TEN
	JR	NC,STORDU	;LOOP UNTIL UNDERFLOW
	ADD	A,'9'+1		;ACCUMULATOR HAS ONES DIGIT
	INC	HL		;BUMP STORAGE POINTER
	LD	(HL),A		;STORE ONES DIGIT IN BUFFER
	INC	HL		;BUMP STORAGE POINTER
	DEC	B		;DECREMENT FIELD COUNTER
	RET	Z		;DONE IF ALL CONVERTED
	LD	(HL),C		;STORE DELIMITER IN BUFFER
	INC	HL		;BUMP STORAGE POINTER
	JR	STORDN		;THEN DO NEXT FIELD
;
;
; ENTRY POINT TO STORE SYSTEM DATE AS A STRING IN A BUFFER
; ENTRY:  HL      - POINTER TO STRING BUFFER
;
	Org	04470H
;
GETDTE:	JP	DTEGET		;GO STORE DATE STRING
;
;
; ROUTINE TO STORE SYSTEM DATE AS A STRING IN A BUFFER
; ENTRY:  HL      - POINTER TO STRING BUFFER
;
	Org	04CD2H
;
DTEGET:	LD	DE,CLKMON	;POINT AT MONTH VALUE
;
	If	PATCHG		;PATCHES ACTIVE
	 LD	C,'.'		;LOAD DATE DELIMITER TO C
	Else			;ORIGINAL
	 LD	C,'/'		;LOAD DATE DELIMITER TO C
	EndIf			;ALL DONE
;
	JR	STORDT		;GO STORE THE DATE STRING
;
;
; TRACE DISPLAY ROUTINE
;
TRATSK	Dw	TRAROU		;INTERRUPT ROUTINE ENTRY
TRAROU:	LD	HL,18		;PC OFFSET ON STACK
	ADD	HL,SP		;INDEX TO PROGRAM COUNTER
	LD	E,(HL)		;GET PROGRAM COUNTER LSB TO E
	INC	HL		;BUMP INDEX TO MSB
	LD	D,(HL)		;GET PROGRAM COUNTER MSB TO D
	LD	HL,TRAPOS	;DISPLAY LOCATION FOR ADDRESS
;
;
; CONVERT A BINARY WORD TO ASCII HEX AND STORE IN A BUFFER
; ENTRY:  DE      - WORD TO CONVERT AND STORE
;         HL      - POINTER TO BUFFER MEMORY
; EXIT:   HL      - INCREMENTED BY FOUR
;
	LD	A,D		;GET PROGRAM COUNTER MSB
	CALL	BINHEX		;STORE ADDRESS MSB ON SCREEN
	LD	A,E		;GET PROGRAM COUNTER LSB
;
;
; CONVERT A BINARY BYTE TO ASCII HEX AND STORE IN A BUFFER
; ENTRY:  A       - BYTE TO CONVERT AND STORE
;         HL      - POINTER TO BUFFER MEMORY
; EXIT:   HL      - INCREMENTED BY TWO
;4CEA
BINHEX:	PUSH	AF		;SAVE BINARY BYTE
	RRA			; ROTATE
	RRA			;  MS NYBBLE
	RRA			;   INTO
	RRA			;    LS NYBBLE
	CALL	NYBHEX		;CONVERT AND STORE NYBBLE
	POP	AF		;RECOVER SAVED BYTE
;
;
; CONVERT A BINARY NYBBLE TO ASCII HEX AND STORE IN A BUFFER
; ENTRY:  A       - NYBBLE TO CONVERT AND STORE
;         HL      - POINTER TO BUFFER MEMORY
; EXIT:   HL      - INCREMENTED BY ONE
;4CF3
NYBHEX:	AND	00001111B	;MASK TO LS NYBBLE
	ADD	A,'0'		;CONVERT TO ASCII
	CP	'9'+1		;TEST IF NUMERIC HEX
	JR	C,STOBYT	;STORE CHARACTER IF IT IS
	ADD	A,'A'-'9'-1	;ELSE ADD ALPHA HEX BIAS 7
;
;
; STORE A BYTE IN A BUFFER
; ENTRY:  A       - BYTE TO STORE
;         HL      - BUFFER POINTER
; EXIT:   A       - UNCHANGED
;         HL      - INCREMENTED BY ONE
;4CFD
STOBYT:	LD	(HL),A		;STORE CHARACTER IN BUFFER
	INC	HL		;BUMP BUFFER POINTER
	RET
;
;
; SYSTEM SECTOR BUFFER, GAT BUFFER OR HIT BUFFER
;4D00
GATBUF	Ds	256		;RESERVE THE SPACE
;
;
; SYSTEM INITIALIZATION CODE AND START OF OVERLAY AREA
;
	Org	04E00H
;
INITIT:	DI			;KILL INTERRUPTS
	IM	1		;SET INTERRUPT MODE 1
	LD	SP,STACKT	;SYSTEM STACK AREA
	LD	HL,UTAREA	;SET UTILITY
	LD	(ULOADA),HL	; LOAD ADDRESS
	LD	HL,65535	;START ADDRESS FOR MEMORY TEST
TSTMEM:	LD	A,(HL)		;GET A MEMORY BYTE
	LD	B,A		;SAVE IT FOR LATER
	CPL			;COMPLEMENT THE BYTE
	LD	(HL),A		;STORE BYTE IN MEMORY
	CP	(HL)		;TEST IF BYTE STORED OK
	LD	(HL),B		;RESTORE SAVED BYTE
	JR	Z,GOTMEM	;JUMP IF MEMORY LOCATION EXISTS
	LD	A,H		;GET MSB OF TEST ADDRESS
	SUB	High 1024	;LOWER BY ONE KILOBYTE
	LD	H,A		;UPDATE TEST ADDRESS MSB
	JR	TSTMEM		;AND THEN REPEAT TEST
GOTMEM:	LD	(MEMSIZ),HL	;SAVE MAX MEMORY ADDRESS
	JP	PATCKI		;GO CHANGE KEYBOARD DRIVER ADDR
INITIR:	LD	(KIDRVA),HL	;SAVE DRIVER ADDRESS
	LD	(KIDRAD),HL	; IN DRIVER ADDRESS TABLE
	LD	HL,(KEYDCB+6)	;GET KEYBOARD DRIVER NAME
	LD	(KIDRNA),HL	;STORE IN ADDRESS TABLE
	LD	HL,(VDUDCB+1)	;GET ADDRESS OF VIDEO DRIVER
	LD	(DODRVA),HL	;SAVE DRIVER ADDRESS
	LD	(DODRAD),HL	; IN DRIVER ADDRESS TABLE
	LD	HL,(VDUDCB+6)	;GET VIDEO DRIVER NAME
	LD	(DODRNA),HL	;STORE IN ADDRESS TABLE
	LD	HL,(PRNDCB+1)	;GET ADDRESS OF PRINTER DRIVER
	LD	(PRDRVA),HL	;STORE DRIVER ADDRESS
	LD	(PRDRAD),HL	; IN DRIVER ADDRESS TABLE
	LD	HL,(PRNDCB+6)	;GET PRINTER DRIVER NAME
	LD	(PRDRNA),HL	;STORE IN ADDRESS TABLE
	LD	HL,AEDRNA	;POINT AT FREE TABLE ENTRIES
	LD	(HL),0		;ZERO TABLE ENTRY BYTE
	INC	L		;BUMP LSB OF ADDRESS POINTER
	JR	NZ,PATTIT	;PATCH TO SKIP MORE ZEROING
PATTIT:	LD	A,3		;LOAD ALTERNATE DCB COUNT
	LD	HL,KEYDCB	;POINT TO KEYBOARD DCB
	LD	DE,KIBDCB	;ALTERNATE DCB AREA
PATALT:	PUSH	AF		;SAVE DCB COUNT FOR LATER
	LD	BC,8		;NUMBER OF BYTES TO MOVE
	LDIR			;MOVE DCB TO ALTERNATE AREA
	XOR	A		;ZERO ACCUMULATOR
	LD	B,8		;NUMBER OF BYTES TO ZERO
PATZER:	LD	(DE),A		;ZERO BYTES AFTER ALTERNATE DCB
	INC	DE		;BUMP STORAGE POINTER
	DJNZ	PATZER		;LOOP UNTIL 8 BYTES ZEROED
	LD	A,-1		;LOAD VALUE TO STORE
	LD	B,16		;NUMBER OF BYTES TO STORE
;
	If	PATCHG		;PATCHES ACTIVE
ZEROBY:	 NOP			;DO NOTHING
	Else			;ORIGINAL
ZEROBY:	 LD	(DE),A		;STORE BYTE IN MEMORY
	EndIf			;DONE WITH IT
;
	INC	DE		;BUMP MEMORY POINTER
	DJNZ	ZEROBY		;LOOP UNTIL 16 BYTES STORED
	POP	AF		;RECOVER COUNTER
	DEC	A		;DECREMENT ALTERNATE DCB COUNT
;
	If	PATCHG		;PATCHES ACTIVE
	 JR	NZ,PATALT	;LOOP UNTIL ALTERNATES DONE
	Else			;ORIGINAL
	 JR	NZ,SKIPIN	;PATCH TO SKIP INITIALIZING
	EndIf			;DONE WITH IT
;
SKIPIN:	LD	A,(CSTREG)	;GET CONTROLLER STATUS (UN)
	XOR	A		;ZERO ACCUMULATOR
	LD	(DEBUGF),A	;SET DEBUG TO OFF
	LD	HL,INTMSK	;POINT TO INTERRUPT MASK BYTE
	LD	(HL),A		;ZERO MASK (IGNORE ALL INTS)
	LD	A,0C3H		;LOAD A JP OP-CODE
	LD	DE,INTSRV	;LOAD ADDRESS OF INTERRUPT CODE
	LD	(INTVEC+1),DE	;STORE INTERRUPT ADDRESS
	LD	(INTVEC),A	;STORE JP OP-CODE
	LD	DE,SYSCLI	;CLOCK INTERRUPT CODE ADDRESS
	LD	(CLKINT),DE	;STORE IN TASK LIST
	SET	7,(HL)		;SET MASK BIT FOR CLOCK INT
	LD	DE,WAINBU	;DISK INTERRUPT CODE ADDRESS
	LD	(DSKINT),DE	;STORE IN TASK LIST
	SET	6,(HL)		;SET MASK BIT FOR DISK INT
	LD	A,00000001B	;SET SYSTEM CONDITION FLAG
	LD	(SYSCON),A	; TO SHOW DOS CONTEXT
	LD	DE,CLKTSK	;ADDR OF CLOCK INTERRUPT TASK
	LD	A,7		;INDEX TO INTERRUPT TASK LIST
	CALL	TSKADD		;ADD TO INTERRUPT TASK LIST
	LD	HL,SIGNON	;POINT TO SIGN ON STRING
HEADNL:	LD	A,(HL)		;LOAD BYTE FROM STRING
	NEG			;DECODE THE BYTE
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	INC	HL		;BUMP STRING POINTER
	CP	CR		;TEST IF TERMINATOR
	JR	NZ,HEADNL	;LOOP UNTIL TERMINATOR
	CALL	KBCHAR		;READ THE KEYBOARD
	CP	CR		;TEST IF CARRIAGE RETURN
	JP	Z,NORENT	;SKIP AUTO TEST IF PRESSED
	LD	C,0		;CODE FOR DRIVE 0
	LD	D,17		;TRACK 17
	LD	E,0		;SECTOR 0
	LD	HL,SYSBUF	;LOAD BUFFER POINTER
	CALL	DDREAD		;GO READ GAT SECTOR
	JP	NZ,DERROR	;ABORT IF READ ERROR
	LD	A,(SYSBUF+224)	;FIRST BYTE OF AUTO PROCEDURE
	CP	CR		;TEST IF CARRIAGE RETURN
	JP	Z,NORENT	;JUMP IF PROCEDURE EMPTY
	LD	HL,SYSBUF+224	;POINT TO PROCEDURE
	LD	DE,CMLBUF	;POINT TO COMMAND LINE BUFFER
	LD	BC,32		;LENGTH OF PROCEDURE
	LDIR			;MOVE IT TO COMMAND LINE BUFFER
	LD	HL,CMLBUF	;POINT TO COMMAND LINE BUFFER
	CALL	DOPMSG		;DISPLAY THE COMMAND LINE
	JP	DOSCMD		;LOAD SYS1/SYS TO EXECUTE
;
;
; SYSTEM HEADER MESSAGE IN NEGATED FORM
;4EED
SIGNON	Db	(Not 'T') + 1
	Db	(Not 'R') + 1
	Db	(Not 'S') + 1
	Db	(Not 'D') + 1
	Db	(Not 'O') + 1
	Db	(Not 'S') + 1
	Db	(Not ' ') + 1
	Db	(Not '-') + 1
	Db	(Not ' ') + 1
	Db	(Not 'D') + 1
	Db	(Not 'I') + 1
	Db	(Not 'S') + 1
	Db	(Not 'K') + 1
	Db	(Not ' ') + 1
	Db	(Not 'O') + 1
	Db	(Not 'P') + 1
	Db	(Not 'E') + 1
	Db	(Not 'R') + 1
	Db	(Not 'A') + 1
	Db	(Not 'T') + 1
	Db	(Not 'I') + 1
	Db	(Not 'N') + 1
	Db	(Not 'G') + 1
	Db	(Not ' ') + 1
	Db	(Not 'S') + 1
	Db	(Not 'Y') + 1
	Db	(Not 'S') + 1
	Db	(Not 'T') + 1
	Db	(Not 'E') + 1
	Db	(Not 'M') + 1
	Db	(Not ' ') + 1
	Db	(Not '-') + 1
	Db	(Not ' ') + 1
	Db	(Not 'V') + 1
	Db	(Not 'E') + 1
	Db	(Not 'R') + 1
	Db	(Not ' ') + 1
	Db	(Not '2') + 1
	Db	(Not '.') + 1
	Db	(Not '3') + 1
	Db	(Not ' ') + 1
	Db	(Not ' ') + 1
	Db	(Not  LF) + 1
	Db	(Not  CR) + 1
;
;
; TEST IF BEYOND EOF PATCH
;
	Org	04B97H
;
TSTEOP:	LD	A,(IX+08)	;FETCH OFFSET EOF FROM DCB
	DEC	A		;ADJUST OFFSET BY 1
	SUB	C		;COMPARE TO CURRENT REC OFFSET
	CCF			;INVERT FOR TEST BEYOND EOF
	INC	BC		;READJUST OFFSET
	RET
	NOP
;
;
; KEYBOARD DRIVER DEBOUNCE OR BLINK PATCH-IN ROUTINE
;
	Org	04F20H
;
PATCKI:	LD	HL,KEYDEB	;POINT TO KEYBOARD DRIVER
	LD	(KEYDCB+1),HL	;STORE ADDRESS IN DCB
	JP	INITIR		;REJOIN MAIN CODE
;
;
; KEYBOARD DRIVER BLINK PATCH ROUTINE
;
	Org	043D8H
;
	If	PATCHG		;PATCHES ACTIVE
KEYDEB:	 EXX			;SWAP TO ALTERNATE REGISTERS
	 INC	DE		;BUMP BLINK COUNTER
	 BIT	1,D		;TEST IF TIME TO BLINK
	 JR	Z,KEYDEX	;EXIT IF NOT TIME YET
	 RES	1,D		;ELSE RESET COUNT TO ZERO
	 LD	HL,(VDUDCB+3)	;GET CURSOR ADDRESS TO HL
	 LD	A,(VDUDCB+5)	;GET CURSOR ON/OFF FLAG
	 OR	A		;TEST IF CURSOR IS OFF
	 JR	Z,KEYDEX	;THEN WE ARE ALL DONE
	 BIT	7,D		;TEST IF FLASH ON BIT SET
	 JR	Z,KEYDFO	;GO SET IF BIT RESET
	 RES	7,D		;RESET FLASH ON BIT
	 LD	(HL),A		;STORE CHARACTER UNDER CURSOR
	 JR	KEYDEX		;THEN WE ARE DONE FOR NOW
KEYDFO:	 SET	7,D		;SET FLASH ON BIT
	 LD	(HL),5FH	;STORE CURSOR CHARACTER
KEYDEX:	 EXX			;SWAP TO NORMAL REGISTERS
	 JP	KYDRVR		;THEN GET KEYBOARD CHARACTER
;
;
; LINE PRINTER DRIVER ROUTINE PATCH
;43FA
PRINTR:	 LD	A,C		;GET CHARACTER TO A
	 JP	PRDRCF		;GO PRINT THE CHARACTER
	Else			;ORIGINAL
;
;
; KEYBOARD DRIVER DEBOUNCE PATCH ROUTINE
;
	 Org	043D8H
;
KEYDEB:	 LD	HL,KBDWRK	;POINT HL TO WORK AREA
	 LD	BC,KROONE	;POINT BC TO ROW 1
	 LD	D,0		;CLEAR COLUMN INDEX
KEYDNR:	 LD	A,(BC)		;LOAD ROW
	 LD	E,A		;SAVE ROW BITS IN E
	 XOR	(HL)		;XOR WITH PREVIOUS
	 LD	(HL),E		;STORE COLUMN BITS
	 AND	E		;TEST FOR ACTIVE ROW
	 JR	NZ,KEYDAR	;GO IF ACTIVE ROW
	 INC	D		;BUMP ROW INDEX
	 INC	L		;BUMP WORK AREA POINTER
	 RLC	C		;STEP KEYBOARD ROW ADDRESS
	 JP	P,KEYDNR	;TRY NEXT ROW
	 RET
;
;
; ACTIVE ROW FOUND
;
KEYDAR:	 LD	E,A		;SAVE COLUMN BITS IN E
	 PUSH	BC		;SAVE ACTIVE ROW ADDRESS
	 LD	BC,1247		;DELAY COUNT VALUE
	 CALL	DELAYL		;DELAY FOR 7 MILLISECOND
	 POP	BC		;RESTORE ROW ADDRESS
	 LD	A,(BC)		;RELOAD ACTIVE ROW
	 AND	E		;TEST IF SAME AS OLD
	 RET	Z		;EXIT IF ROW NOT ACTIVE
	 JP	KYDRAJ		;ELSE LEGIMATE ACTIVE ROW
	EndIf			;DONE WITH IT
;
;
; PATCH TO 'SKIP TO END OF FILE' ROUTINE
;
	Org	04768H
;
	CALL	EOFPAT		;OFFSET TO EOF IN LAST SECTOR
;
;
; DECREMENT COUNT OF RECORDS IN FILE BY 1
;
	If	PATCHG		;PATCHES ACTIVE
	 Org	0439BH		;DEFINE PATCH ORIGIN
	Else			;ORIGINAL
	 Org	043D1H		;DEFINE PATCH ORIGIN
	EndIf			;DONE WITH IT
;
EOFPAT:	LD	A,(IX+08)	;GET EOF BYTE IN LAST SECTOR
	OR	A		;SET STATUS FLAGS
	RET	Z		;RETURN IF ON SECTOR BOUNDARY
	DEC	BC		;DECREMENT NUMBER OF RECORDS
	RET
;
;
; RESELECT LAST UNIT SELECTED
;
; NOTE:  LOCATED IN ALTERNATE PRINTER DEVICE CONTROL BLOCK
;
	If	PATCHG		;PATCHES ACTIVE
	 Org	04391H		;DEFINE PATCH ORIGIN
	Else			;ORIGINAL
	 Org	043ACH		;DEFINE PATCH ORIGIN
	EndIf			;DONE WITH IT
;
RESEUN:	LD	A,(DRVMSK)	;GET MASK FOR CURRENT UNIT
	LD	(DRVREG),A	;SELECT UNIT
	LD	A,(CSTREG)	;FETCH CONTROLLER STATUS
	RET
;
;
; WAIT FOR DISK CONTROLLER TO BECOME NOT BUSY
;
; NOTE:  LOCATED IN ALTERNATE PRINTER DEVICE CONTROL BLOCK
;
	If	PATCHG		;PATCHES ACTIVE
	 Org	04388H		;DEFINE PATCH ORIGIN
	Else			;ORIGINAL
	 Org	04398H		;DEFINE PATCH ORIGIN
	EndIf			;DONE WITH IT
;
WAITNB:	LD	A,(CSTREG)	;GET CONTROLLER STATUS
	BIT	0,A		;TEST IF CONTROLLER BUSY
	RET	Z		;EXIT IF NOT BUSY
	JR	WAITNB		;LOOP UNTIL NOT BUSY
;
;
; ADDITIONAL PATCHES
;
	If	PATCHG		;PATCHES ACTIVE
;
;
; VIDEO DRIVER ROUTINE LOWER CASE PATCH
;
; NOTE:  LOCATED IN ALTERNATE VIDEO DEVICE CONTROL BLOCK
;
	 Org	04378H
;
DOTDCB:	 LD	L,(IX+03)	;GET CURSOR ADDRESS LSB
	 LD	H,(IX+04)	;GET CURSOR ADDRESS MSB
	 JP	C,VIDRCH	;RETURN LAST CHARACTER
	 LD	A,(IX+05)	;GET CURSOR ON FLAG TO A
	 OR	A		;TEST IF CURSOR IS OFF
	 JR	Z,LOCACO	;SKIP IF IT IS OFF
	 LD	(HL),A		;ELSE RESTORE THE CHARACTER
LOCACO:	 LD	A,C		;GET NEW CHARACTER TO A
	 CP	0C0H		;TEST IF GRAPHICS CHARACTER
	 JP	NC,VIDRCO	;COMPRESSION CODE IF NOT
	 CP	20H		;TEST IF CONTROL CODE
	 JP	C,VIDRCC	;THEN HANDLE CONTROL CODE
	 JP	VIDRAU		;ADD CHARACTER TO DISPLAY
;
;
; SET ADDRESS OF VIDEO DRIVER PATCH IN VIDEO DCB
;
	 Org	0401EH
;
VIDPAT	 Dw	DOTDCB		;DRIVER ADDRESS
;
;
; SET ADDRESS OF PRINTER DRIVER PATCH IN PRINTER DCB
;
	 Org	04026H
;
PRTPAT	 Dw	PRINTR		;DRIVER ADDRESS
	EndIf			;DONE WITH IT
;
	End	INITIT

