	Title	'TRSDOS 2.3 Disk Operating System'
;
;
; TRSDOS DISK OPERATING SYSTEM, VERSION 2.3
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON 23.01.2022
;
; PART 1 - OVERLAY 1 - DOS COMMAND PREPROCESSOR
;
;
; DEFINE IF PATCHES ARE ACTIVE
;
PATCHG	Equ	  0		;PATCHES ACTIVE
;
;
; ASCII EQUATES
;
CC	Equ	  3		;CONTROL-C (END-OF-MESSAGE)
LF	Equ	 10		;LINE FEED
CR	Equ	 13		;CARRIAGE RETURN
;
;
; LEVEL II BASIC ROM DEFINITIONS
;
IPLENL	Equ	00036H		;LEVEL II SETUP TABLE LENGTH
KBLINE	Equ	00040H		;INPUT AND FILL KEYBOARD BUFFER
POWRES	Equ	00075H		;ROM BASIC POWER ON OR RESET
IPLINI	Equ	006D2H		;LEVEL II SETUP TABLE
;
;
; INPUT/OUTPUT PORT ADDRESS DEFINITIONS
;
KROSEV	Equ	03840H		;KEYBOARD ROW SEVEN <BREAK> ROW
;
;
; 'RST' VECTORS
;
TNXVEC	Equ	04000H		;COMMUNICATIONS REGION START
LDBVEC	Equ	0400FH		;'DEBUG' RST VECTOR
;
;
; STORAGE LOCATIONS IN TRSDOS NUCLEUS (SYS0/SYS)
;
STACKT	Equ	041FCH		;TOP OF SYSTEM STACK
SYSCON	Equ	0430FH		;SYSTEM CONDITION FLAGS
DEBUGF	Equ	04315H		;DEBUG ON/OFF FLAG AND JUMP
CMLBUF	Equ	04318H		;DOS COMMAND LINE BUFFER
KIBDCB	Equ	04358H		;ALTERNATE KEYBOARD DCB
SYSDCB	Equ	04480H		;SYSTEM DEVICE CONTROL BLOCK
;
;
; FUNCTIONS ADDRESSES IN TRSDOS NUCLEUS (SYS0/SYS)
;
DOSENT	Equ	0402DH		;DO SYS1/SYS REQUEST CODE 10
ERRENT	Equ	04030H		;DO SYS1/SYS REQUEST CODE 20
ADDTSK	Equ	04410H		;ADD TASK TO INTERRUPT LIST
REMTSK	Equ	04413H		;REMOVE TASK FROM LIST
LODEXE	Equ	04433H		;LOAD AND EXECUTE 'CMD' FILE
DOPMSG	Equ	04467H		;DISPLAY MESSAGE STRING
TRATSK	Equ	04CD9H		;'TRACE' TASK IN SYS0/SYS
;
;
; FUNCTIONS ADDRESSES IN TRSDOS COMMAND PROCESSOR (SYS6/SYS)
;
SYSSIX	Equ	05200H		;ENTRY ADDRESS
;
;
; PROGRAM MODULE NAME STRING
;
	Nam	'SYS1  '
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING
;
	Rem	CR
	Rem	'* * * N O T I C E * * *',CR
	Rem	'* PROPRIETARY PROGRAM *',CR
	Rem	'* COPYRIGHT (c) 1979  *',CR
	Rem	'* BY TANDY CORPORATION*',CR
	Rem	'*  FORT WORTH, TEXAS  *',CR
	Rem	'* ALL RIGHTS RESERVED *',CR
	Rem	'* * * N O T I C E * * *',CR
;
;
	Org	04E00H
;
OVRL01:	AND	01110000B	;MASK TO REQUEST BITS
	CP	10H		;REQUEST 10
	JP	Z,NORMEN	;COMMAND PROCESSOR NORMAL ENTRY
	CP	20H		;REQUEST 20
	JR	Z,ERROEN	;COMMAND PROCESSOR ERROR ENTRY
	CP	30H		;REQUEST 30
	JR	Z,CMDEXE	;EXECUTE A DOS COMMAND
	CP	40H		;REQUEST 40
	JP	Z,PARSCL	;PARSE COMMAND LINE
	CP	50H		;REQUEST 50
	JP	Z,ADDEXT	;ADD EXTENSION TO FILE NAME
	CP	60H		;REQUEST 60
	JP	Z,PARSEA	;PARSE COMMAND ARGUMENTS
	RET
;
;
; OVERLAY REQUEST 10 - NORMAL ENTRY TO DOS COMMAND PROCESSOR
;
NORMEN:
;
;
; OVERLAY REQUEST 20 - ERROR ENTRY TO DOS COMMAND PROCESSOR
;4E1F
ERROEN:	EI			;ENABLE INTERRUPTS
	LD	SP,STACKT	;SET UP STACK POINTER
	LD	HL,KIBDCB+01	;POINT AT DCB ACCESS FLAGS
	BIT	5,(HL)		;REDUNDANT INSTRUCTION
	LD	HL,SYSCON	;SYSTEM CONDITION FLAGS
	BIT	7,(HL)		;TEST IF 'DEBUG' ACTIVE
	JR	Z,DEBINA	;SKIP IF INACTIVE
	LD	A,0C3H		;LOAD 'JP' OP-CODE
	LD	(DEBUGF),A	;ACTIVATE 'DEBUG' JUMP
DEBINA:	BIT	5,(HL)		;TEST FOR PROGRAM CHAINING
	JR	Z,CHAINA	;SKIP IF CHAINING INACTIVE
	LD	A,(KROSEV)	;LOAD KEYBOARD ROW BITS
	AND	00000100B	;TEST IF <BREAK> KEY HIT
	JP	NZ,ERRENT	;THEN ABORT TO ERROR HANDLER
CHAINA:	LD	HL,DOSREM	;POINT AT 'DOS READY' PROMPT
	CALL	DOPMSG		;DISPLAY PROMPT STRING
	LD	HL,CMLBUF	;POINT AT COMMAND LINE BUFFER
	LD	B,63		;LOAD BUFFER SIZE TO B
	CALL	KBLINE		;INPUT AND FILL BUFFER
;
;
; OVERLAY REQUEST 30 - EXECUTE A DOS COMMAND
; ENTRY:  HL      - POINTER TO COMMAND LINE BUFFER
;4E4E
CMDEXE:	LD	BC,DOSENT	;LOAD DOS SUCCESS RETURN
	PUSH	BC		;PUT ADDRESS ON THE STACK
	LD	DE,SYSDCB	;POINT AT SYSTEM DCB
	CALL	PARSCL		;PARSE COMMAND LINE TO DCB
	JP	NZ,SYNERR	;ABORT IF ILLEGAL CHARACTER
	LD	A,(DE)		;GET COMMAND LINE CHARACTER
	CP	'*'		;TEST IF DEVICE INDICATOR
	JP	Z,SYNERR	;WE HAVE A SYNTAX ERROR IF SO
	PUSH	HL		;SAVE BUFFER POINTER
	LD	BC,ONECMD	;SYS1/SYS COMMAND ADDRESSES
	CALL	TSTCMD		;TEST FOR THE COMMANDS
	JR	Z,EXECMD	;THEN EXECUTE THE COMMAND
	LD	BC,SIXCMD	;SYS6/SYS COMMAND ADDRESSES
	CALL	TSTCMD		;TEST FOR THE COMMANDS
	JR	Z,EXECMD	;THEN EXECUTE THE COMMAND
;
;
; COMMAND IS NEITHER SYS1 OR SYS6 COMMAND
; ADD 'CMD' SUFFIX TO FILE NAME AND LOAD FILE FROM DISK
;
	LD	A,(SYSCON)	;LOAD SYSTEM CONDITION FLAGS
	RES	4,A		;CLEAR SYS6/SYS LOADED BIT
	LD	(SYSCON),A	;UPDATE CONDITION FLAGS
	LD	HL,CMDEXM	;POINT AT 'CMD' EXTENSION
	CALL	ADDEXT		;ADD EXTENSION TO FILE NAME
	POP	HL		;RECOVER BUFFER POINTER
	JP	LODEXE		;LOAD AND EXECUTE THE FILE
;
;
; COMMAND WAS FOUND - EXECUTE THE COMMAND
; ENTRY:  DE      - COMMAND EXECUTION ADDRESS
;4E84
EXECMD:	POP	HL		;RECOVER BUFFER POINTER
	PUSH	DE		;PUT COMMAND ADDRESS ON STACK
	RET
;
;
; DISPLAY 'WHAT?' SYNTAX ERROR MESSAGE
;4E87
SYNERR:	LD	HL,SYNERM	;POINT AT ERROR STRING
	CALL	DOPMSG		;DISPLAY THE MESSAGE
	JP	ERRENT		;THEN ABORT TO DOS ERROR
;
;
; EXECUTE 'SYS6/SYS' COMMANDS
;4E90
EXESIX:	LD	A,(SYSCON)	;GET CONDITION FLAGS
	BIT	4,A		;TEST IF 'SYS6/SYS' LOADED
	JP	NZ,SYSSIX	;THEN JUST EXECUTE IT
	LD	A,(SYSCON)	;GET CONDITION FLAGS
	SET	4,A		;FLAG 'SYS6/SYS' LOADED
	LD	(SYSCON),A	;RESTORE CONDITION FLAGS
	LD	A,088H		;LOAD REQUEST CODE TO A
	PUSH	AF		;SAVE THE CODE
	RST	28H		;LOAD AND EXECUTE 'SYS6/SYS'
;
;
; COMMAND STRINGS HANDLED BY 'SYS1/SYS' OVERLAY MODULE
;4EA4
ONECMD	Db	'BASIC2'	;CASSETTE BASIC COMMAND
	Dw	BASTWO		;ADDRESS OF 'BASIC2' ROUTINE
	Db	'DEBUG '	;DEBUGGER COMMAND
	Dw	DEBUGS		;ADDRESS OF 'DEBUG' ROUTINE
	Db	'TRACE '	;SYSTEM TRACE COMMAND
	Dw	TRACES		;ADDRESS OF 'TRACE' ROUTINE
	Db	0
;
;
; COMMAND STRINGS HANDLED BY 'SYS6/SYS' EXTENSION MODULE
;4EBD
SIXCMD	Db	'APPEND'	;APPEND ONE FILE TO ANOTHER
	Dw	EXESIX
	Db	'ATTRIB'	;CHANGE FILE ATTRIBUTES
	Dw	EXESIX
	Db	'AUTO  '	;ENTER AUTO SEQUENCE
	Dw	EXESIX
	Db	'CLOCK '	;TURN ON CLOCK DISPLAY
	Dw	EXESIX
	Db	'COPY  '	;COPY A FILE
	Dw	EXESIX
	Db	'DATE  '	;SET SYSTEM DATE
	Dw	EXESIX
	Db	'DEVICE'	;LIST DEVICES
	Dw	EXESIX
	Db	'DIR   '	;DISPLAY DIRECTORY
	Dw	EXESIX
	Db	'DUMP  '	;DUMP MEMORY TO DISK
	Dw	EXESIX
	Db	'FREE  '	;DISPLAY DISK FREE SPACE
	Dw	EXESIX
	Db	'KILL  '	;DELETE A FILE
	Dw	EXESIX
	Db	'LIB   '	;DISPLAY LIBRARY COMMANDS
	Dw	EXESIX
	Db	'LIST  '	;LIST A TEXT FILE
	Dw	EXESIX
	Db	'LOAD  '	;LOAD AN EXECUTABLE FILE
	Dw	EXESIX
	Db	'PRINT '	;PRINT A TEXT FILE
	Dw	EXESIX
	Db	'PROT  '	;CHANGE FILE PROTECTION
	Dw	EXESIX
	Db	'RENAME'	;RENAME A FILE
	Dw	EXESIX
	Db	'TIME  '	;SET SYSTEM TIME
	Dw	EXESIX
	Db	'VERIFY'	;TURN VERIFY ON OR OFF
	Dw	EXESIX
	Db	0
;
;
; OVERLAY REQUEST 40 - PARSE COMMAND LINE
; ENTRY:  DE      - POINTER TO DEVICE CONTROL BLOCK
;         HL      - COMMAND LINE POINTER
;4F56
PARSCL:	PUSH	DE		;SAVE STORAGE BUFFER POINTER
	LD	B,8		;LOAD MAXIMUM CHARACTER COUNT
	CALL	VALCPY		;COPY FILENAME TO BUFFER
	JR	NZ,DEVPAR	;TEST FOR DEVICE IF LINE END
	CP	'/'		;TEST IF EXTENSION DELIMITER
	JR	NZ,NOEXTE	;SKIP IF NO EXTENSION
	LD	(DE),A		;ELSE STORE THE DELIMITER
	INC	DE		;BUMP STORAGE POINTER
	LD	B,3		;LOAD MAXIMUM CHARACTER COUNT
	CALL	VALCPY		;COPY EXTENSION TO BUFFER
	JR	NZ,DEVPAN	;ALL DONE IF LINE END
NOEXTE:	CP	'.'		;TEST IF PASSWORD DELIMITER
	JR	NZ,NOPASS	;SKIP IF NO PASSWORD
	LD	(DE),A		;ELSE STORE THE DELIMITER
	INC	DE		;BUMP STORAGE POINTER
	LD	B,8		;LOAD MAXIMUM CHARACTER COUNT
	CALL	VALCPY		;COPY PASSWORD TO BUFFER
	JR	NZ,DEVPAN	;ALL DONE IF END OF LINE
NOPASS:	CP	':'		;TEST IF DRIVE CODE DELIMITER
	JR	NZ,NODRIV	;SKIP IF NO DRIVE CODE
	LD	(DE),A		;ELSE STORE THE DELIMITER
	INC	DE		;BUMP STORAGE POINTER
	LD	B,1		;LOAD MAXIMUM CHARACTER COUNT
	CALL	VALCPY		;COPY DRIVE CODE TO BUFFER
	JR	NZ,DEVPAN	;ALL DONE IF END OF LINE
NODRIV:	LD	C,A		;SAVE LATEST CHARACTER
	LD	A,CC		;LOAD STRING TERMINATOR
	LD	(DE),A		;TERMINATE FILE SPEC STRING
	XOR	A		;CLEAR CARRY, SET ZERO FLAGS
	LD	A,C		;RESTORE LATEST CHARACTER
	POP	DE		;RECOVER STORAGE POINTER
	PUSH	DE		;RESAVE THE POINTER
	LD	BC,PARMHD	;POINT AT PARAMETER HEADERS
	CALL	TSTCMD		;PARSE THE PARAMETER(S)
	POP	DE		;RECOVER STORAGE POINTER
	JR	Z,PARSCL	;TEST FOR MORE IF NOT LINE END
	XOR	A		;CLEAR CARRY, SET ZERO FLAGS
	RET
;
;
; GET EVENTUAL DEVICE AND PARAMETERS
; ENTRY:  DE      - STORAGE POINTER
;4F98
DEVPAR:	CP	'*'		;TEST IF DEVICE HEADER
	JR	NZ,DEVPAN	;ALL DONE IF NOT THE HEADER
	LD	(DE),A		;ELSE STORE DEVICE HEADER
	INC	DE		;BUMP STORAGE POINTER
	LD	B,2		;LOAD MAXIMUM CHARACTER COUNT
	CALL	VALCPY		;COPY DEVICE NAME TO BUFFER
	JR	Z,NODRIV	;GET PARAMETERS IF NOT LINE END
DEVPAN:	POP	DE		;RECOVER STORAGE POINTER
	RET
;
;
; PARAMETER SEPERATOR HEADERS LIST
;4FA7
PARMHD	Db	'TO    '
	Dw	0
	Db	'ON    '
	Dw	0
	Db	'OVER  '
	Dw	0
	Db	0		;END OF SEPERATORS
;
;
; OVERLAY REQUEST 50 - ADD EXTENSION TO FILE NAME
; ENTRY:  DE      - POINTER TO DEVICE CONTROL BLOCK
;         HL      - POINTER TO FILE NAME EXTENSION
;4FC0
ADDEXT:	PUSH	DE		;SAVE POINTER TO DCB
	PUSH	HL		;SAVE FILE EXTENSION POINTER
	EX	DE,HL		;SWAP DCB POINTER TO HL
	INC	HL		;BUMP THE DCB POINTER
	LD	B,9		;LOAD FILE NAME LENGTH + 1
ADDEXL:	LD	A,(HL)		;GET CHARACTER FROM FILE NAME
	CP	'/'		;TEST IF EXTENSION DELIMITER
	JR	Z,ADDEXX	;NOTHING TO DO IF NONE
	JR	C,EXTADD	;DONE IF SPECIAL CHARACTER
	CP	':'		;TEST IF DRIVE CODE DELIMITER
	JR	C,ADDEXN	;SKIP IF NUMERIC FOUND
	CP	'A'		;TEST IF ALPHABETIC CHARACTER
	JR	C,EXTADD	;DONE IF NOT ALPHABETIC
ADDEXN:	INC	HL		;BUMP DCB POINTER
	DJNZ	ADDEXL		;AND LOOP FOR NEXT CHARACTER
ADDEXX:	POP	HL		;RECOVER EXTENSION POINTER
	POP	DE		;RECOVER DCB POINTER
	RET
;
;
; POSSIBLE END OF FILE SPECIFICATION - ADD THE EXTENSION
; ENTRY:  (SP+00) - SAVED DEVICE CONTROL BLOCK POINTER
;         (SP+02) - SAVED FILE EXTENSION POINTER
;         DE      - POINTER TO FILE NAME EXTENSION
;         HL      - POINTER TO DEVICE CONTROL BLOCK
;4FDB
EXTADD:	LD	BC,15		;MAX DISTANCE TO DCB END
	ADD	HL,BC		;GET LAST BYTE USED ADDRESS
	LD	D,H		;LAST DCB BYTE POINTER MSB
	LD	E,L		;LAST DCB BYTE POINTER LSB
	INC	DE		;MAKE A
	INC	DE		; HOLE FOR
	INC	DE		;  EXTENSION
	INC	DE		;   SUFFIX
	INC	BC		;NUMBER OF BYTES TO MOVE
	LDDR			;MOVE DATA AFTER FILE NAME
	POP	HL		;RECOVER EXTENSION POINTER
	INC	HL		;BUMP TO END
	INC	HL		; OF EXTENSION
	LD	C,3		;LOAD EXTENSION LENGTH
	LDDR			;COPY EXTENSION TO DCB
	LD	A,'/'		;LOAD EXTENSION DELIMITER
	LD	(DE),A		;STORE DELIMITER IN DCB
	POP	DE		;RECOVER DCB POINTER
	RET
;
;
; COPY CHARACTERS FROM LIST AND VALIDATE - COPY TERMINATOR WHEN
; CHARACTER COUNT, 'CC' OR 'CR' ENCOUNTERED IN SOURCE LIST
; ENTRY:  B       - CHARACTER COUNT
;         DE      - DESTINATION POINTER
;         HL      - SOURCE POINTER
;4FF4
VALCPY:	LD	A,B		;GET CHARACTER COUNT TO A
	LD	(VALCPT),A	;SAVE THE CHARACTER COUNT
	INC	B		;BUMP THE CHARACTER COUNT
VALCPL:	LD	A,(HL)		;GET CHARACTER FROM SOURCE
	CP	CC		;TEST IF TERMINATOR
	JR	Z,VALCPD	;THEN WE ARE ALL DONE
	CP	CR		;TEST IF TERMINATOR
	JR	Z,VALCPD	;ALL DONE IF IT IS
	INC	HL		;BUMP SOURCE ADDRESS
	CP	'0'		;TEST IF NUMERIC CHARACTER
	JR	C,VALCPD	;DONE IF NOT NUMERIC
	CP	'9'+1		;TEST IF REALLY NUMERIC
	JR	C,VALCPN	;SKIP IF NUMERIC
	CP	'A'		;TEST IF ALPHABETIC
	JR	C,VALCPD	;DONE IF NOT ALPHABETIC
	CP	'Z'+1		;TEST IF REALLY ALPHABETIC
	JR	NC,VALCPD	;DONE IF NOT ALPHABETIC
VALCPN:	DEC	B		;DECREMENT CHARACTER COUNT
	JR	Z,VALCPE	;SKIP IF COUNT EXHAUSTED
	LD	(DE),A		;ELSE STORE AT DESTINATION
	XOR	A		;ZERO ACCUMULATOR
	LD	(VALCPT),A	;ZERO THE CHARACTER COUNT
	INC	DE		;BUMP DESTINATION POINTER
	JR	VALCPL		;THEN LOOP FOR NEXT ONE
VALCPE:	INC	B		;ADJUST COUNT FOR LAST CHAR
	JR	VALCPL		;THEN CONTINUE SCANNING
VALCPD:	LD	C,A		;SAVE TERMINATING CHARACTER
	LD	A,CC		;LOAD STRING TERMINATOR
	LD	(DE),A		;TERMINATE DESTINATION
	LD	A,0		;GET THE COUNT TO A
VALCPT	Equ	$-1		;STORAGE FOR COUNT TESTED
	OR	A		;TEST IF COUNT IS ZERO
	LD	A,C		;TERMINATING CHARACTER TO A
	RET
;
;
; COMPARE COMMAND LISTS
; ENTRY:  BC      - COMMAND LIST POINTER
;         DE      - COMMAND LINE POINTER
;502A
TSTCMD:	PUSH	HL		;SAVE INPUT STRING ADDRESS
	LD	H,B		;COPY COMMAND ADDRESS MSB
	LD	L,C		;COPY COMMAND ADDRESS LSB
	LD	C,1		;NUMBER OF SEARCHED LISTS
TSTCNE:	LD	A,(DE)		;GET COMMAND LINE CHARACTER
	CP	(HL)		;TEST IF MATCH WITH LIST
	JR	Z,LSMATC	;CONTINUE IF LIST MATCH
TSTCNL:	PUSH	BC		;SAVE THE COMMAND ADDRESS
	LD	BC,8		;OFFSET TO NEXT LIST ENTRY
	ADD	HL,BC		;INDEX TO NEXT ENTRY
	POP	BC		;RECOVER THE COMMAND ADDRESS
	INC	C		;BUMP COMMAND ADDRESS LSB
	LD	A,(HL)		;GET COMMAND CHARACTER
	OR	A		;TEST IF END OF LIST
	JR	NZ,TSTCNE	;LOOP IF NOT LIST END
	POP	HL		;RECOVER INPUT STRING ADDRESS
	OR	00000001B	;SIGNAL NO MATCH
	RET
;
;
; WE HAVE A LIST MATCH SO CONTINUE FOR FURTHER CHARACTERS
;5042
LSMATC:	LD	B,5		;CHARACTER COUNT LEFT TO MATCH
	PUSH	HL		;SAVE COMMAND LIST POINTER
	PUSH	DE		;SAVE COMMAND LINE POINTER
LSMATL:	INC	DE		;BUMP TO NEXT LINE CHARACTER
	INC	HL		;BUMP TO NEXT LIST CHARACTER
	LD	A,(DE)		;GET INPUT LINE CHARACTER
	CP	CC		;TEST IF LINE TERMINATOR
	JR	Z,TESTSP	;ALL DONE IF IT IS
	CP	CR		;TEST IF LINE TERMINATOE
	JR	Z,TESTSP	;ALL DONE IF IT IS
	CP	(HL)		;TEST IF CHARACTER MATCH
	JR	NZ,TESTAN	;SKIP IF CHARACTER MISMATCH
	DJNZ	LSMATL		;LOOP FOR NEXT CHARACTER
LSMATA:	POP	DE		;RECOVER SEARCH LIST POINTER
	LD	A,C		;GET MATCHED LIST COUNT
	POP	BC		;GET STARTING ADDRESS
	LD	HL,6		;GET COMMAND LENGTH TO HL
	ADD	HL,BC		;COMMAND VERB ENDING ADDRESS
	LD	C,A		;LOAD LIST NUMBER TO C
	LD	E,(HL)		;COMMAND ADDRESS LSB
	INC	HL		;BUMP TO ADDRESS MSB
	LD	D,(HL)		;COMMAND ADDRESS MSB
	POP	HL		;GET COMMAND STRING ADDRESS
	XOR	A		;SIGNAL GOOD STATUS
	RET
;
;
; TEST CHARACTER FOR ALPHANUMERIC OR SPECIAL
;5064
TESTAN:	CP	'0'		;TEST IF NUMERIC CHARACTER
	JR	C,TESTSP	;SKIP IF A SPECIAL ONE
	CP	'9'+1		;TEST IF REALLY NUMERIC
	JR	C,TESTEX	;CONTINUE IF IT IS
	CP	'A'		;TEST IF ALHABETIC CHARACTER
	JR	C,TESTSP	;SKIP IF A SPECIAL ONE
	CP	'Z'+1		;TEST IF REALLY ALPHABETIC
	JR	C,TESTEX	;CONTINUE IF IT IS
TESTSP:	LD	A,(HL)		;FETCH CURRENT CHARACTER
	CP	' '		;TEST IF A SPACE CHARACTER
	JR	Z,LSMATA	;ALL DONE IF IT IS
TESTEX:	POP	DE		;RECOVER LIST LINE POINTER
	POP	HL		;RECOVER INPUT STRING ADDRESS
	JR	TSTCNL		;GET NEXT LIST AND RETEST
;
;
; OVERLAY REQUEST 60 - PARSE COMMAND ARGUMENTS
; ENTRY:  HL      - POINTER TO COMMAND LINE
;507D
PARSEA:	LD	A,(HL)		;GET CHARACTER FROM LINE
	CP	CR		;TEST IF COMMAND STRING END
	RET	Z		;THEN NOTHING TO DO
	CP	'('		;TEST IF OPENING BRACKET
	JR	Z,SCNBRA	;THEN HANDLE THE ARGUMENT
	CP	' '		;TEST IF A SPACE CHARACTER
	JR	Z,SKIPSP	;THEN SKIP THE SPACE
	OR	A		;ELSE SET ERROR FLAG
	RET
;
;
; SKIP CURRENT COMMAND LINE CHARACTER
;058B
SKIPSP:	INC	HL		;BUMP TO NEXT CHARACTER
	JR	PARSEA		;THEN CONTINUE PARSING
;
;
; SCAN COMMAND ARGUMENT WITHIN BRACKETS
; ENTRY:  HL      - COMMAND LINE POINTER
;508E
SCNBRA:	PUSH	DE		;SAVE DCB POINTER
	LD	B,6		;LOAD BUFFER LENGTH TO B
	LD	DE,ARGBUF	;POINT AT ARGUMENT BUFFER
	INC	HL		;INCREMENT POINTER PAST '('
	CALL	VALCPY		;ARGUMENT STRING TO BUFFER
	DEC	HL		;BACKUP TO TERMINATOR
	POP	DE		;RECOVER BUFFER POINTER
	RET	NZ		;ERROR IF NO COPIED CHARACTERS
	PUSH	DE		;SAVE DCB POINTER AGAIN
	LD	B,D		;BUFFER POINTER MSB TO B
	LD	C,E		;BUFFER POINTER LSB TO C
	LD	DE,ARGBUF	;POINT AT ARGUMENT BUFFER
	CALL	TSTCMD		;SCAN FOR ARGUMENT HEADER
	JR	Z,PARSAR	;SKIP IF HEADER FOUND
SCNBRX:	POP	DE		;ELSE RECOVER DCB POINTER
	RET
;
;
; ARGUMENT HEADER FOUND - PARSE THE ARGUMENT
; ENTRY:  DE      - ARGUMENT STORAGE
;         HL      - COMMAND LINE POINTER
;         ZF      - RESET IF MORE ARGUMENTS
;50A8
PARSAR:	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	'='		;TEST FOR EQUALS SIGN
	JR	Z,EVANUM	;THEN GET FOLLOWING NUMBER
	LD	BC,-1		;VALUE RETURNED IF NO NUMBER
ARGSTO:	LD	A,C		;GET ARGUMENT VALUE LSB
	LD	(DE),A		;STORE THE BYTE
	INC	DE		;BUMP STORAGE POINTER
	LD	A,B		;GET ARGUMENT VALUE MSB
	LD	(DE),A		;STORE THE BYTE
	POP	DE		;RECOVER STORAGE POINTER
	LD	A,(HL)		;GET COMMAND CHARACTER
	CP	','		;TEST IF A COMMA SEPERATOR
	JR	Z,SCNBRA	;THEN MORE ARGUMENTS
	CP	')'		;TEST IF END OF PARAMETER
	RET	NZ		;RETURN IF NOT TERMINATOR
	INC	HL		;ELSE BUMP LINE POINTER
	XOR	A		;SIGNAL GOOD STATUS
	RET
;
;
; PARSE A NUMBER FOLLOWING AN EQUALS SIGN
;50C1
EVANUM:	INC	HL		;BUMP COMMAND LINE POINTER
	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	'X'		;TEST FOR HEXADECIMAL PREFIX
	JR	Z,EVAHEX	;THEN GO PARSE THE NUMBER
	CP	'A'		;TEST IF ALPHABETIC
	JR	C,EVADEC	;CONTINUE IF POSSIBLY NUMERIC
	CALL	PARSFL		;ELSE PARSE COMMAND LINE FLAGS
	JR	Z,ARGSTO	;THEN GO STORE ARGUMENT
	JR	SCNBRX		;INVALID ENTRY, SO ABORT
;
;
; HEXADECIMAL NUMBER INDICATED - SKIP PAST 'X' AND EVALUE IT
;50D2
EVAHEX:	INC	HL		;BUMP PAST THE CHARACTER
	CALL	GETHEX		;EVALUATE HEXADECIMAL
	JR	Z,ARGSTO	;DONE IF VALID NUMBER
	JR	SCNBRX		;ELSE ABORT SEQUENCE
;
;
; A DECIMAL NUMBER HAS BEEN INDICATED - EVALUE IT
;50DA
EVADEC:	CALL	GETDEC		;EVALUATE DECIMAL
	JR	ARGSTO		;THEN GO STORE ARGUMENT
;
;
; PARSE COMMAND LINE ARGUMENT FOR AFFIRMATIVE OR NEGATIVE
; ENTRY:  HL      - COMMAND LINE POINTER
; EXIT:   A       - TERMINATING CHARACTER
;         BC      - TRUE (-1) OR FALSE (0)
;         HL      - UPDATED COMMAND LINE POINTER
;50DF
PARSFL:	LD	BC,0		;ZERO RESULT REGISTER
	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	'Y'		;TEST FOR AFFIRMATIVE
	JR	Z,PARSFT	;THEN GO FLAG TRUE
	CP	'N'		;TEST FOR NEGATIVE
	JR	Z,PARSFF	;THEN GO FLAG FALSE
	CP	'O'		;TEST IF 'ON' OR 'OF'
	RET	NZ		;DONE IF NEITHER
	INC	HL		;BUMP COMMAND LINE POINTER
	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	'F'		;TEST IF 'OF' FOR NEGATIVE
	JR	Z,PARSFF	;THEN FLAG FALSE
	CP	'N'		;TEST FOR 'ON' FOR AFFIRMATIVE
	RET	NZ		;DONE IF NEITHER
PARSFT:	LD	BC,-1		;LOAD A TRUE FLAG
PARSFF:	INC	HL		;BUMP COMMAND LINE POINTER
	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	')'		;TEST FOR CLOSING PARENTHESIS
	RET	Z		;ALL DONE IF IT IS
	CP	','		;TEST FOR MORE ARGUMENTS
	RET	Z		;ALL DONE IF IT IS
	JR	PARSFF		;LOOP FOR EITHER CHARACTER
;
;
; GET A DECIMAL NUMBER FROM THE COMMAND LINE
; ENTRY:  HL      - COMMAND LINE POINTER
; EXIT:   BC      - BINARY RESULT OF CONVERSION
;         HL      - INCREMENTED PAST ASCII DECIMAL NUMBER
;5104
GETDEC:	LD	BC,0		;ZERO RESULT REGISTER
GETDLP:	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	SUB	'0'		;REMOVE ASCII BIAS
	RET	C		;ALL DONE IF NOT NUMERIC ASCII
	CP	10		;TEST IF VALID DECIMAL DIGIT
	RET	NC		;ALL DONE IF IT ISN'T
	PUSH	HL		;SAVE COMMAND LINE POINTER
	LD	H,B		;GET NUMBER MSB TO H
	LD	L,C		;GET NUMBER LSB TO L
	ADD	HL,HL		;MULTIPLY BY TWO
	ADD	HL,HL		;MULTIPLY BY FOUR
	ADD	HL,BC		;MULTIPLY BY FIVE
	ADD	HL,HL		;MULTIPLY BY TEN
	LD	B,0		;ZERO B REGISTER
	LD	C,A		;GET ONES DIGIT TO C
	ADD	HL,BC		;MERGE IN NEW ONES DIGIT
	LD	B,H		;COPY RESULT MSB TO B
	LD	C,L		;COPY RESULT LSB TO C
	POP	HL		;RECOVER COMMAND LINE POINTER
	INC	HL		;BUMP COMMAND LINE POINTER
	JR	GETDLP		;THEN LOOP FOR NEXT DIGIT
;
;
; GET AN HEXADECIMAL NUMBER DELIMITED BY AN "'" CHARACTER
;511F
GETHEX:	LD	BC,0		;ZERO RESULT REGISTER
	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	"'"		;TEST IF VALID DELIMITER
	RET	NZ		;ABORT IF NOT VALID
	INC	HL		;ELSE BUMP COMMAND POINTER
;
;
; PROCESS AN HEXADECIMAL NUMBER TERMINATED BY AN "'" CHARACTER
;5127
GETHLP:	LD	A,(HL)		;GET LINE CHARACTER
	SUB	'0'		;REMOVE DECIMAL ASCII BIAS
	JR	C,GETHER	;SKIP IF NOT DECIMAL
	CP	10		;TEST IF DECIMAL DIGIT
	JR	C,GETHDI	;CONTINUE IF IT IS
	SUB	7		;SUBTRACT HEXADECIMAL BIAS
	CP	16		;TEST IF HEXADECIMAL DIGIT
	JR	C,GETHDI	;CONTINUE IF IT IS
GETHER:	LD	A,(HL)		;GET LINE CHARACTER
	CP	"'"		;TEST IF HEX TERMINATOR
	INC	HL		;BUMP COMMAND LINE INDEX
	RET	Z		;ALL DONE IF IT IS
	DEC	HL		;BACKUP COMMAND LINE POINTER
	XOR	A		;FLAG AN INVALID NUMBER
	RET
;
;
; WE HAVE A VALID HEXADECIMAL DIGIT
;513E
GETHDI:	PUSH	HL		;SAVE COMMAND LINE POINTER
	LD	H,B		;GET NUMBER MSB TO H
	LD	L,C		;GET NUMBER LSB TO L
	ADD	HL,HL		;MULTIPLY BY TWO
	ADD	HL,HL		;MULTIPLY BY FOUR
	ADD	HL,HL		;MULTIPLY BY EIGHT
	ADD	HL,HL		;MULTIPLY BY SIXTEEN
	LD	B,H		;COPY RESULT MSB TO B
	ADD	A,L		;ADD LSB TO NEW DIGIT
	LD	C,A		;COPY LS DIGIT TO C
	POP	HL		;RECOVER COMMAND LINE POINTER
	INC	HL		;BUMP THE POINTER
	JR	GETHLP		;THEN LOOP FOR NEXT DIGIT
;
;
; 'BASIC2' - EXECUTE LEVEL II ROM BASIC
;514C
BASTWO:	LD	HL,IPLINI	;POINT AT INIT VALUES IN ROM
	LD	DE,TNXVEC	;COMMUNICATIONS REGION START
	LD	BC,IPLENL	;NUMBER OF BYTES TO MOVE
	LDIR			;SET UP THE REGION
	XOR	A		;ZERO THE ACCUMULATOR
	LD	B,39		;NUMBER OF LOCATIONS TO ZERO
BASTWZ:	LD	(DE),A		;CLEAR A LOCATION
	INC	DE		;BUMP THE POINTER
	DJNZ	BASTWZ		;ZERO ALL THE LOCATIONS
	DI			;NO INTERRUPTIONS ALLOWED
	JP	POWRES		;GO ENTER LEVEL II BASIC
;
;
; 'DEBUG' - EXECUTE SYSTEM DEBUGGER
;5162
DEBUGS:	CALL	GETARG		;GET COMMAND LINE ARGUMENT
	LD	HL,SYSCON	;POINT AT CONDITION FLAGS
	DI			;NO INTERRUPTIONS ALLOWED
	JR	Z,DEBUNA	;SKIP IF NO ARGUMENT
	SET	7,(HL)		;ELSE SET DEBUG ACTIVE FLAG
	LD	HL,LDBVEC	;POINT AT RST VECTOR
	LD	A,0C3H		;LOAD A 'JP' OP-CODE
	LD	(DEBUGF+1),HL	;STORE VECTOR ADDRESS
	LD	(DEBUGF),A	;STORE 'JP' OP-CODE
	LD	A,0CDH		;LOAD A 'CALL' OP-CODE
DEBUSE:	LD	(ERRENT+1),HL	;SET ERROR HANDLER ADDRESS
	EI			;WE CAN SAFELY INTERRUPT NOW
	LD	(ERRENT),A	;STORE 'CALL' AT ERROR HANDLER
	JP	NORMEN		;ENTER DOS COMMAND PROCESSOR
DEBUNA:	RES	7,(HL)		;RESET DEBUG ACTIVE FLAG
	XOR	A		;ZERO ACCUMULATOR
	LD	(DEBUGF),A	;DISABLE DEBUGGER
	LD	A,3EH		;LOAD A 'LD' OP-CODE
	LD	HL,0EFH*256+0A3H;OVERLAY CODE AND 'RST 28H'
	JR	DEBUSE		;SET UP ERROR HANDLER
;
;
; 'TRACE' - EXECUTE SYSTEM TRACE
;5191
TRACES:	CALL	GETARG		;GET EVENTUAL ARGUMENT
	LD	DE,TRATSK	;POINT AT 'TRACE' TASK
	LD	A,11		;LOAD TASK NUMBER
	JP	Z,REMTSK	;REMOVE TASK IF 'OFF' FLAG
	JP	ADDTSK		;ADD TASK TO INTERRUPT LIST
;
;
; GET PARAMETER(S) WITHIN PARENTHESES, SEPERATED BY COMMAS
; ENTRY:  HL      - POINTER TO COMMAND LINE
;519F
GETARL:	INC	HL		;BUMP COMMAND LINE POINTER
;
;
; GET PARAMETER(S) WITHIN BRACKETS, SEPERATED BY COMMAS
; ENTRY:  HL      - POINTER TO COMMAND LINE
; EXIT:   BC      - THE BINARY RESULT
;         HL      - INCREMENTED TO RIGHT CLOSING BRACKET
;         ZF      - SET IF RESULT IS ZERO
;51A0
GETARG:	LD	A,(HL)		;GET CHARACTER FROM STRING
	CP	' '		;TEST IF SPACE CHARACTER
	JR	Z,GETARL	;SKIP ALL SPACES
	CP	'('		;TEST IF A BRACKET
	RET	NZ		;ALL DONE IF NOT
	INC	HL		;BUMP COMMAND LINE POINTER
	CALL	PARSFL		;PARSE THE ARGUMENT(S)
	LD	A,B		;GET RESULT MSB TO A
	OR	A		;TEST IF RESULT ZERO
	RET
;
; COMMAND ARGUMENT STRING BUFFER
;51AF
ARGBUF	Ds	6		;RESERVE THE SPACE
;
;
; EXECUTABLE CODE EXTENSION, DOS PROMPT AND ERROR MESSAGE
;
	Org	051B5H
;
CMDEXM	Db	'CMD'
DOSREM	Db	LF,'DOS READY',CR
SYNERM	Db	'WHAT?',CR
;
	End	OVRL01
