	Title	'TRSDOS 2.3 Disk Operating System'
;
;
; TRSDOS DISK OPERATING SYSTEM, VERSION 2.3
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON 21.01.2022
;
; PART 2 - OVERLAY 2 - FILE OPEN AND CREATE
;
;
; DEFINE IF PATCHES ARE ACTIVE
;
PATCHG	Equ	  0		;PATCHES ACTIVE
;
;
; ASCII EQUATES
;
CR	Equ	 13		;CARRIAGE RETURN
;
;
; FLOPPY DISK CONSTANTS
;
MAXDRV	Equ	  4		;MAX NUMBER OF DRIVES
;
;
; WESTERN DIGITAL WD1771 DISK CONTROLLER COMMAND CODES
;
WDFORC	Equ	11010000B	;FORCE INTERRUPT
;
;
; INPUT/OUTPUT PORT ADDRESS DEFINITIONS
;
CSTREG	Equ	037ECH		;FLOPPY STATUS/COMMAND REGISTER
;
;
; STORAGE LOCATIONS IN TRSDOS NUCLEUS (SYS0/SYS)
;
RANDOM	Equ	04040H		;RANDOM NUMBER SEED
DIRIDX	Equ	04ABEH		;DIRECTORY SECTOR INDEX
GATBUF	Equ	04D00H		;SYSTEM SECTOR BUFFER
;
;
; FUNCTIONS ADDRESSES IN TRSDOS NUCLEUS (SYS0/SYS)
;
SELDRV	Equ	04600H		;SELECT A DISK DRIVE
WRDSEC	Equ	046EFH		;WRITE A DIRECTORY SECTOR
REGSAV	Equ	04896H		;SAVE CALLER'S REGISTERS
REDDIR	Equ	04AC1H		;READ DIRECTORY SECTOR
WRTDIR	Equ	04AD6H		;WRITE DIRECTORY SECTOR
DDREAD	Equ	04B35H		;READ A SECTOR TO BUFFER
TRKDIR	Equ	04B55H		;GET DIRECTORY TACK NUMBER
;
;
; PROGRAM MODULE NAME STRING
;
	Nam	'SYS2  '
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING
;
	Rem	CR
	Rem	'* * * N O T I C E * * *',CR
	Rem	'* PROPRIETARY PROGRAM *',CR
	Rem	'* COPYRIGHT (c) 1979  *',CR
	Rem	'* BY TANDY CORPORATION*',CR
	Rem	'*  FORT WORTH, TEXAS  *',CR
	Rem	'* ALL RIGHTS RESERVED *',CR
	Rem	'* * * N O T I C E * * *',CR
;
;
	Org	04E00H
;
OVRL02:	AND	01110000B	;MASK TO REQUEST BITS
	CP	10H		;REQUEST 10 - OPEN FILE
	JP	Z,OPNFIL	;THEN GO HANDLE THE REQUEST
	CP	20H		;REQUEST 20 - INIT FILE
	JP	Z,INIFIL	;THEN GO HANDLE THE REQUEST
	CP	30H		;REQUEST 30 - BUILD OVERFLOW
	JP	Z,BLDOFL	;THEN GO HANDLE THE REQUEST
	RET
;
;
; OVERLAY REQUEST 10 - OPEN A FILE
;4E12
OPNFIL:	CALL	REGSAV		;SAVE ALL REGISTERS
;
;
; BEGIN OPEN FILE PROCESSIBNG
;4E15
OPNPRO:	LD	A,B		;GET RECORD LENGTH TO A
	LD	(RECLEN),A	;SAVE THE RECORD LENGTH
	LD	(BUFADR),HL	;SAVE SECTOR BUFFER ADDRESS
	PUSH	IX		;PUT DCB ADDRESS ON THE STACK
	POP	HL		;COPY DCB ADDRESS TO HL
	CALL	PARSAL		;COPY FILE NAME TO LOCAL DCB
	RET	NZ		;ABORT IF ILLEGAL CHARACTERS
	LD	HL,FILNAM	;POINT AT NAME AND EXTENSION
	CALL	FSHASH		;COMPUTE THE HASH CODE
	LD	(NAMHAS),A	;SAVE THE HASH FOR LATER
	LD	DE,PASSWD	;POINT AT PASSWORD
	CALL	PWHASH		;COMPUTE PASSWORD HASH
	LD	(MASHAS),HL	;STORE AS MASTER PASSWORD HASH
	LD	(FILHAS),HL	;STORE AS FILE PASSWORD HASH
	LD	A,(DRVCOD)	;GET DRIVE NUMBER TO A
	LD	C,A		;COPY DRIVE CODE TO C
	INC	A		;TEST IF DRIVE SPECIFIED
	JR	NZ,GOTDRV	;SKIP IF IT IS SPECIFIED
	LD	C,A		;GET DRIVE NUMBER TO C
GOTDRV:	CALL	TSTRDY		;TEST DRIVE READY STATUS
	JR	NZ,NODRIV	;SKIP IF NOT READY OR PRESENT
	CALL	REDHIT		;READ 'HIT' SECTOR FROM DISK
	RET	NZ		;ABORT IF READ ERROR
HASHSR:	LD	A,(HL)		;GET HASH CODE FROM 'HIT'
	OR	A		;SET STATUS FLAGS FROM 'HIT'
	JR	Z,EMPTYS	;SKIP IF SLOT IS EMPTY
	CP	0		;COMPARE WITH COMPUTED HASH
NAMHAS	Equ	$-1		;STORAGE FOR FILE NAME HASH
	JR	Z,HASHFN	;SKIP IF HASH CODES MATCH
EMPTYS:	INC	L		;ELSE BUMP TO NEXT ENTRY
	JR	NZ,HASHSR	;LOOP IF NOT TABLE END
NODRIV:	LD	A,(DRVCOD)	;GET DRIVE CODE TO A
	INC	A		;TEST IF DRIVE SPECIFIED
	JR	NZ,NOTFND	;FILE NOT FOUND IF SO
	INC	C		;ELSE BUMP DRIVE NUMBER
	LD	A,C		;GET DRIVE NUMBER TO A
	CP	MAXDRV		;TEST IF ALL DRIVES SEARCHED
	JR	C,GOTDRV	;LOOP IF DRIVE(S) REMAINING
;
;
; FILE NOT FOUND ERROR ROUTINE
;4E60
NOTFND:	LD	A,18H		;LOAD ERROR CODE
	OR	A		;FLAG ERROR CONDITION
	RET
;
;
; CLEAR STACK AND PREPARE TO SEARCH 'HIT'
;4E64
SRCHIT:	POP	BC		;CLEAR STACK
	POP	HL		;CLEAR STACK
	POP	BC		;RESTORE DRIVE NUMBER TO C
	POP	HL		;RESTORE HASH SECTOR INDEX
	JR	EMPTYS		;GO TEST NEXT HASH VALUE
;
;
; MATCHING HASH CODE FOUND
; READ DIRECTORY SECTOR CONTAINING FILE ENTRY
;4E6A
HASHFN:	PUSH	HL		;SAVE HASH CODE ADDRESS
	PUSH	BC		;SAVE UNIT NUMBER
	LD	B,L		;INDEX TO DIRECTORY ENTRY
	CALL	REDDIR		;READ DIRECTORY SECTOR
	JR	Z,LOCATE	;CONTINUE IF NO ERROR
	POP	BC		;RECOVE UNIT NUMBER
	POP	HL		;RECOVER HASH CODE ADDRESS
	RET
;
;
; LOCATE FILE ENTRY IN DIRECTORY SECTOR
;4E75
LOCATE:	PUSH	HL		;SAVE FILE ENTRY ADDRESS
	PUSH	BC		;SAVE INDEX AND UNIT NUMBER
	BIT	7,(HL)		;TEST IF PRIMARY ENTRY
	JR	NZ,SRCHIT	;SKIP IF NOT PRIMARY
	LD	A,5		;LOAD OFFSET TO FILE NAME
	ADD	A,L		;INDEX TO THE FILE NAME
	LD	L,A		;UPDATE FILE NAME ADDRESS
	LD	DE,FILNAM	;ADDRESS OF LOCAL DCB
	LD	B,11		;LOAD FILE SPEC LENGTH
LOCATL:	LD	A,(DE)		;GET LOCAL NAME CHARACTER
	CP	(HL)		;TEST FOR DIRECTORY MATCH
	JR	NZ,SRCHIT	;NEXT ENTRY IF MISMATCH
	INC	HL		;BUMP DIRECTORY ADDRESS
	INC	DE		;BUMP LOCAL DCB ADDRESS
	DJNZ	LOCATL		;LOOP UNTIL ALL MATCHED
;
;
; FILENAME LOCATED IN DIRECTORY SECTOR
; ISOLATE ACCESS PERMISSIONS AND PASSWORD ENCODES
;
	POP	BC		;RESTORE UNIT NUMBER
	LD	A,C		;COPY UNIT NUMBER TO A
	LD	(DRVCOD),A	;SAVE THE UNIT FOR LATER
	POP	HL		;DIRECTORY ENTRY SECTOR ADDRESS
	POP	AF		;CLEAN UP THE STACK
	POP	AF		;CLEAN UP THE STACK
	PUSH	BC		;SAVE INDEX AND UNIT NUMBER
	PUSH	HL		;SAVE DIRECTORY ENTRY ADDRESS
	LD	A,(HL)		;GET FIRST BYTE OF ENTRY
	AND	00000111B	;ISOLATE PERMISSION BITS
	LD	C,A		;SAVE PERMISSIONS IN C
	LD	B,00000000B	;NO RESTRICTIONS PERMISSIONS
	LD	A,16		;LOAD OFFSET TO PASSWORD
	ADD	A,L		;ADD OFFSET TO PASSWORD
	LD	L,A		;POINT HL AT UPDATE PASSWORD
	LD	DE,(FILHAS)	;GET HASHED PASSWORD TO DE
	PUSH	HL		;SAVE DIRECTORY ENTRY ADDRESS
	LD	HL,061A2H	;LOAD 'UBETT' PASSWORD ENCODE
	XOR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;TEST IF PASSWORDS MATCH
	POP	HL		;RESTORE DIR ENTRY ADDRESS
	JR	Z,GRANTD	;CONTINUE IF ACCESS GRANTED
	LD	A,C		;GET PERMISSION FLAGS TO A
	CP	00000111B	;TEST FOR NO PERMISSIONS
	JR	Z,DENIED	;THEN ACCESS IS DENIED
	LD	A,(HL)		;GET PASSWORD ENCODE LSB
	INC	HL		;BUMP TO ENCODE MSB
	PUSH	HL		;SAVE DIRECTORY ENTRY ADDRESS
	LD	H,(HL)		;GET PASSWORD ENCODE MSB
	LD	L,A		;HL HAS THE PASSWORD HASH CODE
	XOR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;TEST IF PASSWORDS MATCH
	POP	HL		;RECOVER DIR ENTRY ADDRESS
	JR	Z,GRANTD	;ACCESS GRANTED IF MATCH
	INC	HL		;BUMP TO UPDATE PASSWORD
	LD	B,C		;GET PERMISSIONS TO B
	LD	A,(HL)		;GET PASSWORD ENCODE LSB
	INC	HL		;BUMP TO ENCODE MSB
	LD	H,(HL)		;GET PASSWORD ENCODE MSB
	LD	L,A		;HL HAS THE PASSWORD ENCODE
	XOR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;TEST IF PASSWORDS MATCH
	JR	Z,GRANTD	;ACCESS GRANTED IF MATCH
;
;
; FILE ACCESS DENIED ERROR ROUTINE
;4EC9
DENIED:	POP	HL		;GET DIRECTORY ENTRY ADDRESS
	POP	BC		;GET INDEX AND UNIT NUMBER
	LD	A,19H		;LOAD ERROR CODE TO A
	OR	A		;FLAG ERROR CONDITION
	RET
;
;
; ACCESS GRANTED SO FILL OUT DEVICE CONTRIL BLOCK
;4ECF
GRANTD:	POP	HL		;GET DIRECTORY ENTRY ADDRESS
	LD	A,B		;GET ACCESS FLAGS TO A
	LD	(ACESSF),A	;SAVE THE ACCESS FLAGS
	POP	BC		;GET INDEX AND UNIT NUMBER
	JP	FILDCB		;FILL OUT DEVICE CONTROL BLOCK
;
;
; OVERLAY REQUEST 20 - INIT A FILE
;4ED8
INIFIL:	CALL	REGSAV		;SAVE ALL REGISTERS
	CALL	OPNPRO		;TRY TO OPEN THE FILE
	RET	Z		;DONE IF FILE ALREADY EXISTS
	CP	18H		;TEST IF FILE NOT FOUND
	RET	NZ		;ABORT IF ANY OTHER ERROR
;
;
; FILE DOES NOT EXIST SO CREATE THE ENTRY
;
	LD	A,00010000B	;SET ASSIGNED TO FILE FLAG
	LD	(ACCESF),A	;ENTRY ASSIGNED, TOTAL ACCESS
	LD	A,(DRVCOD)	;GET DRIVE SPECIFICATION
	LD	C,A		;SAVE NUMBER IN C REGISTER
	INC	A		;TEST IF DRIVE SPECIFIED
	JR	NZ,INIFLP	;SKIP IF UNIT SPECIFIED
	LD	C,A		;COPY UNIT NUMBER TO C
INIFLP:	CALL	TSTRDY		;TEST DRIVE READY STATUS
	JR	NZ,INIFNR	;SKIP IF NOT READY OR PRESENT
	JR	C,INIFNR	;SKIP IF WRITE PROTECTED
	CALL	REDHIT		;READ 'HIT' SECTOR FROM DISK
	RET	NZ		;ABORT IF READ ERROR
	CALL	HITHOL		;FIND AVAILABLE SLOT IN 'HIT'
	JR	Z,SLOTFO	;SKIP IF SLOT WAS FOUND
INIFNR:	LD	A,(DRVCOD)	;NONE LEFT, GET DRIVE SPEC
	INC	A		;TEST IF DRIVE SPECIFIED
	JR	NZ,INIFDF	;DIRECTORY FULL IF SO
	INC	C		;BUMP TO NEXT DRIVE
	LD	A,C		;GET DRIVE NUMBER TO A
	CP	MAXDRV		;TEST IF ALL DRIVES TESTED
	JR	C,INIFLP	;IF NOT, THEN LOOP
;
;
; DIRECTORY IS FULL
;4F0B
INIFDF:	LD	A,1AH		;DIRECTORY FULL ERROR CODE
	RET
;
;
; AN AVAILABLE SLOT WAS FOUND IN THE 'HIT' SECTOR
;4F0E
SLOTFO:	LD	B,L		;GET DIRECTORY SECTOR TO B
	LD	A,(NAMHAS)	;GET HASH CODE TO A
	LD	(HL),A		;SAVE IN 'HIT' SECTOR
	CALL	WRTHIT		;WRITE 'HIT' SECTOR TO DISK
	RET	NZ		;ABORT IF WRITE ERROR
	CALL	REDDIR		;READ DIRECTORY SECTOR
	RET	NZ		;ABORT IF READ ERROR
	PUSH	HL		;SAVE DIR ENTRY START ADDRESS
	LD	(HL),0		;STORE ACCESS FLAGS
ACCESF	Equ	$-1		;ENTRY ACCESS FLAGS
	INC	HL		;BUMP TO SECOND BYTE
	LD	(HL),0		;CLEAR OVERFLOW POINTER
	INC	HL		;BUMP TO THIRD BYTE
	LD	(HL),0		;CLEAR RESERVED BYTE
	INC	HL		;BUMP TO FOURTH BYTE
	LD	(HL),0		;CLEAR EOF OFFSET BYTE
	INC	HL		;BUMP TO FIFTH BYTE
	LD	A,(RECLEN)	;GET RECORD LENGTH
	LD	(HL),A		;SAVE IN DIRECTORY ENTRY
	INC	HL		;BUMP TO SIXTH BYTE
	PUSH	BC		;SAVE BC REGISTER
	LD	BC,15		;NUMBER OF BYTES TO COPY
	EX	DE,HL		;SWAP DIRECTORY POINTER TO DE
	LD	HL,FILNAM	;POINT AT FILE NAME BUFFER
	LDIR			;COPY FILE NAME TO ENTRY
	EX	DE,HL		;SWAP DIRECTORY POINTER TO HL
	LD	(HL),0		;CLEAR EOF SECTOR NUMBER LSB
	INC	HL		;BUMP TO SIXTEENTH BYTE
	LD	(HL),0		;CLEAR EOF SECTOR NUMBER MSB
	INC	HL		;BUMP TO SEVENTEENTH BYTE
	LD	B,10		;NUMBER OF BYTES TO INITIALIZE
GAPFIL:	LD	(HL),-1		;STORE ALL BITS SET IN GAP
	INC	HL		;BUMP TO NEXT ENTRY
	DJNZ	GAPFIL		;LOOP UNTIL ALL GAP'S FILLED
	POP	BC		;RECOVER 'HIT' SLOT INDEX
	CALL	WRTDIR		;WRITE DIRECTORY SECTOR
	POP	HL		;RECOVER DIR ENTRY ADDRESS
	RET	NZ		;ABORT IF WRITE ERROR
	CALL	FILDCB		;INIT DCB IN USER AREA
	SCF			;FLAG NOT PREVIOUSLY OPENED
	RET
;
;
; OVERLAY REQUEST 30 - BUILD AN OVERFLOW DIRECTORY ENTRY
;   1. FIND AN AVAILABLE SLOT IN THE 'HIT' SECTOR
;   2. MOVE FILE HASH CODE TO 'HIT' SLOT LOCATED ABOVE
;   3. WRITE UPDATED 'HIT'
;   4. READ DIRECTORY SECTOR FOR 'HIT' SLOT ASSIGNED
;   5. INITIALIZE DIRECTORY SECTOR ENTRY FOR 'HIT' ASSIGNED
;      IN STEP ONE, AS AN OVERFLOW ENTRY
;   6. WRITE DIRECTORY SECTOR CONTAINING OVERFLOW ENTRY
;   7. READ DIRECTORY SECTOR CONTAINING PRIMARY ENTRY
;   8. UPDATE PRIMARY ENTRY WITH OVERFLOW FLAG AND POINTER
;   9. WRITE UPDATED PRIMARY ENTRY
;4F50
BLDOFL:	LD	C,(IX+06)	;GET DRIVE NUMBER TO C
	CALL	REDHIT		;READ 'HIT' SECTOR FROM DISK
	RET	NZ		;ABORT IF READ ERROR
	LD	A,(IX+07)	;GET DIRECTORY SECTOR OFFSET
	CALL	HITHNB		;FIND AVAILABLE HOLE IN 'HIT'
	LD	A,01EH		;DIRECTORY FULL ERROR CODE
	RET	NZ		;ABORT IF NO AVAILABLE SPACE
	LD	B,L		;NEXT AVAILABLE 'HIT' LOCATION
	LD	A,L		;COPY LOCATION TO A
	LD	(OFLENT),A	;SAVE OVERFLOW ENTRY ADDRESS
	LD	D,H		;'HIT' BUFFER ADDRESS MSB
	LD	E,(IX+07)	;'HIT' BUFFER ADDRESS LSB
	LD	A,(DE)		;GET FILE HASH CODE TO A
	LD	(HL),A		;COPY TO OVERFLOW ENTRY
	CALL	WRTHIT		;WRITE 'HIT' SECTOR TO DISK
	RET	NZ		;ABORT IF WRITE ERROR
	CALL	REDDIR		;READ DIRECTORY SECTOR
	RET	NZ		;ABORT IF WRITE ERROR
	LD	(HL),90H	;FLAG AS ASSIGNED/OVERFLOW
	INC	L		;BUMP TO DIR ENTRY BYTE TWO
	PUSH	BC		;SAVE UNIT NUMBER
	LD	A,(DIRIDX)	;GET DIRECTORY SECTOR INDEX
	LD	(HL),A		;SAVE IN ENTRY SECOND BYTE
	INC	L		;BUMP TO ENTRY BYTE THREE
	LD	B,20		;NUMBER OF BYTES TO ZERO
BLDOFZ:	LD	(HL),0		;STORE ZERO IN ENTRY
	INC	L		;BUMP TO NEXT ENTRY BYTE
	DJNZ	BLDOFZ		;LOOP UNTIL ALL ZEROED
	PUSH	HL		;SAVE FIRST GAP ADDRESS
	LD	B,10		;NUMBER OF BYTES TO INITIALIZE
BLDOFS:	LD	(HL),-1		;INIT TO ALL BITS SET
	INC	L		;BUMP DIRECTORY INDEX
	DJNZ	BLDOFS		;LOOP UNTIL GAP'S INITIALIZED
	POP	DE		;GET FIRST GAP ADDRESS TO DE
	INC	DE		;ADDRESS OF NUMBER OF GRANS
	POP	BC		;RECOVER UNIT NUMBER
	CALL	WRTDIR		;WRITE DIRECTORY SECTOR
	RET	NZ		;ABORT IF WRITE ERROR
	LD	A,(DIRIDX)	;GET DIRECTORY SECTOR INDEX
	LD	B,A		;COPY THE INDEX TO B REGISTER
	CALL	REDDIR		;READ DIRECTORY SECTOR
	RET	NZ		;ABORT IF READ ERROR
	LD	A,L		;PRIMARY ENTRY ADDRESS
	ADD	A,30		;FIRST BYTE OF FIFTH GAP
	LD	L,A		;POINT HL AT THE GAP BYTE
	LD	(HL),0FEH	;SIGNAL AN OVERFLOW ENTRY
	INC	L		;POINT AT SECOND GAP BYTE
	LD	(HL),0		;SAVE POINTER TO OVERFLOW ENTRY
OFLENT	Equ	$-1		;OVERFLOW ENTRY POINTER
	CALL	WRTDIR		;WRITE DIRECTORY SECTOR
	RET
;
;
; FILL OUT DEVICE CONTROL BLOCK
; COPY PORTIONS OF PRIMARY ENTRY TO DEVICE CONTROL BLOCK
; ENTRY:  DE      - POINTER TO DIRECTORY ENTRY
;         IX      - POINTER TO DEVICE CONTROL BLOCK
;4FA7
FILDCB:	EX	DE,HL		;DIRECTORY ENTRY ADDRESS TO DE
	PUSH	IX		;PUT DCB ADDRESS ON THE STACK
	POP	HL		;COPY DCB ADDRESS TO HL
	LD	(HL),10000000B	;SIGNAL THAT THE FILE IS OPEN
	INC	HL		;BUMP TO RECORD LENGTH
	LD	A,0		;GET RECORD LENGTH TO A
RECLEN	Equ	$-1		;RECORD LENGTH STORAGE
	OR	A		;SET STATUS FLAGS FOR LENGTH
	LD	A,0		;LOAD ACCESS FLAGS
ACESSF	Equ	$-1		;ACCESS FLAGS STORAGE
	JR	Z,PHYSAC	;SKIP IF RECORD LENGTH ZERO
	OR	10000000B	;ELSE SIGNAL LOGICAL ACCESS
PHYSAC:	OR	00100000B	;FORCE READ ON FIRST ACCESS
	LD	(HL),A		;SAVE THE ACCESS FLAGS
	INC	HL		;BUMP TO UNUSED BYTE
	LD	(HL),0		;STORE A ZERO THERE
	INC	HL		;BUMP TO NEXT DCB BYTE
	PUSH	DE		;SAVE ORIGINAL DCB ADDRESS
	LD	DE,0		;SECTOR BUFFER ADDRESS TO DE
BUFADR	Equ	$-2		;SECTOR BUFFER POINTER STORAGE
	LD	(HL),E		;BUFFER ADDRESS LSB TO DCB
	INC	HL		;BUMP DCB POINTER
	LD	(HL),D		;BUFFER ADDRESS MSB TO DCB
	INC	HL		;BUMP DCB POINTER
	POP	DE		;RECOVER ORIGINAL DCB ADDRESS
	LD	(HL),0		;CURRENT RECORD END OFFSET
	INC	HL		;BUMP DCB POINTER
	LD	(HL),C		;STORE CURRENT DRIVE NUMBER
	INC	HL		;BUMP DCB POINTER
	LD	(HL),B		;SAVE OVERFLOW POINTER
	INC	HL		;BUMP DCB POINTER
	LD	A,3		;INDEX TO DIRECTORY EOF BYTE
	ADD	A,E		;ADD TO BASE OF DIRECTORY
	LD	E,A		;UPDATE SECTOR INDEX
	LD	A,(DE)		;LOAD EOF BYTE OFFSET
	LD	(HL),A		;SAVE EOF BYTE OFFSET
	INC	HL		;BUMP DCB POINTER
	INC	DE		;BUMP TO NEXT DIRECTORY BYTE
	LD	A,(RECLEN)	;LOAD RECORD LENGTH
	LD	(HL),A		;STORE BYTE IN DCB
	INC	HL		;BUMP DCB POINTER
	LD	(HL),0		;CLEAR NEXT RECORD LSB
	INC	HL		;BUMP DCB POINTER
	LD	(HL),0		;CLEAR NEXT RECORD MSB
	INC	HL		;BUMP DCB POINTER
	LD	A,16		;INDEX TO EOF SECTOR NUMBER
	ADD	A,E		;ADD TO BASE OF DIRECTORY
	LD	E,A		;UPDATE SECTOR INDEX
	LD	A,(DE)		;GET EOF SECTOR LSB
	LD	(HL),A		;SAVE IT IN THE DCB
	INC	HL		;BUMP DCB POINTER
;
	If	PATCHG		;PATCHES ACTIVE
	 CALL	BMPEOF		;COPY NUMBER OF SECTORS MSB
	Else			;ORIGINAL
	 INC	DE		;BUMP TO NUMBER OF SECTORS
	 LD	A,(DE)		;GET SECTOR COUNT TO A
	 LD	(HL),A		;SAVE IT IN THE DCB
	EndIf			;ALL DONE
;
	INC	HL		;BUMP DCB POINTER
	INC	DE		;BUMP TO FIRST TRACK ADDRESS
	LD	A,(DE)		;GET TRACK ADDRESS TO A
	LD	(HL),A		;STORE THE ADDRESS IN DCB
	INC	HL		;BUMP DCB POINTER
	INC	DE		;BUMP TO GRANULE COUNT
	LD	A,(DE)		;GET GRANULE COUNT TO A
	LD	(HL),A		;STORE THE COUNT IN DCB
	INC	HL		;TRACK NUMBER FOR SECOND GAP
	AND	00011111B	;ISOLATE CONSECUTIVE GRANULES
	INC	A		;COMPUTE TRUE COUNT
	LD	C,A		;GET TOTAL GRANULES TO C
	LD	B,0		;BC HAS THE TOTAL COUNT
	LD	A,4		;EXTENT PAIRS REMAINING
GRANCO:	PUSH	AF		;SAVE REMAINING COUNT
	INC	DE		;BUMP TO NEXT GAP
	LD	A,(DE)		;GET NEXT GAP FROM DIRECTORY
	CP	0FEH		;TEST FOR END OR OVERFLOW
	JR	NC,FILGAP	;SKIP IF END OR OVERFLOW
	LD	(HL),C		;PREVIOUS GAP TOTAL GRANS LSB
	INC	HL		;BUMP TO MSB
	LD	(HL),B		;PREVIOUS GAP TOTAL GRANS MSB
	INC	HL		;BUMP TO NEXT GAP START
	LD	A,(DE)		;GET NEXT GAP TRACK NUMBER
	LD	(HL),A		;SAVE TRACK NUMBER IN DCB
	INC	HL		;BUMP TO SECOND GAP IN DCB
	INC	DE		;BUMP TO COUNT IN DIR SECTOR
	LD	A,(DE)		;GET COUNT OF ASSIGNED GRANS
	LD	(HL),A		;SAVE THE COUNT IN THE DCB
	INC	HL		;BUMP TO LSB OF TOTALS IN DCB
	AND	00011111B	;ISOLATE THE COUNT
	INC	A		;GET TRUE GRANULE COUNT
	ADD	A,C		;FORM NEW TOTAL GRANULES
	LD	C,A		;COPY THE COUNT LSB TO C
	LD	A,B		;GET MSB OF GRANULE COUNT TO A
	ADC	A,0		;ADD ANY CARRY TO THE MSB
	LD	B,A		;COPY THE COUNT MSB TO B
	POP	AF		;RESTORE THE GAP COUNT
	DEC	A		;DECREMENT THE COUNT
	JR	NZ,GRANCO	;LOOP IF MORE TO COPY
	RET
;
;
; END OF GAP'S IN DIRECTORY HAVE BEEN REACHED FILL REMAINDER
; OF DEVICE CONTROL BLOCK GAP AREA WITH ALL BITS SET BYTES
;501C
FILGAP:	POP	AF		;NUMBER OF UNFILLED ENTRIES
	RLCA			;MULTIPLY BY TWO
	RLCA			;MULTIPLY BY FOUR
	LD	B,A		;COPY THE COUNT TO B
FILGAL:	LD	(HL),11111111B	;LOAD ALL BITS SET BYTE
	INC	HL		;BUMP TO NEXT ENTRY IN DCB
	DJNZ	FILGAL		;LOOP UNTIL ALL FILLED
	XOR	A		;RETURN CF RESET AND ZF SET
	RET
;
;
; PARSE FILE NAME, FILE EXTENSION, PASSWORD AND DRIVE
;5027
PARSAL:	LD	B,11		;FILE AND EXTENSION LENGTH
	LD	DE,FILNAM	;POINT AT STORAGE LOCATION
	LD	A,' '		;LOAD A SPACE CHARACTER
PARSFN:	LD	(DE),A		;STORE SPACE IN STORAGE
	INC	DE		;BUMP STORAGE POINTER
	DJNZ	PARSFN		;LOOP UNTIL STORAGE SET
	LD	B,8		;LOAD PASSWORD LENGTH
	LD	DE,PASSWD	;POINT AT STORAGE LOCATION
PARSPA:	LD	(DE),A		;STORE SPACE IN STORAGE
	INC	DE		;BUMP STORAGE POINTER
	DJNZ	PARSPA		;LOOP UNTIL STORAGE SET
	LD	A,-1		;FLAG DRIVE CODE UNSPECIFIED
	LD	(DRVCOD),A	;STORE THE DRIVE CODE
	LD	DE,FILNAM	;POINT AT STORAGE LOCATION
	LD	B,8		;LOAD MAXIMUM FILENAME LENGTH
	CALL	PARSES		;GO PARSE THE FILENAME
	LD	C,A		;TERMINATING CHARACTER TO C
	LD	A,B		;COPY CHARACTER COUNT TO A
	CP	8		;TEST IF ANY CHARACTERS PARSED
	JR	NZ,PARSEP	;CONTINUE IF AT LEAST ONE
	LD	A,13H		;ELSE LOAD ERROR CODE
	OR	A		;FLAG ERROR CONDITION
	RET
;
;
; PARSE FILE EXTENSION, PASSWORD AND DRIVE
;5052
PARSEP:	LD	A,C		;TERMINATING CHARACTER TO A
	CP	'/'		;TEST IF EXTENSION DELIMITER
	JR	NZ,PARSPW	;SKIP IF IT ISN'T
	LD	DE,FILEXT	;POINT AT STORAGE LOCATION
	LD	B,3		;LOAD MAXIMUM EXTENSION LENGTH
	CALL	PARSES		;PARSE FILE EXTENSION
PARSPW:	CP	'.'		;TEST IF PASSWORD DELIMITER
	JR	NZ,PARSDR	;SKIP IF IT ISN'T
	LD	DE,PASSWD	;POINT AT STORAGE LOCATION
	LD	B,8		;LOAD MAXIMUM PASSWORD LENGTH
	CALL	PARSES		;PARSE PASSWORD STRING
PARSDR:	CP	':'		;TEST IF DRIVE DELIMITER
	JR	NZ,PARSZE	;SKIP IF IT ISN'T
	LD	A,(HL)		;ELSE GET DRIVE CODE
	SUB	'0'		;REMOVE ASCII BIAS
	JR	C,PARSER	;ABORT IF INVALID CODE
	CP	MAXDRV		;TEST IF VALID DRIVE CODE
	JR	C,PARSDC	;CONTINUE IF VALID CODE
PARSER:	LD	A,20H		;ELSE LOAD ERROR CODE
	OR	A		;FLAG ERROR CONDITION
	RET
;
;
; VALID DRIVE CODE FOUND SO SAVE IT
; ENTRY:  A       - DRIVE CODE
;507C
PARSDC:	LD	(DRVCOD),A	;STORE THE DRIVE CODE
;
;
; NO DRIVE CODE FOUND - RETURN A ZERO BYTE
; EXIT:   A       - ZERO
;         ZF      - SET
;507F
PARSZE:	XOR	A		;FLAG SUCCESSFUL PARSE
	RET
;
;
; SCAN FILENAME OR PASSWORD STRING FOR INVALID CHARACTERS
; ENTRY:  B       - MAXIMUM BUMBER OF CHARACTERS
;         HL      - POINTER TO THE STRING
;         DE      - POINTER TO STORAGE BUFFER
; EXIT:   B       - REMAINING CHARACTER COUNT
;         HL      - POINTER TO TERMINATOR
;         DE      - POINTS PAST LAST BUFFER CHARACTER
;5081
PARSES:	LD	A,(HL)		;GET CHARACTER FROM STRING
	INC	HL		;BUMP STRING POINTER
	JR	PARSEA		;THEN START SCANNING
PARSEN:	LD	A,(HL)		;GET CHARACTER FROM STRING
	INC	HL		;BUMP STRING POINTER
	CP	'0'		;TEST IF NUMERIC CHARACTER
	RET	C		;ABORT IF NOT NUMERIC
	CP	'9'+1		;TEST IF NUMERIC CHARACTER
	JR	C,PARSEB	;SKIP IF CHARACTER NUMERIC
PARSEA:	CP	'A'		;TEST IF ALPHABETIC CHARACTER
	RET	C		;ABORT IF NOT ALPHABETIC
	CP	'Z'+1		;TEST IF ALPHABETIC CHARACTER
	RET	NC		;ABORT IF NOT ALPHABETIC
PARSEB:	LD	(DE),A		;STORE CHARACTER IN BUFFER
	INC	DE		;BUMP STORAGE BUFFER POINTER
	DJNZ	PARSEN		;LOOP UNTIL ALL SCANNED
	LD	A,(HL)		;LOAD CHARACTER FROM STRING
	INC	HL		;BUMP STRING POINTER
	RET
;
;
; COMPUTE A HASH CODE FOR A FILE
; EXCLUSIVE OR EACH CHARACTER OF FILE NAME WITH THE FOLLOWING
; CHARACTER, THEN MULTIPLY RESULT BY TWO AND USE AS CURRENT
; ENTRY:  HL      - POINTER TO FILE NAME AND EXTENSIOM
; EXIT:   A       - THE HASH CODE
;509B
FSHASH:	LD	B,11		;LOAD ITERATION COUNT
	LD	C,0		;INITIALIZE A MARK VALUE
FSHASL:	LD	A,(HL)		;GET CHARACTER FROM FILE NAME
	INC	HL		;BUMP FILE NAME POINTER
	XOR	C		;EXCLUSIVE OR WITH PREVIOUS
	RLCA			;MULTIPLY RESULT BY TWO
	LD	C,A		;SAVE TEMPORARY CODE
	DJNZ	FSHASL		;LOOP FOR ALL CHARACTERS
	LD	A,C		;GET FINAL HASH TO A
	OR	A		;TEST IF RESULT IS ZERO
	RET	NZ		;ALL DONE IF IT ISN'T
	INC	A		;ELSE FORCE A VALUE OF ONE
	RET
;
;
; FIND AN AVAILABLE HOLE IN THE 'HIT' SECTOR
; ENTRY:  HL      - POINTER TO LOADED 'HIT' SECTOR
; EXIT:   HL      - POINTER TO FREE 'HIT' ENTRY
;         ZF      - SET IF ENTRY FOUND
;50AB
HITHOL:	LD	A,(RANDOM)	;CHOOSE A RANDOM NUMBER
	AND	11100111B	;FORCE 00-07, 20-27, 40-47..
	CP	40H		;TEST IF BELOW 40
	JR	NC,HITHNB	;SKIP IF NOT BELOW
	OR	10000000B	;FORCE 80-87, A0-A7, C0-C7..
;
;
; FIND AN AVAILABLE HOLE IN THE 'HIT' SECTOR
; ENTRY:  A       - STARTING SEARCH INDEX
;         HL      - POINTER TO LOADED 'HIT' SECTOR
; EXIT:   HL      - POINTER TO FREE 'HIT' ENTRY
;         ZF      - SET IF ENTRY FOUND
;50B6
HITHNB:	LD	L,A		;FORM BEGINNING SEARCH IN HL
	CALL	HITHLP		;LOOK FOR AVAILABLE SLOT
	RET	Z		;ALL DONE IF ONE FOUND
	LD	L,40H		;SEARCH AGAIN FROM TABLE START
;
;
; FIND AN AVAILABLE HOLE IN THE 'HIT' SECTOR
; ENTRY:  HL      - POINTER TO LOADED 'HIT' SECTOR
; EXIT:   HL      - POINTER TO FREE 'HIT' ENTRY
;         ZF      - SET IF ENTRY FOUND
;50BD
HITHLP:	LD	A,(HL)		;GET A 'HIT' ENTRY
	OR	A		;TEST IF FREE ENTRY
	RET	Z		;ALL DONE IF ENTRY FREE
	LD	A,L		;GET TABLE POINTER LSB TO A
	ADD	A,20H		;INDEX TO NEXT ENTRY SET
	LD	L,A		;UPDATE TABLE POINTER
	JR	NC,HITHLP	;CONTINUE IF NOT TABLE END
	ADD	A,41H		;RESTART SEARCH AT 2, 3..
	LD	L,A		;UPDATE TABLE POINTER
	AND	11100111B	;FORCE 41-47, 61-67, 81-87..
	CP	L		;IF LSB IS E7 THEN TABLE END
	JR	Z,HITHLP	;LOOP IF NOT TABLE END
	OR	00000001B	;SIGNAL NO AVAILABLE ENTRIES
	RET
;
;
; COMPUTE PASSWORD HASH CODE
; ENTRY:  DE      - POINTER TO PASSWORD BUFFER
; EXIT:   HL      - PASSWORD HASH CODE
;50D1
PWHASH:	LD	HL,-1		;LOAD INITIAL VALUE
	LD	B,8		;PASSWORD CHARACTER COUNT
	LD	A,E		;GET BUFFER POINTER LSB TO A
	ADD	A,7		;INDEX TO END OF BUFFER
	LD	E,A		;UPDATE BUFFER POINTER LSB
	JR	NC,PWHASL	;SKIP IF NOT OVERFLOW
	INC	D		;ELSE BUMP BUFFER POINTER MSB
PWHASL:	LD	A,(DE)		;GET CHARACTER FROM PASSWORD
	PUSH	DE		;SAVE BUFFER POINTER
	LD	D,A		;COPY THE CHARACTER TO D
	LD	E,H		;MARK VALUE 1 (MV1) TO E
	LD	A,L		;MARK VALUE 2 (MV2) TO A
	AND	00000111B	;MASK OFF TOP FIVE BITS
	RRCA			;ROTATE LOWER THREE
	RRCA			; BITS INTO UPPER
	RRCA			;  THREE BITS
	XOR	L		;EXCLUSIVE OR LOWER AND UPPER
	LD	L,A		;SAVE AS NEW MV2
	LD	H,0		;CLEAR FOR MULTIPLY BY SIXTEEN
	ADD	HL,HL		;MULTIPLY MV2 BY TWO
	ADD	HL,HL		;MULTIPLY MV2 BY FOUR
	ADD	HL,HL		;MULTIPLY MV2 BY EIGHT
	ADD	HL,HL		;MULTIPLY MV2 BY SIXTEEN
	XOR	H		;COMBINE UPPER EIGHT BITS
	XOR	D		;COMBINE CURRENT CHARACTER
	LD	D,A		;SAVE ENCODE UPPER EIGHT BITS
	LD	A,L		;SAVE ENCODE LOWER EIGHT BITS
	ADD	HL,HL		;COMPUTE MV2 TIMES THIRTY-TWO
	XOR	H		;COMBINE UPPER EIGHT BITS
	XOR	E		;COMBINE LOWER EIGHT BITS
	LD	E,A		;SAVE ENCODE LOWER EIGHT BITS
	EX	DE,HL		;SWAP RESULT TO HL REGISTER
	POP	DE		;RECOVER BUFFER POINTER
	DEC	DE		;BACKUP TO PREVIOUS CHARACTER
	DJNZ	PWHASL		;LOOP UNTIL PASSWORD HASHED
	RET
;
;
; TEST DRIVE READY STATUS BY TESTING FOR INDEX HOLE
; ENTRY:  C       - DRIVE NUMBER TO SELECT AND TEST
; EXIT:   A       - UNDEFINED
;         C       - UNCHANGED
;         CF      - SET IF WRITE PROTECTED
;         ZF      - RESET IF DRIVE NOT READY OR NOT PRESENT
;50FD
TSTRDY:	LD	A,WDFORC	;FORCE INTERRUPT COMMAND
	LD	(CSTREG),A	;RESET FLOPPY CONTROLLER
	CALL	SELDRV		;SELECT THE DISK DRIVE
	PUSH	BC		;SAVE DRIVE NUMBER
	LD	BC,12629	;LOAD LOOP COUNTER TO BC
BEGIDX:	CALL	TSTIDX		;WAIT FOR INDEX HOLE START
	JR	NZ,BEGIDX	;LOOP UNTIL HOLE REACHED
ENDIDX:	CALL	TSTIDX		;WAIT FOR INDEX HOLE END
	JR	Z,ENDIDX	;LOOP UNTIL END REACHED
IDXBEG:	CALL	TSTIDX		;WAIT FOR INDEX HOLE START
	JR	NZ,IDXBEG	;LOOP UNTIL HOLE REACHED
	POP	BC		;RECOVER DRIVE NUMBER
	RLCA			;WRITE PROTECT TO BIT SEVEN
	AND	10000000B	;MASK TO WRITE PROTECT
	ADD	A,A		;SET CARRY IF PROTECTED
	RET
;
;
; TEST FLOPPY CONTROLLER INDEX HOLE STATUS
; ENTRY:  BC      - NUMBER OF TIMES TO TEST COUNTER
; EXIT:   A       - FLOPPY CONTROLLER STATUS
;         BC      - DECREMENTED COUNTER
;         ZF      - RESET IF AT INDEX HOLE
;511E
TSTIDX:	DEC	BC		;DECREMENT TEST COUNT
	LD	A,B		;GET COUNTER MSB TO A
	OR	C		;MERGE IN COUNTER LSB
	JR	Z,IDXNOF	;ABORT IF COUNT TURNS ZERO
	LD	A,(CSTREG)	;GET FLOPPY STATUS
	BIT	1,A		;TEST THE INDEX FLAG
	RET
;
;
; INDEX HOLE NOT NOT FOUND - CLEAN STACK AND ABORT
; EXIT:   C       - DRIVE NUMBER
;         ZF      - RESET TO SHOW DRIVE NOT READY OR PRESENT
;5129
IDXNOF:	POP	BC		;REMOVE RETURN ADDRESS
	POP	BC		;RECOVER DRIVE NUMBER
	OR	00000001B	;RESET ZERO FLAG
	RET
;
;
; READ HASH INDEX TABLE (HIT) SECTOR FROM DISK
; ENTRY:  C       - DRIVE NUMBER
; EXIT:   A       - ERROR CODE
;         HL      - HASH IBDEX TABLE BUFFER POINTER
;         ZF      - SET IF ERROR
;512E
REDHIT:	PUSH	BC		;SAVE DRIVE NUMBER
	PUSH	DE		;SAVE DE REGISTER
	CALL	TRKDIR		;GET DIRECTORY TRACK NUMBER
	LD	E,1		;LOAD SECTOR NUMBER
	LD	HL,GATBUF	;POINT AT SECTOR BUFFER
	CALL	DDREAD		;READ SECTOR FROM DISK
	POP	DE		;RECOVER  DE REGISTER
	POP	BC		;RECOVER DRIVE NUMBER
	RET	Z		;ALL DONE IF SUCCESSFUL
	LD	A,16H		;ELSE LOAD ERROR CODE
	RET
;
;
; WRITE HASH INDEX TABLE (HIT) SECTOR TO DISK
; ENTRY:  C       - DRIVE NUMBER
; EXIT:   A       - ERROR CODE
;         HL      - HASH INDEX TABLE BUFFER POINTER
;         ZF      - SET IF ERROR
;5141
WRTHIT:	PUSH	BC		;SAVE DRIVE NUMBER
	PUSH	DE		;SAVE DE REGISTER
	CALL	TRKDIR		;GET DIRECTORY TRACK NUMBER
	LD	E,1		;LOAD SECTOR NUMBER
	LD	HL,GATBUF	;POINT AT SECTOR BUFFER
	CALL	WRDSEC		;WRITE SECTOR TO DISK
	POP	DE		;RECOVER DE REGISTER
	POP	BC		;RECOVER DRIVE NUMBER
	RET	Z		;ALL DONE IF SUCCESSFUL
	LD	A,17H		;ELSE LOAD ERROR CODE
	RET
;
;
; DRIVE AND FILE SPECIFICATION STORAGE
;5154
DRVCOD	Db	  0		;DRIVE CODE
PASSWD	Ds	  8		;PASSWORD
FILNAM	Ds	  8		;FILE NAME
FILEXT	Ds	  3		;FILE EXTENSION
MASHAS	Ds	  2		;MASTER PASSWORD HASH
FILHAS	Ds	  2		;FILE PASSWORD HASH
;
	If	PATCHG		;PATCHES ACTIVE
;
;
; PATCH FOR DEVICE CONTROL BLOCK FILL ROUTINE
;
	 Org	04FE8H
;
	 CALL	BMPEOF		;EXECUTE THE PATCH
;
;
; PATCH CODE - COPY EOF ADDRESS AND IF BUILDING AN OVERFLOW
; DIRECTORY ENTRY, THEN DECREMENT THE EOF SECTOR NUMBER
;
	 Org	05180H
;
BMPEOF:	 INC	DE		;BUMP TO MSB OF EOF
	 LD	A,(DE)		;LOAD MSB OF EOF
	 LD	(HL),A		;COPY THE BYTE TO DCB
	 LD	A,(IX+08)	;GET EOF ADDRESS FROM DCB
	 OR	A		;SET THE STATUS FLAGS
	 RET	Z		;DONE IF OPEN OR INIT CALL
	 LD	A,(IX+12)	;GET EOF SECTOR LSB FROM DCB
	 DEC	(IX+12)		;DECREMENT SECTOR NUMBER LSB
	 OR	A		;TEST IF SECTOR WAS ZERO
	 RET	NZ		;RETURN IF IT WASN'T
	 DEC	(IX+13)		;ELSE DECREMENT SECTOR MSB
	 RET
;
	EndIf			;ALL DONE
;
	End	OVRL02
