	Title	'TRSDOS 2.3 Disk Operating System'
;
;
; TRSDOS DISK OPERATING SYSTEM, VERSION 2.3
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON 20.01.2022
;
; PART 3 - OVERLAY 3 - CLOSE AND KILL FILE
;
;
; DEFINE IF PATCHES ARE ACTIVE
;
PATCHG	Equ	  1		;PATCHES ACTIVE
;
;
; ASCII EQUATES
;
CC	Equ	  3		;CONTROL-C (END-OF-MESSAGE)
CR	Equ	 13		;CARRIAGE RETURN
;
;
; FLOPPY DISK CONSTANTS
;
MAXDRV	Equ	  4		;MAX NUMBER OF DRIVES
NUMTRK	Equ	 35+(5*PATCHG)	;TRACKS PER DISK
;
;
; STORAGE LOCATIONS IN TRDSOS NUCLEUS (SYS0/SYS)
;
RAMBEG	Equ	04000H		;START OF SYSTEM MEMORY
MEMSIM	Equ	0404AH		;MEMORY SIZE MSB
SYSBUF	Equ	04200H		;SYSTEM SECTOR BUFFER
GATBUF	Equ	04D00H		;SECTOR BUFFER
;
;
; FUNCTIONS ADDRESSES IN TRSDOS NUCLEUS (SYS0/SYS)
;
WRDSEC	Equ	046EFH		;WRITE A DIRECTORY SECTOR
PURGEB	Equ	04878H		;PURGE SECTOR BUFFER
SAVREG	Equ	04892H		;SAVE ALL REGISTERS
REDDIR	Equ	04AC1H		;READ DIRECTORY SECTOR ENTRY
WRTDIR	Equ	04AD6H		;WRITE DIRECTORY SECTOR ENTRY
REDGAT	Equ	04AF0H		;READ 'GAT' SECTOR
WRTGAT	Equ	04B03H		;WRITE 'GAT' SECTOR
DDREAD	Equ	04B35H		;READ A SECTOR TO BUFFER
TRKDIR	Equ	04B55H		;GET DIRECTORY TRACK NUMBER
DIVMOD	Equ	04B84H		;MODULO DIVISION ROUTINE
;
;
;
; PROGRAM MODULE NAME STRING - NOT USED
;
;	Nam	'SYS3  '
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING - NOT USED
;
;	Rem	CR
;	Rem	'* * * N O T I C E * * *',CR
;	Rem	'* PROPRIETARY PROGRAM *',CR
;	Rem	'* COPYRIGHT (c) 1979  *',CR
;	Rem	'* BY TANDY CORPORATION*',CR
;	Rem	'*  FORT WORTH, TEXAS  *',CR
;	Rem	'* ALL RIGHTS RESERVED *',CR
;	Rem	'* * * N O T I C E * * *',CR
;
;
	Org	04E00H
;
OVRL03:	PUSH	IX		;SAVE POINTER TO DCB
	PUSH	HL		;SAVE BUFFER POINTER
	PUSH	AF		;SAVE REQUEST CODE
	LD	A,D		;GET DCB ADDRESS MSB
	CP	High RAMBEG	;TEST IF WITHIN RAM AREA
	JR	C,OVRLER	;ABORT IF OUTSIDE AREA
	LD	HL,MEMSIM	;POINT AT MEMORY SIZE MSB
	CP	(HL)		;TEST IF AT END OF RAM AREA
	JR	Z,DCBINR	;CONTINUE IF IT IS
	JR	NC,OVRLER	;ABORT IF OUTSIDE RAM AREA
DCBINR:	LD	A,(DE)		;LOAD OPEN FLAG FROM DCB
	BIT	7,A		;TEST IF FILE IS OPEN
	JR	Z,OVRLER	;ABORT IF FILE IS CLOSED
	PUSH	DE		;COPY FILE DCB ADDRESS
	POP	IX		; INTO IX INDEX REGISTER
	LD	A,(IX+04)	;SECTOR BUFFER ADDRESS MSB
	CP	High RAMBEG	;TEST IF WITHIN RAM AREA
	JR	C,OVRLER	;ABORT IF OUTSIDE RAM AREA
	CP	(HL)		;TEST IF AT END OF RAM AREA
	JR	Z,BUFINR	;CONTINUE IF IT IS
	JR	NC,OVRLER	;ABORT IF OUTSIDE RAM AREA
BUFINR:	LD	A,(IX+06)	;LOAD DRIVE NUMBER TO A
	CP	0		;TEST IF DRIVE WITHIN RANGE
	JR	C,OVRLER	;ABORT IF OUT OF RANGE
	CP	MAXDRV		;TEST IF DRIVE WITHIN RANGE
	JR	NC,OVRLER	;ABORT IF OUT OF RANGE
	LD	A,(IX+07)	;GET 'HIT' INDEX TO A
	BIT	4,A		;TEST IF FIRST ENTRY USED
	JR	NZ,OVRLER	;ABORT IF IT IS UNUSED
	BIT	3,A		;TEST IF SECOND ENTRY USED
	JR	NZ,OVRLER	;ABORT IF IT IS UNUSED
	LD	A,(IX+14)	;TRACK NUMBER FIRST 'GAP'
	CP	00000000B	;TEST IF ANY TRACKS ASSIGNED
	JR	NZ,TRKASG	;CONTINUE IF THERE ARE
	LD	A,(IX+15)	;GET GRANULE COUNT TO A
	CP	00100000B	;MUST BE SECOND GRANULE
	JR	C,OVRLER	;ABORT IF FIRST GRANULE
	LD	A,(IX+14)	;TRACK NUMBER FIRST 'GAP'
TRKASG:	CP	11111111B	;TEST IF NO TRACKS ASSIGNED
	JR	Z,NOTRKA	;SKIP IF NONE ASSIGNED
	CP	NUMTRK		;TEST IF MORE THAN MAXIMUM
	JR	NC,OVRLER	;ABORT IF ABOVE MAXIMUM
NOTRKA:	POP	AF		;RECOVER REQUEST CODE
	POP	HL		;RECOVER BUFFER POINTER
	POP	IX		;RECOVER POINTER TO DCB
	AND	01110000B	;MASK TO REQUEST CODE
	CP	10H		;TES IF FILE CLOSE
	JP	Z,CLSFIL	;THEN CLOSE THE FILE
	CP	20H		;TEST IF FILE KILL
	JP	Z,KILFIL	;THEN KILL THE FILE
	RET
;
;
; ALL ERRORS END UP HERE - RECOVER REGISTERS AND REPORT ERROR
; EXIT:   A       - ERROR CODE
;         CF      - RESET
;         ZF      - RESET
;4E65
OVRLER:	POP	AF		;RECOVER REQUEST CODE
	POP	HL		;RECOVER BUFFER POINTER
	POP	IX		;RECOVER POINTER TO DCB
	LD	A,26H		;FILE NOT OPENED ERROR
	OR	A		;RESET ZERO AND CARRY FLAGS
	RET
;
;
; OVERLAY REQUEST 10H - CLOSE AN OPEN FILE
;4E6D
CLSFIL:	CALL	SAVREG		;SAVE CALLER'S REGISTERS
	RET	NZ		;ABORT IF FILE NOT OPEN
	CALL	PURGEB		;FLUSH BUFFER IF NEEDED
	RET	NZ		;EXIT IF PURGE ERROR
	LD	B,(IX+07)	;GET 'HIT' INDEX TO B
	LD	C,(IX+06)	;GET UNIT NUMBER TO C
	CALL	REDDIR		;READ DIRECTORY SECTOR ENTRY
	RET	NZ		;EXIT IF ANY READ ERRORS
	LD	A,3		;LOAD OFFSET TO EOF BYTE
	ADD	A,L		;ADD TO ENTRY INDEX
	LD	L,A		;UPDATE DIRECTORY ENTRY ADDRESS
	PUSH	HL		;SAVE EOF BYTE ADDRESS
	LD	A,(IX+08)	;GET DCB EOF BYTE OFFSET
	CP	(HL)		;IF NOT SAME AS DIRECTORY
	JR	NZ,UPDEOF	;UPDATE DIRECTORY ENTRY EOF
	LD	A,17		;INDEX TO EOF SECTOR NUMBER
	ADD	A,L		;ADD TO CURRENT ADDRESS
	LD	L,A		;UPDATE DIRECTORY ADDRESS
	LD	A,(IX+12)	;EOF SECTOR LSB FROM DCB
	CP	(HL)		;IF NOT SAME AS DIRECTORY
	JR	NZ,UPDEOF	;UPDATE DIRECTORY ENTRY EOF
	INC	L		;BUMP TO EOF SECTOR MSB
	LD	A,(IX+13)	;EOF SECTOR MSB FROM DCB
	CP	(HL)		;IF NOT SAME AS DIRECTORY
	JR	NZ,UPDEOF	;UPDATE DIRECTORY ENTRY EOF
	POP	AF		;CLEAN UP THE STACK
	JR	CALGRC		;COMPUTE TOTAL GRANULE COUNT
;
;
; UPDATE END-OF-FILE POINTERS FROM DEVICE CONTROL BLOCK
;4E9E
UPDEOF:	POP	HL		;RESTORE ENTRY BASE ADDRESS
	LD	A,(IX+08)	;LOAD EOF OFFSET FROM DCB
	LD	(HL),A		;COPY OFFSET TO DIRECTORY
	LD	A,17		;INDEX TO EOF SECTOR NUMBER
	ADD	A,L		;ADD TO CURRENT ADDRESS
	LD	L,A		;UPDATE DIRECTORY ADDRESS
	LD	A,(IX+12)	;EOF SECTOR LSB FROM DCB
	LD	(HL),A		;COPY TO DIRECTORY ENTRY
	INC	L		;BUMP TO EOF SECTOR MSB
	LD	A,(IX+13)	;EOF SECTOR MSB FROM DCB
	LD	(HL),A		;COPY TO DIRECTORY ENTRY
	PUSH	HL		;SAVE CURRENT DIRECTORY ADDRESS
	CALL	WRTDIR		;WRITE DIRECTORY SECTOR ENTRY
	POP	HL		;RESTORE DIRECTORY ADDRESS
	RET	NZ		;ABORT IF ANY WRITE ERRORS
;
;
; COMPUTE THE TOTAL NUMBER OF GRANULES ASSIGNED TO THE FILE
;4EB6
CALGRC:	INC	L		;BUMP TO TRACK FOR FIRST GAP
	LD	DE,0		;ZERO TOTAL GRANULE STORAGE
CALGRL:	LD	A,(HL)		;GET STARTING TRACK FROM GAP
	INC	L		;BUMP TO GRANULE COUNT
	CP	11111110B	;TEST OVERFLOW OR END OF GAPS
	JR	NC,OVFGEN	;SKIP IF EITHER CONDITION
	LD	A,(HL)		;ELSE GET GRANULE COUNT TO A
	INC	L		;THEN BUMP TO NEXT GAP
	AND	00011111B	;ISOLATE THE GRANULE COUNT
	INC	A		;ADJUST FOR THE TRUE VALUE
	ADD	A,E		;ADD TO CURRENT TOTAL
	LD	E,A		;UPDATE THE TOTAL LSB
	JR	NC,CALGRL	;SKIP IF NOT OVERFLOW
	INC	D		;ELSE UPDATE THE TOTAL MSB
	JR	CALGRL		;LOOP UNTIL GRANULES SUMMED
;
;
; WE HAVE EITHER AN OVERFLOW ENTRY OR THE END OF GAPS
;4ECC
OVFGEN:	JR	NZ,ENDGAP	;SKIP IF END OF GAPS REACHED
	LD	B,(HL)		;GET HIT INDEX FOR OVERFLOW
	CALL	REDDIR		;READ OVERFLOW DIRECTORY ENTRY
	RET	NZ		;ABORT IF ANY READ ERRORS
	LD	A,L		;GET DIRECTORY ADDRESS LSB
	ADD	A,22		;ADD TO REACH GAP ADDRESS
	LD	L,A		;UPDATE LSB OF ADDRESS
	JR	CALGRL		;SCAN UNTIL END OF GAPS
;
;
; TEST FOR CHANGE IN FILE SIZE USING FOLLOWING METHOD:
;   DIRECTORY FILE SIZE (GRANULE TOTAL FROM DIRECTORY GAP'S)
;   (MINUS) TRUE FILE SIZE (GRANULE TOTAL FROM ENDING SECTOR
;   IN *DCB (DIVIDED) BY FIVE)
; YIELDS:
;   (NEGATIVE, IF FILE HAS INCREASED)
;   (ZERO,     IF FILE SIZE IS UNCHANGED)
;   (POSITIVE, IF FILE SIZE HAS DECREASED)
;4ED9
ENDGAP:	PUSH	HL		;SAVE END OF GAPS ADDRESS
	LD	L,(IX+12)	;L HAS NUMBER OF RECORDS LSB
	LD	H,(IX+13)	;H HAS NUMBER OF RECORDS MSB
	LD	A,5		;LOAD DIVISOR TO A
	CALL	DIVMOD		;MODULO DIVIDE COUNT BY FIVE
	INC	HL		;MAKE TRUE NUMBER OF GRANS
	XOR	A		;ZERO ACCUMULATOR, CLEAR CARRY
	EX	DE,HL		;SWAP GRANULE COUNT, FILE SIZE
	SBC	HL,DE		;COMPUTE TRUE FILE SIZE
	EX	DE,HL		;COPY DIFFERENCE TO DE
	POP	HL		;RESTORE CORRENT GAPS END
	JP	Z,RECOFE	;DONE IF COUNT IS EQUAL
	JP	C,RECOFE	;DONE IF COUNT IS GREATER
	DEC	L		;ELSE BACKUP TO GRANULE
	DEC	L		; COUNT FOR LAST GAP
	PUSH	HL		;SAVE LAST GOOD GAP ADDRESS
	PUSH	DE		;SAVE GRANULE DIFFERENCE
	CALL	REDGAT		;READ 'GAT' SECTOR TO BUFFER
	JR	NZ,GATRDE	;SKIP IF ANY READ ERRORS
	CALL	HASHRD		;READ 'HIT' SECTOR TO BUFFER
GATRDE:	POP	DE		;RESTORE GRANULE DIFFERENCE
	POP	HL		;RESTORE LAST GAP ADDRESS
	RET	NZ		;ABORT IF ANY READ ERRORS
TESTDO:	LD	A,E		;LOAD GRANULE DIFFERENCE TO A
	CP	0		;TEST IF ALL DONE
	JR	Z,PRIMEN	;EXIT IF WE ARE ALL DONE
	PUSH	DE		;SAVE GRANULE DIFFERENCE
	LD	A,(HL)		;RECOVER COUNT FROM LAST GAP
	AND	11100000B	;ISOLATE STARTING GRANULE
	RLCA			;SHIFT INTO LOW
	RLCA			; ORDER THREE BITS
	RLCA			;  OF ACCUMULATOR
	LD	E,A		;SAVE VALUE IN E REGISTER
	LD	A,(HL)		;RECOVER COUNT FROM LAST GAP
	AND	00011111B	;ISOLATE NUMBER OF GRANULES
	ADD	A,E		;ADD OFFSET FOR FIRST GRANULE
	LD	E,A		;SAVE RESULT IN E REGISTER
	AND	11111110B	;CLEAR BIT ZERO FOR ROTATE
	RRCA			;DIVIDE GRANULE COUNT BY TWO
	LD	(TRKCNT),A	;SAVE THE NUMBER OF TRACKS
	LD	A,E		;RESTOR GRAN COUNT AND OFFSET
	AND	00000001B	;ISOLATE BIT ZERO
;
;
; CONSTRUCT MASK FOR CLEARING BIT IN GAT FOR LAST GRAN ASSIGNED
;   USE FOLLOWING RULES:
;
;     -----------------------------------------
;       # SECTORS IN      SECTOR       OFFSET
;       GRANULE COUNT       00           01
;     ----------------- ----------  -----------
;         EVEN              FE           FD
;     -----------------  ---------  -----------
;         ODD               FD           FE
;     -----------------------------------------
;
	INC	A		;ADD ONE AND
	CPL			;THEN COMPLEMENT
	PUSH	AF		;SAVE LAST GRANULE MASK
	DEC	HL		;BACKSPACE GAP POINTER
	LD	A,(HL)		;GET GAP STARTING ADDRESS
	ADD	A,0		;ADD CONSECUTIVE TRACK COUNT
TRKCNT	Equ	$-1		;CONSECUTIVE TRACK COUNT
	EX	DE,HL		;SAVE GAP ADDRESS IN DE
	LD	H,High GATBUF	;GAT BUFFER ADDRESS MSB IN H
	LD	L,A		;GAT BUFFER ADDRESS LSB IN L
	POP	AF		;GET GRANULE ASSIGNMENT MASK
	AND	(HL)		;ZAP LAST ASSIGNED GRANULE BIT
	LD	(HL),A		;STORE UPDATED BYTE TO GAT
;
;
; LOOK FOR GAPS WHICH HAVE NO GRANULES ASSIGNED. WHEN ONE IS
; FOUND, SET BOTH BYTES OF THE GAP ENTRY TO ALL BITS SET. IF
; ALL GAP'S IN AN ENTRY ARE RELEASED (SET TO ALL BITS SET),
; RELEASE THE DIRECTORY ENTRY AND THE 'HIT' INDEX IN THE 'HIT'
; SECTOR FOR THE DIRECTORY ENTRY
;
	EX	DE,HL		;RESTORE GAP ADDRESS TO HL
	INC	HL		;SKIP TO GRANULE COUNT
	DEC	(HL)		;PREPARE TEST FOR NO GRANULES
	LD	A,(HL)		;GET ASSIGNED GRANULE COUNT
	INC	A		;MAKE ZERO IF NONE ASSIGNED
	AND	00011111B	;ISOLATE TRUE GRANULE COUNT
	POP	DE		;RESTORE GRANULE DIFFERENCE
	JR	NZ,REDGRC	;SKIP IF AT LEAST ONE ASSIGNED
	LD	(HL),-1		;FLAG NO GRANULES ASSIGNED
	DEC	HL		;BACKUP TO TRACK NUMBER
	LD	(HL),-1		;FLAG NO TRACKS ASSIGNED
	DEC	HL		;BACKUP TO GRANULE COUNT
	LD	A,L		;GET GAP INDEX TO A
	AND	00011111B	;ISOLATE START OF GAP
	CP	21		;TEST IF GAP ENTRIES START
	JR	NZ,REDGRC	;SKIP IF NOT THE BEGGINNING
	XOR	L		;DIRECTORY ENTRY LSB IN A
	LD	L,A		;REFORM DIRECTORY ENTRY START
	LD	A,(HL)		;GET ACCESS AND DIR ENTRY FLAGS
	LD	(HL),0		;FLAG ENTRY AS AVAILABLE
	INC	HL		;BUMP ENTRY TO OVERFLOW BYTE
	LD	D,(HL)		;GET OVERFLOW POINTER TO D
	LD	H,High LCLBUF	;GET 'HIT' BUFFER ADDRESS MSB
	LD	L,B		;'HIT' ADDRESS IN BUFFER
	LD	(HL),0		;CLEAR THE 'HIT' ENTRY
	BIT	7,A		;TEST TYPE IF DIRECTORY ENTRY
	JR	Z,PRIMEN	;SKIP IF PRIMARY ENTRY
	PUSH	DE		;SAVE GRANULE COUNT DIFFERENCE
	CALL	WRTDIR		;WRITE RELEASED DIRECTORY ENTRY
	POP	DE		;GET GRANULE COUNT DIFFERENCE
	RET	NZ		;ABORT IF ANY WRITE ERRORS
	LD	A,B		;RECOVER 'HIT' INDEX
	XOR	D		;GET SECTOR PORTION OF IT
	AND	00000111B	;ISOLATE SECTOR PORTION
	LD	B,D		;SAVE THE SECTOR NUMBER
	CALL	NZ,REDDIR	;READ DIRECTORY SECTOR ENTRY
	RET	NZ		;ABORT IF ANY READ ERRORS
	LD	A,B		;ENTRY ADDRESS AND SECTOR / 2
	AND	11100000B	;MASK DIRECTORY ENTRY ADDRESS
	ADD	A,31		;SKIP TO GAP ENTRY IN OVERFLOW
	LD	L,A		;FORM END ADDRESS IN HL
	LD	(HL),-1		;SIGNAL DIRECTORY END OF GAP'S
	DEC	HL		;BACKUP DIRECTORY POINTER
	LD	(HL),-1		;SIGNAL DIRECTORY END OF GAP'S
	DEC	HL		;BACSPACE TO NEXT GRANULE COUNT
REDGRC:	DEC	E		;REDUCE GRAN COUNT DIFFERENCE
	JR	TESTDO		;THEN GO TEST IF ALL DONE
;
;
; WRITE UPDATED DIRECTORY ENTRY AND RECONSTRUCT DCB
;4F6F
PRIMEN:	CALL	WRTDIR		;WRITE DIRECTORY SECTOR ENTRY
	RET	NZ		;ABORT IF ANY WRITE ERRORS
	CALL	HASHWR		;WRITE 'HIT' SECTOR
	RET	NZ		;ABORT IF ANY WRITE ERRORS
	CALL	WRTGAT		;WRITE 'GAT' SECTOR
	RET	NZ		;ABORT IF ANY WRITE ERRORS
;
;
; RECONSTRUCT FILE NAME, EXTENSION AND DRIVE AND STORE IN DCB
;4F7B
RECOFE:	LD	A,(IX+07)	;GET 'HIT' INDEX TO A
	XOR	B		;MASK WITH LAST INDEX
	AND	00011111B	;ISOLATE ANY DIFFERENCE
	CALL	NZ,REDDIR	;READ DIRECTORY SECTOR ENTRY
	RET	NZ		;ABORT IF ANY READ ERRORS
	LD	A,(IX+06)	;LOAD DRIVE NUMBER TO A
	AND	00000011B	;FORCE TO VALID DRIVE CODE
	OR	'0'		;CONVERT TO ASCII DRIVE CODE
	LD	(DRCODE),A	;SAVE THE DRIVE CODE
	LD	H,High SYSBUF	;LOAD SECTOR BUFFER MSB
	LD	A,(IX+07)	;GET 'HIT' INDEX TO A
	AND	11100000B	;OFFSET TO FILE ENTRY
	OR	00000101B	;MERGE FILE NAME OFFSET BIT
	LD	L,A		;UPDATE SECTOR BUFFER OFFSET
	PUSH	HL		;SAVE SECTOR BUFFER ADDRESS
	PUSH	IX		;COPY DEVICE CONTROL BLOCK
	POP	DE		; ADDRESS TO DE REGISTER
	LD	B,8		;LOAD LENGTH OF FILE NAME
SCANFN:	LD	A,(HL)		;GET FILE NAME CHARACTER
	CP	' '		;TEST IF SPACE CHARACTER
	JR	Z,SCANEX	;THEN WE ARE DONE WITH NAME
	LD	(DE),A		;ELSE STORE NAME CHARACTER
	INC	HL		;BUMP SOURCE POINTER
	INC	DE		;BUMP DESTINATION POINTER
	DJNZ	SCANFN		;LOOP UNTIL FILE NAME DONE
SCANEX:	POP	HL		;RECOVER SOURCE POINTER
	LD	A,L		;GET POINTER LSB TO A
	ADD	A,8		;BUMP TO FILE EXTENSION
	LD	L,A		;UPDATE SOURCE POINTER
	LD	A,(HL)		;GET FILE EXTENSION CHARACTER
	CP	' '		;TEST IF SPACE CHARACTER
	JR	Z,SCNDRL	;THEN DONE WITH EXTENSION
	LD	A,'/'		;LOAD SEPERATOR CHARACTER
	LD	(DE),A		;STORE CHARACTER IN BUFFER
	INC	DE		;BUMP DESTINATION POINTER
	LD	B,3		;LOAD FILE EXTENSION LENGTH
SCNEXL:	LD	A,(HL)		;GET EXTENSION CHARACTER
	CP	' '		;TEST IF SPACE CHARACTER
	JR	Z,SCNDRL	;THEN DONE WITH EXTENSION
	LD	(DE),A		;ELSE STORE THE CHARACTER
	INC	HL		;BUMP SOURCE POINTER
	INC	DE		;BUMP DESTINATION POINTER
	DJNZ	SCNEXL		;LOOP UNTIL EXTENSION DONE
SCNDRL:	LD	A,':'		;LOAD DRIVE DELIMITER
	LD	(DE),A		;STORE CHARACTER IN BUFFER
	INC	DE		;BUMP DESTINATION POINTER
	LD	A,0		;GET DRIVE CODE TO A
DRCODE	Equ	$-1		;DRIVE CODE STORAGE
	LD	(DE),A		;STORE CODE IN BUFFER
	INC	DE		;BUMP DESTINATION POINTER
	LD	A,CC		;LOAD STRING TERMINATOR
	LD	(DE),A		;STORE CHARACTER IN BUFFER
	XOR	A		;FLAG SUCCESSFUL OPERATION
	RET
;
;
; OVERLAY REQUEST 20H - KILL AN OPEN FILE
;4FD0
KILFIL:	CALL	SAVREG		;SAVE CALLER'S REGISTERS
	RET	NZ		;RETURN IF FILE NOT OPEN
	LD	A,(IX+01)	;GET FILE ACCESS FLAGS TO A
	AND	00000111B	;MASK TO ACCESS FLAGS
	CP	00000010B	;TEST IF PROTECTED FILE
	JR	C,KILACC	;SKIP IF UNPROTECTED
	LD	A,25H		;ILLEGAL PROTECTED FILE ACCESS
	OR	A		;RESET CARRY AND ZERO FLAGS
	RET
;
;
; ACCESS IS GRANTED TO THE FILE, SO WE MAY KILL IT
;4FE1
KILACC:	LD	C,(IX+06)	;GET UNIT NUMBER TO C
	LD	B,(IX+07)	;GET 'HIT' INDEX NUMBER TO B
	CALL	HASHRD		;READ THE 'HIT' SECTOR
	RET	NZ		;ABORT IF ANY READ ERROR
	CALL	REDGAT		;READ THE 'GAT' SECTOR
	RET	NZ		;ABORT IF ANY READ ERROR
;
;
; PROCESS ALL GAP'S IN A DIRECTORY
;4FEF
KILPEG:	CALL	REDDIR		;READ DIRECTORY SECTOR ENTRY
	RET	NZ		;EXIT IF ANY READ ERRORS
	LD	A,22		;LOAD OFFSET INTO GAP'S
	ADD	A,L		;FORM GAP ADDRESS FOR ENTRY
	LD	L,A		;UPDATE THE GAP ADDRESS
LOOPGE:	LD	E,(HL)		;GET TRACK ADDRESS FROM GAP
	INC	L		;BUMP TO GRANULE COUNT
	LD	D,(HL)		;GET ASSIGNED GRANULES TO D
	LD	A,E		;PREPARE TO TEST FOR THE END
	CP	11111110B	;TEST FOR GAP END OR OVERFLOW
	JR	NC,GAPEOV	;SKIP IF EITHER ONE
	INC	L		;ELSE BUMP TO NEXT GAP ENTRY
	CALL	GAPDEA		;DEALLOCATE THE GAP
	JR	LOOPGE		;LOOP UNTIL END OF GAP'S
;
;
; EITHER END OF GAP OR OVERFLOW ENCOUNTERED
;5005
GAPEOV:	LD	A,L		;GET DIRECTORY ENTRY LSB
	AND	11100000B	;ISOLATE STARTING ADDRESS
	LD	L,A		;FORM BEGINNING ADDRESS
	LD	(HL),0		;CLEAR ACCESS FLAGS
	PUSH	BC		;SAVE HIT INDEX AND UNIT
	PUSH	DE		;SAVE GAP FLAGS AND UNIT NUMBER
	PUSH	HL		;SAVE DIRECTORY ENTRY ADDRESS
	POP	DE		;COPY THE ADDRESS TO DE
	INC	DE		;BUMP TO SECOND DIRECTORY ENTRY
	LD	BC,31		;LOAD ENTRY COUNT TO BC
	LDIR			;ZERO THE DIRECTORY ENTRY
	POP	DE		;RESTORE GAP TERNITATION FLAG
	POP	BC		;RESTORE HIT AND INDEX UNIT
	CALL	WRTDIR		;WRITE DIRECTORY SECTOR ENTRY
	RET	NZ		;ABORT IF WRITE ERROR
	LD	H,High LCLBUF	;LOAD 'HIT' BUFFER ADDRESS MSB
	LD	L,B		;LOAD THE BUFFER ADDRESS LSB
	LD	(HL),0		;REMOVE HASH CODE FROM BUFFER
	LD	B,D		;GET POSSIBLE OVERFLOW ENTRY
	LD	A,E		;GET GAP TERMINATION FLAG
	CP	11111110B	;TEST IF OVERFLOW ENTRY
	JR	Z,KILPEG	;CONTINUE IF OVERFLOW ENTRY
	CALL	WRTGAT		;ELSE WRITE 'GAT' SECTOR
	RET	NZ		;ABORT IF ANY WRITE ERRORS
	CALL	HASHWR		;ELSE WRITE 'HIT' SECTOR
	RET	NZ		;ABORT IF ANY WRITE ERRORS
	PUSH	IX		;COPY DCB ADDRESS
	POP	HL		; INTO HL REGISTER
	LD	B,32		;NUMBER OF DCB BYTES TO CLEAR
	XOR	A		;ZERO ACCUMULATOR
DCBCLR:	LD	(HL),A		;CLEAR A DCB BYTE
	INC	HL		;BUMP DCB POINTER
	DJNZ	DCBCLR		;LOOP UNTIL ALL CLEARED
	RET
;
;
; GAP DEALLOCATION ROUTINE
;5039
GAPDEA:	PUSH	HL		;SAVE CURRENT DIR ADDRESS
	PUSH	BC		;SAVE HIT INDEX AND UNIT
	LD	L,E		;SAVE TRACK NUMBER IN L
	LD	H,High GATBUF	;SET BUFFER ADDRESS MSB
	LD	A,D		;GRANULE COUNT IS IN A
	AND	00011111B	;MASK TO THE COUNT IN A
	LD	C,A		;SAVE THE COUNT IN C
	INC	C		;TRUE COUNT IS IN C
	XOR	D		;ISOLATE STARTING GRANULE
	RLCA			;REPOSITION COUNT
	RLCA			; IN THE
	RLCA			;  ACCUMULATOR
GAPDMR:	PUSH	AF		;SAVE THE COUNT FOR LATER
	LD	B,(HL)		;GET GAP ENTRY TO B
	CALL	RLSGRA		;RELEASE A GRANULE
	LD	(HL),B		;RESTORE UPDATED GAP ENTRY
	POP	AF		;GET UPDATED BIT COUNTER
	INC	A		;BUMP THE COUNTER
	CP	2		;TEST IF MAXIMUM RELEASED
	JR	NZ,GAPDNR	;JUMP IF MORE TO RELEASE
	XOR	A		;ELSE RESET COUNTER TO ZERO
	INC	L		;BUMP GAT ENTRY TO NEXT TRACK
GAPDNR:	DEC	C		;COUNT ONE GRANULE RELEASED
	JR	NZ,GAPDMR	;JUMP IF MORE TO RELEASE
	POP	BC		;RESTORE HIT INDEX AND UNIT
	POP	HL		;RESTORE CURRENT GAP ADDRESS
	RET
;
;
; CLEAR A GRANULE ALLOCATION BIT
; ENTRY:  A       - BIT NUMBER TO CLEAR
;         B       - GRANULE ALLOCATION ENTRY
; EXIT:   B       - GRANULE ALLOCATION ENTRY WITH BIT RESET
;505B
RLSGRA:	AND	00000111B	;ISOLATE BIT TO BE RESET
	RLCA			;POSITION
	RLCA			; BIT
	RLCA			;  INTO INSTRUCTION
	OR	10000000B	;COMBINE WITH OP-CODE
	LD	(RLSGCO),A	;SAVE SYNTHESIZED CODE
	RES	0,B		;CLEAR BIT FOR GRANULE
RLSGCO	Equ	$-1		;THE BIT RESET CODE
	RET
;
;
; READ HASH INDEX TABLE (HIT) SECTOR FROM DISK
;5068
HASHRD:	CALL	TRKDIR		;GET DIRECTORY TRACK NUMBER
	LD	E,1		;DIRECTORY SECTOR NUMBER
	LD	HL,LCLBUF	;POINT AT LOCAL BUFFER
	CALL	DDREAD		;READ DIRECTORY SECTOR
	RET	Z		;DONE IF SUCCESSFUL READ
	LD	A,16H		;LOAD 'HIT' READ ERROR CODE
	RET
;
;
; WRITE HASH INDEX TABLE (HIT) SECTOR TO DISK
;5077
HASHWR:	CALL	TRKDIR		;GET DIRECTORY TRACK NUMBER
	LD	E,1		;DIRECTORY SECTOR NUMBER
	LD	HL,LCLBUF	;POINT AT LOCAL BUFFER
	CALL	WRDSEC		;WRITE DIRECTORY SECTOR
	RET	Z		;DONE IF SUCCESSFUL WRITE
	LD	A,17H		;LOAD 'HIT' WRITE ERROR CODE
	RET
;
;
; UNUSED LOCATIONS SET TO ALL BITS SET
;
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1
;
;
; LOCAL SECTOR BUFFER
;5100
LCLBUF	Ds	256		;RESERVE THE SPACE
;
	End	OVRL03
