	Title	'TRSDOS 2.3 Disk Operating System'
;
;
; TRSDOS DISK OPERATING SYSTEM, VERSION 2.3
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON 18.01.2022
;
; PART 4 - OVERLAY 4 - ERROR MESSAGE PROCESSOR
;
;
; DEFINE IF PATCHES ARE ACTIVE
;
PATCHG	Equ	  0		;PATCHES ACTIVE
;
;
; ASCII EQUATES
;
CC	Equ	  3		;CONTROL-C (END-OF-MESSAGE)
LF	Equ	 10		;LINE FEED
CR	Equ	 13		;CARRIAGE RETURN
CO	Equ	192		;SPACE COMPRESSION (0 TO 63)
;
;
; ROM ROUTINE ADDRESSES
;
VDCHAR	Equ	00033H		;VIDEO DRIVER ENTRY
;
;
; STORAGE LOCATIONS IN TRSDOS NUCLEUS (SYS0/SYS)
;
DCBADR	Equ	0430AH		;CURRENT OPERATION DCB ADDRESS
BUFADR	Equ	0430CH		;CURRENT OPERATION BUFFER ADDR
;
;
; FUNCTIONS ADDRESSESSES IN TRSDOS NUCLEUS (SYS0/SYS)
;
DOSERR	Equ	04030H		;DO REQUEST WITH CODE 20
DOPMSG	Equ	04467H		;DISPLAY MESSAGE STRING
REDDIR	Equ	04AC1H		;READ DIRECTORY SECTOR ENTRY
;
;
; PROGRAM MODULE NAME STRING
;
	Nam	'SYS4  '
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING
;
	Rem	CR
	Rem	'* * * N O T I C E * * *',CR
	Rem	'* PROPRIETARY PROGRAM *',CR
	Rem	'* COPYRIGHT (c) 1979  *',CR
	Rem	'* BY TANDY CORPORATION*',CR
	Rem	'*  FORT WORTH, TEXAS  *',CR
	Rem	'* ALL RIGHTS RESERVED *',CR
	Rem	'* * * N O T I C E * * *',CR
;
;
	Org	04E00H
;
OVRL04:	EX	(SP),HL		;GET RETURN ADDRESS TO HL
	LD	(USERAD),HL	;STORE AT EXIT JUMP
	POP	HL		;RECOVER HL REGISTER
	POP	AF		;RECOVER ERROR CODE
	PUSH	HL		;SAVE HL REGISTER
	PUSH	DE		;SAVE DE REGISTER
	PUSH	BC		;SAVE BC REGISTER
	PUSH	AF		;SAVE ERROR CODE
	LD	B,A		;SAVE ERROR CODE IN B
	AND	00111111B	;MASK OFF THE ERROR FLAGS
	LD	C,A		;COPY ERROR CODE TO C
	BIT	6,B		;TEST IF ERROR CODE DISPLAY
	LD	B,0		;BC HOLDS THE ERROR CODE
	JR	NZ,ERRPNH	;SKIP IF NO HEADER DISPLAY
	LD	E,'0'		;INIT ASCII ERROR CODE MSB
ERRPRT:	SUB	10		;SUBTRACT DECIMAL TEN
	JR	C,ERRPRR	;DONE IF UNDERFLOW
	INC	E		;ELSE BUMP ERROR CODE MSB
	JR	ERRPRT		;THEN LOOP UNTIL BORROW
ERRPRR:	ADD	A,'9'+1		;ADD TO REMAINDER
	LD	D,A		;SET ASCII ERROR CODE LSB
	LD	(ERRCOD),DE	;STORE ASCII ERROR CODE
	LD	HL,ERRCOM	;POINT AT ERROR MESSAGE
	CALL	DOPMSG		;DISPLAY MESSAGE STRING
ERRPNH:	LD	HL,ERROFS	;POINT AT MESSAGE INDEX TABLE
	ADD	HL,BC		;INDEX INTO THE TABLE
	LD	L,(HL)		;GET MESSAGE POINTER LSB
	LD	H,High NOTANE	;HL HAS THE MESSAGE POINTER
ERRPNS:	LD	A,(HL)		;GET STRING INDEX TO A
	AND	00111111B	;MASK TO ERROR CODE
	ADD	A,A		;MAKE INTO A WORD INDEX
	PUSH	HL		;SAVE MESSAGE POINTER
	LD	C,A		;LOAD ADDRESS INDEX TO C
	LD	B,0		;BC HAS ADDRESS INDEX
	LD	HL,PARTPT-2	;POINT AT STRING POINTERS
	ADD	HL,BC		;POINT HL AT POINTERS
	LD	E,(HL)		;GET ADDRESS LSB TO E
	INC	HL		;BUMP TABLE POINTER
	LD	D,(HL)		;GET ADDRESS MSB TO D
	INC	HL		;BUMP TABLE POINTER
	LD	A,(HL)		;GET STRUCTURE ADDRESS LSB
	INC	HL		;BUMP TABLE POINTER
	LD	H,(HL)		;GET STRUCTURE ADDRESS MSB
	LD	L,A		;STRUCTURE ADDRESS IS IN HL
	OR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;GET ADDRESS OF NEXT PHRASE
	LD	B,L		;GET STRING LENGTH TO B
	EX	DE,HL		;SWAP STRING POINTER TO HL
ERRPDM:	LD	A,(HL)		;GET CHARACTER FROM STRING
	INC	HL		;BUMP STRING POINTER
	CALL	VDCHAR		;DISPLAY STRING CHARACTER
	DJNZ	ERRPDM		;LOOP UNTIL ALL DISPLAYED
	LD	A,' '		;LOAD A SPACE CHARACTER
	CALL	VDCHAR		;DISPLAY THE SPACE
	POP	HL		;RESTORE PHRASE ADDRESS
	LD	A,(HL)		;REFETCH INDEX
	INC	HL		;BUMP TO NEXT INDEX
	RLCA			;TEMINATING BIT TO CARRY
	JR	NC,ERRPNS	;PROCESS NEXT IF NOT END
	POP	AF		;RESTORE ERROR CODE
	PUSH	AF		;RE-SAVE ERROR CODE
	BIT	6,A		;TEST IF FILE ERROR CODE
	CALL	Z,DSPFER	;THEN DISPLAY FILE NAME
	LD	A,CR		;LOAD A NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE NEWLINE
	POP	AF		;RECOVER ERROR CODE
	POP	BC		;RECOVER BC REGISTER
	POP	DE		;RECOVER DE REGISTER
	POP	HL		;RECOVER HL REGISTER
	OR	A		;SET FLAGS FOR USER RETURN
	JP	M,0		;RETURN TO CALLER IF MINUS
USERAD	Equ	$-2		;DEFINE ABOVE JUMP ADDRESS
	JP	DOSERR		;ELSE ABORT TO DOS ERROR
;
;
; DISPLAY FILE ERROR MESSAGE
;4E73
DSPFER:	PUSH	HL		;SAVE LAST PHRASE ADDRESS
	LD	HL,TRISTM	;POINT AT THREE STARS MESSAGE
	CALL	DOPMSG		;DISPLAY MESSAGE STRING
	POP	HL		;RESTORE LAST PHRASE ADDRESS
	PUSH	IX		;SAVE CURRENT DCB ADDRESS
	LD	IX,(DCBADR)	;GET ERROR FILE DCB ADDRESS
	DEC	HL		;SET TO TERMINATING CHARACTER
	BIT	6,(HL)		;TEST IF FILE NAME IN DCB
	JR	NZ,FINDCB	;SKIP IF FILE NAME THERE
	LD	C,(IX+06)	;GET DRIVE NUMBER TO C
	LD	B,(IX+07)	;GET DIRECTORY SECTOR TO B
	BIT	7,(IX+00)	;TEST IF FILE IS OPEN
	JR	NZ,COPYDE	;THEN READ DIR AND COPY NAME
DSPDEM:	POP	IX		;ELSE CLEAR THE STACK
	LD	(DEVNAM),BC	;STORE DEVICE NAME IN STRING
	LD	HL,DEVEQM	;POINT AT DEVICE MESSAGE
	CALL	DOPMSG		;DISPLAY MESSAGE STRING
	JR	DSPERA		;THEN SKIP FILE PROCESSING
FINDCB:	LD	A,(IX+00)	;TEST FOR SPECIAL DCB CODE
	CP	'*'		;FIRST CHARACTER MUST BE STAR
	JR	NZ,COPYFS	;GO IF NOT, NAME IS IN DCB
	LD	C,(IX+01)	;GET DEVICE NAME MSB
	LD	B,(IX+02)	;GET DEVICE NAME LSB
	JR	DSPDEM		;GO DISPLAY DEVICE MESSAGE
;
;
; COPY FILE SPEC FROM DCB TO ERROR MESSAGE
;4EAF
COPYFS:	PUSH	IX		;SAVE ERROR FILE DCB ADDRESS
	POP	HL		;COPY DCB ADDRESS TO HL
	LD	DE,FILNAM	;POINT AT FILE NAME IN STRING
;
	If	PATCHG		; PATCHES ACTIVE
	 LD	B,24		;LOAD LEANGTH OF FILE SPEC
	 NOP			;PAD OUT UNUSED BYTE
	Else			;ORIGINAL
	 LD	BC,24		;LOAD LENGTH OF FILE SPEC
	EndIf			;ALL DONE
;
COPYFL:	LD	A,(HL)		;GET FILE SPEC CHARACTER
	CP	CC		;TEST IF END OF STRING
	JR	Z,STOADM	;DONE IF END OF STRING
	INC	HL		;BUMP TO NEXT STRING CHARACTER
	LD	(DE),A		;COPY CHARACTER TO MESSAGE
	INC	DE		;BUMP TO NEXT MESSAGE BYTE
	DJNZ	COPYFL		;LOOP UNTIL FILESPEC COPIED
	JR	STOADM		;GO DISPLAY THE MESSAGE
;
;
; READ DIRECTORY ENTRY AND COPY TO MESSAGE
;4EC4
COPYDE:	CALL	REDDIR		;READ DIRECTORY SECTOR ENTRY
	LD	BC,5		;INDEX TO FILE NAME
	ADD	HL,BC		;POINT HL AT THE NAME
	LD	DE,FILNAM	;POINT AT FILE NAME IN STRING
	LD	B,8		;LOAD MAXIMUM FILE NAME LENGTH
COPYNA:	LD	A,(HL)		;GET FILE NAME CHARACTER
	CP	' '		;TEST IF END OF NAME
	JR	Z,COPYLI	;THEN WE ARE ALL DONE
	INC	L		;BUMP NAME ADDRESS LSB
	LD	(DE),A		;STORE FILE NAME CHARACTER
	INC	DE		;BUMP STRING POINTER
	DJNZ	COPYNA		;LOOP UNTIL END OF FILE NAME
COPYLI:	LD	A,'/'		;LOAD EXTENSION DELIMITER
	LD	(DE),A		;STORE EXTENSION DELIMITER
	INC	DE		;BUMP STRING POINTER
	LD	C,B		;GET REMAINING COUNT TO C
	LD	B,0		;BC HOLDS THE COUNT
	ADD	HL,BC		;INDEX TO FILE EXTENSION
	LD	B,3		;LOAD MAXIMUM EXTENSION LENGTH
COPYEX:	LD	A,(HL)		;GET FILE EXTENSION CHARACTER
	INC	L		;BUMP EXTENSION ADDRESS LSB
	CP	' '		;TEST IF END OF EXTENSION
	JR	Z,COPYDR	;THEN WE ARE ALL DONE
	LD	(DE),A		;STORE EXTENSION CHARACTER
	INC	DE		;BUMP STORAGE POINTER
	DJNZ	COPYEX		;LOOP UNTIL EXTENSION END
COPYDR:	EX	DE,HL		;SWAP STORAGE POINTER TO HL
	LD	(HL),':'	;STORE DRIVE CODE DELIMITER
	INC	HL		;BUMP STRING POINTER
	LD	A,(IX+06)	;GET DRIVE CODE FROM DCB
	ADD	A,'0'		;CONVERT TO ASCII CODE
	LD	(HL),A		;STORE THE DRIVE NUMBER
	INC	HL		;BUMP STRING POINTER
;
;
; STORE CLOSING ANGLE BRACKET AND DISPLAY FILE SPEC MESSAGE
;4EF9
STOADM:	LD	(HL),'>'	;STORE CLOSING ANGLED BRACKET
	INC	HL		;BUMP STRING POINTER
	LD	(HL),CR		;STORE MESSAGE TERMINATOR
	POP	IX		;RECOVER INDEX REGISTER IX
	LD	HL,FILEQM	;POINT AT FILE SPEC STRING
	CALL	DOPMSG		;DISPLAY MESSAGE STRING
;
;
; DISPLAY ERROR ADDRESS
;4F06
DSPERA:	LD	HL,REFATM	;PRINT AT ADDRESS MESSAGE
	CALL	DOPMSG		;DISPLAY MESSAGE STRING
	LD	HL,(BUFADR)	;GET ERROR ADDRESS TO HL
	DEC	HL		;BACKUP TO
	DEC	HL		; START OF
	DEC	HL		;  ERROR ADDRESS
	CALL	HEXWRD		;DISPLAY ADDRESS IN HEX
	LD	HL,SGLQUM	;POINT AT SINGLE QUOTE
	JP	DOPMSG		;DISPLAY MESSAGE STRING
;
;
; DISPLAY A BINARY WORD IN ASCII HEXADECIMAL
; ENTRY:  HL      - WORD TO CONVERT AND DISPLAY
;4F1B
HEXWRD:	LD	A,H		;GET MSB TO A
	CALL	HEXBYT		;CONVERT AND DISPLAY
	LD	A,L		;GET LSB TO A
;
;
; DISPLAY A BINARY BYTE IN ASCII HEXADECIMAL
; ENTRY:  A       - BYTE TO CONVERT AND DISPLAY
;4F20
HEXBYT:	PUSH	AF		;SAVE THE BYTE
	RRA			;SHIFT MS
	RRA			; NYBBLE
	RRA			;  INTO LS
	RRA			;   NYBBLE
	CALL	HEXNYB		;DISPLAY MS NYBBLE
	POP	AF		;RECOVER SAVED BYTE
;
;
; DISPLAY A BINARY NYBBLE IN ASCII HEXADECIMAL
; ENTRY:  A       - NYBBLE TO CONVERT AND DISPLAY
;4F29
HEXNYB:	AND	00001111B	;MASK OFF MS NYBBLE
	ADD	A,'0'		;ADD ASCII NUMERIC BIAS
	CP	'9'+1		;TEST IF NUMERIC
	JR	C,HEXCHR	;SKIP IF IT IS
	ADD	A,7		;ADD ALPHABETIC BIAS
;
;
; DISPLAY AN ASCII CHARACTER
; ENTRY:  A       - CHARACTER TO DISPLAY
;4F33
HEXCHR:	JP	VDCHAR		;DISPLAY THE CHARACTER
;
;
; ERROR MESSAGE STRINGS
;4F36
ERRCOM	Db	LF,'*** ERRCOD=XX, ',CC
ERRCOD	Equ	$-5		;ERROR CODE STORAGE
TRISTM	Db	'***',CR
DEVEQM	Db	CO+006,'<DEVICE=*XX>',CR
DEVNAM	Equ	$-4		;DEVICE NAME STORAGE
FILEQM	Db	CO+005,'<FILE=NNNNNNNN/EEE:D>',CR
FILNAM	Equ	$-16		;FILE NAME STORAGE
FILEXT	Equ	$-7		;FILE EXTENSION STORAGE
DRVNAM	Equ	$-3		;ASCII DRIVE CODE STORAGE
REFATM	Db	CO+003,"REFERENCED AT X'",CC
SGLQUM	Db	"'",CR
;
;
; LOW BYTES OF OFFSETS INTO ERROR MESSAGE DATA STRUCTURE
;
; THE ENTRIES CORRESPOND TO ERROR CODES 0 TO 63 (00H TO 3FH)
;4F84
ERROFS	Db	Low NOTANE	;00 - NO ERROR
	Db	Low PARHRE
	Db	Low SEKDRE
	Db	Low LOSDRE
	Db	Low PARDRE
	Db	Low RNFDRE
	Db	Low LOKDDE
	Db	Low SYSDRE
	Db	Low DEVNAE
	Db	Low PARHWE
	Db	Low SEKDWE
	Db	Low LOSDWE
	Db	Low PARDWE
	Db	Low RNFDWE
	Db	Low WFAULE
	Db	Low WPROTE
	Db	Low ILLFNE
	Db	Low DIRRDE
	Db	Low DIRWRE
	Db	Low ILFNAE
	Db	Low GATRDE
	Db	Low GATWRE
	Db	Low HITRDE
	Db	Low HITWRE
	Db	Low FILNIE
	Db	Low FACCDE
	Db	Low DIRSFE
	Db	Low DSKSFE
	Db	Low EOFENE
	Db	Low RNOORE
	Db	Low DIRFUE
	Db	Low PRNOFE
	Db	Low ILLDRE
	Db	Low NODSPE
	Db	Low LODFFE
	Db	Low MEMFAE
	Db	Low ROMEME
	Db	Low PROTAE
	Db	Low FINOPE	;38 - FILE NOT OPEN
	Db	Low UNKNWE	;39 - UNKNOWN ERROR
	Db	Low UNKNWE	;    ..
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE
	Db	Low UNKNWE	;    ..
	Db	Low UNKNWE	;63 - UNKNOWN ERROR
;
;
; ERROR MESSAGE STRING PART POINTERS
;4FC4
PARTPT	Dw	NOSTRM		;NO
	Dw	ERRORM		;ERROR
	Dw	FORMAM		;FORMAT
	Dw	PARITM		;PARITY
	Dw	DURINM		;DURING
	Dw	HEADRM		;HEADER
	Dw	DATASM		;DATA
	Dw	SEEKSM		;SEEK
	Dw	READSM		;READ
	Dw	WRITEM		;WRITE
	Dw	LOSTSM		;LOST
	Dw	NOTSTM		;NOT
	Dw	ATTMTM		;ATTEMPTED TO
	Dw	LOKDEM		;LOCKED/DELETED
	Dw	SYSTEM		;SYSTEM
	Dw	DIRECM		;DIRECTORY
	Dw	MEMORM		;MEMORY
	Dw	ONSTRM		;ON
	Dw	DISKSM		;DISK
	Dw	DISKEM		;DISKETTE
	Dw	FAULTM		;FAULT
	Dw	PROTEM		;PROTECTED
	Dw	ILLEGM		;ILLEGAL
	Dw	LOGICM		;LOGICAL
	Dw	NUMBEM		;NUMBER
	Dw	FILESM		;FILE
	Dw	RECORM		;RECORD
	Dw	ENDSTM		;END
	Dw	OFSTRM		;OF
	Dw	OUTSTM		;OUT
	Dw	RANGEM		;RANGE
	Dw	ENCOUM		;ENCOUNTERED
	Dw	CODESM		;CODE
	Dw	GATSTM		;GAT
	Dw	HITSTM		;HIT
	Dw	OVERLM		;OVERLAY
	Dw	UNKNOM		;UNKNOWN
	Dw	LOADSM		;LOAD
	Dw	SPACEM		;SPACE
	Dw	ONLYSM		;ONLY
	Dw	NAMESM		;NAME
	Dw	DEVICM		;DEVICE
	Dw	FORMTM		;FORMAT
	Dw	FOUNDM		;FOUND
	Dw	INSTRM		;IN
	Dw	ACCESM		;ACCESS
	Dw	FULLSM		;FULL
	Dw	DRIVEM		;DRIVE
	Dw	DENIEM		;DENIED
	Dw	PROGRM		;PROGRAM
	Dw	AVAILM		;AVAILABLE
	Dw	CANTEM		;- CAN'T EXTEND
	Dw	OPENSM		;OPEN
;
;
; POINTER TO FIRST ENTRY IN ERROR MESSAGE DATA STRUCTURE
;
	Dw	NOTANE		;THE POINTER PROPER
;
;
; ERROR MESSAGE STRING PARTS
;5030
NOSTRM	Db	'NO'		;01
ERRORM	Db	'ERROR'		;02
FORMAM	Db	'FORMAT'	;03
PARITM	Db	'PARITY'	;04
DURINM	Db	'DURING'	;05
HEADRM	Db	'HEADER'	;06
DATASM	Db	'DATA'		;07
SEEKSM	Db	'SEEK'		;08
READSM	Db	'READ'		;09
WRITEM	Db	'WRITE'		;0A
LOSTSM	Db	'LOST'		;0B
NOTSTM	Db	'NOT'		;0C
ATTMTM	Db	'ATTEMPTED TO'	;0D
LOKDEM	Db	'LOCKED/DELETED';0E
SYSTEM	Db	'SYSTEM'	;0F
DIRECM	Db	'DIRECTORY'	;10
MEMORM	Db	'MEMORY'	;11
ONSTRM	Db	'ON'		;12
DISKSM	Db	'DISK'		;13
DISKEM	Db	'DISKETTE'	;14
FAULTM	Db	'FAULT'		;15
PROTEM	Db	'PROTECTED'	;16
ILLEGM	Db	'ILLEGAL'	;17
LOGICM	Db	'LOGICAL'	;18
NUMBEM	Db	'NUMBER'	;19
FILESM	Db	'FILE'		;1A
RECORM	Db	'RECORD'	;1B
ENDSTM	Db	'END'		;1C
OFSTRM	Db	'OF'		;1D
OUTSTM	Db	'OUT'		;1E
RANGEM	Db	'RANGE'		;1F
ENCOUM	Db	'ENCOUNTERED'	;20
CODESM	Db	'CODE'		;21
GATSTM	Db	'GAT'		;22
HITSTM	Db	'HIT'		;23
OVERLM	Db	'OVERLAY'	;24
UNKNOM	Db	'UNKNOWN'	;25
LOADSM	Db	'LOAD'		;26
SPACEM	Db	'SPACE'		;27
ONLYSM	Db	'ONLY'		;28
NAMESM	Db	'NAME'		;29
DEVICM	Db	'DEVICE'	;2A
FORMTM	Db	'FORMAT'	;2B
FOUNDM	Db	'FOUND'		;2C
INSTRM	Db	'IN'		;2D
ACCESM	Db	'ACCESS'	;2E
FULLSM	Db	'FULL'		;2F
DRIVEM	Db	'DRIVE'		;30
DENIEM	Db	'DENIED'	;31
PROGRM	Db	'PROGRAM'	;32
AVAILM	Db	'AVAILABLE'	;33
CANTEM	Db	"- CAN'T EXTEND";34
OPENSM	Db	'OPEN'		;35
;
;
; ERROR MESSAGES DATA STRUCTURES
;
;
; ERROR 00 (00) - NO ERROR
;515B
NOTANE	Db	001H,082H
;
;
; ERROR 01 (01) - PARITY ERROR DURING HEADER READ
;515D
PARHRE	Db	004H,002H,005H,006H,089H
;
;
; ERROR 02 (02) - SEEK ERROR DURING READ
;5162
SEKDRE	Db	008H,002H,005H,089H
;
;
; ERROR 03 (03) - LOST DATA DURING READ
;5166
LOSDRE	Db	00BH,007H,005H,089H
;
;
; ERROR 04 (04) - PARITY ERROR DURING READ
;516A
PARDRE	Db	004H,002H,005H,089H
;
;
; ERROR 05 (05) - DATA RECORD NOT FOUND DURING READ
;516E
RNFDRE	Db	007H,01BH,00CH,02CH,005H,089H
;
;
; ERROR 06 (06) - ATTEMPTED TO READ LOCKED/DELETED DATA RECORD
;5174
LOKDDE	Db	00DH,009H,00EH,007H,09BH
;
;
; ERROR 07 (07) - ATTEMPTED TO READ SYSTEM DATA RECORD
;5179
SYSDRE	Db	00DH,009H,00FH,007H,09BH
;
;
; ERROR 08 (08) - DEVICE NOT AVAILABLE
;517E
DEVNAE	Db	02AH,00CH,0F3H
;
;
; ERROR 09 (09) - PARITY ERROR DURING HEADER WRITE
;5181
PARHWE	Db	004H,002H,005H,006H,08AH
;
;
; ERROR 0A (10) - SEEK ERROR DURING WRITE
;5186
SEKDWE	Db	008H,002H,005H,08AH
;
;
; ERROR 0B (11) - LOST DATA DURING WRITE
;518A
LOSDWE	Db	00BH,007H,005H,08AH
;
;
; ERROR 0C (12) - PARITY ERROR DURING WRITE
;518E
PARDWE	Db	004H,002H,005H,08AH
;
;
; ERROR 0D (13) - DATA RECORD NOT FOUND DURING WRITE
;5192
RNFDWE	Db	007H,01BH,00CH,02CH,005H,08AH
;
;
; ERROR 0E (14) - WRITE FAULT ON DISK DRIVE
;5198
WFAULE	Db	00AH,015H,012H,013H,0B0H
;
;
; ERROR 0F (15) - WRITE PROTECTED DISKETTE
;519D
WPROTE	Db	00AH,016H,094H
;
;
; ERROR 10 (16) - ILLEGAL LOGICAL FILE NUMBER
;51A0
ILLFNE	Db	017H,018H,01AH,099H
;
;
; ERROR 11 (17) - DIRECTORY READ ERROR
;51A4
DIRRDE	Db	010H,009H,082H
;
;
; ERROR 12 (18) - DIRECTORY WRITE ERROR
;51A7
DIRWRE	Db	010H,00AH,082H
;
;
; ERROR 13 (19) - ILLEGAL FILE NAME
;51AA
ILFNAE	Db	017H,01AH,0E9H
;
;
; ERROR 14 (20) - GAT READ ERROR
;51AD
GATRDE	Db	022H,009H,082H
;
;
; ERROR 15 (21) - GAT WRITE ERROR
;51B0
GATWRE	Db	022H,00AH,082H
;
;
; ERROR 16 (22) - HIT READ ERROR
;51B3
HITRDE	Db	023H,009H,082H
;
;
; ERROR 17 (23) - HIT WRITE ERROR
;51B6
HITWRE	Db	023H,00AH,082H
;
;
; ERROR 18 (24) - FILE NOT IN DIRECTORY
;51B9
FILNIE	Db	01AH,00CH,02DH,0D0H
;
;
; ERROR 19 (25) - FILE ACCESS DENIED
;51BD
FACCDE	Db	01AH,02EH,0F1H
;
;
; ERROR 1A (26) - DIRECTORY SPACE FULL
;51C0
DIRSFE	Db	010H,027H,0EFH
;
;
; ERROR 1B (27) - DISK SPACE FULL
;51C3
DSKSFE	Db	013H,027H,0AFH
;
;
; ERROR 1C (28) - END OF FILE ENCOUNTERED
;51C6
EOFENE	Db	01CH,01DH,01AH,0A0H
;
;
; ERROR 1D (29) - RECORD NUMBER OUT OF RANGE
;51CA
RNOORE	Db	01BH,019H,01EH,01DH,09FH
;
;
; ERROR 1E (30) - DIRECTORY FULL - CAN'T EXTEND FILE
;51CF
DIRFUE	Db	010H,02FH,034H,09AH
;
;
; ERROR 1F (31) - PROGRAM NOT FOUND
;51D3
PRNOFE	Db	032H,00CH,0ACH
;
;
; ERROR 20 (32) - ILLEGAL DRIVE NUMBER
;51D6
ILLDRE	Db	017H,030H,0D9H
;
;
; ERROR 21 (33) - NO DEVICE SPACE AVAILABLE
;51D9
NODSPE	Db	001H,02AH,027H,0F3H
;
;
; ERROR 22 (34) - LOAD FILE FORMAT ERROR
;51DD
LODFFE	Db	026H,01AH,02BH,082H
;
;
; ERROR 23 (35) - MEMORY FAULT
;51E1
MEMFAE	Db	011H,095H
;
;
; ERROR 24 (36) - ATTEMPTED TO LOAD READ ONLY MEMORY
;51E3
ROMEME	Db	00DH,026H,009H,028H,091H
;
;
; ERROR 25 (37) - ILLEGAL ACCESS APPEMPTED TO PROTECTED FILE
;51E8
PROTAE	Db	017H,02EH,00DH,016H,09AH
;
;
; ERROR 26 (38) - FILE NOT OPEN
;51ED
FINOPE	Db	01AH,00CH,0F5H
;
;
; ERROR 27 (39) - UNKNOWN ERROR CODE
;51F0
UNKNWE	Db	025H,002H,0A1H
;
	End	OVRL04
