	Title	'TRSDOS 2.3 Disk Operating System'
;
;
; TRSDOS DISK OPERATING SYSTEM, VERSION 2.3
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON 18.01.2022
;
; PART 5 - OVERLAY 5 - DEBUG UTILITY
;
;
; DEFINE IF PATCHES ARE ACTIVE
;
PATCHG	Equ	  0		;PATCHES ACTIVE
;
;
; ASCII EQUATES
;
CR	Equ	 13		;CARRIAGE RETURN
HO	Equ	 28		;HOME DISPLAY CURSOR
EE	Equ	 30		;ERASE TO END OF LINE
CO	Equ	192		;SPACE COMPRESSION (0 TO 63)
;
;
; DEFINE CHUNKY CHARACTER GRAPHICS
;
LEFBAR	Equ	095H		;LEFT VERTICAL BAR
RIGBAR	Equ	0AAH		;RIGHT VERTICAL BAR
;
;
; VIDEO CONSTANTS
;
ROW	Equ	 16		;NUMBER OF SCREEN ROWS
COL	Equ	 64		;NUMBER OF SCREEN COLUMNS
;
;
; VIDEO DEVICE CONTROL BLOCK OFFSETS
;
VIA	Equ	  3		;VIDEO MEMORY POINTER
;
;
; DEFINE OFFSETS INTO CPU REGISTER STORAGE
;
AFM	Equ	  0		;MAIN AF REGISTER
BCM	Equ	  2		;MAIN BC REGISTER
DEM	Equ	  4		;MAIN DE REGISTER
HLM	Equ	  6		;MAIN HL REGISTER
AFA	Equ	  8		;ALTERNATE AF REGISTER
BCA	Equ	 10		;ALTERNATE BC REGISTER
DEA	Equ	 12		;ALTERNATE DE REGISTER
HLA	Equ	 14		;ALTERNATE HL REGISTER
IXR	Equ	 16		;IX REGISTER
IYR	Equ	 18		;IY REGISTER
SPR	Equ	 20		;STACK POINTER
PCR	Equ	 22		;PROGRAM COUNTER
;
;
; DEFINE NUMBER OF Z-80 REGISTERS
;
NUMREG	Equ	(PCR+2)/2	;DEFINE THE COUNT
;
;
; ROUTINES IN BASIC ROM
;
KBCHAR	Equ	0002BH		;INSTANTANEOUS KEYBOARD SCAN
VDCHAR	Equ	00033H		;DISPLAY CHARACTER ON VIDEO
KBWAIT	Equ	00049H		;WAIT FOR A KEY PRESS
;
;
; VIDEO MEMORY LOCATIONS
;
VIDMEM	Equ	03C00H		;START OF VIDEO MEMORY
THIBOL	Equ	03F40H		;THIRD BOTTOM LINE
SECBOL	Equ	03F80H		;SECOND BOTTOM LINE
FIRBOL	Equ	03FC0H		;FIRST BOTTOM LINE
;
;
; VECTORS AT START OF RAM
;
LDBVEC	Equ	0400FH		;RST 28H - LOAD DEBUG
;
;
; DEVICE CONTROL BLOCK ADDRESSES
;
VDUDCB	Equ	0401DH		;VIDEO DCB
;
;
; DEFINE A 'TRAP' INSTRUCTION - RST 30H IS USED HERE
;
TRAP	Equ	0F7H		;DEFINE THE INSTRUCTION
;
;
; TRAP ADDRESSES AT START OF RAM
;
FIRTRA	Equ	0405DH		;FIRST TRAP ADDRESS
FIRTRL	Equ	FIRTRA+0	;TRAP ADDRESS LSB
FIRTRM	Equ	FIRTRA+1	;TRAP ADDRESS MSB
FIRTRB	Equ	FIRTRA+2	;CONTENTS OF THE ADDRESS
SECTRA	Equ	04060H		;SECOND TRAP ADDRESS
SECTRL	Equ	SECTRA+0	;TRAP ADDRESS LSB
SECTRM	Equ	SECTRA+1	;TRAP ADDRESS MSB
SECTRB	Equ	SECTRA+2	;CONTENTS OF THE ADDRESS
THITRA	Equ	04063H		;THIRD TRAP ADDRESS
THITRL	Equ	THITRA+0	;TRAP ADDRESS LSB
THITRM	Equ	THITRA+1	;TRAP ADDRESS MSB
THITRB	Equ	THITRA+2	;CONTENTS OF THE ADDRESS
;
;
; REGISTER LOCATIONS AT START OF RAM
;
BUGREG	Equ	04065H		;DEBUG CONTEXT SAVE AREA
;
;
; TRSDOS ADDRESSESS
;
DEBUGJ	Equ	04315H		;DEBUG ON/OFF FLAG AND JUMP
;
;
; PROGRAM MODULE NAME STRING
;
	Nam	'SYS5  '
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING
;
	Rem	CR
	Rem	'* * * N O T I C E * * *',CR
	Rem	'* PROPRIETARY PROGRAM *',CR
	Rem	'* COPYRIGHT (c) 1979  *',CR
	Rem	'* BY TANDY CORPORATION*',CR
	Rem	'*  FORT WORTH, TEXAS  *',CR
	Rem	'* ALL RIGHTS RESERVED *',CR
	Rem	'* * * N O T I C E * * *',CR
;
;
	Org	04E00H
;
OVRL05:	POP	AF		;REMOVE RETURN ADDRESS
	POP	AF		;RECOVER AF REGISTER
	PUSH	AF		;RE-SAVE AF REGISTER
	PUSH	IY		;SAVE IY REGISTER
	PUSH	IX		;SAVE IX REGISTER
	EX	AF,AF'		;SWAP IN ALTERNATE AF REGISTER
	EXX			;SWAP IN ALTERNATE REGISTERS
	PUSH	HL		;SAVE ALTERNATE HL REGISTER
	PUSH	DE		;SAVE ALTERNATE DE REGISTER
	PUSH	BC		;SAVE ALTERNATE BC REGISTER
	PUSH	AF		;SAVE ALTERNATE AF REGISTER
	EX	AF,AF'		;SWAP IN MAIN AF REGISTER
	EXX			;SWAP IN MAIN REGISTERS
	PUSH	HL		;SAVE HL REGISTER
	PUSH	DE		;SAVE DE REGISTER
	PUSH	BC		;SAVE BC REGISTER
	PUSH	AF		;SAVE AF REGISTER
	LD	HL,0		;ZERO HL REGISTER
	ADD	HL,SP		;GET STACK POINTER TO HL
	LD	DE,BUGREG	;POINT AT CONTEXT SAVE AREA
	LD	BC,NUMREG*2	;LOAD REGISTER COUNT * WORD
	LDIR			;COPY REGISTERS INTO STORE
	LD	(BUGREG+SPR),HL	;SAVE STACK POINTER
	LD	SP,HL		;SET UP LOCAL TOP OF STACK
	LD	HL,(BUGREG+PCR)	;GET SAVED PROGRAM COUNTER
	DEC	HL		;BACKUP PROGRAM COUNTER
	LD	A,(HL)		;GET BYTE FROM MEMORY
	CP	TRAP		;TEST IF 'TRAP' INSTRUCTION
	JR	NZ,NOTRAP	;CONTINUE IF IT ISN'T
	LD	(BUGREG+PCR),HL	;SAVE PROGRAM COUNTER
NOTRAP:	LD	HL,FIRTRA	;POINT AT FIRST TRAP ADDRESS
	LD	B,2		;LOAD TABLE ENTRY COUNT
LPTRAP:	XOR	A		;ZERO THE ACCUMULATOR
	LD	C,2		;LOAD C WITH 2 - REDUNDANT
	LD	E,(HL)		;GET FIRST TRAP ADDRESS LSB
	LD	(HL),A		;ZERO TRAP ADDRESS LSB
	INC	HL		;BUMP TO ADDRESS MSB
	LD	D,(HL)		;FIRST TRAP ADDRESS MSB
	LD	(HL),A		;ZERO TRAP ADDRESS MSB
	INC	HL		;BUMP TO MEMORY BYTE
	LD	A,E		;GET TRAP ADDRESS LSB TO A
	OR	D		;TEST IF TRAPPING CODE
	JR	Z,NXTRAP	;ALL DONE IF NOT
	LD	A,(DE)		;FIRST TRAP ADDSESS BYTE
	CP	TRAP		;TEST IF 'TRAP' INSTRUCTION
	JR	NZ,NXTRAP	;ALL DONE IF NOT
	LD	A,(HL)		;ELSE BYTE AT TRAP ADDRESS
	LD	(DE),A		;RESTORE THE BYTE
NXTRAP:	INC	HL		;BUMP TO NEXT TRAP ADDRESS
	DJNZ	LPTRAP		;LOOP FOR NEXT TRAP ADDRESS
;
;
; MAIN DEBUGGER COMMAND LOOP - GET COMMAND CHARACTER
;4E4B
CMDLUP:	LD	SP,(BUGREG+SPR)	;INIT LOCAL STACK POINTER
	CALL	DSPREG		;UPDATE THE DISPLAY
	LD	HL,FIRBOL	;FIRST BOTTOM VIDEO LINE
	LD	(VDUDCB+VIA),HL	;STORE IN VIDEO DCB
	CALL	WAITKB		;GET KEYBOARD CHARACTER
	CP	'G'		;TEST IF EXECUTE COMMAND
	JP	Z,EXECUT	;THEN PROCESS THE COMMAND
	LD	HL,CMDLUP	;LOAD COMMAND LOOP ADDRESS
	PUSH	HL		;SET AS RETURN POINT ADDRESS
	CP	'S'		;TEST IF MEMORY DISPLAY
	JR	Z,MEMDSP	;THEN SWITCH TO MEMORY DISPLAY
	CP	';'		;TEST IF NEXT MEMORY BLOCK
	JR	Z,NXTDSP	;THEN SHOW THE BLOCK
	CP	'-'		;TEST IF PREVIOUS MEMORY BLOCK
	JR	Z,PRVDSP	;THEN SHOW THE BLOCK
	CP	'A'		;TEST IF ASCII DISPLAY
	JR	Z,ASCDSP	;THEN SWITCH TO ASCII
	CP	'C'		;TEST IF SINGLE STEP WITH CALLS
	JR	Z,STPNXB	;THEN GO HANDLE THE STEP
	CP	'D'		;TEST IF DISPLAY MEMORY
	JR	Z,DSPMEM	;THEN DUMP THE LOCATION
	CP	'H'		;TEST IF HEX DISPLAY
	JR	Z,HEXDSP	;THEN SWITCH TO HEX
	CP	'I'		;SINGLE STEP NEXT INSTRUCTION
STPNXB:	JP	Z,STPNXT	;THEN GO HANDLE THE STEPS
	CP	'M'		;TEST IF MODIFY MEMORY
	JP	Z,MODMEM	;THEN MODIFY THE MEMORY
	CP	'R'		;TEST IF MODIFY REGISTER
	JP	Z,MODREG	;THEN MODIFY THE REGISTER
	CP	'U'		;DYNAMIC DISPLAY
	JR	Z,DYNDSP	;THEN WAIT FOR ABORT
	CP	'X'		;TEST IF REGISTER DISPLAY
	JR	Z,REGDSP	;THEN SWITCH TO REGISTER
	RST	28H		;ELSE PASS REQUEST TO TRSDOS
	RET
;
;
; 'X' COMMAND - REGISTER DISPLAY FORMAT
; EXIT:   FIRTRA  - MSB SET TO ZERO
;4E99
REGDSP:	XOR	A		;LOAD REGISTER DISPLAY FLAG
;
;
; 'S' COMMAND - MEMORY DISPLAY FORMAT
; ENTRY:  A       - THE CHARACTER 'S'
; EXIT:   FIRTRA  - MSB SET TO 'S'
;4E9A
MEMDSP:	LD	(FIRTRM),A	;FLAG MEMORY DISPLAY
	RET
;
;
; 'U' COMMAND - DYNAMIC DISPLAY USING INTERRUPTS
;4E9E
DYNDSP:	CALL	KBCHAR		;SCAN THE KEYBOARD
	OR	A		;TEST IF ANY KEYPRESS
	RET	NZ		;ALL DONE IF NO KEY
	CALL	DSPREG		;UPDATE DISPLAY CONTINUALLY
	JR	DYNDSP		;LOOP UNTIL ABORTED
;
;
; 'D' COMMAND - DISPLAY MEMORY
;4EA8
DSPMEM:	CALL	HEXADR		;GET ADDRESS FROM KEYBOARD
	RET	Z		;EXIT IF NO ADDRESS ENTERED
	JR	UPDADR		;ELSE STORE THE ADDRESS
;
;
; ';' COMMAND - ADJUST DISPLAY ADDRESS FORWARDS
;4EAE
NXTDSP:	LD	BC,COL		;LOAD COLUMN COUNT TO BC
;
;
; ADJUST DISPLAY ADDRESS FORWARDS OF BACKWARDS
; ENTRY:  BC      - POSITIVE OR NEGATIVE DISPLAY ADJUSTMENT
;         FIRTRA  - CURRENT TRAP ADDRESS
;         THITRA  - CURRENT DISPLAY ADDRESS
; EXIT:   THITRA  - NEW DISPLAY ADDRESS
;4EB1
ADJDSP:	LD	HL,(THITRA)	;GET CURRENT DISPLAY ADDRESS
	LD	A,(FIRTRM)	;GET TRAP ADDRESS MSB
	OR	A		;TEST IF CURRENTLY TRAPPING
	JR	Z,DSPADJ	;ALL DONE IF NOT
	LD	C,0		;ELSE ZERO ADJUSTMENT LSB
	LD	A,B		;LOAD ADJUSTMENT MSB TO A
	OR	A		;TEST IF MSB IS ZERO
	JR	NZ,DSPADJ	;SKIP IF IT ISN'T
	INC	B		;ELSE INCREMENT MSB
;
;
; ADJUST DISPLAY ADDRESS
; ENTRY:  BC      - DISPLAY ADJUSTMENT VALUE
;         HL      - CURRENT DISPLAY ADDRESS
; EXIT:   HL      - ADJUSTED ADDRESS
;         THITRA  - NEW DISPLAY ADDRESS
;4EC1
DSPADJ:	ADD	HL,BC		;ADD OFFSET TO CURRENT ADDRESS
;
;
; STORE ADDRESS FOR CURRENT COMMAND
; ENTRY:  HL      - NEW OR UPDATED ADDRESS
; EXIT:   HL      - NEW DISPLAY ADDRESS
;         THITRA  - UPDATED ADDRESS
;4EC2
UPDADR:	LD	(THITRA),HL	;SAVE THE ADDRESS
	RET
;
;
; '-' COMMAND - ADJUST DISPLAY ADDRESS BACKWARDS
;4EC6
PRVDSP:	LD	BC,-COL		;LOAD NEGATIVE COLUMN COUNT
	JR	ADJDSP		;ADJUST DISPLAY ADDRESS
;
;
; 'A' COMMAND - ASCII DISPLAY FORMAT
; ENTRY:  A       - FORMAT BYTE 'A' FOR ASCII
;
ASCDSP:
;
;
; 'H' COMMAND - HEXADECIMAL DISPLAY FORMAT
; ENTRY:  A       - FORMAT BYTE 'H' FOR HEXADECIMAL
;4ECB
HEXDSP:	LD	(FIRTRL),A	;STORE THE FORMAT BYTE
	RET
;
;
; REGISTER DISPLAY - UPDATE THE DISPLAY
;4ECF
DSPREG:	LD	A,(FIRTRM)	;GET 'TRAP' ADDRESS MSB
	OR	A		;TEST IF TRAPPING ON
	JR	NZ,DSPALL	;DISPLAY REGISTERS AND DATA
	LD	A,HO		;LOAD CURSOR HOME CHARACTER
	CALL	VDCHAR		;MOVE DISPLAY CURSOR HOME
	LD	HL,BUGREG	;POINT AT REGISTERS
	PUSH	HL		;SAVE REGISTER POINTER
	LD	HL,REGNAM	;POINT AT REGISTER NAMES
	LD	B,NUMREG	;LOAD REGISTER COUNT
	JR	REGALL		;GO DISPLAY THE REGISTERS
;
;
; DISPLAY REGISTER ADDRESS AND DATA POINTED TO BY REGISTERS
;
; -- PRECEDE BY A NEWLINE --
;4EE5
ALLREG:	LD	A,CR		;LOAD NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
;
;
; DISPLAY REGISTER ADDRESS AND DATA POINTED TO BY REGISTERS
;
; -- NO NEWLINE PRECEDED --
;4EEA
REGALL:	CALL	MEMTCH		;DISPLAY THREE MEMORY BYTES
	EX	(SP),HL		;GET TOP OF STACK TO HL
	LD	E,(HL)		;GET ADDRESS LSB TO E
	INC	HL		;BUMP TO NEXT ADDRESS BYTE
	LD	D,(HL)		;GET ADDRESS MSB TO D
	INC	HL		;BUMP TO NEXT ADDRESS
	PUSH	HL		;SAVE THE MEMORY POINTER
	EX	DE,HL		;SWAP THE ADDRESS TO HL
	LD	A,'='		;LOAD EQUALS CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	CALL	DSPSPC		;DISPLAY ASCII SPACE CHARACTER
	LD	A,H		;LOAD REGISTER CONTENTS MSB
	CALL	HEXSPC		;DISPLAY HEX FOLLOWED BY SPACE
	LD	A,L		;LOAD REGISTER CONTENTS LSB
	CALL	HEXSPC		;DISPLAY HEX FOLLOWED BY SPACE
	LD	A,B		;GET REGISTER COUNT TO A
	AND	00001011B	;MASK TO RELEVANT BITS
	CP	00001000B	;TEST IF EIGHT DONE
	JR	NZ,REGARD	;DUMP REGISTER AND DATA IF NOT
	LD	C,L		;ELSE GET ADDRESS LSB TO C
	PUSH	BC		;SAVE REGISTER COUNT
	LD	HL,FLGNAM	;POINT AT FLAG CHARACTERS
	LD	B,8		;LOAD FLAG COUNT TO B
REGAFL:	SLA	C		;SHIFT FLAG TO A
	LD	A,(HL)		;GET FLAG CHARACTER TO A
	JR	C,REGANF	;SKIP IF UNDEFINED FLAG
	LD	A,'-'		;LOAD MINUS CHARACTER
REGANF:	CALL	VDCHAR		;DISPLAY FLAG CHARACTER
	INC	HL		;BUMP FLAG TABLE POINTER
	DJNZ	REGAFL		;LOOP FOR NEXT FLAG
	POP	BC		;RECOVER REGISTER COUNT
	LD	A,CO+44		;DISPLAY 44 SPACES
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	JR	REGASD		;THEN SKIP REGISTER DUMP
REGARD:	CALL	REGDTA		;DISPLAY REGISTER AND DATA
REGASD:	POP	HL		;GET RETURN ADDRESS TO HL
	EX	(SP),HL		;SWAP MEMORY ADDRESS TO HL
	DJNZ	ALLREG		;DO NEXT REGISTER AND DATA
	POP	HL		;CLEAN UP THE STACK
	LD	HL,(THITRA)	;LOAD ADDRESS TO HL
	LD	B,4		;LOAD LINE COUNTER
;
;
; DISPLAY SEVEN SPACES, A CHARACTER, SPACE, REGISTER AND DATA
; ENTRY:  B       - NUMBER OF REGISTER LINES
;4F34
DSPRDA:	LD	A,CO+7		;DISPLAY 7 SPACES
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	CALL	WORHEX		;DISPLAY HEXADECIMAL ADDRESS
	CALL	DSPSPC		;DISPLAY ASCII SPACE CHARACTER
	CALL	REGDTA		;DISPLAY REGISTER AND DATA
	DJNZ	DSPRDA		;LOOP UNTIL ALL DONE
	RET
;
;
; DISPLAY ALL REGISTERRS AND DATA ON THE SCREEN
;4F45
DSPALL:	LD	HL,VIDMEM-1	;LOAD VIDEO MEMORY ADDRESS
	LD	(VDUDCB+VIA),HL	;STORE IN VIDEO DCB
	LD	HL,(THITRA)	;POINT AT VIDEO LOCATION
	LD	L,0		;ZERO LSB OF VIDEO ADDRESS
	LD	B,ROW		;LOAD ROW COUNT TO B
	JR	DSPRDA		;DISPLAY REGISTERS AND DATA
;
;
; PROCESSOR REGISTER NAMES
;4F54
REGNAM	Db	"AF "		;MAIN AF REGISTER
	Db	"BC "		;MAIN BC REGISTER
	Db	"DE "		;MAIN DE REGISTER
	Db	"HL "		;MAIN HL REGISTER
	Db	"AF'"		;ALTERNATE AF REGISTER
	Db	"BC'"		;ALTERNATE BC REGISTER
	Db	"DE'"		;ALTERNATE DE REGISTER
	Db	"HL'"		;ALTERNATE HL REGISTER
	Db	"IX "		;IX REGISTER
	Db	"IY "		;IY REGISTER
	Db	"SP "		;STACK POINTER
	Db	"PC "		;PROGRAM COUNTER
;
;
; PROCESSOR FLAG NAMES
;4F78
FLGNAM	Db	'S'		;SIGN
	Db	'Z'		;ZERO
	Db	'1'		;UNUSED
	Db	'H'		;HALF CARRY
	Db	'1'		;UNUSED
	Db	'P'		;PARITY/OVERFLOW
	Db	'N'		;DECIMAL ADD/SUBTRACT
	Db	'C'		;CARRY
;
;
; 'G' COMMAND - EXECUTE PROGRAM WITH UP-TO TWO TRAP ADDRESSES
;4F80
EXECUT:	LD	B,2		;COLLECT UP-TO TWO ADDRESSES
	LD	DE,SECTRB	;POINT AT TRAP ADDRESS TABLE
	CALL	HEXADR		;GET ADDRESS FROM KEYBOARD
	JR	Z,EXECNA	;SKIP IF NO ADDRESS ENTERED
	LD	(BUGREG+PCR),HL	;STORE AS PROGRAM COUNTER
EXECNA:	JR	C,EXECEN	;SKIP IF NOTHING FOLLOWS
	CALL	HEXADR		;GET ADDRESS FROM KEYBOARD
	PUSH	AF		;SAVE ADDRESS FOUND FLAG
	CALL	NZ,SVTRAD	;SAVE ADDRESS IF ENTERED
	POP	AF		;RECOVER ADDRESS FOUND FLAG
	DJNZ	EXECNA		;LOOP FOR NEXT ADDRESS
EXECEN:	LD	HL,LDBVEC	;POINT AT DEBUG LOAD VECTOR
	LD	(DEBUGJ+1),HL	;SET JUMP LOCATION IN TRSDOS
	LD	A,0C3H		;LOAD 'JP' OP-CODE
	LD	(DEBUGJ),A	;STORE OP-CODE IN TRSDOS
;
;
; COPY REGISTER VALUES FROM OR TO CONTEXT AREA TO OR FROM STACK
;4FA4
EXECXF:	LD	HL,BUGREG+SPR+1	;POINT AT STACK POINTER MSB
	LD	B,NUMREG-1	;LOAD REGISTER COUNT TO B
EXECSR:	LD	D,(HL)		;GET WORD MSB FROM THE STACK
	DEC	HL		;BACKUP STACK INDEX
	LD	E,(HL)		;GET WORD LSB FROM THE STACK
	DEC	HL		;BACKUP STACK INDEX
	PUSH	DE		;PUT THE WORD ON THE STACK
	DJNZ	EXECSR		;LOOP FOR NEXT REGISTER PAIR
	POP	AF		;RECOVER AF REGISTER
	POP	BC		;RECOVER BC REGISTER
	POP	DE		;RECOVER DE REGISTER
	POP	HL		;RECOVER HL REGISTER
	EX	AF,AF'		;SWAP TO ALTERNATE AF
	EXX			;SWAP TO ALTERNATE REGISTERS
	POP	AF		;RECOVER ALTERNATE AF
	POP	BC		;RECOVER ALTERNATE BC
	POP	DE		;RECOVER ALTERNATE DE
	POP	HL		;RECOVER ALTERNATE HL
	EX	AF,AF'		;SWAP TO MAIN AF REGISTER
	EXX			;SWAP TO MAIN REGISTERS
	POP	IX		;RECOVER IX REGISTER
	POP	IY		;RECOVER IY REGISTER
	POP	HL		;RECOVER SP REGISTER
	LD	SP,HL		;COPY HL TO STACK POINTER
	LD	HL,(BUGREG+PCR)	;GET PROGRAM COUNTER TO HL
	PUSH	HL		;RESTORE EXECUTION ADDRESS
	LD	HL,(BUGREG+HLM)	;RESTORE HL REGISTER
	RET
;
;
; STORE TRAP ADDRESS IN ADDRESS TABLE
; ENTRY:  DE      - POINTER TO TRAP ADDRESS TABLE
;         HL      - THE TRAP ADDRESS
; EXIT:   DE      - UPDATED TRAP ADDRESS TABLE POINTER
;4FCA
SVTRAD:	LD	A,(HL)		;GET A BYTE FROM MEMORY
	LD	(DE),A		;SAVE IN THE TRAP TABLE
	DEC	DE		;BACKUP TRAP TABLE POINTER
	LD	A,TRAP		;LOAD 'TRAP' INSTRUCTION
	LD	(HL),A		;SET EXECUTION TRAPPING
	CP	(HL)		;TEST IF TRAPPING ROM
	JP	NZ,NOTRAP	;EXIT IF TRYING TO TRAP ROM
	LD	A,H		;GET TRAP ADDRESS MSB
	LD	(DE),A		;SAVE IN THE TRAP TABLE
	DEC	DE		;BACKUP TRAP TABLE POINTER
	LD	A,L		;GET TRAP ADDRESS LSB
	LD	(DE),A		;SAVE IN THE TRAP TABLE
	DEC	DE		;BACKUP TRAP TABLE POINTER
	RET
;
;
; 'M' COMMAND - MODIFY MEMORY
;4FDB
MODMEM:	LD	HL,(SECTRA)	;GET MODIFY ADDRESS
	CALL	HEXADR		;GET ADDRESS FROM KEYBOARD
MODMEL:	LD	(SECTRA),HL	;SAVE ENTERED ADDRESS
	RET	C		;EXIT IF CARRIAGE RETURN
	PUSH	HL		;SAVE MODIFY ADDRESS
	CALL	DSPREG		;UPDATE DISPLAY IF CHANGED
	LD	HL,THIBOL	;THIRD BOTTOM VIDEO LINE
	LD	(VDUDCB+VIA),HL	;STORE ADDRESS IN DCB
	LD	HL,(SECTRA)	;GET MEMORY ADDRESS TO HL
	CALL	WORHEX		;DISPLAY HEXADECIMAL ADDRESS
	PUSH	HL		;SAVE MEMORY ADDRESS
	LD	HL,SECBOL	;SECOND BOTTOM VIDEO LINE
	LD	(VDUDCB+VIA),HL	;STORE IN VIDEO DCB
	POP	HL		;RECOVER MEMORY ADDRESS
	CALL	MEMHEX		;DISPLAY MEMORY BYTE IN HEX
	LD	A,'-'		;LOAD A MINUS CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	POP	DE		;RECOVER MODIFY ADDRESS
	CALL	HEXADR		;GET WORD FROM KEYBOARD
	EX	DE,HL		;SWAP THE BYTE TO E
	JR	Z,MODMEN	;DONE IF NO ADDRESS
	LD	(HL),E		;STORE THE BYTE IN MEMORY
MODMEN:	RET	C		;DONE IF CARRIAGE RETURN
	INC	HL		;BUMP MEMORY LOCATION
	JR	MODMEL		;LOOP FOR NEXT MODIFY BYTE
;
;
; 'R' COMMAND - MODIFY A REGISTERS CONTENTS
;5011
MODREG:	CALL	WAITKB		;GET KEYBOARD CHARACTER
	RET	Z		;DONE IF SPACE OR A COMMA
	LD	C,A		;SAVE CHARACTER IN C
	CALL	WAITKB		;GET KEYBOARD CHARACTER
	RET	Z		;DONE IF SPACE OR A COMMA
	LD	D,A		;SAVE CHARACTER IN D
	LD	E,' '		;LOAD SPACE CHARACTER
	CALL	WAITKB		;GET KEYBOARD CHARACTER
	RET	C		;DONE IF 'ENTER' KEY
	JR	Z,MODRTM	;SKIP IF NO MORE CHARACTERS
	LD	E,A		;COPY CHARACTER TO E
	CALL	WAITKB		;GET KEYBOARD CHARACTER
	RET	NZ		;DONE IF SPACE OR A COMMA
	RET	C		;DONE IF 'ENTER' KEY
MODRTM:	LD	HL,REGNAM	;POINT AT REGISTER NAMES
	LD	B,NUMREG	;LOAD REGISTER COUNT
MODRTL:	LD	A,(HL)		;GET REGISTER NAME CHARACTER
	CP	C		;TEST IF REGISTER NAME MATCH
	JR	Z,MODRTN	;CONTINUE IF NAME MATCH
	INC	HL		;BUMP PAST NAME CHARACTER
MODRNE:	INC	HL		;BUMP PAST NAME CHARACTER
MODRNI:	INC	HL		;BUMP PAST NAME CHARACTER
	DJNZ	MODRTL		;LOOP UNTIL ALL TESTED
	RET
;
;
; TEST FOR REGISTER NAME MATCH AND MODIFY CONTENTS IF FOUND
; ENTRY:  B       - INDEX INTO REGISTER NAME
;         D       - SECOND REGISTER NAME CHARACTER
;         E       - THIRD REGISTER NAME CHARACTER
;         HL      - POINTER TO REGISTER NAME
;5038
MODRTN:	INC	HL		;BUMP TO NEXT CHARACTER
	LD	A,(HL)		;GET REGISTER NAME CHARACTER
	CP	D		;TEST IF REGISTER NAME MATCH
	JR	NZ,MODRNE	;BUMP TO NEXT IF MISMATCH
	INC	HL		;BUMP TO NEXT CHARACTER
	LD	A,(HL)		;GET REGISTER NAME CHARACTER
	CP	E		;TEST IF REGISTER NAME MATCH
	JR	NZ,MODRNI	;BUMP TO NEXT IF MISMATCH
	LD	A,NUMREG*2	;GET REGISTER COUNT * WORD
	SUB	B		;SUBTRACT CURRENT COUNT
	SUB	B		;SUBTRACT CURRENT COUNT AGAIN
	LD	C,A		;COPY RESULT TO C
	LD	B,0		;REMAINING COUNT IS IN BC
	LD	HL,BUGREG	;POINT AT CONTEXT SAVE AREA
	ADD	HL,BC		;INDEX TO REGISTER WORD
	PUSH	HL		;SAVE REGISTER WORD INDEX
	LD	A,EE		;ERASE TO LINE END CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	POP	DE		;GET REGISTER WORD INDEX
	CALL	HEXADR		;GET ADDRESS FROM KEYBOARD
	RET	Z		;DONE IF NO ADDRESS ENTERED
	EX	DE,HL		;SWAP ADDRESS AND DATA
	LD	(HL),E		;STORE REGISTER CONTENTS LSB
	INC	HL		;BUMP TO MSB
	LD	(HL),D		;STORE REGISTER CONTENTS MSB
	RET
;
;
; 'C' COMMAND - SINGLE STEP WITH CALLS
;
STPCAL:
;
;
; 'I' COMMAND - SINGLE STEP NEXT INSTRUCTION
;505D
STPNXT:	PUSH	AF		;SAVE COMMAND CHARACTER
	LD	DE,(BUGREG+PCR)	;LOAD RESUMPTION ADDRESS
	LD	A,(DE)		;LOAD 'OP'CODE' AT ADDRESS
	LD	HL,GRPTRI	;GROUP 3 INSTRUCTION TYPES
	CP	0DDH		;TEST FOR INDEXED INSTRUCTION
	JR	Z,ISINDX	;SKIP IF 'IX' INSTRUCTION
	CP	0FDH		;ELSE TEST FOR 'IY' INSTRUCTION
	JR	Z,ISINDX	;SKIP IF 'IY' INSTRUCTION
	LD	HL,GRPONE	;GROUP 1 INSTRUCTION TYPES
	CP	0EDH		;TEST FOR SPECIAL INSTRUCTION
	JR	NZ,NOTIDS	;GO IF NOT INDEXED OR SPECIAL
	LD	HL,GRPTWO	;GROUP 2 INSTRUCTION TYPES
ISINDX:	INC	DE		;BUMP TO NEXT INSTRUCTION BYTE
	LD	A,(DE)		;GET NEXT INSTRUCTION BYTE
	DEC	DE		;BACSPACE TO INSTRUCTION START
NOTIDS:	LD	C,A		;COPY OP-CODE LSB TO C
NXTENT:	LD	A,(HL)		;FETCH OP-CODE MASK
	AND	C		;APPLY MASK TO OP-CODE LSB
	INC	HL		;BUMP TO OP-CODE IN LIST
	CP	(HL)		;COMPARE TO CODE IN TABLE
	INC	HL		;BUMP TO CODE LENGTH VALUE
	JR	Z,OPCMAT	;JUMP IF OP-CODES MATCH
	INC	HL		;BUMP TO NEXT TABLE ENTRY
	LD	A,(HL)		;FETCH OP-CODE MASK
	CP	005H		;TEST FOR END OF LIST
	JR	NC,NXTENT	;LOOP IF END NOT REACHED
OPCMAT:	LD	A,(HL)		;GET INSTRUCTION LENGTH TO A
	LD	B,A		;SAVE THE LENGTH IN B
	AND	00001111B	;ISOLATE INSTRUCTION LENGTH
	LD	L,A		;GET LENGTH BYTE TO L
	LD	H,0		;HL HAS INSTRUCTION LENGTH
	ADD	HL,DE		;ADD NEXT INSTRUCTION ADDRESS
	PUSH	DE		;SAVE INSTRUCTION ADDRESS
	LD	DE,SECTRB	;POINT AT TRAP ADDRESS TABLE
	CALL	SVTRAD		;SAVE THE TRAP ADDRESS
	POP	HL		;ADDRESS AFTER CURRENT ADDRESS
	LD	A,B		;GET SAVED LENGTH TO A
	AND	11110000B	;ISOLATE INSTRUCTION TYPE
	JR	Z,SGLCAL	;EXECUTE IF JUST DROP TO NEXT
	INC	HL		;BUMP NEXT INSTRUCTION ADDRESS
	CP	00100000B	;TEST REGISTER JUMP INSTRUCTION
	JR	C,GEJEXE	;EXECUTE IF 'JP (HL)'
	JR	Z,TSTIRJ	;HANDLE INDEX REGISTER JUMP
	CP	01000000B	;TEST JUMP TYPE INSTRUCTION
	JR	C,TSTREL	;GO HANDLE RELATIVE JUMP
	JR	Z,NXTSGL	;ELSE HANDLE ABSOLUTE JUMP
	CP	01100000B	;TEST RETURN TYPE INSTRUCTION
	JR	C,SGLNXT	;GO HANDLE 'RET' INSTRUCTIONS
	POP	AF		;RECOVER COMMAND CHARACTER
	CP	'I'		;TEST IF SINGLE STEP NEXT
	JR	Z,NXTSGL	;THEN GO DO THE SINGLE STEP
;
;
; SINGLE STEP WITH CALLS
;50B4
SGLCAL:	JP	EXECXF		;THEN ENTER EXECUTION LOOP
;
;
; SINGLE STEP NEXT INSTRUCTION
;50B7
SGLNXT:	LD	HL,(BUGREG+SPR)	;GET RETURN ADDRESS FROM STACK
;
;
; SINGLE STEP NEXT INSTRUCTION
;50BA
NXTSGL:	LD	A,(HL)		;GET RETURN ADDRESS LSB
	INC	HL		;BUMP TO THE MSB
	LD	H,(HL)		;GET RETURN ADDRESS MSB
	LD	L,A		;HL HAS THE ADDRESS
	JR	STOEXE		;RESTORE CONTEXT AND EXECUTE
;
;
; EXECUTE RELATIVE BRANCH
;50C0
TSTREL:	LD	C,(HL)		;GET OFFSET FOR BRANCH TO C
	XOR	A		;ASSUME FORWARD BRANCH
	BIT	7,C		;TEST IF POSITIVE VALUE
	JR	Z,RELFWD	;THEN DO FORWARD BRANCH
	CPL			;ELSE COMPLEMENT BRANCH VALUE
RELFWD:	LD	B,A		;GET DISPLACEMENT MSB TO B
	INC	HL		;BUMP INSTRUCTION ADDRESS
	ADD	HL,BC		;NEXT INSTRUCTION ADDRESS IN HL
	JR	STOEXE		;RESTORE CONTEXT AND EXECUTE
;
;
; TEST FOR REGISTER JUMP
;50CC
TSTIRJ:	LD	HL,(BUGREG+IXR)	;GET IX REGISTER CONTENTS
	BIT	5,C		;TEST IF IX REGISTER JUMP
	JR	Z,STOEXE	;THEN TRAP THE REGISTER JUMP
	LD	HL,(BUGREG+IYR)	;GET IY REGISTER CONTENTS
	JR	STOEXE		;RESTORE CONTEXT AND EXECUTE
:
;
; GET JUMP ADDRESS, STORE TRAP, RESTORE CONTEXT AND EXECUTE
;50D8
GEJEXE:	LD	HL,(BUGREG+HLM)	;GET JUMP ADDRESS TO HL
;
;
; STORE TRAP INSTRUCTION, RESTORE CONTEXT AND EXECUTE
;50DB
STOEXE:	CALL	SVTRAD		;SAVE THE TRAP ADDRESS
	JR	SGLCAL		;RESTORE CONTEXT AND EXECUTE
;
;
; GROUP 1 INSTRUCTION LIST
;
; EACH ENTRY HAS THE FOLLOWING FORMAT:
;
;   MASK, OPCODE, TYPE OR LENGTH
;
; TYPE IS A CODE INDICATING WHERE THE ADDRESS OF OF THE NEXT
; INSTRUCTION MAY BE FOUND, TYPE CODES DEFINED AS FOLLOWS:
;
;   0 - NEXT INSTRUCTION FOLLOWS CURRENT INSTRUCTION
;   1 - NEXT INSTRUCTION ADDRESS COMES FROM HL AS IN JP (HL)
;   2 - NEXT INSTRUCTION ADDRESS CONDITIONALLY COMES FROM
;       OPERAND, AS IN JP C,XXXX
;   3 - CONDITIONAL AS IN DJNZ XXXX
;   4 - OPERAND AS IN JP XXXX
;   5 - CONDITIONAL AND INDIRECT AS IN RET, OR RET NZ
;   6 - CONDITIONAL, OPERAND AS IN CALL NZ,XXXX OR CALL XXXX
;50E0
GRPONE	Db	0C7H,0C0H,051H
	Db	0FFH,0C9H,051H
	Db	0FFH,0E9H,011H
	Db	0CFH,001H,003H
	Db	0E7H,022H,003H
	Db	0C7H,0C2H,043H
	Db	0FFH,0C3H,043H
	Db	0C7H,0C4H,063H
	Db	0FFH,0CDH,063H
	Db	0C7H,006H,002H
	Db	0F7H,0D3H,002H
	Db	0C7H,0C6H,002H
	Db	0FFH,0CBH,002H
	Db	0F7H,010H,032H
	Db	0E7H,020H,032H
	Db	001H
;
;
; DEFAULT LENGTH FOR INSTRUCTIONS NOT MATCHING THOSE IN LIST
;
; GROUP 2 INSTRUCTION LIST
;
; EACH BYTE HAS THE FOLLOWING FORMAT:
;
;   MASK, OPCODE, TYPE OR LENGTH
;
; LENGTH EQUALS THE LENGTH OF THE CURRENT OPCODE
;510E
GRPTWO	Db	0C7H,043H,004H
	Db	0F7H,045H,052H
	Db	002H
;
;
; DEFAULT LENGTH FOR ANY INSTRUCTIONS NOT MATCHING LISTS ABOVE
;
; GROUP 3 INSTRUCTION LIST
;
; EACH BYTE HAS THE FOLLOWING FORMAT:
;
;   MASK, OPCODE, TYPE OR LENGTH
;
; LENGTH EQUALS THE LENGTH OF THE CURRENT OPCODE
;5115
GRPTRI	Db	0FEH,034H,003H
	Db	0C0H,040H,003H
	Db	0C0H,080H,003H
	Db	0FFH,021H,004H
	Db	0FFH,022H,004H
	Db	0FFH,02AH,004H
	Db	0FFH,036H,004H
	Db	0FFH,0CBH,004H
	Db	0FFH,0E9H,022H
	Db	002H
;
;
; DISPLAY ALL REGISTER VALUES AND THE MEMORY THEY POINT AT
;5131
REGDTA:	PUSH	BC		;SAVE BC REGISTER
	LD	A,'='		;LOAD EQUALS CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	LD	A,'>'		;LOAD GREATER THAN CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	CALL	DSPSPC		;DISPLAY ASCII SPACE CHARACTER
	LD	B,16		;LOAD BYTE COUNTER
REGDTL:	CALL	PUTBAR		;BARS AROUND MODIFY LOCATION
	LD	A,(FIRTRL)	;GET DISPLAY FORMAT TO A
	CP	'A'		;TEST IF ASCII DISPLAY
	JR	NZ,HEXDIS	;SKIP IF HEX DISPLAY
	CALL	DSPSPC		;DISPLAY ASCII SPACE CHARACTER
	LD	A,(HL)		;LOAD BYTE FROM MEMORY
	CP	' '		;TEST IF CONTROL CHARACTER
	JR	C,REGDTD	;DISPLAY A DOT IF IT IS
	CP	CO		;TEST IF COMPRESSION CODE
	JR	C,REGDTN	;CONTINUE IF IT ISN'T
REGDTD:	LD	A,'.'		;LOAD DECIMAL POINT CHARACTER
REGDTN:	CALL	VDCHAR		;DISPLAY THE CHARACTER
	INC	HL		;BUMP MEMORY POINTER
	XOR	A		;FLAG PROCESSING ASCII DISPLAY
;
;
; WE WANT AN HEX DISPLAY
; ENTRY:  ZF      - SET IF HEX DISPLAY
;515E
HEXDIS:	CALL	NZ,MEMHEX	;DISPLAY MEMORY BYTE IN HEX
	DJNZ	REGDTL		;LOOP UNTIL ALL BYTES DONE
	POP	BC		;RECOVER BC REGISTER
	RET
;
;
; PUT DISPLAY BARS AROUND LOCATION BEING MODIFIED
; ENTRY:  B       - CHARCTER COUNT
;         HL      - DISPLAY ADDRESS
;         SECTRA  - THE LOCATION
;5165
PUTBAR:	LD	DE,(SECTRA)	;GET ADDRESS TO DE
	INC	DE		;BUMP TO NEXT INSTRUCTION
	PUSH	HL		;SAVE CURRENT DISPLAY ADDRESS
	XOR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;COMPARE DISPLAY AND MODIFY
	LD	A,LEFBAR	;LEFT VERTICAL BAR
	JR	Z,PUTBAL	;IF MODIFY, DISPLAY LEFT BAR
	CALL	SPCEIG		;SPACE IF EIGHT VALUES DONE
	INC	HL		;BUMP DISPLAY ADDRESS
	LD	A,L		;GET DISPLAY ADDRESS LSB TO A
	OR	H		;TEST IF ADDRESS IS ZERO
	POP	HL		;RECOVER DISPLAY ADDRESS
	LD	A,RIGBAR	;RIGHT VERTICAL BAR
	JP	Z,VDCHAR	;THEN DISPLAY THE CHARACTER
	JR	SPCDSP		;AND THEN FOLLOW WITH A SPACE
PUTBAL:	CALL	VDCHAR		;DISPLAY THE CHARACTER
	POP	HL		;RECOVER DISPLAY ADDRESS
;
;
; DISPLAY A SPACE IF 'B' REGISTER IS 8
;5184
SPCEIG:	LD	A,B		;GET B REGISTER TO A
	CP	8		;TEST IF DONE EIGHT BYTES
	RET	NZ		;RETURN IF NOT
;
;
; DISPLAY AN ASCII SPACE
;5188
SPCDSP:	JR	DSPSPC		;DISPLAY ASCII SPACE CHARACTER
;
;
; WAIT FOR A KEYBOARD CHARACTER
; EXIT:   A       - THE CHARACTER
;         ZF      - SET IF CHARACTER IS A COMMA OR A SPACE
;         CF      - SET IF 'ENTER' KEY PRESSED
;518A
WAITKB:	PUSH	DE		;SAVE DE REGISTER
WAITKL:	CALL	KBWAIT		;WAIT FOR KEYBOARD KEY PRESS
	CP	CR		;TEST IF CARRIAGE RETURN
	JR	Z,WAITKE	;THEN WE JUST RETURN
	CP	' '		;TEST IF CONTROL CHARACTER
	JR	C,WAITKL	;THEN IGNORE THE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	POP	DE		;RECOVER DE REGISTER
	CP	','		;TEST IF COMMA CHARACTER
	RET	Z		;THEN WE RETURN
	CP	' '		;TEST FOR A SPACE CHARACTER
	RET
;
;
; THE 'ENTER' KEY HAS BEEN PRESSED
; EXIT:   A       - CARRIAGE RETURN CHARACTER
;         CF      - SET
;51A0
WAITKE:	POP	DE		;RECOVER DE REGISTER
	SCF			;SET THE CARRY FLAG
	RET
;
;
; GET ADDRESS FROM KEYBOARD
; EXIT:   HL      - THE ADDRESS
;         ZF      - SET IF NO ADDRESS
;         CF      - SET IF CARRIAGE RETURN
;51A3
HEXADR:	CALL	WAITKB		;GET KEYBOARD CHARACTER
	RET	Z		;RETURN IF SPACE OR COMMA
	LD	HL,0		;ZERO ADDRESS REGISTER
HEXADL:	CALL	HEXNIB		;GET ADDRESS NIBBLE TO A
	JP	C,CMDLUP	;ABORT IF INVALID NIBBLE
	ADD	HL,HL		;ADDRESS TIMES 2
	ADD	HL,HL		;ADDRESS TIMES 4
	ADD	HL,HL		;ADDRESS TIMES 8
	ADD	HL,HL		;ADDRESS TIMES 16
	OR	L		;MERGE IN LS NIBBLE
	LD	L,A		;UPDATE LS BYTE
	CALL	WAITKB		;GET KEYBOARD CHARACTER
	JR	NZ,HEXADL	;LOOP IF NOT SPACE OR A COMMA
	RRA			;CARRY TO BIT 7
	ADC	A,129		;SET CARRY IF CARRIAGE RETURN
	RET
;
;
; CONVERT ASCII NIBBLE TO BINARY NIBBLE
; ENTRY:  A       - ASCII BYTE
; EXIT:   A       - BINARY NIBBLE
;         CF      - SET IF INVALID NIBBLE
;51BF
HEXNIB:	SUB	'0'		;REMOVE ASCII BIAS
	RET	C		;ABORT IF INVALID DIGIT
	ADD	A,0E9H		;ADD LETTER BIAS
	RET	C		;DONE IF NOT LETTER
	ADD	A,6		;TEST IF 'A' TO 'Z'
	JR	C,HEXNIX	;CONTINUE IF 'A' TO 'Z'
	ADD	A,7		;ELSE DIGIT '0' TO '9'
	RET	C		;DOES NOTHING IN THIS CONTEXT
HEXNIX:	ADD	A,10		;ELSE MAKE BINARY VALUE
	OR	A		;SET FLAGS FOR RESULT
	RET
;
;
; DISPLAY A BYTE IN ASCII HEXADECIMAL
; ENTRY:  HL      - POINTER TO THE BYTE
; EXIT:   HL      - INCREMENTED
;51D0
MEMHEX:	LD	A,(HL)		;GET BYTE TO DISPLAY
	INC	HL		;INCREMENT MEMORY POINTER
	JR	BYTHEX		;GO CONVERT AND DISPLAY
;
;
; DISPLAY A WORD IN ASCII HEXADECIMAL
; ENTRY:  HL      - THE WORD TO CONVERT AND DISPLAY
;51D4
WORHEX:	LD	A,H		;GET MSB OF WORD TO A
	CALL	BYTHEX		;GO CONVERT AND DISPLAY
	LD	A,L		;GET LSB OF WORD TO A
;
;
; DISPLAY A BYTE IN ASCII HEXADECIMAL
; ENTRY:  A       - THE BYTE TO CONVERT AND DISPLAY
;51D9
BYTHEX:	PUSH	AF		;SAVE THE BINARY BYTE
	RRA			;SHIFT FOUR
	RRA			; MS BITS
	RRA			;  INTO FOUR
	RRA			;   LS BITS
	CALL	NIBHEX		;CONVERT AND DISPLAY NIBBLE
	POP	AF		;RECOVER SAVED BYTE
NIBHEX:	AND	00001111B	;MASK OFF MS NIBBLE
	ADD	A,'0'		;CONVERT TO ASCII
	CP	'9'+1		;TEST IF NUMERIC ASCII
	JR	C,DSPCHR	;GO DISPLAY IF IT IS
	ADD	A,'A'-'9'-1	;ADD ALPHABETICAL BIAS
;
;
; DISPLAY AN ASCII CHARACTER
; ENTRY:  A       - CHARACTER TO DISPLAY
;51EC
DSPCHR:	JP	VDCHAR		;DISPLAY THE CHARACTER
;
;
; DISPLAY A BYTE IN HEXADECIMAL FOLLOWED BY A SPACE CHARACTER
; ENTRY:  A       - BINARY BYTE TO DISPLAY
;51EF
HEXSPC:	CALL	BYTHEX		;DISPLAY BYTE IN ASCII HEX
;
;
; DISPLAY AN ASCII SPACE CHARACTER
;51F2
DSPSPC:	LD	A,' '		;LOAD ASCII SPACE CHARACTER
	JR	DSPCHR		;GO DISPLAY THE CHARACTER
;
;
; DISPLAY THREE CONSECUTIVE CHARACTERS FROM MEMORY LOCATIONS
; ENTRY:  HL      - POINTER TO THE CHARACTERS
; EXIT:   HL      - INCREMENTED THREE TIMES
;51F6
MEMTCH:	CALL	MEMCHR		;DISPLAY MEMORY CHARACTER
	CALL	MEMCHR		;DISPLAY MEMORY CHARACTER
;
;
; DISPLAY A CHARACTER FROM A MEMORY LOCATION
; ENTRY:  HL      - POINTER TO THE CHARACTER
; EXIT:   HL      - INCREMENTED
;51FC
MEMCHR:	LD	A,(HL)		;GET CHARACTER FROM MEMORY
	INC	HL		;BUMP MEMORY POINTER
	JR	DSPCHR		;DISPLAY THE CHARACTER
;
	End	OVRL05
