	Title	'TRSDOS 2.3 Disk Operating System'
;
;
; TRSDOS DISK OPERATING SYSTEM, VERSION 2.3
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON 11.03.2022
;
; PART 6 - COMMAND PROCESSOR
;
;
; DEFINE IF PATCHES ARE ACTIVE
;
PATCHG	Equ	  0		;PATCHES ACTIVE
;
;
; ASCII EQUATES
;
CC	Equ	  3		;CONTROL-C (END-OF-MESSAGE)
LF	Equ	 10		;LINE FEED
CR	Equ	 13		;CARRIAGE RETURN
HO	Equ	 28		;HOME DISPLAY CURSOR
EE	Equ	 30		;ERASE TO END OF LINE
CE	Equ	 31		;CLEAR TO SCREEN END
CO	Equ	192		;SPACE COMPRESSION (0 TO 63)
;
;
; FLOPPY DISK CONSTANTS
;
MAXDRV	Equ	  4		;MAX NUMBER OF DRIVES
NUMTRK	Equ	 35+(5*PATCHG)	;DEFINE THE COUNT
NUMSEC	Equ	 10		;SECTORS PER TRACK
FIRSEC	Equ	  0		;FIRST SECTOR NUMBER
LASSEC	Equ	NUMSEC-1+FIRSEC	;LAST SECTOR NUMBER
SECSIZ	Equ	256		;SECTOR SIZE IN BYTES
;
;
; TRSDOS BINARY LOAD MODULE CODES
;
LOC	Equ	  1		;CODE LOAD ADDRESS
TRC	Equ	  2		;CODE EXECUTION ADDRESS
HDC	Equ	  5		;MODULE NAME STRING
COC	Equ	 31		;MODULE COPYRIGHT STRING
;
;
; LEVEL II BASIC ROM ADDRESSES
;
BYTINP	Equ	00013H		;DEVICE INPUT DRIVER ROUTINE
BYTOUT	Equ	0001BH		;DEVICE OUTPUT DRIVE ROUTINE
KBCHAR	Equ	0002BH		;INSTANTANEOUS KEYBOARD SCAN
VDCHAR	Equ	00033H		;DISPLAY CHARACTER ON VIDEO
PRCHAR	Equ	0003BH		;SEND CHARACTER TO PRINTER
KBLINE	Equ	00040H		;FILL LINE INPUT BUFFER
KBWAIT	Equ	00049H		;WAIT FOR KEYBOARD CHARACTER
;
;
; KEYBOARD MATRIX ADDRESSES
;
KROSEV	Equ	03840H		;KEYBOARD ROW SEVEN
;
;
; DEFINE OFFSETS INTO 'HIT' SECTOR
;
SHI	Equ	000H		;HASH CODES FOR SYSTEM FILES
UHI	Equ	040H		;HASH CODES FOR USER FILES
;
;
; DEFINE 'AUTO' PROCEDURE LENGTH
;
ALE	Equ	 32		;DEFINE THE 'AUTO' LENGTH
;
;
; DEFINE GAP LENGTH BETWEEN 'HIT' SLOT AREAS
;
NHI	Equ	 32		;DEFINE THE 'GAP' LENGTH
;
;
; OFFSETS INTO 'GAT' SECTOR
;
DGA	Equ	000H		;GRANULE ALLOCATION TABLE (96)
DTL	Equ	060H		;TRACK LOCK OUT TABLE (96)
DPA	Equ	0CEH		;DISK PASSWORD (2)
DNA	Equ	0D0H		;DISK NAME (8)
DDA	Equ	0D8H		;CREATION DATE (8)
DAU	Equ	0E0H		;AUTO PROCEDURE (32)
;
;
; DEFAULT PASSWORD 'PASSWORD' ENCODING (HASH)
;
PASSWO	Equ	04296H		;DEFAULT PASSWORD HASH
;
;
; STORAGE LOCATIONS IN TRSDOS NUCLEUS (SYS0/SYS)
;
DOSTME	Equ	04041H		;TIME REGISTERS IN TRSDOS
DOSDTE	Equ	04044H		;DATE REGISTERS IN TRSDOS
DIRBUF	Equ	04200H		;DIRECTORY BUFFER
SYSCON	Equ	0430FH		;SYSTEM CONDITION FLAGS
KIDRNA	Equ	043C0H		;DRIVER NAME AND ADDRESS TABLE
VERIFL	Equ	0485EH		;VERIFY WRITE FLAG
GATBUF	Equ	04D00H		;SYSTEM SECTOR BUFFER
HITBUF	Equ	04D00H		;SYSTEM SECTOR BUFFER
;
;
; FUNCTIONS ADDRESSES IN TRSDOS NUCLEUS (SYS0/SYS)
;
DOSENT	Equ	0402DH		;DO SYS1/SYS REQUEST CODE 10
ERRENT	Equ	04030H		;DO SYS1/SYS REQUEST CODE 20
DERROR	Equ	04409H		;OVERLAY CALL TO ERROR HANDLER
TSKADD	Equ	04410H		;ADD TASK TO INT TASK LIST
TSKREM	Equ	04413H		;REMOVE TASK FROM INT TASK LIST
VALNAM	Equ	0441CH		;VALIDATE NAME AND COPY TO DCB
CREFIL	Equ	04420H		;CREATE A NEW FILE
OPNFIL	Equ	04424H		;OPEN AN EXISTING FILE
CLSFIL	Equ	04428H		;CLOSE A FILE
KILFIL	Equ	0442CH		;KILL A FILE
LODFIL	Equ	04430H		;LOAD A 'CMD' FILE
REDREC	Equ	04436H		;READ RECORD FROM FILE
WRTREC	Equ	04439H		;WRITE RECORD TO FILE
POSEOF	Equ	04448H		;POSITION AT FILE END
DOPMSG	Equ	04467H		;DISPLAY A MESSAGE STRING
ADDEXT	Equ	04473H		;ADD EXTENSION TO FILENAME
PARSEC	Equ	04476H		;PARSE COMMAND LINE PARAMETERS
WRDSEC	Equ	046EFH		;WRITE A DIRECTORY SECTOR
RECWRT	Equ	0478BH		;WRITE A DISK RECORD
RECVFY	Equ	047A8H		;VERIFY A DISK RECORD
REDDIR	Equ	04AC1H		;READ DIRECTORY SECTOR
WRTDIR	Equ	04AD6H		;WRITE DIRECTORY SECTOR
REDGAT	Equ	04AF0H		;READ 'GAT' SECTOR
WRTGAT	Equ	04B03H		;WRITE 'GAT' SECTOR
DDREAD	Equ	04B35H		;READ SECTOR TO BUFFER
TRKDIR	Equ	04B55H		;GET DIRECTORY TRACK NUMBER
CLKTAS	Equ	04CA9H		;CLOCK DISPLAY TASK
;
;
; FUNCTIONS ADDRESSES IN TRSDOS OVERLAY 1 (SYS1/SYS)
;
GETARG	Equ	051A0H		;GET PARAMETER(S) IN BRACKETS
;
;
; DATA ADDRESSES IN TRSDOS OVERLAY 1 (SYS1/SYS)
;
SYSCMS	Equ	04EBDH		;STRINGS FOR SYS6/SYS COMMANDS
;
;
; FUNCTIONS ADDRESSES IN TRSDOS OVERLAY 2 (SYS2/SYS)
;
PARSES	Equ	05081H		;SCAN FOR INVALID CHARACTERS
FSHASH	Equ	0509BH		;COMPUTE A FILE HASH CODE
PWHASH	Equ	050D1H		;COMPUTE PASSWORD HASH CODE
TSTRDY	Equ	050FDH		;TEST DRIVE READY STATUS
REDHIT	Equ	0512EH		;READ 'HIT' SECTOR FROM DISK
WRTHIT	Equ	05141H		;WRITE 'HIT' SECTOR TO DISK
;
;
; DATA ADDRESSES IN TRSDOS OVERLAY 2 (SYS2/SYS)
;
PASSWD	Equ	05155H		;PASSWORD STORAGE
FILNAM	Equ	0515DH		;FILE NAME STORAGE
MASHAS	Equ	05168H		;STORAGE FOR MASTER PASSWORD
MASHAL	Equ	MASHAS+0	;MASTER PASSWORD HASH STORE LSB
MASHAH	Equ	MASHAS+1	;MASTER PASSWORD HASH STORE MSB
FILHAS	Equ	0516AH		;STORAGE FOR FILE PASSWORD
FILHAL	Equ	FILHAS+0	;FILE PASSWORD HASH STORE LSB
FILHAH	Equ	FILHAS+1	;FILE PASSWORD HASH STORE MSB
;
;
; DEFINE LOAD ADDRESS OF USER EXECUTABLE BINARY CODE
;
LOWMEM	Equ	07000H		;START OF EXECUTABLE CODE
;
;
; PROGRAM MODULE NAME STRING
;
	Nam	'SYS6  '
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING
;
	Rem	CR
	Rem	'* * * N O T I C E * * *',CR
	Rem	'* PROPRIETARY PROGRAM *',CR
	Rem	'* COPYRIGHT (c) 1979  *',CR
	Rem	'* BY TANDY CORPORATION*',CR
	Rem	'*  FORT WORTH, TEXAS  *',CR
	Rem	'* ALL RIGHTS RESERVED *',CR
	Rem	'* * * N O T I C E * * *',CR
;
;
	Org	05200H
;
EXTE01:	LD	A,C		;GET COMMAND INDEX TO A
	LD	BC,DOSENT	;GET RETURN ADDRESS TO BC
	PUSH	BC		;STACK THE ADDRESS
	DEC	A		;COMMAND INDEX 1
APNCMJ:	JP	Z,RNGERR	;APPEND
	DEC	A		;COMMAND INDEX 2
ATRCMJ:	JP	Z,RNGERR	;ATTRIB
	DEC	A		;COMMAND INDEX 3
	JP	Z,AUTCMD	;AUTO
	DEC	A		;COMMAND INDEX 4
	JP	Z,CLKCMD	;CLOCK
	DEC	A		;COMMAND INDEX 5
CPYCMJ:	JP	Z,RNGERR	;COPY
	DEC	A		;COMMAND INDEX 6
	JP	Z,DTECMD	;DATE
	DEC	A		;COMMAND INDEX 7
	JP	Z,DEVCMD	;DEVICE
	DEC	A		;COMMAND INDEX 8
DIRCMJ:	JP	Z,RNGERR	;DIR
	DEC	A		;COMMAND INDEX 9
DMPCMJ:	JP	Z,RNGERR	;DUMP
	DEC	A		;COMMAND INDEX 10
FRECMJ:	JP	Z,RNGERR	;FREE
	DEC	A		;COMMAND INDEX 11
KILCMJ:	JP	Z,RNGERR	;KILL
	DEC	A		;COMMAND INDEX 12
	JP	Z,LIBCMD	;LIB
	DEC	A		;COMMAND INDEX 13
LISCMJ:	JP	Z,RNGERR	;LIST
	DEC	A		;COMMAND INDEX 14
LODCMJ:	JP	Z,RNGERR	;LOAD
	DEC	A		;COMMAND INDEX 15
PRTCMJ:	JP	Z,RNGERR	;PRINT
	DEC	A		;COMMAND INDEX 16
	JP	Z,PROCMD	;PROT
	DEC	A		;COMMAND INDEX 17
RENCMJ:	JP	Z,RNGERR	;RENAME
	DEC	A		;COMMAND INDEX 18
	JP	Z,TMECMD	;TIME
	DEC	A		;COMMAND INDEX 19
	JP	Z,VFYCMD	;VERIFY
;
;
; COMMAND INDEX OUT OF RANGE
;5251
RNGERR:	LD	HL,RSVCMD	;POINT AT ERROR MESSAGE
	CALL	DOPMSG		;DISPLAY THE STRING
	JP	ERRENT		;ABORT TO ERROR ENTRY
;
;
; ERROR MESSAGE IF INVALID COMMAND CODE
;525A
RSVCMD	Db	'RESERVED COMMAND',CR
;
;
; ERROR MESSAGE WHEN NOTHING HAS BEEN DONE
;526B
NODONE:	LD	HL,NODMSG	;POINT AT ERROR MESSAGE
	CALL	DOPMSG		;DISPLAY THE STRING
	JP	ERRENT		;ABORT TO ERROR ENTRY
;
;
; ERROR MESSAGE IF NOTHING IS DONE
;5274
NODMSG	Db	'-NOTHING DONE-',CR
;
;
; 'AUTO' COMMAND PROCESSING
; ENTRY:  HL      - POINTER TO 'AUTO' BUFFER
;5283
AUTCMD:	LD	C,0		;SPECIFY DRIVE ZERO
	CALL	REDGAT		;READ 'GAT' SECTOR
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	D,High GATBUF	;LOAD 'GAT' BUFFER MSB TO D
	LD	E,DAU		;INDEX TO 'AUTO' PROCEDURE
	LD	BC,ALE		;LOAD PROCEDURE LENGTH
	LDIR			;COPY THE STRING TO BUFFER
	LD	C,0		;LOAD UNIT NUMBER TO C
	CALL	WRTGAT		;WRITE THE 'AUTO' PROCEDURE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	RET
;
;
; 'DATE' COMMAND PROCESSING
;529D
DTECMD:	LD	C,'/'		;LOAD DATE SEPERATOR
	CALL	CONVDT		;CONVERT THE DATE STRING
	JP	NZ,BADTDV	;ABORT IF ANY ERRORS
	LD	HL,TIDREG	;POINT AT LOCAL STORAGE
	LD	DE,DOSDTE	;POINT AT DATE REGISTERS
	LD	BC,3		;LOAD BYTE COUNT
	LDIR			;COPY DATE INTO TRSDOS
	RET
;
;
; 'TIME' COMMAND PROCESSING
;52B1
TMECMD:	LD	C,':'		;LOAD TIME SPERATOR
	CALL	CONVDT		;CONVERT THE TIME STRING
	JP	NZ,BADTDV	;ABORT IF ANY ERRORS
	LD	HL,TIDREG	;POINT AT LOCAL STORAGE
	LD	DE,DOSTME	;POINT AT TIME REGISTERS
	LD	BC,3		;LOAD BYTE COUNT
	LDIR			;COPY TIME INTO TRSDOS
	RET
;
;
; 'CLOCK' COMMAND PROCESSING
;52C5
CLKCMD:	CALL	GETARG		;GET PARAMETER(S) IN BRACKETS
	LD	DE,CLKTAS	;POINT AT CLOCK DISPLAY TASK
	LD	A,6		;LOAD TASK NUMBER TO A
	JP	Z,TSKREM	;REMOVE TASK IF NEGATIVE FLAG
	JP	TSKADD		;ELSE ADD THE TASK
;
;
; INVALID DATE OR TIME ERROR MESSAGE
;52D3
BADTDV:	LD	HL,BADTID	;POINT AT ERROR MESSAGE
	CALL	DOPMSG		;DISPLAY MESSAGE STRING
	JP	ERRENT		;ABORT TO TRSDOS ERROR HANDLER
;
;
; STORAGE FOR TIME AND DATE VALUES
;52DC
TIDREG	Ds	3		;RESERVE THE SPACE
;
;
; ERROR MESSAGE DISPLAYED WHEN INVALID DATE OR TIME STRING
;52DF
BADTID	Db	'BAD FORMAT',CR
;
;
; CONVERT DATE OR TIME STRING TO BINARY CODED DECIMAL
; ENTRY:  C       - DATE OR TIME SEPERATOR
;         HL      - POINTER TO TIME OR DATE STRING
; EXIT:   DE      - POINTER TO START OF STORAGE AREA
;         HL      - POINTER TO END OF STRING
;52EA
CONVDT:	LD	DE,TIDREG+2	;POINT AT LOCAL REGISTERS
	LD	B,3		;LOAD REGISTER COUNT
CONVDL:	PUSH	DE		;SAVE REGISTER POINTER
	CALL	CNVBCD		;CONVERT TO BCD
	POP	DE		;RECOVER REGISTER POINTER
	RET	NZ		;RETURN IF ANY ERRORS
	LD	(DE),A		;ELSE STORE BYTE IN REGISTER
	DEC	DE		;BACKUP REGISTER POINTER
	DEC	B		;DECREMENT REGISTER COUNT
	RET	Z		;RETURN IF ALL DONE
	LD	A,(HL)		;GET DELIMITER TO A
	INC	HL		;BUMP STRING POINTER
	CP	C		;TEST IF VALID SEPERATOR
	JR	Z,CONVDL	;LOOP FOR NEXT IF SO
	RET
;
;
; GET BINARY CODED DECIMAL BYTE FROM ASCII STRING
; ENTRY:  HL      - POINTER TO ASCII STRING
; EXIT:   A       - BINARY CODED DECIMAL BYTE
;         HL      - INCREMENTED TWICE
;         ZF      - SET IF VALID BINARY CODED DECIMAL
;52FF
CNVBCD:	CALL	CNVBCN		;GET MS BCD DIGIT
	JR	NC,CNVBCE	;ABORT IF ANY ERROR
	LD	E,A		;SAVE BCD NIBBLE IN E
	RLCA			;MULTIPLY BY TWO
	RLCA			;MULTIPLY BY FOUR
	ADD	A,E		;MULTIPLY BY FIVE
	RLCA			;MULTIPLY BY TEN
	LD	E,A		;SAVE RESULT IN E
	CALL	CNVBCN		;GET LS BCD DIGIT
	JR	NC,CNVBCE	;ABORT IF ANY ERROR
	ADD	A,E		;MERGE BOTH NIBBLES
	LD	E,A		;SAVE BCD BYTE IN E
	XOR	A		;SET ZERO FLAG
	LD	A,E		;COPY RESULT TO A
	RET
;
;
; ERROR ENCOUNTERED, SO CLEAR THE ZERO FLAG
;5314
CNVBCE:	OR	A		;CLEAR ZERO FLAG
	RET
;
;
; GET ASCII DATE OR TIME CHARACTER AND CONVERT TO BCD NIBBLE
; ENTRY:  HL      - POINTER TO ASCII STRING
; EXIT:   A       - BINARY CODED DECIMAL NIBBLE
;         HL      - INCREMENTED
;         CF      - RESET IF NOT BINARY CODED DECIMAL
;5316
CNVBCN:	LD	A,(HL)		;GET CHARACTER FROM STRING
	INC	HL		;BUMP STRING POINTER
	SUB	'0'		;REMOVE ASCII BIAS
	CP	10		;TEST IF VALID BCD
	RET
;
;
; 'DEVICE' COMMAND - ONLY DISPLAYS DEVICES
;531D
DEVCMD:	LD	HL,KIDRNA	;POINT AT DEVICE LIST
DEVCML:	LD	A,(HL)		;GET DEVICE CHARACTER
	INC	L		;BUMP LIST POINTER LSB
	OR	A		;TEST IF LIST END
	JR	Z,DEVCMX	;THEN WE JUST EXIT
	CALL	VDCHAR		;DIAPLAY DEVICE CHARACTER
	LD	A,(HL)		;GET NEXT CHARACTER
	CALL	VDCHAR		;DISPLAY THW CHARACTER
	LD	A,CR		;LOAD A NEWLINE
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	LD	A,L		;GET TABLE POINTER LSB
	ADD	A,3		;BUMP TO NEXT ENTRY
	LD	L,A		;GET ENTRY LSB TO A
	JR	NC,DEVCML	;LOOP IF MORE ENTRIES
DEVCMX:	JP	DOSENT		;ELSE RETURN TO TRSDOS
;
;
; 'LIB' COMMAND
;533A
LIBCMD:	LD	HL,SYSCMS	;SYS6/SYS COMMAND STRINGS
LIBCNL:	LD	C,4		;LOAD COLUMN COUNT TO C
	LD	A,CO+2		;TWO SPACE COMPRESSION CODE
	CALL	VDCHAR		;DISPLAY TWO SPACES
LIBCNC:	LD	B,6		;LOAD CHARACTER COUNTER
LIBCNB:	LD	A,(HL)		;GET COMMAND CHARACTER
	INC	HL		;BUMP STRING POINTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	DJNZ	LIBCNB		;LOOP UNTIL COMMAND DISPLAYED
	LD	A,CO+8		;EIGHT SPACE COMPRESSION CODE
	CALL	VDCHAR		;DISPLAY EIGHT SPACES
	INC	HL		;BUMP TO ADDRESS MSB
	INC	HL		;BUMP TO NEXT COMMAND STRING
	LD	A,(HL)		;GET CHARACTER FROM TABLE
	OR	A		;TEST IF END OF TABLE
	JR	Z,LIBCEX	;THEN WE EXIT TO TRSDOS
	DEC	C		;DECREMENT COLUMN COUNT
	JR	NZ,LIBCNC	;LOOP UNTIL COUNT DONE
	LD	A,CR		;LOAD NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	JR	LIBCNL		;THEN DISPLAY NEXT COMMAND
LIBCEX:	LD	A,CR		;LOAD NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	JP	DOSENT		;THEN EXIT DO TRSDOS
;
;
; 'PROT' COMMAND PROCESSING
; FORMAT:  PROT :D ([LOCK][UNLOCK][PW=PW])
;536A
PROCMD:	LD	A,(SYSCON)	;GET SYSTEM CONDITION FLAGS
	BIT	5,A		;TEST IF CHAINING IN PROGRESS
	JP	NZ,INVPCH	;THEN INVALID DURING CHAINING
	LD	BC,0		;ZERO BC REGISTER
	LD	(PASSWP),BC	;CLEAR PASSWORD POINTER
	LD	(LOCKFL),BC	;CLEAR LOCK FLAG
	LD	(UNLOFL),BC	;CLEAR UNLOCK FLAG
	LD	C,0		;DEFAULT TO UNIT NUMBER ZERO
	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	':'		;TEST IF DRIVE CODE DELIMITER
	JR	NZ,PROCND	;USE DEFAULT IF NO DRIVE
	INC	HL		;BUMP COMMAND LINE POINTER
	LD	A,(HL)		;GET ASCII DRIVE NUMBER
	SUB	'0'		;REMOVE ASCII BIAS
	LD	C,A		;COPY DRIVE NUMBER TO C
	INC	HL		;BUMP COMMAND LINE POINTER
PROCND:	LD	A,C		;GET UNIT NUMBER TO A
	LD	(UNITNO),A	;SAVE THE DRIVE CODE
	LD	DE,PROPAR	;POINT AT PARAMETER STRINGS
	CALL	PARSEC		;PARSE THE COMMAND LINE
	LD	A,(PASSWP)	;GET PASSWORD POINTER LSB
	LD	HL,LOCKFL	;POINT AT LOCK FLAG
	OR	(HL)		;MERGE WITH LOCK FLAG
	LD	HL,UNLOFL	;POINT AT UNLOCK FLAG
	OR	(HL)		;MERGE WITH UNLOCK FLAG
	JP	Z,NODONE	;EXIT IF NO PARAMETERS
	LD	A,CC		;LOAD STRING TERMINATOR
	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	LD	(DE),A		;STORE AS A FILENAME
	CALL	OPNFIL		;FAKE OPEN TO LOAD 'SYS2/SYS'
	LD	HL,CURMAP	;POINT AT PASSWORD PROMPT
	CALL	DOPMSG		;DISPLAY PROMPT STRING
	CALL	GETPAS		;GET CURRENT MASTER PASSWORD
	LD	(MASHAS),HL	;SAVE PASSWORD HASH CODE
	LD	C,0		;GET UNIT NUMBER TO C
UNITNO	Equ	$ - 1		;DRIVE NUMBER STORAGE
	CALL	REDGAT		;READ 'GAT' SECTOR
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	HL,(GATBUF+DPA)	;GET PASSWORD HASH FROM 'GAT'
	LD	DE,(MASHAS)	;GET MASTER PASSWORD HASH
	XOR	A		;CLEAR THE CARRY FLAG
	SBC	HL,DE		;TEST FOR A PASSWORD MATCH
	JR	Z,PROCHM	;CONTINUE IF MATCHING HASH
	LD	HL,INVMAP	;POINT AT ERROR MESSAGE
	CALL	DOPMSG		;DISPLAY THE MESSAGE
	JP	ERRENT		;THEN ABORT TO DOS ERROR ENTRY
PROCHM:	LD	DE,0		;GET PASSWORD STRING POINTER
PASSWP	Equ	$ - 2		;POINTER TO PASSWORD STRING
	LD	A,D		;GET POINTER MSB TO A
	OR	E		;TEST IF PASSWORD ENTERED
	JR	Z,PROCNP	;SKIP IF NO PASSWORD
	LD	HL,NEWMAP	;POINT AT PASSWORD PROMPT
	CALL	DOPMSG		;DISPLAY PROMPT STRING
	CALL	GETPAS		;GET NEW MASTER PASSWORD
	LD	(GATBUF+DPA),HL	;SAVE PASSWORD HASH IN BUFFER
	LD	A,(UNITNO)	;GET DISK DRIVE CODE TO A
	LD	C,A		;COPY UNIT NUMBER TO C
	CALL	WRTGAT		;WRITE 'GAT' SECTOR TO DISK
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
PROCNP:	LD	HL,(GATBUF+DPA)	;GET DISK PASSWORD TO HL
	LD	DE,0		;GET SUPPLIED LOCK FLAG
LOCKFL	Equ	$ - 2		;STORAGE FOR LOCK FLAG
	LD	A,D		;GET LOCK FLAG MSB TO A
	OR	E		;TEST IF LOCK A FILE
	JR	NZ,PROCCL	;CONTINUE LOCKING FILE
	LD	HL,PASSWO	;LOAD DEFAULT PASSWORD HASH
	LD	DE,0		;GET SUPPLIED UNLOCK FLAG
UNLOFL	Equ	$ - 2		;STORAGE FOR UNLOCK FLAG
	LD	A,D		;GET UNLOCK FLAG MSB TO A
	OR	E		;TEST IF UNLOCK FILE
	JR	NZ,PROCCL	;GO IF UNLOCKING FILE
	JP	DOSENT		;ELSE EXIT TO DOS PROMPT
PROCCL:	LD	(DSKHAS),HL	;STORE DEFAULT HASH
	LD	A,(UNITNO)	;GET UNIT NUMBER TO A
	LD	C,A		;COPY UNIT CODE TO C
	CALL	TRKDIR		;GET DIRECTORY TRACK NUMBER
	LD	E,2		;LOAD FIRST FILE SECTOR NUMBER
PROCNS:	LD	HL,DIRBUF	;POINT AT DIRECTORY BUFFER
	CALL	DDREAD		;READ SECTOR TO BUFFER
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	L,64		;FORM THIRD FILE ENTRY ADDRESS
PROCNE:	LD	A,(HL)		;GET FILE ACCESS BITS TO A
	AND	11111000B	;MASK OFF PERMISSION BITS
	CP	00010000B	;TEST IF ENTRY ASSIGNED
	JR	NZ,PROCUA	;SKIP IF ENTRY UNASSIGNED
	LD	A,L		;GET SECTOR INDEX LSB TO A
	ADD	A,16		;INDEX TO UPDATE PASSWORD
	LD	L,A		;FORM ADDRESS OF PASSWORDS
	PUSH	DE		;SAVE SECTOR NUMBER
	LD	DE,0		;GET PASSWORD ENCODE TO DE
DSKHAS	Equ	$ - 2		;STORAGE FOR PASSWORD ENCODE
	LD	(HL),E		;STORE UPDATE PASSWORD LSB
	INC	L		;BUMP PASSWORD POINTER
	LD	(HL),D		;STORE UPDATE PASSWORD MSB
	INC	L		;BUMP PASSWORD POINTER
	LD	(HL),E		;STORE ACCESS PASSWORD LSB
	INC	L		;BUMP PASSWORD POINTER
	LD	(HL),D		;STORE ACCESS PASSWORD MSB
	POP	DE		;RECOVER SECTOR NUMBER
PROCUA:	LD	A,L		;GET BUFFER ADDRESS LSB
	AND	11100000B	;MASK OFF BUFFER INDEX
	ADD	A,32		;INDEX TO NEXT ENTRY
	LD	L,A		;UPDATE BUFFER ADDRESS LSB
	JR	NC,PROCNE	;LOOP IF SECTOR NOT DONE
	LD	HL,DIRBUF	;POINT AT DIRECTORY BUFFER
	CALL	WRDSEC		;WRITE DIRECTORY SECTOR
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	INC	E		;BUMP DIRECTORY SECTOR NUMBER
	LD	A,E		;GET SECTOR NUMBER TO A
	CP	NUMSEC		;TEST IF LAST SECTOR DONE
	JR	C,PROCNS	;LOOP FOR NEXT SECTOR IF NOT
	JP	DOSENT		;ELSE EXIT TO DOS PROMPT
;
;
; INPUT NEW MASTER PASSWORD INTO BUFFER - PAD WITH SPACES
; THEN COMPUTE SIXTEEN BIT HASH CODE FROM THE CHARACTERS
; EXIT:   HL      - PASSWORD HASH CODE
;5454
GETPAS:	LD	B,8		;MAXIMUM PASSWORD LENGTH
	LD	HL,SECBUF	;POINT AT INPUT BUFFER
	CALL	KBLINE		;GET PASSWORD INTO BUFFER
	EX	DE,HL		;SWAP BUFFER POINTER TO DE
	LD	H,0		;ZERO MSB OF INDEX
	LD	L,B		;HL HAS INDEX TO BUFFER END
	ADD	HL,DE		;POINT HL AT BUFFER END
	LD	A,8		;MAXIMUM PASSWORD LENGTH
	SUB	B		;COMPUTE SPACE FILL COUNT
	LD	B,A		;COPY FILL COUNT TO B
	LD	A,' '		;LOAD SPACE CHARACTER
GETPAP:	LD	(HL),A		;STORE SPACE IN BUFFER
	INC	HL		;BUMP BUFFER POINTER
	DJNZ	GETPAP		;LOOP UNTIL ALL PADDED
	JP	PWHASH		;GO COMPUTE PASSWORD HASH
;
;
; INVALID COMMAND DURING PROGRAM CHAINING
;545E
INVPCH:	LD	HL,INVDPC	;INVALID DURING CHAINING
	CALL	DOPMSG		;DISPLAY MESSAGE
	JP	ERRENT		;THE ABORT TO DOS ERROR
;
;
; ERROR MESSAGES FOR 'PROT' COMMAND
;5477
INVDPC	Db	LF,'INVALID COMMAND DURING PROGRAM CHAINING',CR
CURMAP	Db	LF,'MASTER PASSWORD ?      ',CC
NEWMAP	Db	LF,'NEW MASTER PASSWORD ?  ',CC
INVMAP	Db	LF,'INVALID MASTER PASSWORD',CR
;
;
; TEXT STRINGS FOR 'PROT' PARAMETER
;54EB
PROPAR	Db	'PW    '
	Dw	PASSWP		;PASSWORD POINTER
	Db	'LOCK  '
	Dw	LOCKFL		;LOCKED FLAG
	Db	'UNLOCK'
	Dw	UNLOFL		;UNLOCKED FLAG
	Db	0
;
;
; 'VERIFY' COMMAND
; FORMAT:  VERIFY [(ON|OFF)]
;5504
VFYCMD:	CALL	GETARG		;GET PARAMETER(S) IN BRACKETS
	LD	HL,RECWRT	;POINT AT WRITE ROUTINE
	JR	Z,VFYCMS	;SKIP IF VERIFY OFF
	LD	HL,RECVFY	;POINT AT WRITE WITH VERIFY
VFYCMS:	LD	(WRTREC+1),HL	;STORE RECORD WRITE ADDRESS
	JP	DOSENT		;RETURN TO DOS PROMPT
;
;
; TEST FOR <BREAK> KEY AND SCROLL HALT <SHIFT> <@> KEYS
; ENTRY:  SYSCON  - SYSTEM CONDITION FLAGS
; EXIT:   A       - NOT ZERO IF <BREAK> KEY ELSE ZERO
;         ZF      - RESET IF <BREAK> ELSE SET
;5515
BRKHLT:	LD	A,(SYSCON)	;GET SYSTEM CONDITION FLAGS
	AND	00100000B	;MASK TO PROGRAM CHAINING
	XOR	00100000B	;TEST IF CHAINING ACTIVE
	RET	Z		;ALL DONE IF ACTIVE
	LD	A,(KROSEV)	;LOAD <BREAK> KEY ROW
	AND	00000100B	;TEST IF <BREAK> PRESSED
	RET	NZ		;RETURN IF IT IS
	CALL	KBCHAR		;READ KEYBOARD CHARACTER
	CP	96		;TEST IF SCROLL PAUSE
	JR	Z,WAITKY	;THEN GO WAIT FOR A KEY
	XOR	A		;ZERO ACCUMULATOR, SET Z FLAG
	RET
;
;
; WAIT FOR EITHER <BREAK> KEY OR OTHER KEYBOARD CHARACTER
; EXIT:   A       - NOT ZERO IF <BREAK> KEY ELSE ZERO
;         ZF      - RESET IF <BREAK> OR SET IF OTHER KEY
;552C
WAITKY:	LD	A,(KROSEV)	;LOAD <BREAK> KEY ROW
	AND	00000100B	;TEST IF <BREAK> PRESSED
	RET	NZ		;RETURN IF IT IS
	CALL	KBCHAR		;READ KEYBOARD CHARACTER
	OR	A		;TEST IF ANY KEY PRESSED
	JR	Z,WAITKY	;WAIT FOR A KEYPRESS
	XOR	A		;ZERO ACCUMULATOR, SET Z FLAG
	RET
;
;
; DISPLAY 'FILE SPEC REQUIRED' STRING
;553A
FSPREQ:	LD	HL,REQFSP	;POINT AT THE STRING
	CALL	DOPMSG		;DISPLAY THE MESSAGE
	JP	ERRENT		;THEN ABORT TO ERROR HANDLER
;
;
; DISPLAY 'DEVICE SPEC REQUIRED' STRING (UNUSED)
;5543
DSPREQ:	LD	HL,REQDSP	;POINT AT THE STRING
	CALL	DOPMSG		;DISPLAY THE MESSAGE
	JP	ERRENT		;THEN ABORT TO ERROR HANDLER
;
;
; SET ERROR CONDITION AND ABORT TO SYSTEM
;554C
SYSABO:	OR	01000000B	;SET SYSTEM ABORT FLAG
	JP	DERROR		;ABORT TO TRSDOS
;
;
; LOCAL DEVICE CONTROL BLOCKS
;5551
DCBONE	Ds	32		;RESERVE SPACE FOR BLOCK
DCBTWO	Ds	32		;RESERVE SPACE FOR BLOCK
;
;
; FILE AND DEVICE SPEC ERROR MESSAGES
;5591
REQFSP	Db	LF,'FILE SPEC REQUIRED',CR
REQDSP	Db	LF,'DEVICE SPEC REQUIRED',CR
;
;
; RESERVE UNUSED SPACE
;
	Ds	69
;
;
; SECTOR BUFFER FOR LOCAL COMMANDS
;5600
SECBUF	Ds	256		;RESERVE THE SPACE
;
;
; STORE 'ATTRIB' COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	ATRCMJ+1
;
	Dw	ATTCMD		;'ATTRIB' COMMAND ADDRESS
;
;
; 'ATTRIB' COMMAND PROCESSING
; FORMAT:  ATTRIB <FILE> ([ACC=A],[UPD=U],[PROT=P], [I]])
;
	Org	05B00H
;
ATTCMD:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF MISSING OR INVALID
	LD	A,(DE)		;GET CHARACTER FROM NAME
	CP	'*'		;TEST IF DEVICE HEADER BYTE
	JP	Z,FSPREQ	;ABORT IF DEVICE NAME
	PUSH	HL		;SAVE COMMAND LINE POINTER
	LD	B,0		;LOAD LOGICAL RECORD LENGTH
	LD	HL,GATBUF	;POINT AT SECTOR BUFFER
	CALL	OPNFIL		;TRY OPENING THE FILE
	JP	NZ,SYSABO	;ABORT TO DOS IF ANY ERRORS
	POP	HL		;RECOVER COMMAND LINE POINTER
	LD	A,(DCBONE+1)	;GET PERMISSION BITS FROM DCB
	AND	00000111B	;ISOLATE ACCESS FLAGS
;
	If PATCHG		;PATCHES ACTIVE
	 LD	A,25H		;PROTECTED FILE ILLEGAL ACCESS
	Else			;ORIGINAL
	 LD	A,37H		;UNKNOWN ERROR (BUG)
	EndIf			;ALL DONE
;
	JP	NZ,SYSABO	;ABORT TO DOS IF ACCESS ERROR
	XOR	A		;ZERO ACCUMULATOR
	LD	(ATCHFL),A	;CLEAR ATTRIBUTES CHANGED FLAG
	LD	(VISIBI),A	;CLEAR VISIBILITY FLAG
ATTCGD:	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	'('		;TEST IF PARAMETER DELIMITER
	JR	Z,ATTCDG	;CONTINUE IF IT IS
	CP	' '		;TEST IF SPACE CHARACTER
	JP	NZ,NODONE	;ABORT IF NEITHER CHARACTER
	INC	HL		;BUMP COMMAND LINE POINTER
	JR	ATTCGD		;IGNORE ALL LEADING SPACES
ATTCDG:	INC	HL		;BUMP COMMAND LINE POINTER
	LD	A,(HL)		;GET OPTION CHARACTER
	CP	'I'		;TEST IF INVISIBLE ATTRIBUTE
	JR	Z,GETINV	;THEN SET THE INVISIBILITY BIT
	CP	'A'		;TEST IF ACCESS PASSWORD
	JR	Z,GETAPW	;THEN GO GET THE PASSWORD
	CP	'U'		;TEST IF UPDATE PASSWORD
	JR	Z,GETUPW	;THEN GO GET THE PASSWORD
	CP	'P'		;TEST IF PROTECTION LEVEL
	JP	NZ,ATTERR	;ATTRIBUTE SPEC ERROR IF NOT
;
;
; 'P' FLAG - SET PROTECTION LEVEL
;
	CALL	PASGET		;GET AND FORMAT ARGUMENT
	JP	Z,ATTERR	;ABORT IF NO ARGUMENTS
	PUSH	HL		;SAVE COMMAND LINE POINTER
	LD	B,7		;NUMBER OF TEST STRINGS
	LD	DE,(PASSWD)	;GET ARGUMENT FROM BUFFER
	LD	HL,ATTPRO	;POINT AT PROTECTION LEVELS
ATTCTP:	LD	A,(HL)		;GET LEVEL CHARACTER TO A
	INC	HL		;BUMP TABLE POINTER
	CP	E		;TEST IF MATCHING CHARACTERS
	CALL	Z,ATTCTN	;TEST FOR NEXT IF A MATCH
	INC	HL		;BUMP POINTER IF MISMATCH
	DJNZ	ATTCTP		;LOOP UNTIL ALL TESTED
	JP	ATTERR		;ABORT IF NO MATCH FOUND
;
;
; FIRST CHARACTER OF ACCESS STRING MATCHES COMMAND PARAMETER
;5B69
ATTCTN:	LD	A,(HL)		;GET SECOND LEVEL CHARACTER
	CP	D		;TEST IF WE HAVE A MATCH
	RET	NZ		;TEST NEXT PAIR IF MISMATCH
	POP	AF		;REMOVE RETURN ADDRESS
	LD	A,B		;GET LOOP COUNTER TO A
	DEC	A		;ZERO BASE THE COUNT
	CP	5		;TEST EITHER 'READ' OR 'RENAME'
	JR	NZ,ATTCNR	;SKIP IF NEITHER ONE
	LD	A,(PASSWD+2)	;GET THIRD PARAMETER CHARACTER
	CP	'N'		;TEST IF 'RENAME' NOT 'READ'
	LD	A,00000101B	;ASSUME 'READ' PARAMETER
	JR	NZ,ATTCNR	;SKIP IF NOT 'RENAME'
	LD	A,00000010B	;ELSE LOAD 'RENAME' FLAG
ATTCNR:	LD	(PERMBI),A	;STORE THE PERMISSION BITS
	POP	HL		;RECOVER COMMAND LINE POINTER
	LD	B,00000001B	;ATTRIBUTES CHANGED FLAG
ATTCNO:	LD	A,(ATCHFL)	;LOAD ATTRIBUTES FLAGS
	OR	B		;MERGE IN CHANGED BIT
	LD	(ATCHFL),A	;UPDATE ATTRIBUTES STORAGE
	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	')'		;TEST IF PARAMETER LIST END
	JR	Z,UPEPAS	;THEN UPDATE PERMISSIONS
	CP	','		;TEST IF MORE PARAMETERS
	JR	Z,ATTCDG	;THEN LOOP FOR NEXT OPTION
	JP	ATTERR		;ELSE ABORT TO DOS PROMPT
;
;
; 'I' FLAG - FLAG FILE AS INVISIBLE
; EXIT:   B       - BIT THREE IS SET
;5B97
GETINV:	CALL	PASGET		;GET AND FORMAT ARGUMENT
	JP	NZ,ATTERR	;ABORT IF ANY ARGUMENTS
	LD	A,(VISIBI)	;ELSE GET FILE ATTRIBUTES
	OR	00001000B	;SET INVISIBLE FLAG
	LD	(VISIBI),A	;RE-SAVE THE ATTRIBUTES
	JR	ATTCNO		;THEN SCAN FOR MORE OPTIONS
;
;
; 'A' FLAG - GET AND SET ACCESS PASSWORD
; EXIT:   B       - BIT ONE IS SET
;         HILHAS  - NEW ACCESS PASSWORD
;5BA7
GETAPW:	CALL	PASGET		;GET AND FORMAT ARGUMENT
	JP	Z,ATTERR	;ABORT IF NO PASSWORD ENTERED
	PUSH	HL		;SAVE COMMAND LINE POINTER
	LD	DE,PASSWD	;POINT AT PASSWORD BUFFER
	CALL	PWHASH		;COMPUTE PASSWORD HASH
	LD	(FILHAS),HL	;STORE AS ACCESS PASSWORD HASH
	POP	HL		;RECOVER COMMAND LINE POINTER
	LD	B,00000010B	;FLAG NEW ACCESS PASSWORD
	JR	ATTCNO		;THEN SCAN FOR MORE OPTIONS
;
;
; 'U' FLAG - GET AND SET UPDATE PASSWORD
; EXIT:   B       - BIT TWO IS SET
;         MASHAS  - NEW UPDATE PASSWORD
;5BBC
GETUPW:	CALL	PASGET		;GET AND FORMAT ARGUMENT
	JP	Z,ATTERR	;ABORT IF NO PASSWORD ENTERED
	PUSH	HL		;SAVE COMMAND LINE POINTER
	LD	DE,PASSWD	;POINT AT PASSWORD BUFFER
	CALL	PWHASH		;COMPUTE PASSWORD HASH
	LD	(MASHAS),HL	;STORE AS UPDATE PASSWORD HASH
	POP	HL		;RECOVER COMMAND LINE POINTER
	LD	B,00000100B	;FLAG NEW UPDATE PASSWORD
	JR	ATTCNO		;THEN SCAN FOR MORE OPTIONS
;
;
; GET PARAMETER FROM COMMAND LINE INTO PASSWORD BUFFER
; ENTRY:  HL      - COMMAND LINE POINTER
; EXIT:   DE      - POINTER TO PASSWORD BUFFER END
;         ZF      - RESET IF PASSWORD WAS SUCCESSFULLY READ
;5BD1
PASGET:	INC	HL		;BUMP COMMAND LINE POINTER
	LD	A,(HL)		;GET CHARACTER FROM LINE
	CP	CR		;TEST IF END OF LINE
	RET	Z		;RETURN ERROR IF IT IS
	CP	')'		;TEST IF PARAMETER(S) END
	RET	Z		;RETURN ERROR IF IT IS
	CP	','		;TEST IF MORE PARAMETERS
	RET	Z		;RETURN ERROR IF THERE ARE
	CP	'='		;TEST IF EQUALS SIGN
	JR	NZ,PASGET	;LOOP UNTIL FOUND OR ERROR
	INC	HL		;BUMP COMMAND LINE POINTER
	LD	DE,PASSWD	;POINT AT PASSWORD BUFFER
	LD	B,8		;NUMBER OF PASSWORD CHARACTERS
	PUSH	DE		;SAVE PASSWORD BUFFER POINTER
	PUSH	BC		;SAVE CHARACTER COUNTER
	LD	A,' '		;LOAD AN ASCII SPACE CHARACTER
PASGEC:	LD	(DE),A		;CLEAR PASSWORD CHARACTER
	INC	DE		;BUMP BUFFER POINTER
	DJNZ	PASGEC		;LOOP UNTIL BUFFER CLEARED
	POP	BC		;RECOVER CHARACTER COUNTER
	POP	DE		;RECOVER BUFFER POINTER
	CALL	PARSES		;PARSE PASSWORD INTO BUFFERS
	DEC	HL		;BACKUP COMMAND LINE POINTER
	OR	00000001B	;RESET ZERO FLAG (GOT PASSWORD)
	RET
;
;
; UPDATE PERMISSIONS AND PASSWORDS
;5BF7
UPEPAS:	LD	BC,(DCBONE+6)	;GET DRIVE CODE AND HASH INDEX
	CALL	REDDIR		;READ DIRECTORY SECTOR ENTRY
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	A,(HL)		;LOAD FILE ATTRIBUTES INTO A
	AND	11111000B	;MASK OFF PERMISSION BITS
	LD	D,0		;GET ATTRIBUTES CHANGED FLAGS
ATCHFL	Equ	$ - 1		;ATTRIBUTES CHANGED FLAGS
	BIT	0,D		;TEST IF ALL PERMISSIONS
	JR	Z,PERMNC	;SKIP IF UNCHANGED
	OR	0		;MERGE IN NEW PERMISSIONS
PERMBI	Equ	$ - 1		;PERMISSION BITS STORAGE
PERMNC:	OR	0		;SET NEW FILE VISIBILITY
VISIBI	Equ	$ - 1		;FILE VISIBILITY BIT STORAGE
	LD	(HL),A		;UPDATE FILE ATTRIBUTES
	LD	A,L		;GET BUFFER POINTER LSB
	ADD	A,16		;INDEX TO PASSWORD FIELDS
	LD	L,A		;UPDATE BUFFER POINTER LSB
	BIT	2,D		;TEST UPDATE PASSWORD CHANGED
	JR	Z,UPDPNC	;SKIP IF NO CHANGE
	LD	A,(MASHAL)	;ELSE GET PASSWORD HASH LSB
	LD	(HL),A		;STORE IN DIRECTORY ENTRY
	LD	A,(MASHAH)	;THEN GET PASSWORD HASH MSB
	INC	HL		;BUMP DIRECTORY ENTRY POINTER
	LD	(HL),A		;STORE PASSWORD HASH MSB
	DEC	HL		;BACKUP DIRECTORY ENTRY POINTER
UPDPNC:	INC	HL		;BUMP TO ACCESS
	INC	HL		; PASSWORD HASH LSB
	BIT	1,D		;TEST ACCESS PASSWORD CHANGED
	JR	Z,ACCPNC	;SKIP IF NO CHANGE
	LD	A,(FILHAL)	;ELSE GET PASSWORD HASH LSB
	LD	(HL),A		;STORE IN DIRECTORY ENTRY
	LD	A,(FILHAH)	;GET PASSWORD HASH MSB
	INC	HL		;BUMP DIRECTORY ENTRY POINTER
	LD	(HL),A		;STORE PASSWORD HASH MSB
ACCPNC:	CALL	WRTDIR		;WRITE DIRECTORY SECTOR
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	JP	DOSENT		;ELSE RETURN TO DOS READY
;
;
; ATTRIBUTE SPECIFICATION ERROR ROUTINE
;5C39
ATTERR:	LD	HL,ATTERM	;POINT AT ERROR MESSAGE
	CALL	DOPMSG		;DISPLAY THE MESSAGE
	JP	ERRENT		;EXIT TO DOS ERROR HANDLER
;
;
; ATTTIBUTE SPECIFICATION ERROR MESSAGE
;5C42
ATTERM	Db	LF,'ATTRIBUTE SPECIFICATION ERROR',CR
;
;
; 'PROT' PARAMETER LIST FOR 'ATTRIB' PROCESSING
;5C61
ATTPRO	Db	'EX'		;EXECUTE
	Db	'RE'		;READ
	Db	'WR'		;WRITE
	Db	'~~'		;UNKNOWN
	Db	'NA'		;NO ACCESS
	Db	'KI'		;KILL
	Db	'FU'		;FULL
;
;
; STORE 'DIR' COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	DIRCMJ+1
;
	Dw	DIRCMD		;'DIR' COMMAND ADDRESS
;
;
; 'DIR' COMMAND PROCESSING
; FORMAT:  DIR [[:D] [(I[,S][,A])]]
;
	Org	05C6FH
;
DIRCMD:	LD	BC,0		;ZERO BC REGISTER
	LD	(DALLFL),BC	;CLEAR ALLOCATION LIST FLAG
	LD	(DINVFL),BC	;CLEAR INVISIBLE FILES FLAG
	LD	(DSYSFL),BC	;CLEAR SYSTEM FILES FLAG
	LD	C,0		;DEFAULT TO DRIVE ZERO
	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	CP	':'		;TEST IF DRIVE DELIMITER
	JR	NZ,DIRCND	;USE DEFAULT DRIVE IF NOT
	INC	HL		;BUMP COMMAND LINE POINTER
	LD	A,(HL)		;GET ASCII DRIVE CODE TO A
	INC	HL		;BUMP COMMAND LINE POINTER
	SUB	'0'		;REMOVE ASCII BIAS
	LD	C,A		;COPY DRIVE CODE TO C
DIRCND:	PUSH	BC		;SAVE THE DRIVE CODE
	LD	A,C		;GET DRIVE CODE TO A
	ADD	A,'0'		;CONVERT CODE TO ASCII
	LD	(DIRHDF),A	;STORE DRIVE CODE IN STRING
	LD	DE,DIROPT	;POINT AT PARAMETER STRINGS
	CALL	PARSEC		;PARSE THE COMMAND LINE
	LD	HL,DIRHDR	;POINT AT DIRECTORY HEADER
	CALL	DOPMSG		;DISPLAY THE HEADER STRING
	POP	BC		;RECOVER DRIVE CODE
	PUSH	BC		;RESAVE THE DRIVE CODE
	CALL	TRKDIR		;GET DIRECTORY TRACK NUMBER
	LD	E,0		;SET TO 'GAT' SECTOR
	LD	HL,DIRBUF	;POINT AT SECTOR BUFFER
	CALL	DDREAD		;READ THE 'GAT' SECTOR
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	HL,DIRBUF+DNA	;POINT AT DISK NAME STRING
	LD	DE,DIRHNA	;POINT AT HEADER NAME FIELD
	LD	BC,8		;LOAD SIZE OF NAME STRING
	LDIR			;COPY NAME INTO THE HEADER
	LD	DE,DIRMDF	;POINT AT DATE HEADER FIELD
	LD	BC,8		;LOAD SIZE OF DATE STRING
	LDIR			;COPY DATE INTO HEADER
	LD	HL,DIRHNA	;POINT AT DISK NAME AND DATE
	CALL	DOPMSG		;DISPLAY THE STRING
	POP	BC		;RECOVER DRIVE CODE
	LD	B,0		;LOAD 'HIT' SECTOR INDEX
	LD	DE,RECBUF	;LOAD BUFFER POINTER TO DE
DIRCNS:	CALL	REDDIR		;READ DIRECTORY SECTOR ENTRY
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	L,Low DIRBUF	;INDEX TO BUFFER START
	PUSH	BC		;SAVE 'HIT' INDEX AND DRIVE
	LD	BC,SECSIZ	;LOAD SECTOR SIZE TO BC
	LDIR			;COPY DIRECTORY SECTOR LOCALLY
	POP	BC		;RECOVER 'HIT' INDEX AND DRIVE
	INC	B		;BUMP TO NEXT 'HIT' ENTRY
	LD	A,B		;GET THE INDEX TO A
	CP	NUMSEC - 2	;TEST IF LAST SECTOR READ
	JR	NZ,DIRCNS	;LOOP UNTIL ALL DONE
	LD	HL,RECBUF	;LOAD BUFFER POINTER TO HL
	LD	A,12		;LOAD LINE COUNTER TO A
	LD	(DIRCLC),A	;SAVE THE LINE COUNT
	LD	B,3		;LOAD FIELD COUNT TO B
DIRCNF:	LD	A,(HL)		;LOAD PERMISSION FLAGS TO A
	PUSH	HL		;SAVE SECTOR BUFFER POINTER
	BIT	4,A		;TEST IF ASSIGNED TO A FILE
	JP	Z,DIRCNX	;NEXT ENTRY IF UNASSIGNED
	BIT	7,A		;TEST IF PRIMARY ENTRY
	JP	NZ,DIRCNX	;NEXT ENTRY IF EXTENSION
	BIT	6,A		;TEST IF A SYSTEM FILE
	JR	Z,DIRCTI	;CONTINUE IF NOT SYSTEM FILE
	LD	DE,0		;GET SYSTEM FILE DISPLAY FLAG
DSYSFL	Equ	$ - 2		;DISPLAY SYSTEM FILES FLAG
	LD	A,D		;GET SYSTEM FILES FLAG MSB
	OR	E		;TEST IF SYSTEM FILES ALLOWED
	JP	Z,DIRCNX	;NEXT ENTRY IF NOT ALLOWED
	JR	DIRCNA		;THEN CONTINUE TESTING FLAGS
DIRCTI:	BIT	3,A		;TEST IF INVISIBLE FILE
	JR	Z,DIRCNA	;CONTINUE IF NOT INVISIBLE
	LD	DE,0		;INVISIBLE FILES DISPLAY FLAG
DINVFL	Equ	$ - 2		;DISPLAY INVISIBLE FILES FLAG
	LD	A,D		;GET INVISIBLE FLAG MSB
	OR	E		;TEST INVISIBLE FILES ALLOWED
	JP	Z,DIRCNX	;NEXT ENTRY IF NOT ALLOWED
DIRCNA:	PUSH	BC		;SAVE FIELD COUNT FOR LATER
	LD	A,L		;GET SECTOR POINTER LSB TO A
	ADD	A,5		;INDEX TO START OF NAME
	LD	L,A		;UPDATE SECTOR POINTER LSB
	LD	C,17		;LOAD FIELD WIDTH TO C
	LD	B,8		;LOAD NAME CHARACTER COUNT
DIRCNL:	LD	A,(HL)		;GET A NAME CHARACTER
	INC	HL		;BUMP THE NAME POINTER
	CP	' '		;TEST IF SPACE CHARACTER
	JR	Z,DIRCNE	;THEN DONE WITH THE NAME
	CALL	VDCHAR		;DISPLAY THE NAME CHARACTER
	DEC	C		;DECREMENT FIELD WIDTH
	DJNZ	DIRCNL		;LOOP FOR NEXT NAME CHARACTER
	JR	DIRCSE		;THEN DISPLAY SEPERATOR
DIRCNE:	LD	A,L		;GET BUFFER INDEX LSB
	ADD	A,B		;ADD REMAING COUNT
	DEC	A		;BACKUP ONE CHARACTER
	LD	L,A		;UPDATE BUFFER INDEX LSB
DIRCSE:	LD	A,(HL)		;GET EXTENSION CHARACTER
	CP	' '		;TEST IF SPACE CHARACTER
	JR	Z,DIRCEE	;THEN SPACE OUT TO NEXT FIELD
	LD	A,'/'		;NAME AND EXTENSION SEPERATOR
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	DEC	C		;DECREMENT FIELD WIDTH
	LD	B,3		;EXTENSION CHARACTER COUNT
DIRCCE:	LD	A,(HL)		;GET EXTENSION CHARACTER
	INC	HL		;BUMP THE EXTENSION POINTER
	CP	' '		;TEST IF SPACE CHARACTER
	JR	Z,DIRCEE	;SKIP THE SPACE IF SO
	CALL	VDCHAR		;ELSE DISPLAY THE CHARACTER
	DEC	C		;DECREMENT FIELD WIDTH
	DJNZ	DIRCCE		;LOOP FOR NEXT CHARACTER
DIRCEE:	LD	A,' '		;LOAD A SPACE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	DEC	C		;DECREMENT FIELD WIDTH
	LD	A,L		;GET BUFFER INDEX LSB
	AND	11100000B	;MASK TO NEXT BUFFER ENTRY
	LD	L,A		;UPDATE BUFFER POINTER
	LD	B,(HL)		;GET ACCESS CONTROL BYTE
	LD	A,'S'		;ASSUME SYSTEM FILE
	BIT	6,B		;TEST IF SYSTEM
	JR	NZ,DIRCIS	;CONTINUE IF IT IS
	LD	A,' '		;ELSE LOAD A SPACE CHARACTER
DIRCIS:	CALL	VDCHAR		;DISPLAY THE CHARACTER
	LD	A,'I'		;ASSUME INVISIBLE FILE
	BIT	3,B		;TEST IF INVISIBLE
	JR	NZ,DIRCII	;CONTINUE IF IT IS
	LD	A,' '		;ELSE LOAD A SPACE CHARACTER
DIRCII:	CALL	VDCHAR		;DISPLAY THE CHARACTER
	PUSH	HL		;SAVE BUFFER POINTER
	LD	A,L		;GET BUFFER POINTER LSB TO A
	ADD	A,16		;INDEX TO ACCESS PASSWORD
	LD	L,A		;UPDATE BUFFER POINTER LSB
	LD	E,(HL)		;GET ACCESS PASSWORD LSB TO E
	INC	L		;BUMP BUFFER POINTER
	LD	D,(HL)		;GET ACCESS PASSWORD MSB TO D
	PUSH	HL		;SAVE BUFFER POINTER
	LD	HL,PASSWO	;LOAD DEFAULT PASSWORD TO HL
	SBC	HL,DE		;TEST IF DEFAULT PASSWORD
	POP	HL		;RECOVER BUFFER POINTER
	JR	Z,DIRCPM	;SKIP IF PASSWORD MATCH
	LD	A,B		;GET ACCESS CONTROL BYTE
	AND	00000111B	;MASK TO PERMISSION BITS
	LD	A,'P'		;LOAD PROTECTED CHARACTER
	JR	NZ,DIRCBP	;CONTINUE IF PROTECTED
	INC	L		;BUMP BUFFER POINTER
	LD	E,(HL)		;GET UPDATE PASSWORD LSB TO E
	INC	L		;BUMP BUFFER POINTER
	LD	D,(HL)		;GET UPDATE PASSWORD MSB TO D
	LD	HL,PASSWO	;LOAD DEFAULT PASSWORD TO HL
	SBC	HL,DE		;TEST IF DEFAULT PASSWORD
	LD	A,'P'		;LOAD PROTECTED CHARACTER
	JR	NZ,DIRCBP	;SKIP IF NOT THE DEFAULT
DIRCPM:	LD	A,' '		;NOT PROTECTED CHARACTER
DIRCBP:	CALL	VDCHAR		;DISPLAY THE CHARACTER
	POP	HL		;RECOVER BUFFER POINTER
DIRCSF:	LD	A,' '		;LOAD SPACE CHARACTER
	CALL	VDCHAR		;DISPLAY THE SPACE
	DEC	C		;DECREMENT FIELD WIDTH
	JR	NZ,DIRCSF	;LOOP UNTIL FIELD PADDED
	LD	DE,0		;GET FILE ALLOCATION FLAG
DALLFL	Equ	$ - 2		;DISPLAY FILE ALLOCATION FLAG
	LD	A,D		;GET ALLOCATION FLAG MSB TO A
	OR	E		;TEST IF ALLOCATION DISPLAY
	POP	BC		;RECOVER FIELD COUNT TO B
	CALL	NZ,DIRCAL	;DISPLAY ALLOCATIONS IF WANTED
	DJNZ	DIRCNX		;ELSE LOOP FOR NEXT FIELD
	LD	A,CR		;LOAD A NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	LD	A,0		;GET LINE COUNTER TO A
DIRCLC	Equ	$ - 1		;STORAGE FOR LINE COUNT
	DEC	A		;DECREMENT THE LINE COUNT
	JR	NZ,DIRCML	;SKIP IF MORE LINES TO DO
	CALL	KBWAIT		;ELSE WAIT FOR A KEYPRESS
	LD	A,12		;LOAD LINE COUNT TO A
DIRCML:	LD	(DIRCLC),A	;SET THE LINE COUNTER
	CALL	BRKHLT		;TEST FOR PAUSE KEY
	JP	NZ,DIRCER	;ABORT IF <BREAK> KEY PRESSED
	LD	B,3		;LOAD FIELD COUNT TO B
DIRCNX:	POP	HL		;RECOVER BUFFER POINTER
	INC	H		;BUMP TO NEXT BUFFER PAGE
	LD	A,H		;GET BUFFER POINTER MSB TO A
	CP	High RECBUE	;TEST IF DIRECTORY END
	JP	NZ,DIRCNF	;LOOP FOR NEXT ENTRY IF NOT
	LD	H,High RECBUF	;ELSE SET TO BUFFER START
	LD	A,L		;GET BUFFER INDEX TO A
	ADD	A,32		;INDEX TO NEXT ENTRY
	LD	L,A		;UPDATE BUFFER POINTER
	JP	NC,DIRCNF	;LOOP IF MORE REMAINING
	CALL	DIRCLR		;ELSE CLEAR OUT THE BUFFER
	LD	A,CR		;LOAD NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	JP	DOSENT		;THEN RETURN TO DOS PROMPT
;
;
; CLEAR OUT DIRECTORY BUFFER AND ABORT TO DOS ERROR
;5DDB
DIRCER:	CALL	DIRCLR		;CLEAR OUT THE BUFFER
	JP	ERRENT		;THEN RETURN TO DOS ERROR
;
;
; CLEAR OUT DIRECTORY BUFFER TO ALL ZEROES
;5DE1
DIRCLR:	LD	HL,RECBUF	;LOAD BUFFER POINTER TO HL
	LD	B,0		;ZERO B REGISTER
DIRCLL:	LD	(HL),B		;STORE A ZERO IN THE BUFFER
	INC	L		;BUMP BUFFER POINTER LSB
	JR	NZ,DIRCLL	;LOOP UNTIL PAGE IS CLEARED
	INC	H		;BUMP BUFFER POINTER MSB
	LD	A,H		;GET BUFFER ADDRESS MSB TO A
	CP	High RECBUE	;TEST IF BUFFER ALL CLEARED
	JR	NZ,DIRCLL	;LOOP FOR NEXT PAGE IF NOT
	RET
;
;
; 'A' OPTION SPECIFIED - DISPLAY FILE ALLOCATIONS
;5dF1
DIRCAL:	PUSH	HL		;SAVE BUFFER POINTER
	INC	L		;BUMP BUFFER POINTER
	INC	L		; TO 'EOF' SECTOR
	INC	L		;  BUFFER ADDRESS
	LD	A,(HL)		;GET 'EOF' BYTE OFFSET
	LD	(EOFBOF),A	;SAVE THE OFFSET FOR LATER
	INC	L		;BUMP TO LOGICAL RECORD LENGTH
	PUSH	HL		;SAVE THE BUFFER POINTER
	LD	L,(HL)		;GET LOGICAL RECORD LENGTH
	LD	A,L		;COPY THE LENGTH TO A
	LD	(LRLSIZ),A	;SAVE THE LENGTH FOR LATER
	SUB	1		;FORCE CARRY IF 'LRL' = 256 (0)
	LD	A,0		;LOAD ZERO BYTE TO A
	ADC	A,0		;ADD THE CARRY TO A
	LD	H,A		;SIXTEEN BIT VALUE IS IN HL
	LD	DE,DIRHDL	;POINT AT LOGICAL RECORD FIELD
	CALL	WORASC		;CONVERT TO DECIMAL AND STORE
	POP	HL		;RECOVER BUFFER POINTER
	LD	A,L		;GET ADDRESS LSB TO A
	ADD	A,16		;INDEX TO 'EOF' SECTOR NUMBER
	LD	L,A		;FORM THE ADDRESS IN HL
	LD	A,(HL)		;GET ENDING SECTOR LSB TO A
	LD	(EOFSEL),A	;SAVE THE ENDING SECTOR BYTE
	INC	L		;BUMP POINTER TO MSB
	LD	A,(HL)		;GET ENDING SECTOR MSB TO A
	LD	(EOFSEM),A	;SAVE THE ENDING SECTOR BYTE
	LD	HL,EOFSEM	;POINT AT SECTOR NUMBER MSB
	LD	C,0		;GET LOGICAL RECORD LENGTH
LRLSIZ	Equ	$ - 1		;LOGICAL RECORD LENGTH STORAGE
	CALL	DIVIDE		;DIVIDE RECORD COUNT BY SIZE
	EX	DE,HL		;SWAP QUOTIENT TO HL
	LD	DE,DIRHDE	;POINT AT 'EOF' NUMBER FIELD
	CALL	WORASC		;CONVERT TO DECIMAL AND STORE
	POP	HL		;RESTORE 'LRL' ADDRESS
	CALL	GETGRC		;GO COMPUTE GRANULE COUNT
	EX	DE,HL		;SWAP THE COUNT TO HL
	LD	DE,DIRHDG	;POINT AT FILE SIZE FIELD
	CALL	WORASC		;CONVERT TO DECIMAL AND STORE
	LD	HL,DIRHDP	;POINT AT ALLOCATION STRING
	CALL	DOPMSG		;DISPLAY THE MESSAGE
	LD	B,1		;SET LINE COUNTER TO ONE
	RET
;
;
; COMPUTE GRANULE COUNT
;5E3E
GETGRC:	LD	DE,0		;ZERO ACCUMULATOR
	LD	A,L		;FETCH LSB OF LRL
	ADD	A,22		;POSITION INTO "GAP'S"
	LD	L,A		;FORM ADDRESS OF "GAP'S" IN HL
GETGRL:	LD	A,(HL)		;FETCH FIRST BYTE OF A 'GAP'
	INC	L		;BUMP TO GRANULE COUNT
	CP	11111110B	;TEST FOR END OR OVERFLOW
	JR	NC,GETGRE	;GO IF END OR OVERFLOW
	LD	A,(HL)		;LOAD GRANULE COUNT TO A
	INC	L		;BUMP TO NEXT 'GAP'
	AND	00011111B	;ISOLATE GRANULE COUNT
	INC	A		;COMPUTE TRUE GRANULE COUNT
	ADD	A,E		;FORM SUM IN DE
	LD	E,A		;UPDATE LSB OF SUM
	JR	NC,GETGRL	;CONTINUE IF NOT OVERFLOW
	INC	D		;ELSE BUMP MSB OF THE COUNT
	JR	GETGRL		;LOOP UNTIL END OF "GAP'S"
;
;
; REACHED END OF "GAP'S" OR AN OVERFLOW ENTRY
;5E57
GETGRE:	RET	NZ		;ALL DONE IF END OF "GAP'S"
	LD	B,(HL)		;GET POINTER TO OVERFLOW ENTRY
	LD	A,B		;COPY THE POINTER TO A
	AND	00000111B	;ISOLATE SECTOR NUMBER
	ADD	A,High RECBUF	;FORM ADDRESS IN SECTORS BUFFER
	LD	H,A		;COPY ADDRESS MSB TO H
	LD	A,B		;GET OVERFLOW POINTER TO A
	AND	11100000B	;ISOLATE OFFSET TO FILE ENTRY
	ADD	A,22		;INDEX INTO THE "GAP'S"
	LD	L,A		;OVERFLOW "GAP'S" ADDRESS IN HL
	JR	GETGRL		;CONTINUE UNTIL "GAP'S" END
;
;
; STORAGE LOCATIONS FOR 'DIR' COMMAND
;5E67
EOFSEM	Ds	1		;MSB OF 'EOF' SECTOR
EOFSEL	Ds	1		;LSB OF 'EOF' SECTOR
EOFBOF	Ds	1		;HOLDS 'EOF' BYTE OFFSET
;
;
; 'DIR' OPTION TEXT LIST
;
DIROPT	Db	'A     '
	Dw	DALLFL		;DISPLAY ALLOCATIONS
	Db	'I     '
	Dw	DINVFL		;DISPLAY INVISIBLE
	Db	'S     '
	Dw	DSYSFL		;DISPLAY SYSTEM
	Db	0
;
;
; FILE DIRECTORY HEADER STRING FIRST PART
;5E83
DIRHDR	Db	HO,CE,'FILE DIRECTORY --- DRIVE X',CO+5,CC
;
;
; DEFINE FIELD OFFSET TO DRIVE CODE IN ABOVE HEADER STRING
;5997
DIRHDF	Equ	$ - 3		;OFFSET TO DRIVE CODE
;
;
; FILE DIRECTORY HEADER STRING SECOND PART DISK NAME AND DATE
;5EA1
	If	PATCHG		;PATCHES ACTIVE
DIRHNA	 Db	'NNNNNNNN -- DD.MM.YY',LF,CR
	Else			;ORIGINAL
DIRHNA	 Db	'NNNNNNNN -- MM/DD/YY',LF,CR
	EndIf			;ALL DONE
;
;
; DEFINE FIELD OFFSET TO DATE IN ABOVE HEADER STRING
:
DIRMDF	Equ	$ - 10		;OFFSET TO DATE STRING
;
;
; FILE DIRECTORY DETAILED FILE INFORMATION STRING
;5EB7
DIRHDP	Db	'LRL=      / EOF=      / SIZE=      GRANS',CC
;
;
; DEFINE FIELD OFFSETS INTO DETAILED 'DIR' HEADER STRING
;
DIRHDL	Equ	$ - 37		;LRL NUMBER
DIRHDE	Equ	$ - 25		;EOF NUMBER
DIRHDG	Equ	$ - 12		;GRANS NUMBER
;
;
; STORE 'FREE' COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	FRECMJ + 1
;
	Dw	FRECMD		;'FREE' COMMAND ADDRESS
;
;
; 'FREE' COMMAND PROCESSING
; FORMAT:  FREE
;
	Org	05EE0H
;
FRECMD:	LD	C,0		;INIT UNIT NUMBER TO ZERO
	LD	A,CC		;LOAD A STRING TERMINATOR
	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	LD	(DE),A		;STORE EMPTY FILESPEC IN DCB
	CALL	OPNFIL		;LOAD 'SYS2/SYS' BY OPEN CALL
FRECND:	PUSH	BC		;SAVE DRIVE CODE FOR LATER
	CALL	TSTRDY		;TEST DRIVE READY STATUS
	JR	NZ,FRECBD	;SKIP IF NO DRIVE AVAILABLE
	LD	A,C		;ELSE GET UNIT NUMBER TO A
	ADD	A,'0'		;CONVERT TO ASCII DRIVE CODE
	LD	(FREMCF),A	;STORE IN HEADER DRIVE FIELD
	CALL	REDGAT		;READ 'GAT' SECTOR TO BUFFER
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	HL,GATBUF+DNA	;GET DISK NAME POINTER
	LD	DE,FREMNF	;POINT AT HEADER NAME FIELD
	LD	BC,8		;LOAD CHARACTER COUNT
	LDIR			;MOVE THE NAME INTO STRING
	LD	DE,FREMDF	;POINT AT HEADER DATE FIELD
	LD	BC,8		;LOAD CHARACTER COUNT
	LDIR			;MOVE THE DATE INTO STRING
	LD	HL,GATBUF	;POINT AT 'GAT' BUFFER
	LD	DE,0		;ZERO GRANULE COUNTER
	LD	B,NUMTRK	;LOAD TRACK COUNT TO B
FRECFG:	LD	A,(HL)		;GET ALLOCATION BITS TO A
FRECNG:	SCF			;SET CARRY FLAG FOR TESTING
	RRA			;ROTATE GRANULE BIT TO CARRY
	JR	C,FRECGA	;SKIP IF GRANULE ALLOCATED
	INC	DE		;ELSE COUNT GRANULE FREE
FRECGA:	CP	11111111B	;TEST IF ANOTHER ONE FREE
	JR	NZ,FRECNG	;THEN GO COUNT IT
	INC	L		;BUMP 'GAT' BUFFER POINTER
	DJNZ	FRECFG		;LOOP UNTIL TABLE ALL TESTED
	EX	DE,HL		;SWAP GRANULE COUNT TO HL
	LD	DE,FREMGF+1	;POINT AT FREE GRANS SLOT
	CALL	WORASC		;CONVERT AND STORE THE NUMBER
	POP	BC		;RECOVER UNIT NUMBER
	PUSH	BC		;RESAVE UNIT NUMBER
	CALL	REDHIT		;READ 'HIT' SECTOR
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	HL,HITBUF+UHI	;POINT AT 'HIT' BUFFER
	LD	DE,0		;CLEAR FREE FILES COUNT
FRECFF:	LD	A,(HL)		;FETCH AN 'HIT' ENTRY
	OR	A		;TEST IF SLOT ASSIGNED
	JR	NZ,FRECFA	;NEXT ENTRY IF ASSIGNED
	INC	DE		;ELSE COUNT FILE ENTRY FREE
FRECFA:	INC	L		;BUMP TO NEXT 'HIT' SLOT
	LD	A,L		;GET POINTER LSB TO A
	AND	11100111B	;MASK TO RELEVANT BITS
	CP	L		;TEST IF SLOT RANGE END
	JR	Z,FRECFF	;LOOP FOR NEXT IF NOT
	ADD	A,NHI		;BUMP TO NEXT SLOT AREA
	LD	L,A		;UPDATE 'HIT' BUFFER POINTER
	JR	NZ,FRECFF	;LOOP FOR NEXT IF NOT END
	EX	DE,HL		;SWAP THE FILE COUNT TO HL
	LD	DE,FREMFF	;POINT AT FREE FILES SLOT
	CALL	WORASC		;CONVERT AND STORE NUMBER
	LD	HL,FREMSG	;POINT AT MESSAGE STRING
	CALL	DOPMSG		;DISPLAY THE MESSAGE
FRECBD:	POP	BC		;RECOVER DISK DRIVE NUMBER
	INC	C		;BUMP THE DRIVE NUMBER
	LD	A,C		;GET DRIVE NUMBER TO A
	CP	MAXDRV		;TEST IF ALL DRIVES DONE
	JR	NZ,FRECND	;LOOP FOR NEXT DRIVE IF NOT
	JP	DOSENT		;RE-ENTER TO DOS PROMPT
;
;
; 'FREE' DISPLAY MESSAGES
;5F62
FREMSG	Db	'DRIVE X --  '
;
	If	PATCHG		;PATCHES ACTIVE
FREMNF	 Db	'NNNNNNNN   DD.MM.YY        FILES,'
	Else			;ORIGINAL
FREMNF	 Db	'NNNNNNNN   MM/DD/YY        FILES,'
	EndIf			;ALL DONE
;
FREMGF	Db	'       GRANS',CR
;
;
; DEFINE FIELD DISPLAY OFFSETS INTO 'FREE' HEADER STRINGS
;
FREMCF	Equ	FREMSG +  6	;DRIVE NUMBER CODE
FREMDF	Equ	FREMNF + 11	;DISK CREATION DATE STRING
FREMFF	Equ	FREMNF + 21	;NUMBER OF FREE DISK FILES
;
;
; STORE 'RENAME' COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	RENCMJ + 1
;
	Dw	RENCMD		;'RENAME' COMMAND ADDRESS
;
;
; 'RENAME' COMMAND PROCESSING
; FORMAT:  RENAME <FILESPEC> TO <FILESPEC>
;
	Org	05F9CH
;
RENCMD:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF ILLEGAL OR NO NAME
	LD	A,(DE)		;GET FILE NAME CHARACTER
	CP	'*'		;TEST IF DEVICE SPEC HEADER
	JP	Z,FSPREQ	;THEN WE ABORT THE RENAME
	CALL	OPNFIL		;ELSE OPEN THE FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	DE,DCBTWO	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF ILLEGAL OR NO NAME
	LD	A,(DCBONE+1)	;GET ACCESS FLAGS TO A
	AND	00000111B	;MASK TO PERMISSION BITS
	CP	00000011B	;TEST IF FILE IS PROTECTED
	LD	A,25H		;ABORT TO SYSTEM IF PROTECTED
	JP	NC,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	HL,DCBTWO	;POINT AT DEVICE CONTROL BLOCK
RENCSE:	LD	A,(HL)		;GET FILENAME CHARACTER
	CP	':'		;TEST IF DRIVE CODE DELIMITER
	JR	Z,ILLOND	;THAT WOULD BE ILLEGAL
	CP	' '		;TEST IF SPACE CHARACTER
	JR	C,RENCEN	;DONE IF CONTROL CHARACTER
	INC	HL		;ELSE BUMP FILENAME POINTER
	JR	RENCSE		;THEN CONTINUE SCANNING
RENCEN:	LD	(HL),':'	;STORE DRIVE CODE DELIMITER
	INC	HL		;BUMP FILENAME POINTER
	LD	A,(DCBONE+6)	;GET DRIVE CODE FROM DCB
	ADD	A,'0'		;CONVERT THE CODE TO ASCII
	LD	(HL),A		;STORE THE DRIVE CODE IN DCB
	INC	HL		;BUMP FILENAME POINTER
	LD	(HL),CC		;STORE TERMINATING CHARACTER
	LD	DE,DCBTWO	;POINT AT DEVICE CONTROL BLOCK
	CALL	OPNFIL		;TRY TO OPEN THE FILE
	JP	Z,ALREXI	;ABORT IF FILE ALREADY EXISTS
	CP	18H		;TEST IF FILE NOT IN DIRECTORY
	JP	NZ,SYSABO	;ABORT TO IF FILE EXISTS
	LD	BC,(DCBONE+6)	;GET DRIVE AND OVERFLOW POINTER
	PUSH	BC		;SAVE THE DRIVE AND POINTER
	CALL	REDDIR		;READ THE DIRECTORY SECTOR
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	D,H		;DESTINATION POINTER MSB TO D
	LD	A,L		;DESTINATION POINTER LSB TO E
	ADD	A,5		;INDEX TO FILE NAME FIELD
	LD	E,A		;UPDATE DESTINATTION POINTER
	LD	HL,FILNAM	;POINT AT FILESPEC BUFFER
	LD	BC,11		;LOAD LENGTH OF FILESPEC
	LDIR			;COPY FILESPEC TO DIRECTORY
	POP	BC		;RECOVER UNIT AND OVERFLOW PTR
	CALL	WRTDIR		;WRITE DIRECTORY SECTOR
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	CALL	REDHIT		;READ 'HIT' SECTOR
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	D,H		;GET 'HIT' SSECTOR POINTER MSB
	LD	E,B		;GET OVERFLOW POINTER TO E
	PUSH	BC		;SAVE UNIT AND POINTER
	LD	HL,FILNAM	;POINT AT FILESPEC BUFFER
	CALL	FSHASH		;COMPUTE FILE NAME HASH CODE
	POP	BC		;RECOVER UNIT AND OVERFLOW PTR
	LD	(DE),A		;STORE THE HASH CODE
	CALL	WRTHIT		;WRITE 'HIT' SECTOR
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	JP	DOSENT		;ELSE GO TO DOS PROMPT
;
;
; DRIVE CODE IS ILLEGAL ON DESTINATION FILE NAME
;6028
ILLOND:	LD	HL,ILLONM	;POINT AT ERROR MESSAGE
	CALL	DOPMSG		;DISPLAY THE MESSAGE STRING
	JP	ERRENT		;THEN ABORT TO DOS ERROR
;
;
; DRIVE CODE ILLEGAL ACROSS DISKS
;6031
ILLONM	Db	LF,'DRIVE SPECIFICATION ILLEGAL',CR
;
;
; ERROR ROUTINE IF NEW FILE NAME ALREADY EXISTS IN DIRECTORY
;604E
ALREXI:	LD	HL,ALREXM	;POINT AT ERROR MESSAGE
	CALL	DOPMSG		;DISPLAY THE MESSAGE STRING
	JP	ERRENT		;THEN ABORT TO DOS ERROR
;
;
; ERROR MESSAGE FOR FILE NAME ALREADY PRESENT IN DIRECTORY
;6057
ALREXM	Db	LF,'DUPLICATE FILE NAME',CR
;
;
; CONVERT A BINARY NUMBER TO ASCII DECIMAL STRING
; ENTRY:  DE      - POINTER TO STRING STORAGE
;         HL      - BINARY NUMBER
; EXIT:   DE      - POINTER TO END OF STORAGE
;         HL      - LAST QUOTIENT
;606C
WORASC:	LD	A,' '		;LOAD PAD CHARACTER
	LD	BC,10000	;LOAD TEN THOUSANDS DIVISOR
	CALL	DIGASC		;DIVIDE AND STORE DIGIT
	LD	BC,1000		;LOAD THOUSANDS DIVISOR
	CALL	DIGASC		;DIVIDE AND STORE DIGIT
	LD	BC,100		;LOAD HUNDREDS DIVISOR
	CALL	DIGASC		;DIVIDE AND STORE DIGIT
	LD	BC,10		;LOAD TENS DIVISOR
	CALL	DIGASC		;DIVIDE AND STORE DIGIT
	LD	A,L		;GET REMAINDER TO A
	ADD	A,'0'		;CONVERT TO ASCII DECIMAL
	LD	(DE),A		;STORE CHARACTER IN STRING
	INC	DE		;BUMP STORAGE POINTER
	RET
;
;
; CONVERT A BINARY DIGIT TO ASCII DECIMAL BY SUBTRACTION
; ENTRY:  A       - PAD CHARACTER
;         HL      - BINARY NUMBER
;         BC      - DIVISOR
;         DE      - POINTER TO STRING STORAGE
; EXIT:   A       - PAD CHANGED TO '0' IF NON-ZERO DIGIT
;         B       - QUOTIENT
;         HL      - REMAINDER FROM DIVISION
;         DE      - STORAGE POINTER INCREMENTED
;608C
DIGASC:	PUSH	DE		;SAVE STORAGE POINTER
	LD	E,A		;GET PAD CHARACTER TO E
	LD	D,-1		;INITIALIZE QUOTIENT
	XOR	A		;CLEAR CARRY FLAG
DIGASS:	INC	D		;BUMP QUOTIENT
	SBC	HL,BC		;SUBTRACT DIVISOR
	JR	NC,DIGASS	;LOOP UNTIL UNDERFLOW
	ADD	HL,BC		;CORRECT THE UNDERFLOW
	LD	A,E		;GET PAD CHARACTER TO A
	LD	B,D		;GET QUOTIENT TO B
	POP	DE		;RECOVER STORAGE POINTER
	LD	(DE),A		;STORE PAD IN STORAGE
	INC	B		;BUMP QUOTIEND
	DEC	B		;DECREMENT QUOTIENT
	JR	Z,DIGASX	;DONE IF QUOTIENT ZERO
	LD	A,B		;COPY QUOTIENT TO A
	ADD	A,'0'		;CONVERT TO ASCII DECIMAL
	LD	(DE),A		;STORE DIGIT IN BUFFER
	LD	A,'0'		;CHANGE PAD CHARACTER
DIGASX:	INC	DE		;BUMP STORAGE POINTER
	RET
;
;
; DIVIDE A THREE BYTE NUMBER BY A ONE BYTE NUMBER
; ENTRY:  C       - DIVISOR
;         HL      - POINTER TO SIXTEEN BIT DIVIDEND
; EXIT:   DE      - QUOTIENT
;60A7
DIVIDE:	LD	DE,0		;ZERO QUOTIENT REGISTER
	LD	A,C		;GET DIVISOR TO A FOR TEST
	OR	A		;TEST IF DIVISION BY ZERO
	JR	Z,DIVIZE	;THEN JUST RETURN DIVIDEND
	XOR	A		;CLEAR CARRY AND ACCUMULATOR
	LD	B,3		;NUMBER OF BYTES IN DIVIDEND
DIVIOL:	PUSH	BC		;SAVE DIVISOR AND BYTE COUNT
	PUSH	HL		;SAVE CURRENT DIVIDEND ADDRESS
	LD	H,(HL)		;FETCH A BYTE TO DIVIDE
	LD	B,8		;NUMBER OF BITS TO TEST IN BYTE
DIVIIL:	EX	DE,HL		;SWAP QUOTIENT TO HL
	ADD	HL,HL		;LEFT SHIFT QUOTIENT
	EX	DE,HL		;SWAP QUOTIENT BACK TO DE
	RLC	H		;ROTATE MS BIT TO CARRY
	RLA			;ROTATE BIT INTO ACCUMULATOR
	CP	C		;COMPARE TO DIVISOR
	JR	C,DIVILE	;JUMP IF DIVIDEND LESS
	SUB	C		;ADJUST DIVIDEND TO LESS
	INC	DE		;BUMP QUOTIENT REGISTER
DIVILE:	DJNZ	DIVIIL		;LOOP FOR ALL DIVIDEND BITS
	POP	HL		;RESTORE CURRENT BYTE ADDERSS
	INC	HL		;BUMP TO NEXT DIVIDEND
	POP	BC		;QUOTIENT OF DIVIDED BYTES
	DJNZ	DIVIOL		;LOOP UNTIL ALL BYTES DIVIDED
	RET
;
;
; DIVISION IS BY ZERO, SO RETURN QUOTIENT EQUAL TO DIVIDEND
; EXIT:  DE      - DIVIDEND
;60C9
DIVIZE:	LD	D,(HL)		;GET QUOTIENT MSB TO D
	INC	HL		;BUMP POINTER TO DIVIDEND
	LD	E,(HL)		;GET QUOTIENT LSB TO E
	RET
;
;
; STORE 'APPEND' COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	APNCMJ+1
;
	Dw	APPCMD		;'APPEND' COMMAND ADDRESS
;
;
; 'APPEND' COMMAND PROCESSING
; FORMAT:  APPEND <FILESPEC> TO <FILESPEC>
;
	Org	05700H
;
APPCMD:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF ANY ERRORS
	LD	A,(DE)		;GET CHARACTER FROM NAME
	CP	'*'		;TEST IF DEVICE SPEC HEADER
	JP	Z,FSPREQ	;THEN WE ABORT THE APPEND
	LD	DE,DCBTWO	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF ANY ERRORS
	LD	A,(DE)		;GET CHARACTER FROM NAME
	CP	'*'		;TEST IF DEVICE SPEC HEADER
	JP	Z,FSPREQ	;THEN WE ABORT THE APPEND
	LD	B,0		;LOAD LOGICAL RECORD LENGTH
	LD	HL,SECBUF	;POINT AT SECTOR BUFFER
	CALL	OPNFIL		;OPEN INPUT FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	B,0		;LOAD LOGICAL RECORD LENGTH
	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	LD	HL,SCTBUF	;POINT AT SECTOR BUFFER
	CALL	OPNFIL		;OPEN OUTPUT FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	DE,DCBTWO	;POINT AT DEVICE CONTROL BLOCK
	CALL	POSEOF		;POSITION AT FILE END
	NOP			;DO
	NOP			; ABSOLUTELY
	NOP			;  AND
	NOP			;   TOTALLY
	NOP			;    NOTHING
	NOP			;     AT
	NOP			;      ALL
	NOP			;       WHATSOEVER
	NOP			;      OTHER
	NOP			;     THAN
	NOP			;    WASTE
	NOP			;   SPACE
	NOP			;  AND
	NOP			; SOME
	NOP			;TIME
	JP	COPYBY		;APPEND FIRST FILE TO SECOND
;
;
; STORE 'COPY' COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	CPYCMJ+1
;
	Dw	CPYCMD		;'COPY' ROUTINE ADDRESS
;
;
; 'COPY' COMMAND PROCESSING
; FORMAT:  COPY <FILESPEC> TO <FILESPEC>
;
	Org	0574FH
;
CPYCMD:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF FILE SPEC MISSING
	LD	DE,DCBTWO	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF FILE SPEC MISSING
	LD	B,0		;LOAD LOGICAL RECORD LENGTH
	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	LD	HL,SECBUF	;POINT AT SECTOR BUFFER
	CALL	OPNFIL		;OPEN THE SOURCE FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	B,0		;LOAD LOGICAL RECORD LENGTH
	LD	DE,DCBTWO	;POINT AT DEVICE CONTROL BLOCK
	LD	HL,SECBUF	;POINT AT SECTOR BUFFER
	CALL	CREFIL		;CREATE DESTINATION FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
CPYCMN:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	REDREC		;READ NEXT RECORD TO BUFFER
	JR	Z,CPYCMW	;WRITE RECORD IF ALL OK
	CP	1CH		;TEST IF END-OF-FILE
	JR	Z,CLOSEF	;THEN WE ARE DONE
	CP	1DH		;TEST IF NO-RECORD-FOUND
	JR	Z,CPYCMX	;THEN WE ARE DONE
	JP	SYSABO		;ABORT TO SYSTEM IF ANY ERRORS
CPYCMW:	LD	DE,DCBTWO	;POINT AT DEVICE CONTROL BLOCK
	CALL	WRTREC		;WRITE OUT THE RECORD
	JR	Z,CPYCMN	;LOOP FOR NEXT RECORD IF OK
	JP	SYSABO		;ABORT TO SYSTEM IF ANY ERRORS
CPYCMX:	LD	HL,(DCBONE+8)	;GET EOF OFFSET AND LRL
	LD	(DCBTWO+8),HL	;COPY INTO DESTINATION DCB
;
;
; CLOSE INPUT AND OUTPUT FILES
; ENTRY:  DCBONE  - POINTER TO INPUT FILE DEVICE CONTROL BLOCK
;         DCBTWO  - POINTER TO OUTPUT FILE DEVICE CONTROL BLOCK
;57A1
CLOSEF:	LD	DE,DCBTWO	;POINT AT DEVICE CONTROL BLOCK
	CALL	CLSFIL		;CLOSE OUTPUT FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	CLSFIL		;CLOSE INPUT FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	JP	DOSENT		;ELSE EXIT TO DOS PROMPT
;
;
; COPY BYTES FROM ONE FILE TO ANOTHER
; ENTRY:  DCBONE  - POINTER TO INPUT FILE DEVICE CONTROL BLOCK
;         DCBTWO  - POINTER TO OUTPUT FILE DEVICE CONTROL BLOCK
;57B6
COPYBY:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	BYTINP		;READ INPUT BYTE TO A
	JR	Z,COPYBO	;CONTINUE IF NO ERRORS
	CP	1CH		;TEST IF END-OF-FILE
	JR	Z,CLOSEF	;THEN CLOSE OUTPUT FILE
	JP	SYSABO		;ABORT TO SYSTEM IF ANY ERRORS
COPYBO:	LD	B,A		;SAVE INPUT BYTE IN B
	CALL	BRKHLT		;TEST IF PAUSE KEY PRESSED
	JR	NZ,CLOSEF	;ABORT IF <BREAK> KEY PRESSED
	LD	A,B		;COPY INPUT BYTE TO A
	LD	DE,DCBTWO	;POINT AT DEVICE CONTROL BLOCK
	CALL	BYTOUT		;OUTPUT THE DATA BYTE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	JR	COPYBY		;THEN LOOP FOR NEXT BYTE
;
;
; STORE 'DUMP' COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	DMPCMJ+1
;
	Dw	DMPCMD		;'DUMP' COMMAND ADDRESS
;
;
; 'DUMP' COMMAND PROCESSING - SELF MODIFYING CODE PRESENT   (*)
; FORMAT:  DUMP <FILESPEC> (START=X'SSSS',END=X'EEEE'[,TRA=X'TTTT'])
;
	Org	057D7H
;
DMPCMD:	LD	BC,LOWMEM	;LOAD START OF WORKSPACE
	LD	(DMPBEG),BC	;STORE ADDRESS IN OUR CODE  (*)
	LD	(DMPEND),BC	;STORE IN OUR CODE AGAIN    (*)
	LD	BC,DOSENT	;LOAD ENTRY TO TRSDOS
	LD	(DMPEXE),BC	;STORE ADDRESS IN OUR CODE  (*)
	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF INVALID FILENAME
	LD	A,(DE)		;GET DCB CHARACTER
	CP	'*'		;TEST IF DEVICE SPEC CHARACTER
	JP	Z,FSPREQ	;ABORT IF DEVICE INDICATOR
	LD	DE,DMPPAR	;POINT AT PARAMETER STRINGS
	CALL	PARSEC		;PARSE THE COMMAND LINE
	LD	DE,MODULN	;LOAD MODULE NAME BUFFER
	LD	HL,DCBONE	;DEVICE CONTROL BLOCK
	LD	B,6		;LOAD CHARACTER COUNT
DMPCNA:	LD	A,(HL)		;GET CHARACTER FROM FILENAME
	CP	'0'		;TEST IF NUMERIC ASCII
	JR	C,DMPCNS	;USE SPACE IF NOT NUMERIC
	CP	'9'+1		;TEST IF NUMERIC ASCII
	JR	C,DMPCST	;STORE IF NUMERIC
	CP	'A'		;TEST IF ALPHABETIC
	JR	C,DMPCNS	;USE SPACE IF NOT ALPHABETIC
	CP	'Z'+1		;TEST IF ALPHABETIC
	JR	NC,DMPCNS	;USE SPACE IF NOT
DMPCST:	LD	(DE),A		;STORE THE CHARACTER
	INC	HL		;BUMP DCB POINTER
	INC	DE		;BUMP NAME BUFFER POINTER
	DJNZ	DMPCNA		;LOOP UNTIL NAME DONE
	JR	DMPCSE		;ELSE SKIP SPACE FILL
DMPCNS:	LD	A,' '		;LOAD ASCII SPACE CHARACTER
	LD	(DE),A		;STORE IN NAME BUFFER
	INC	DE		;BUMP BUFFER POINTER
	DJNZ	DMPCNS		;LOOP UNTIL NAME DONE
DMPCSE:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	LD	HL,CIMEXT	;POINT AT 'CIM' EXTENSION
	CALL	ADDEXT		;ADD EXTENSION TO FILENAME
	LD	B,0		;LOAD LOGICAL RECORD LENGTH
	LD	HL,SECBUF	;POINT AT SECTOR BUFFER
	CALL	CREFIL		;CREATE A NEW FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	A,HDC		;LOAD MODULE NAME HEADER
	CALL	BYTOUT		;OUTPUT THE HEADER BYTE
	LD	A,6		;LOAD NAME HEADER SIZE
	CALL	BYTOUT		;OUTPUT THE SIZE BYTE
	LD	B,6		;LOAD BYTE COUNTER
	LD	HL,MODULN	;POINT AT NAME STRING
DMPCSN:	LD	A,(HL)		;GET CHARACTER FROM NAME
	INC	HL		;BUMP STRING POINTER
	CALL	BYTOUT		;WRITE CHARACTER TO FILE
	DJNZ	DMPCSN		;LOOP UNTIL NAME SAVED TO FILE
	LD	HL,(DMPEND)	;GET END ADDRESS TO HL
	LD	BC,(DMPBEG)	;GET START ADDRESS TO BC
	XOR	A		;CLEAR CARRY FLAG
	SBC	HL,BC		;COMPUTE CODE SIZE
	LD	HL,ENDLES	;POINT AT ERROR MESSAGE
	JR	C,DMPERR	;ABORT IF START MORE THAN END
	LD	HL,LOWMEM-1	;LOAD WORKSPACE MINUS ONE
	SBC	HL,BC		;COMPUTE CODE LIMITS
	LD	HL,STALES	;POINT AT ERROR MESSAGE
;
	If	PATCHG		;PATCHES ACTIVE
	 NOP			;PAD OUT BRANCH OP-CODE
	 NOP			;PAD OUT BRANCH DESTINATION
	Else			;ORIGINAL
	 JR	NC,DMPERR	;ABORT IF END LESS THAN ALLOWED
	EndIf			;ALL DONE
;
	LD	HL,0		;LOAD START ADDRESS TO HL
DMPBEG	Equ	$ - 2		;DEFINE THE ADDRESS
DMPNXR:	PUSH	HL		;SAVE THE START ADDRESS
	LD	B,H		;COPY START ADDRESS MSB TO B
	LD	C,L		;COPY START ADDRESS LSB TO C
	LD	HL,0		;LOAD END ADDRESS TO HL
DMPEND	Equ	$ - 2		;DEFINE THE ADDRESS
	INC	HL		;BUMP THE END ADDRESS
	XOR	A		;CLEAR CARRY FLAG
	SBC	HL,BC		;COMPUTE CODE SIZE
	JR	Z,DMPECO	;DONE IF END OF CODE
	LD	B,254		;LOAD RECORD TRANSFER SIZE TO B
	LD	A,H		;GET CURRENT ADDRESS MSB TO A
	OR	A		;TEST IF 'DUMP' IS DONE
	JR	NZ,DMPLAP	;CONTINUE IF IT IS NOT
	LD	A,L		;GET ADDRESS LSB TO A
	CP	255		;TEST IF LAST PAGE ADDRESS
	JR	NC,DMPLAP	;SKIP IF NOT LAST PAGE
	LD	B,L		;ELSE LOAD REMAINDER TO B
DMPLAP:	POP	HL		;RECOVER START ADDRESS
	LD	A,LOC		;GET LOAD ADDRESS CODE
	CALL	BYTOUT		;OUTPUT CODE TO FILE
	LD	A,B		;LOAD RECORD SIZE TO B
	ADD	A,2		;ADD ADDRESS SIZE
	CALL	BYTOUT		;OUTPUT RECORD SIZE
	LD	A,L		;GET LOAD ADDRESS LSB
	CALL	BYTOUT		;OUTPUT ADDRESS LSB TO FILE
	LD	A,H		;GET LOAD ADDRESS MSB
	CALL	BYTOUT		;OUTPUT ADDRESS MSB TO FILE
DMPREO:	LD	A,(HL)		;GET BYTE FROM MEMORY
	INC	HL		;BUMP MEMORY ADDRESS
	CALL	BYTOUT		;OUTPUT MEMORY DATA BYTE
	DJNZ	DMPREO		;LOOP UNTIL RECORD OUTPUTTED
	JR	DMPNXR		;THEN DO NEXT RECORD
DMPECO:	POP	HL		;RECOVER TRANSFER ADDRESS
	LD	A,TRC		;GET TRANSFER ADDRESS CODE
	CALL	BYTOUT		;OUTPUT CODE TO FILE
	LD	A,2		;GET ADDRESS SIZE TO A
	CALL	BYTOUT		;OUTPUT THE BYTE
	LD	HL,0		;GET TRANSFER ADDRESS TO HL
DMPEXE	Equ	$ - 2		;DEFINE THE ADDRESS
	LD	A,L		;GET TRANSFER ADDRESS LSB
	CALL	BYTOUT		;OUTPUT THE BYTE TO FILE
	LD	A,H		;GET TRANSFER ADDRESS MSB
	CALL	BYTOUT		;OUTPUT THE BYTE TO FILE
	CALL	CLSFIL		;CLOSE THE FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	JP	DOSENT		;ELSE NORMAL TRSDOS RE-ENTRY
;
;
; DISPLAY 'DUMP' ERROR MESSAGE AND ABORT TO TRSDOS
; ENTRY:  HL      - POINTER TO MESSAGE
;58BE
DMPERR:	CALL	DOPMSG		;DISPLAY ERROR MESSAGE
	JP	ERRENT		;THEN ERROR ENTRY TO TRSDOS
;
;
; 'DUMP' ERROR MESSAGES
;58C4
ENDLES	Db	LF,'END LESS THAN START',CR
STALES	Db	LF,"START LESS THAN X'7000'",CR
;
;
; DEFAULT EXTENSION FOR 'DUMP' FILE NAME
;58F2
CIMEXT	Db	'CIM'
;
;
; 'DUMP' PARAMETERS TEXT STRINGS
;58F5
DMPPAR	Db	'START '
	Dw	DMPBEG		;STORAGE FOR START ADDRESS
	Db	'END   '
	Dw	DMPEND		;STORAGE FOR END ADDRESS
	Db	'TRA   '
	Dw	DMPEXE		;STORAGE FOR TRANSFER ADDRESS
	Db	0
;
;
; TEMPORARY BUFFER AREA FOR LOAD MODULE TITLE STRING
;590E
MODULN	Ds	6		;RESERVE THE SPACE
;
;
; STORE 'KILL' COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	KILCMJ+1
;
	Dw	KILCMD		;'KILL' COMMAND ADDRESS
;
;
; 'KILL' COMMAND PROCESSING - DELETE A DISK FILE
; FORMAT:  KILL <FILESPEC>
;
	Org	05914H
;
KILCMD:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF INVALID FILESPEC
	CALL	OPNFIL		;ELSE OPEN THE FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	CALL	KILFIL		;ELSE KILL THE FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	JP	DOSENT		;THEN EXIT TO DOS
;
;
; STORE 'LIST COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	LISCMJ+1
;
	Dw	LSTCMD		;'LIST' COMMAND ADDRESS
;
;
; 'LIST' COMMAND PROCESSING - TYPE A TEXT FILE TO SCREEN
; FORMAT:  LIST <FILESPEC> [(LINE=L)]
;
	Org	0592CH
;
LSTCMD:	LD	BC,0		;LOAD STARTING LINE NUMBER
	LD	(BEGLIN),BC	;SAVE THE NUMBER FOR LATER
	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF NO OR INVALID NAME
	LD	A,(DE)		;GET FILENAME CHARACTER
	CP	'*'		;TEST IF DEVICE SPECIFICATION
	JP	Z,FSPREQ	;ABORT IF DEVICE, NOT FILENAME
;
	If	PATCHG		;PATCHES ACTIVE
	 LD	DE,LSTPAR	;POINT AT PARAMETER STRING
	Else			;ORIGINAL
	 LD	BC,LSTPAR	;POINT AT PARAMETER STRING
	EndIf			;ALL DONE
;
	CALL	PARSEC		;PARSE THE COMMAND LINE
	LD	B,0		;LOAD LOGICAL RECORD LENGTH
	LD	HL,SECBUF	;POINT AT SECTOR BUFFER
	CALL	OPNFIL		;OPEN THE INPUT FILE
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
	LD	BC,0		;GET STARTING LINE NUMBER
BEGLIN	Equ	$ - 2		;STARTING LINE NUMBER STORAGE
	LD	A,B		;GET LINE NUMBER MSB FOR TEST
	OR	C		;TEST IF FIRST LINE START
	JR	Z,LSTCNL	;BEGIN LISTING IF SO
LSTCSL:	CALL	BYTINP		;GET CHARACTER FROM OPEN FILE
	CP	CR		;TEST IF LINE END
	JR	NZ,LSTCSL	;LOOP UNTIL IT IS
	DEC	C		;DECREMENT LINE COUNT LSB
	JR	NZ,LSTCSL	;LOOP UNTIL COUNT TURNS ZERO
	DEC	B		;DECREMENT LINE COUNT MSB
	JR	NZ,LSTCSL	;LOOP UNTIL COUNT TURNS ZERO
LSTCNL:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	BYTINP		;GET CHARACTER FROM FILE
	JR	NZ,LSTCEX	;SKIP IF ANY ERRORS
	CALL	VDCHAR		;DISPLAY FILE CHARACTER
	CP	CR		;TEST IF END-OF-LINE
	JR	NZ,LSTCNL	;LOOP UNTIL IT IS
	CALL	BRKHLT		;TEST IF PAUSE KEY PRESSED
	JP	NZ,ERRENT	;ABORT IF <BREAK> KEY PRESSED
	JR	LSTCNL		;LOOP FOR NEXT CHARACTER
LSTCEX:	CP	1CH		;TEST IF END-OF-FILE
	JP	Z,DOSENT	;EXIT TO DOS IF SO
	CP	1DH		;TEST IF NO-RECORD-FOUND
	JP	Z,DOSENT	;THEN EXIT TO DOS
	JP	SYSABO		;ABORT TO SYSTEM IF ANY ERRORS
;
;
; 'LIST' PARAMETER TEXT LIST
;598B
LSTPAR	Db	'LINE  '
	Dw	BEGLIN		;STARTING LINE NUMBER
	Db	0
;
;
; STORE 'LOAD' COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	LODCMJ+1
;
	Dw	LODCMD		;'LOAD' COMMAND ADDRESS
;
;
; 'LOAD' COMMAND PROCESSING - LOAD MACHINE LANGUAGE FILE
; FORMAT:  LOAD <FILESPEC>
;
	Org	05994H
;
LODCMD:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF NO OR BAD FILENAME
	LD	A,(DE)		;GET CHARACTER FROM NAME
	CP	'*'		;TEST IF DEVICE SPEC HEADER
	JP	Z,FSPREQ	;ABORT IF DEVICE SPECIFIED
	CALL	LODFIL		;LOAD 'CMD' FILE TO MEMORY
	JP	Z,DOSENT	;DONE IF SUCCESSFUL
	JP	SYSABO		;ABORT TO SYSTEM IF ANY ERRORS
;
;
; STORE 'PRINT' COMMAND ADDRESS IN COMMAND TEST ROUTINE
;
	Org	PRTCMJ+1
;
	Dw	PRTCMD		;'PRINT' COMMAND ADDRESS
;
;
; 'PRINT' COMMAND PROCESSING - SEND A TEXT FILE TO PRINTER
; FORMAT:  PRINT <FILESPEC>
;
	Org	059ACH
;
PRTCMD:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	VALNAM		;VALIDATE NAME AND COPY TO DCB
	JP	NZ,FSPREQ	;ABORT IF INVALID FILENAME
	LD	A,(DE)		;GET CHARACTER FROM FILENAME
	CP	'*'		;TEST IF DEVICE SPEC CHARACTER
	JP	Z,FSPREQ	;ABORT IF DEVICE INDICATOR
	LD	B,0		;LOAD LOGICAL RECORD LENGTH
	LD	HL,SECBUF	;POINT AT SECTOR BUFFER
	CALL	OPNFIL		;OPEN THE FILE FOR INPUT
	JP	NZ,SYSABO	;ABORT TO SYSTEM IF ANY ERRORS
PRTCML:	LD	DE,DCBONE	;POINT AT DEVICE CONTROL BLOCK
	CALL	BYTINP		;GET CHARACTER FROM FILE
	JR	NZ,PRTCMX	;DONE IF END-OF-FILE
	CALL	PRCHAR		;SEND CHARACTER TO PRINTER
	CALL	BRKHLT		;TEST IF PAUSE KEY PRESSED
	JP	NZ,ERRENT	;ABORT IF <BREAK> KEY PRESSED
	JP	PRTCML		;THEN GO FOR NEXT CHARACTER
PRTCMX:	PUSH	AF		;SAVE RETURN CODE FOR LATER
	LD	A,CR		;LOAD A NEWLINE CHARACTER
	CALL	PRCHAR		;SEND CHARACTER TO PRINTER
	POP	AF		;RECOVER RETURN CODE
	CP	1CH		;TEST IF END-OF-FILE
	JP	Z,DOSENT	;THEN EXIT TO DOS
	CP	1DH		;TEST IF NO-RECORD-FOUND
	JP	Z,DOSENT	;THEN EXIT TO DOS
	JP	SYSABO		;ABORT TO SYSTEM IF ANY ERRORS
;
;
; STORE 'VERIFY' COMMAND PATCH ADDRESS IN 'VERIFY' ROUTINE
;
	Org	VFYCMD+3
;
	CALL	VERIFY		;EXECUTE THE PATCH
;
;
; 'VERIFY' COMMAND PATCH
; FORMAT:  VERIFY [(ON|OFF)]
;
	Org	060CDH
;
VERIFY:	LD	HL,RECWRT	;WRITE ROUTINE IN NUCLEUS
	JR	Z,VERIFS	;CLEAR VERIFY FLAG IF (OFF)
	XOR	A		;ZERO ACCUMULATOR, CLEAR CARRY
	INC	A		;LOAD VERIFY (ON) OPTION
	OR	A		;RESET ZERO FLAG
VERIFS:	LD	(VERIFL),A	;SAVE NUCLEUS VERIFY FLAG
	RET
;
;
; ALIGN BUFFERS ON A PAGE BOUNDARY
;60D9
	Ds	256 - $ And 255	;PAGE ALIGN BUFFERS
;
;
; DIRECTORY SECTORS BUFFER
;6100
RECBUF	Ds	8 * SECSIZ	;RESERVE THE SPACE
;
;
; DIRECTORY SECTOR BUFFER EXTENSION
;6900
RECBUE	Ds	6 * SECSIZ	;RESERVE THE SPACE
;
;
; SECTOR BUFFER
;6F00
SCTBUF	Ds	1 * SECSIZ	;RESERVE THE SPACE
;
	End	EXTE01
