	Title	'TRSDOS 2.3 Tape To Disk Utility'
;
;
; TRSDOS OPERATING SYSTEM, VERSION 2.3 - TAPE TO DISK UTILITY
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON, 06.01.2022
;
;
; ASCII EQUATES
;
CR	Equ	 13		;CARRIAGE RETURN
;
;
; HARDWARE PORT ADDRESSES
;
CASLTC	EQU	0FFH		;CASSETTE PORT
;
;
; TERMINAL SCREEN ADDRESSES
;
LFSTAR	Equ	03C3EH		;LEFT BLINKING STAR
RGSTAR	Equ	LFSTAR+1	;RIGHT BLINKING STAR
;
;
; LEVEL II BASIC ROM ROUTINE ADDRESSES
;
VDCHAR	Equ	00033H		;VIDEO DRIVER ENTRY
FILLKB	Equ	005D9H		;INPUT AND FILL BUFFER
;
;
; DISK AND CASSETTE BASIC ADDRESS DEFINITIONS
;
VCCTRL	Equ	0403DH		;DISPLAY/CASSETTE CONTROL BYTE
;
;
; STORAGE LOCATIONS IN TRSDOS NUCLEUS (SYS0/SYS)
;
STACKT	EQU	041FCH		;TOP OF SYSTEM STACK
CMLBUF	Equ	04318H		;DOS COMMAND LINE BUFFER
;
;
; FUNCTIONS ADDRESSES IN TRSDOS NUCLEUS (SYS0/SYS)
;
DOSENT	Equ	0402DH		;RE-ENTRY TO TRSDOS
DERROR	Equ	04409H		;OVERLAY CALL TO ERROR HANDLER
CREFIL	Equ	04420H		;CREATE A NEW FILE
CLSFIL	Equ	04428H		;CLOSE A FILE
WRTREC	Equ	04439H		;WRITE RECORD TO FILE
;
;
; PROGRAM MODULE NAME STRING
;
;	NAM	'TAPEDI'
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING
;
;	REM	CR
;	REM	'* * * N O T I C E * * *',CR
;	REM	'* PROPRIETARY PROGRAM *',CR
;	REM	'* COPYRIGHT (c) 1979  *',CR
;	REM	'* BY TANDY CORPORATION*',CR
;	REM	'*  FORT WORTH, TEXAS  *',CR
;	REM	'* ALL RIGHTS RESERVED *',CR
;	REM	'* * * N O T I C E * * *',CR
;
;
	Org	5200H
;
TAPDSK:	LD	SP,STACKT	;LOAD TOP OF STACK
	LD	A,CR		;LOAD A NEWLINE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
CMDLUP:	LD	A,'?'		;LOAD PROMPT CHARACTER
	CALL	VDCHAR		;DISPLAY PROMPT CHARACTER
	LD	B,63		;LOAD MAXIMUM LINE LENGTH
	LD	HL,CMLBUF	;POINT AT INPUT BUFFER
	CALL	FILLKB		;GET COMMAND LINE STRING
	JR	C,CMDLUP	;LOOP BACK IF <BREAK>
	LD	A,(HL)		;GET COMMAND CHARACTER
	CP	'C'		;TEST IF LOAD CASSETTE TAPE
	JP	Z,CASSIN	;THEN WE GO READ IT
	NOP			;DO
	NOP			; ABSOLUTELY
	NOP			;  AND
	NOP			;   TRULY
	NOP			;    NOTHING
	CP	'E'		;TEST IF EXIT TO DOS
	JP	Z,DOSENT	;THEN WE ARE ALL DONE
	CP	'F'		;TEST IF SAVE FILE TO DISK
	JP	NZ,SYNTAX	;WE HAVE AN ERROR IF NOT
;
;
; 'F' COMMAND _ SAVE LOADED FILE TO A DISK FILE
; FORMAT:  F filename[/ext][.password]:d start end exec
;
	CALL	SKIPBL		;SKIP LEADING ASCII SPACES
	LD	(LINDCB),HL	;DEVICE CONTROL BLOCK ADDRESS
WDELIM:	LD	A,(HL)		;GET COMMAND LINE CHARACTER
	INC	HL		;BUMP LINE POINTER
	CP	':'		;TEST IF DRIVE DELIMITER
	JR	NZ,WDELIM	;LOOP UNTIL DELIMITER FOUND
	CALL	SKIPBL		;SKIP LEADING ASCII SPACES
	CALL	HEXBYT		;GET START ADDRESS MSB
	LD	(BEGADM),A	;STORE THE ADDRESS BYTE
	INC	HL		;BUMP COMMAND LINE POINTER
	CALL	HEXBYT		;GET START ADDRESS LSB
	LD	(BEGADL),A	;STORE THE ADDRESS BYTE
	CALL	SKIPBL		;SKIP LEADING ASCII SPACES
	CALL	HEXBYT		;GET END ADDRESS MSB
	LD	(ENDADM),A	;STORE THE ADDRESS BYTE
	INC	HL		;BUMP COMMAND LINE POINTER
	CALL	HEXBYT		;GET END ADDRESS LSB
	LD	(ENDADL),A	;STORE THE ADDRESS BYTE
	CALL	SKIPBL		;SKIP LEADING ASCII SPACES
	CALL	HEXBYT		;GET EXECUTION ADDRESS MSB
	LD	(RUNADM),A	;STORE THE ADDRESS BYTE
	INC	HL		;BUMP COMMAND LINE POINTER
	CALL	HEXBYT		;GET EXECUTION ADDRESS LSB
	LD	(RUNADL),A	;STORE THE ADDRESS BYTE
	LD	DE,CMLBUF+2	;POINT AT DEVICE CONTROL BLOCK
;
;
; COMMAND LINE BUFFER POINTER
;5269
LINDCB	Equ	$-2		;COMMAND LINE BUFFER ADDRESS
;
;
; CONTINUATION OF SAVE TO DISK FILE ROUTINE
;
	LD	B,0		;LOAD RECORD LENGTH (256 BYTES)
	LD	HL,SECTBF	;POINT AT SECTOR BUFFER
	CALL	CREFIL		;CREATE THE DISK FILE
	JP	NZ,DISKER	;ABORT IF ANY ERROR
	LD	DE,TAPDSK	;GET START ADDRESS TO DE
;
;
; STORAGE FOR START ADDRESS MSB
;5277
BEGADL	Equ	$-2		;START ADDRESS MSB
;
;
; STORAGE FOR START ADDRESS LSB
;5278
BEGADM	Equ	$-1		;START ADDRESS LSB
;
;
; CONTINUATION OF SAVE TO DISK FILE ROUTINE
;
	LD	HL,RUNADL-1	;GET END ADDRESS TO HL
;
;
; STORAGE FOR END ADDRES MSB
;527A
ENDADL	Equ	$-2		;END ADDRESS MSB
;
;
; STORAGE FOR END ADDRESS LSB
;527B
ENDADM	Equ	$-1		;END ADDRESS LSB
;
;
; CONTINUATION OF SAVE TO DISK FILE ROUTINE
;
	XOR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;COMPUTE LENGTH OF CODE
	INC	HL		;INCREMENT LENGTH BY ONE
	LD	C,0		;ZERO BYTES WRITTEN COUNT
WRITEL:	DEC	H		;DECREMENT MSB OF DATA LENGTH
	JP	M,WRITER	;DONE IF UNDERFLOW
	LD	B,0		;LOAD RECORD SIZE (256 BYTES)
	CALL	DATAOT		;OUTPUT ONE DATA RECORD
	JR	WRITEL		;LOOP FOR NEXT RECORD
WRITER:	XOR	A		;ZERO ACCUMULATOR
	CP	L		;TEST IF NO BYTES REMAINING
	JR	Z,WRITEX	;THEN OUTPUT EXECUTION ADDRESS
	LD	B,L		;GET REMAINING COUNT TO B
	CALL	DATAOT		;OUTPUT THE REMAINING BYTES
WRITEX:	LD	A,2		;LOAD RUN RECORD TYPE
	CALL	FILBYT		;OUTPUT THE RECORD TYPE
	CALL	FILBYT		;OUTBUT BYTE COUNT
	LD	A,(RUNADL)	;GET EXECUTION ADDRESS LSB
	CALL	FILBYT		;OUTPUT THE ADDRESS BYTE
	LD	A,(RUNADM)	;GET EXECUTION ADDRESS MSB
	CALL	FILBYT		;OUTPUT THE ADDRESS BYTE
	XOR	A		;ZERO ACCUMULATOR
	CP	C		;TEST IF ANY BYTES REMAINING
	LD	DE,(LINDCB)	;GET DCB ADDRESS TO DE
	JR	Z,WRITEC	;SKIP IF ALL WRITTEN OUT
	CALL	WRTREC		;WRITE OUT LAST RECORD
	JR	NZ,DISKER	;ABORT IF ANY ERROR
WRITEC:	CALL	CLSFIL		;CLOSE THE DISK FILE
	JP	Z,TAPDSK	;TO COMMAND LOOP IF NO ERROR
;
;
; DISK ERROR PROCESSING ROUTINE
;52BC
DISKER:	OR	10000000B	;FLAG WE WANT TO RETURN HERE
	CALL	DERROR		;REPORT THE ERROR
	JP	TAPDSK		;THEN RE-ENTER MAIN LOOP
;
;
; COMMAND ERROR ENCOUNTERED - DISPLAY MESSAGE AND LOOP
;52C4
SYNTAX:	LD	HL,ERRORM	;POINT AT ERROR MESSAGE
	LD	B,8		;LOAD MESSAGE LENGTH
	CALL	MSGDIS		;DISPLAY THE MESSAGE
	JP	TAPDSK		;THEN RE-ENTER MAIN LOOP
;
;
; READ CASSETTE TAPE FILE INTO MEMORY
;52CF
CASSIN:	DI			;DISABLE INTERRUPTS
	CALL	CASMON		;TURN CASSETTE MOTOR ON
WASYNC:	CALL	CBITIN		;READ DATA BIT FROM CASSETTE
	CP	0A5H		;TEST IF SYNC BYTE
	JR	NZ,WASYNC	;LOOP UNTIL WE HAVE ONE
WAIHDR:	CALL	CBYTIN		;READ A BYTE FROM CASSETTE
	CP	55H		;TEST IF 'SYSTEM' FILE HEADER
	JR	NZ,WAIHDR	;WAIT FOR FOR THE HEADER
	LD	B,6		;NUMBER OF CHARACTERS TO MATCH
GETNAM:	CALL	CBYTIN		;READ NAME CHARACTER FROM TAPE
	DJNZ	GETNAM		;LOOP UNTIL ALL READ IN
RDLOOP:	LD	A,(RGSTAR)	;GET VIDEO MEMORY BYTE
	XOR	00001010B	;TOGGLE BETWEEN SPACE AND STAR
	LD	(RGSTAR),A	;PUT BACK INTO VIDEO MEMORY
WAITYP:	CALL	CBYTIN		;READ A BYTE FROM CASSETTE
	CP	78H		;TEST IF TRANSFER ADDRESS
	JR	Z,GETADR	;THEN GET THE ADDRESS
	CP	3CH		;TEST IF START OF THE FILE
	JR	NZ,WAITYP	;LOOP IN NEITHER OF THE ABOVE
	CALL	CBYTIN		;GET NUMBER OF BYTES TO READ
	LD	B,A		;TRANSFER COUNT TO B
	CALL	CBTWIN		;GET TRANSFER ADDRESS
	ADD	A,L		;CHECKSUM STARTS WITH ADDRESS
	LD	C,A		;SAVE CHECKSUM IN C
BYTLUP:	CALL	CBYTIN		;READ A BYTE FROM CASSETTE
	LD	(HL),A		;STORE BYTE IN MEMORY
	INC	HL		;BUMP TRANSFER ADDRESS
	ADD	A,C		;ADD CHECKSUM TO BYTE
	LD	C,A		;UPDATE CHECKSUM
	DJNZ	BYTLUP		;READ ALL THE BYTES
	CALL	CBYTIN		;READ CHECKSUM BYTE
	CP	C		;TEST IF A MATCH
	JR	Z,RDLOOP	;LOOP IF ALL IS OK
	LD	A,'C'		;LOAD 'C' FOR CHECKSUM ERROR
	LD	(LFSTAR),A	;STORE CHARACTER ON SCREEN
	JR	WAITYP		;THEN TRY FOR NEXT
GETADR:	CALL	CBTWIN		;READ THE TRANSFER ADDRESS
	CALL	CASMOF		;TURN CASSETTE MOTOR OFF
	EI			;ENABLE INTERRUPTS
	JP	TAPDSK		;THEN LOOP FOR NEXT TAPE FILE
;
;
; UNUSED JUMP TO LOOP FOR NEXT TAPE FILE
;
	JP	TAPDSK		;JUMP INTO COMMAND LOOP
;
;
; OUTPUT DATA FILE HEADER AND DATA BLOCK TO DISK
; ENTRY:  DE      - ADDRESS OF DATA
;         LINDCB  - DCB ADDRESS
;5327
DATAOT:	LD	A,1		;LOAD DATA RECORD TYPE
	CALL	FILBYT		;WRITE THE HEADER BYTE
	LD	A,2		;LOAD SIZE OF ADDRESS
	ADD	A,B		;ADD SIZE TO THE COUNT
	CALL	FILBYT		;WRITE THE RECORD SIZE
	LD	A,E		;GET LOAD ADDRESS LSB
	CALL	FILBYT		;WRITE THE ADDRESS BYTE
	LD	A,D		;GET LOAD ADDRESS MSB
	CALL	FILBYT		;WRITE THE ADDRESS BYTE
DATAOL:	LD	A,(DE)		;GET BYTE FROM LOADED FILE
	CALL	FILBYT		;WRITE THE DATA BYTE
	INC	DE		;BUMP MEMORY POINTER
	DJNZ	DATAOL		;LOOP UNTIL ALL WRITTEN
	RET
;
;
; STORE BYTE IN SECTOR BUFFER - WRITE RECORD IF BUFFER FULL
; ENTRY:  A       - BYTE TO STORE
;         C       - BUFFER INDEX
;         LINDCB  - DCB ADDRESS
; EXIT:   C       - UPDATED BUFFER INDEX
;5342
FILBYT:	LD	IX,SECTBF	;POINT AT SECTOR BUFFER
	PUSH	BC		;SAVE BUFFER INDEX
	LD	B,0		;ZERO BUFFER INDEX MSB
	ADD	IX,BC		;UPDATE SECTOR BUFFER INDEX
	POP	BC		;RECOVER BUFFER INDEX
	LD	(IX+00),A	;STORE THE BYTE IN BUFFER
	INC	C		;BUMP BUFFER INDEX
	RET	NZ		;DONE IF BUFFER NOT FULL
	PUSH	DE		;ELSE SAVE DE REGISTER
	LD	DE,(LINDCB)	;GET DCB ADDRESS TO DE
	CALL	WRTREC		;WRITE OUT THE RECORD
	JP	NZ,DISKER	;ABORT IF WRITE ERROR
	POP	DE		;RECOVER DE REGISTER
	RET
;
;
; SKIP LEADING ASCII BLANKS IN A STRING
; ENTRY:  HL      - STRING POINTER
; EXIT:   HL      _ POINTER TO FIRST NON-BLANK
;535E
SKIPBL:	INC	HL		;BUMP STRING POINTER
	LD	A,(HL)		;GET CHARACTER FROM STRING
	CP	' '		;TEST IF SPACE CHARACTER
	JR	Z,SKIPBL	;THEN WE SKIP THE SPACE
	RET
;
;
; READ TWO BYTES FROM CASSETTE AND ASSEMBLE AS 16-BIT VALUE
; EXIT:   HL      - THE SIXTEEN BIT VALUE
;5365
CBTWIN:	CALL	CBYTIN		;READ BYTE FROM CASSETTE
	LD	L,A		;SAVE AS LSB OF VALUE
	CALL	CBYTIN		;READ BYTE FROM CASSETTE
	LD	H,A		;SAVE AS MSB OF VALUE
	RET
;
;
; DISPLAY A MESSAGE STRING
; ENTRY:  B       - LENGTH OF THE STRING
;         HL      - POINTER TO THE STRING
;536E
MSGDIS:	LD	A,(HL)		;GET MESSAGE CHARACTER
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	INC	HL		;BUMP STRING POINTER
	DJNZ	MSGDIS		;LOOP UNTIL ALL DISPLAYED
	RET
;
;
; CONVERT TWO HEXADECIMAL ASCII CHARACTERS TO A BINARY BYTE
; ENTRY:  HL      - POINTER TO THE CHARACTER STRING
; EXIT:   A       - BINARY BYTE
;         B       - UPPER NYBBLE IN FOUR MS BITS
;         HL      - POINTER TO SECOND CHARACTER
;5376
HEXBYT:	LD	A,(HL)		;GET CHARACTER FROM STRING
	CALL	HEXBIN		;CONVERT TO BINARY NYBBLE
	LD	B,A		;SAVE UPPER NYBBLE IN B
	INC	HL		;BUMP STRING POINTER
	LD	A,(HL)		;GET CHARACTER FROM STRING
	CALL	HEXBIN		;CONVERT TO BINARY NYBBLE
	SLA	B		;SHIFT
	SLA	B		; LOWER NYBBLE
	SLA	B		;  TO
	SLA	B		;   UPPER NYBBLE
	OR	B		;MERGE NYBBLE TO BYTE
	RET
;
;
; CONVERT HEXADECIMAL ASCII CHARACTER TO A BINARY NYBBLE
; ENTRY:  A       - HEXADECIMAL ASCII CHARACTER
; EXIT:   A       - BINARY NYBBLE
;538A
HEXBIN:	CP	'A'		;TEST IF ALPHABETIC CHARACTER
	JR	C,DECBIN	;SKIP IF POSSIBLY NUMERIC
	CP	'F'+1		;TEST IF ALPHABETIC CHARACTER
	JR	NC,INVHEX	;ABORT IF NOT ALPHABETIC
	SUB	'0'+'A'-'9'-1	;ELSE REMOVE ASCII BIAS
	RET
;
;
; CONVERT DECIMAL ASCII CHARACTER TO A BINARY NYBBLE
; ENTRY:  A       - DECIMAL ASCII CHARACTER
; EXIT:   A       - BINARY NYBBLE
;5395
DECBIN:	CP	'0'		;TEST IF NUMERIC CHARACTER
	JR	C,INVHEX	;ABORT IF NOT NUMERIC
	CP	'9'+1		;TEST IF NUMERIC CHARACTER
	JR	NC,INVHEX	;ABORT IF NOT NUMERIC
	SUB	'0'		;ELSE REMOVE ASCII BIAS
	RET
;
;
; INVALID ASCII HEXADECIMAL CHARACTER - ABORT TO ERROR ROUTINE
;53A0
INVHEX:	POP	BC		;REMOVE RETURN ADDRESS
	LD	HL,SYNTAX	;POINT AT ERROR HANDLER
	EX	(SP),HL		;SWAP HANDLER ADDRESS AS RETURN
	RET
;
;
; READ ONE DATA BYTE FROM CASSETTE
; EXIT:   A       - VALUE JUST READ
;53A6
CBYTIN:	PUSH	BC		;SAVE CALLER'S BC
	LD	B,8		;NUMBER OF BITS TO READ
CBYTIL:	CALL	CBITIN		;READ ONE BIT INTO A
	DJNZ	CBYTIL		;LOOP UNTIL ONE BYTE READ
	POP	BC		;RECOVER CALLERS BC
	RET
;
;
; READ ONE DATA BIT FROM CASSETTE
; ENTRY:  A       - UNCOMPLETE DATA BYTE
; EXIT:   A       - DATA BYTE WITH NEW BIT IN POSITION ZERO
;53B0
CBITIN:	EXX			;SWAP TO ALTRNATE REGISTERS
	EX	AF,AF'		;SWAP TO ALTERNATE AF REGISTER
CBITWC:	IN	A,(CASLTC)	;READ THE CASSETTE LATCH
	RLA			;ROTATE BIT INTO CARRY
	JR	NC,CBITWC	;WAIT FOR CLOCK PULSE
	LD	B,65		;VALUE FOR 953 US DELAY
CBIDLO:	DJNZ	CBIDLO		;DELAY FOR THE PERIOD
	CALL	RESOSG		;RESET 'OUTSIG' FLIP/FLOP
	LD	B,118		;VALUE FOR 1.73 MS DELAY
CBIDLT:	DJNZ	CBIDLT		;DELAY FOR THE PERIOD
	IN	A,(CASLTC)	;READ THE CASSETTE LATCH
	LD	B,A		;SAVE VALUE IN B REGISTER
	EX	AF,AF'		;SWAP TO MAIN AF REGISTER
	RL	B		;ROTATE DATA BIT TO CARRY
	RLA			;ROTATE BIT TO LS BIT OF A
	PUSH	AF		;SAVE THE DATA BYTE
	CALL	RESOSG		;RESET 'OUTSIG' FLIP/FLOP
	POP	AF		;RECOVER THE DATA BYTE
	EXX			;SWAP TO MAIN REGISTERS
	RET
;
;
; TURN ON CASSETTE DRIVE MOTOR
;53D0
CASMOF:	LD	HL,0FB00H	;CODE TO TURN OFF CASSETTE
	JR	OSGOUT		;RURN OFF THE CASSETTE
;
;
; TURN ON CASSETTE DRIVE MOTOR
;53D5
CASMON:	LD	HL,0FF04H	;CODE TO TURN ON CASSETTE
	JR	OSGOUT		;GO TURN ON THE CASSETTE
;
;
; RESET 'OUTSIG' FLIP/FLOP
;53DA
RESOSG:	LD	HL,0FF00H	;MASK TO PRESERVE VIDEO BITS
;
;
; OUTPUT A BYTE TO THE 'OUTSIG' FLIP/FLOP
; OUTPUT A BYTE TO THE OUTSIG FLIP/FLOP
; ENTRY:  H       - MASK TO 'AND' CURRENT VALUE WITH
;         L       - MASK TO 'OR' CURRENT VALUE WITH
; EXIT:   ZF      - RESET IF CASSETTE MOTOR IS RUNNING
;53DD
OSGOUT:	LD	A,(VCCTRL)	;GET VIDEO CONTROL BITS
	AND	H		;COMBINE WITH
	OR	L		; CASSETTE CONTROL BITS
	OUT	(CASLTC),A	;WRITE TO CASSETTE/VIDEO PORT
	LD	(VCCTRL),A	;SAVE AS CURRENT CONTROL BITS
	BIT	2,A		;TEST IF CASSETTE MOTOR IS ON
	RET
;
;
; ERROR MESSAGE
;53EA
ERRORM	Db	'SN ERROR'
;
;
; STORAGE
;53F2
RUNADL	Ds	1		;EXECUTION ADDRESS LSB
RUNADM	DS	1		;EXECUTION ADDRESS MSB
SECTBF	Ds	256		;SECTOR BUFFER
;
	End	TAPDSK
