	Title	'TRSDOS 2.3 ROM BASIC Test Utility'
;
;
; TRSDOS OPERATING SYSTEM, VERSION 2.3 - ROM BASIC TEST UTILITY
;
; COPYRIGHT BY TANDY CORPORATION
;
; DISASSEMBLY AND COMMENTS BY GUDMUNDUR EINARSSON, 07.01.2022
;
;
; CONDITIONAL PATCHES ENABLED
;
PATCHG	Equ	0		;MY OWN PATCHES ENABLED
;
;
; ASCII EQUATES
;
CC	Equ	  3		;CONTROL-C (END-OF-MESSAGE)
BS	Equ	  8		;BACKSPACE AND ERASE CHARACTER
LF	Equ	 10		;LINE FEED
CR	Equ	 13		;CARRIAGE RETURN (NEWLINE)
ON	Equ	 14		;TURN CURSOR ON
OF	Equ	 15		;TURN CURSOR OFF
NA	Equ	 23		;SWITCH TO NARROW SCREEN
LC	Equ	 24		;CURSOR LEFT
RC	Equ	 25		;CURSOR RIGHT
DC	Equ	 26		;CURSOR DOWN
UC	Equ	 27		;CURSOR UP
HO	Equ	 28		;HOME DISPLAY CURSOR
BL	Equ	 29		;TO LINE START
EE	Equ	 30		;ERASE TO LINE END
CE	Equ	 31		;CLEAR TO SCREEN END
CO	Equ	192		;SPACE COMPRESSION (0 TO 63)
;
;
; LEVEL II BASIC ROM CHECKSUM WORDS
;
CKAE5D	Equ	0AE5DH		;ROM A V1.0
CKAE60	Equ	0AE60H		;ROM A V1.1 AND 1.2
CKB078	Equ	0B078H		;ROM A V1.3
;
	If	PATCHG		;MY OWN PATCH
CKAB96	 Equ	0AB96H		;ROM A V1.4 GE
	EndIf			;END OF PATCH
;
CKDA45	Equ	0DA45H		;ROM B V1.1, V1.2 AND 1.3
CKDA84	Equ	0DA84H		;ROM B V1.0
CK3E3E	Equ	03E3EH		;ROM C V1.1
CK4002	Equ	04002H		;ROM C V1.0
CK4006	Equ	04006H		;ROM C V1.3
CK40BA	Equ	040BAH		;ROM C V1.2
CK40E0	Equ	040E0H		;ROM C V1.1

;
;
; DEFINE LOWEST ADDRESS TO BE TESTED
;
ADRLOW	Equ	04C20H		;DEFINE LOWEST ADDRESS
;
; STACK POINTER DEFINITIONS
;
STKTWO	Equ	043B0H		;STACK POINTER TWO
STKONE	Equ	043C0H		;STACK POINTER ONE
;
;
; MAIN CODE RELOCATION ADDRESS
;
RELOCA	Equ	04400H		;DEFINE THE ADDRESS
;
;
; HARDWARE PORT ADDRESSES
;
KROSEV	EQU	03840H		;KEYBOARD <BREAK> KEY ROW
;
;
; LEVEL II BASIC ROM ROUTINE ADDRESSES
;
RBASIC	Equ	00000H		;COLD START ENTRY
KBCHAR	Equ	0002BH		;SCAN KEYBOARD
VDCHAR	Equ	00033H		;VIDEO DRIVER ENTRY
;
;
; PROGRAM MODULE NAME STRING
;
;	NAM	'TEST1A'
;
;
; PROGRAM MODULE COPYRIGHT REMARK STRING
;
;	REM	CR
;	REM	'* * * N O T I C E * * *',CR
;	REM	'* PROPRIETARY PROGRAM *',CR
;	REM	'* COPYRIGHT (c) 1979  *',CR
;	REM	'* BY TANDY CORPORATION*',CR
;	REM	'*  FORT WORTH, TEXAS  *',CR
;	REM	'* ALL RIGHTS RESERVED *',CR
;	REM	'* * * N O T I C E * * *',CR
;
;
	Org	063F0H
;
TEST1A:	DI			;DISABLE INTERRUPTS
	LD	HL,MAINEN	;POINT AT MAIN CODE BLOCK
	LD	DE,RELOCA	;POINT AT RELOCATION ADDRESS
	LD	BC,CODLEN	;LOAD LENGTH OF CODE BLOCK
	LDIR			;MOVE THE CODE TO RUN ADDRESS
	JP	RELOCA		;EXECUTE RELOCATED CODE
;
;
; DO ABSOLUTELY NOTHING AT ALL BUT PAD TO PARAGRAPH
;
	Db	0		;PAD TO PARAGRAPH ADDRESS
;
;
; DEFINE OFFSET TO RELOCATED CODE
;
O	Equ	$-RELOCA	;DEFINE THE OFFSET
;
;
; ENTRY POINT TO RELOCATED HARDWARE TEST CODE
;6400 (4400)
MAINEN:	LD	SP,STKONE	;SET UP TOP OF STACK
	CALL	CLRSCR-O	;CLEAR DISPLAY SCREEN
;
;
; COMPUTE CHECKSUM FOR ROM A AND TEST FOR A VALID MATCH
;
	LD	DE,0		;INIT OFFSET TO ROM A
	CALL	SUMCHK-O	;CALCULATE ROM A CHECKSUM
;
	If	PATCHG		;MY OWN PATCH
	 LD	HL,CKAB96	;ROM A V1.4 CHECKSUM
	 SBC	HL,DE		;TEST IF CHECKSUM MATCH
	 JP	Z,CKROMB-O	;CONTINUE IF A MATCH
	 OR	A		;CLEAR CARRY FLAG
	EndIf			;END OF PATCH
;
	LD	HL,CKAE5D	;ROM A V1.0 CHECKSUM
	SBC	HL,DE		;TEST IF CHECKSUM MATCH
	JP	Z,CKROMB-O	;CONTINUE IF A MATCH
	LD	HL,CKAE60	;ROM A V1.1 AND V1.2 CHECKSUM
	OR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;TEST IF CHECKSUM MATCH
	JP	Z,CKROMB-O	;CONTINUE IF A MATCH
	LD	HL,CKB078	;ROM A V1.3 CHECKSUM
	OR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;TEST IF CHECKSUM MATCH
	JP	NZ,CKERRA-O	;ABORT IF A MISMATCH
;
;
; COMPUTE CHECKSUM FOR ROM B AND TEST FOR A VALID MATCH
;6426
CKROMB:	LD	DE,4096		;INIT OFFSET TO ROM B
	CALL	SUMCHK-O	;CALCULATE ROM B CHECKSUM
	LD	HL,CKDA84	;ROM B V1.0 CHECKSUM
	SBC	HL,DE		;TEST IF CHECKSUM MATCH
	JP	Z,CKROMC-O	;CONTINUE IF A MATCH
	LD	HL,CKDA45	;ROM B V1.1, V1.2 AND V1.3 SUM
	OR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;TEST IF CHECKSUM MATCH
	JP	NZ,CKERRB-O	;ABORT IF A MISMATCH
;
;
; COMPUTE CHECKSUM FOR ROM C AND TEST FOR A VALID MATCH
;643D
CKROMC:	LD	DE,8192		;INIT OFFSET TO ROM C
	CALL	SUMCHK-O	;CALCULATE ROM C CHECKSUM
	LD	HL,CK4002	;ROM C V1.0 CHECKSUM
	SBC	HL,DE		;TEST IF CHECKSUM MATCH
	JP	Z,CKROMO-O	;CONTINUE IF A MATCH
	LD	HL,CK40BA	;ROM C V1.2 CHECKSUM
	OR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;TEST IF CHECKSUM MATCH
	JP	Z,CKROMO-O	;CONTINUE IF A MATCH
	LD	HL,CK3E3E	;ROM C V1.1 CHECKSUM
	OR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;TEST IF CHECKSUM MATCH
	JP	Z,CKROMO-O	;CONTINUE IF A MATCH
	LD	HL,CK40E0	;ROM C V1.1 CHECKSUM
	OR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;TEST IF CHECKSUM MATCH
	JP	Z,CKROMO-O	;CONTINUE IF A MATCH
	LD	HL,CK4006	;ROM C V1.3 CHECKSUM
	OR	A		;CLEAR CARRY FLAG
	SBC	HL,DE		;TEST IF CHECKSUM MATCH
	JP	NZ,CKERRC-O	;ABORT IF A MISMATCH
CKROMO:	LD	HL,ROMPAS-O	;ROM PASSED MESSAGE STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	JP	RAMTST-O	;THEN GO TEST THE RAM
;
;
; DISPLAY A MESSAGE STRING TERMINATED BY A 'CR' OR 'CC'
; ENTRY:  HL      - MESSAGE STRING POINTER
;6478 (4478)
MSGOUT:	LD	A,(HL)		;GET CHARACTER FROM STRING
	CP	CC		;TEST IF TERMINATOR
	RET	Z		;THEN WE ARE DONE
	CALL	VDCHAR		;DISPLAY THE CHARACTER
	INC	HL		;BUMP STRING POINTER
	CP	CR		;TEST IF TERMINATOR
	JR	NZ,MSGOUT	;LOOP FOR NEXT IF NOT
	RET
;
;
; CONVERT A BINARY BYTE TO ASCII HEXADECIMAL AND DISPLAY
; ENTRY:  E       - BYTE TO CONVERT AND DISPLAY
;6485 (4485)
BINHEX:	PUSH	DE		;SAVE BINARY BYTE
	PUSH	AF		;SAVE AF REGISTER
	LD	A,E		;GET BINARY BYTE TO A
	LD	D,0		;ZERO CHARACTER COUNTER
	RRC	A		;ROTATE
	RRC	A		; UPPER NYBBLE
	RRC	A		;  INTO
	RRC	A		;   LOWER NYBBLE
BINHEL:	AND	00001111B	;MASK TO LOWER NYBBLE
	CP	10		;TEST IF NUMERIC HEX
	JP	P,BINHEA-O	;SKIP IF ALPHA HEX
	OR	'0'		;CONVERT TO ASCII
	JP	BINHED-O	;THEN GO DISPLAY CHARACTER
BINHEA:	ADD	A,'A'-'9'-1	;ADD ALPHA BIAS
	AND	00001111B	;MASK TO LOWER NYBBLE
	OR	'A'-1		;CONVERT TO ASCII
BINHED:	CALL	DSPCHR-O	;DISPLAY THE CHARACTER
	INC	D		;BUMP CHARACTER COUNTER
	LD	A,D		;GET THE COUNT TO A
	CP	2		;TEST IF TWO DIGITS DONE
	JR	Z,BINHEQ	;THEN WE ARE ALL DONE
	LD	A,E		;GET BINARY BYTE TO A
	JR	BINHEL		;THEN DISPLAY LOWER NYBBLE
BINHEQ:	POP	AF		;RECOVER AF REGISTER
	POP	DE		;RECOVER BINARY BYTE
	RET
;
;
; DISPLAY A MESSAGE STRING TERMINATED BY 'CC' CHARACTER
; ENTRY:  HL      - POINTER TO THE STRING
;64B3 (44B3)
DSPMSG:	PUSH	AF		;SAVE ACCUMULATOR AND FLAGS
DSPMSL:	LD	A,(HL)		;GET CHARACTER FROM MESSAGE
	CP	CC		;TEST IF TERMINATOR
	JR	Z,DSPMSX	;EXIT IF STRING END
	CALL	DSPCHR-O	;DISPLAY THE CHARACTER
	INC	HL		;BUMP THE STRING POINTER
	JR	DSPMSL		;THEN LOOP FOR NEXT CHARACTER
DSPMSX:	POP	AF		;RECOVER ACCUMULATOR AND FLAGS
	RET
;
;
; DISPLAY CHARACTER AND SCAN KEYBOARD
; TEST FOR THE 'H' KEY OR THE 'E' KEY. IF THE 'E' KEY IS
; PRESSED THEN WE PROMPT FOR THE 'ENTER' KEY AND THEN RETURN
; TO DOS. IF THE 'H' KEY IS PRESSED, THEN WE HALT AND WAIT FOR
; EITHER THE 'C' KEY OR THE 'E' KEY. IF THE 'C' KEY IS PRESSED,
; THEN WE JUST RETURN. IF THE 'E' KEY IS PRESSED, THEN WE
; PROMPT FOR THE 'ENTER' KEY AND THEN RETURN TO DOS
;64C1 (44C1)
DSPCHR:	PUSH	DE		;SAVE DE REGISTER
	PUSH	IY		;SAVE IY REGISTER
	PUSH	AF		;SAVE AF REGISTER
	CALL	VDCHAR		;DISPLAY CHARACTER
	CALL	KBCHAR		;READ KEYBOARD CHARACTER
	JR	Z,DSPCHX	;DONE IF NO KEYPRESS
	CP	'H'		;TEST FOR THE 'H' KEY
	CALL	Z,EXICON-O	;TEST FOR 'E' OR 'C' KEYS
	CP	'E'		;TEST FOR THE 'E' KEY
	JP	Z,HITENT-O	;RETUR TO DOS IF SO
DSPCHX:	POP	AF		;RECOVER AF REGISTER
	POP	IY		;RECOVER IY REGISTER
	POP	DE		;RECOVER DE REGISTER
	RET
;
;
; WAIT FOR A KEYPRESS AND THEN CLEAR THE SCREEN (UNUSED)
; EXIT:   A       - PRESSED KEYBOARD KEY
;64DC (44DC)
KEYCLS:	CALL	KBCHAR		;GET KEYBOARD CHARACTER
	OR	A		;TEST IF ANY KEYPRESS
	JR	Z,KEYCLS	;LOOP UNTIL KEYPRESS
	PUSH	AF		;SAVE THE CHARACTER
	CALL	CLRSCR-O	;CLEAR DISPLAY SCREEN
	POP	AF		;RECOVER CHARACTER
	RET
;
;
; COMPUTE ROM CHECKSUM
; ENTRY:  DE      - POINTER INTO ROM
; EXIT:   DE      - CHECKSUM WORD
;         HL      - POINTER TO NEXT ROM OR RAM
;64E8 (44E8)
SUMCHK:	LD	HL,0		;ZERO CHECKSUM WORD
	LD	B,L		;ZERO B REGISTER
SUMCHL:	LD	A,(DE)		;GET A BYTE FROM ROM
	LD	C,A		;COPY BYTE TO C
	ADD	HL,BC		;ADD BYTE TO CHECKSUM
	INC	DE		;BUMP ROM POINTER
	LD	A,D		;GET POINTER MSB TO A
	AND	00001111B	;MASK TO ROM BOUNDARY
	OR	E		;TEST IF ALL ROM SUMMED
	JR	NZ,SUMCHL	;LOOP UNTIL IT IS
	EX	DE,HL		;SWAP CHECKSUM AND POINTER
	OR	A		;CLEAR CARRY FLAG
	RET
;
;
; DISPLAY ERROR ADDRESS, TEST BYTE AND MEMORY BYTE
; ENTRY:  A       - BYTE READ FROM MEMORY
;         D       - TEST BYTE
;         HL      - MEMORY ADDRESS
;64F9 (44F9)
RAMERR:	PUSH	BC		;SAVE BC REGISTER
	PUSH	DE		;SAVE TEST BYTE
	PUSH	AF		;SAVE MEMORY BYTE
	PUSH	HL		;SAVE ERROR ADDRESS
	LD	A,0		;ZERO ACCUMULATOR
	LD	(UNULOC-O),A	;ZERO UNUSED LOCATION
	LD	HL,MEMERM-O	;MEMORY ERROR MESSAGE
	CALL	DSPMSG-O	;DISPLAY ERROR MESSAGE
	POP	HL		;RECOVER ERROR ADDRESS
	PUSH	HL		;RE-SAVE ERROR ADDRESS
	LD	E,H		;GET ADDRESS MSB TO E
	CALL	BINHEX-O	;DISPLAY ADDRESS MSB
	LD	E,L		;GET ADDRESS LSB TO E
	CALL	BINHEX-O	;DISPLAY ADDRESS LSB
	LD	HL,SHOULM-O	;'SHOULD BE' ERROR STRING
	CALL	DSPMSG-O	;DISPLAY ERROR MESSAGE
	LD	E,D		;GET TEST BYTE TO E
	CALL	BINHEX-O	;DISPLAY THE TEST BYTE
	LD	HL,WASERM-O	;POINT AT 'WAS' MESSAGE
	CALL	DSPMSG-O	;DISPLAY ERROR MESSAGE
	POP	HL		;RECOVER ERROR ADDRESS
	POP	AF		;RECOVER MEMORY BYTE READ
	PUSH	AF		;RE-SAVE MEMORY BYTE
	PUSH	HL		;RE-SAVE ERROR ADDRESS
	LD	E,A		;GET MEMORY BYTE TO E
	CALL	BINHEX-O	;DISPLAY THE MEMORY BYTE
	PUSH	AF		;SAVE THE MEMORY BYTE
	LD	A,CR		;LOAD NEWLINE CHARACTER
	CALL	DSPCHR-O	;DISPLAY THE NEWLINE
	POP	AF		;RECOVER MEMORY BYTE
	BIT	7,H		;TEST IF EXPANSION INTERFACE
	JR	NZ,BADEXP	;THEN EXPANSION ERROR STRING
	CALL	BADCAS-O	;ELSE SHOW MAIN STRING
RAMERX:	LD	A,CR		;LOAD NEWLINE CHARACTER
	CALL	DSPCHR-O	;DISPLAY THE NEWLINE
	POP	HL		;RECOVER MEMORY ADDRESS
	POP	AF		;RECOVER MEMORY BYTE
	POP	DE		;RECOVER TEST BYTE
	POP	BC		;RECOVER BC REGISTER
	RET
;
;
; BAD MEMORY IN EXPANSION INTERFACE
;6542 (4542)
BADEXP:	PUSH	BC		;SAVE BC REGISTER
	PUSH	AF		;SAVE MEMORY BYTE
	PUSH	DE		;SAVE TEST BYTE
	PUSH	HL		;SAVE MEMORY ADDRESS
	LD	HL,BADEXM-O	;BAD EXPANSION INTERFACE RAM
	CALL	DSPMSG-O	;DISPLAY THE ERROR MESSAGE
	POP	HL		;RECOVER MEMORY ADDRESS
	PUSH	HL		;RE-SAVE MEMORY ADDRESS
	XOR	D		;CLEAR CARRY FLAG
	LD	D,A		;GET MEMORY BYTE TO D
	LD	E,1		;INIT FOR RAM CHIP Z01
	LD	B,8		;THERE ARE EIGHT IC'S
	BIT	6,H		;TEST IF MORE THAN 16K
	CALL	Z,UPDAIC-O	;THEN UPDATE IC NUMBER
NEXTIC:	RL	D		;ROTATE BIT TO CARRY
	CALL	C,DISPIC-O	;DISPLAY CHIP NUMBER
	INC	E		;BUMP THE CHIP NUMBER
	DEC	B		;DECREMENT CHIP COUNTER
	JR	NZ,NEXTIC	;LOOP UNTIL ALL DISPLAYED
	POP	HL		;RECOVER MEMORY ADDRESS
	POP	DE		;RECOVER TEST BYTE
	POP	AF		;RECOVER MEMORY BYTE
	POP	BC		;RECOVER BC REGISTER
	JR	RAMERX		;THEN EXIT THE ROUTINE
;
;
; DISPLAY RAM CHIP HEADER ' Z' AND NUMBER
; ENTRY:  A       - INTEGRATED CIRCUIT NUMBER
;6568 (4568)
DISPIC:	PUSH	AF		;SAVE CHIP NUMBER
	LD	A,' '		;LOAD ASCII SPACE CHARACTER
	CALL	DSPCHR-O	;DISPLAY THE CHARACTER
	LD	A,'Z'		;LOAD ASCII CHIP HEADER
	CALL	DSPCHR-O	;DISPLAY THE CHARACTER
	POP	AF		;RECOVER CHIP NUMBER
	CALL	BINHEX-O	;DISPLAY THE CHIP NUMBER
	RET
;
;
; WAIT FOR EITHER 'E' FOR EXIT OR 'C' FOR CONTINUE
;6578 (4578)
EXICON:	CALL	KBCHAR		;READ KEYBOARD CHARACTER
	CP	'E'		;TEST IF EXIT REQUESTED
	JP	Z,HITENT-O	;THEN WE RE-BOOT SYSTEM
	CP	'C'		;TEST IF CONTINUE WANTED
	RET	Z		;THEN WE JUST RETURN
	JR	EXICON		;LOOP UNTIL EITHER CHARACTER
;
;
; BAD MEMORY IN KEYBOARD CASE
; THIS CODE CONTAINS ONE FATAL ERROR WHICH 'PATCHG' CORRECTS
; SAVED REGISTERS ARE NEVER RESTORED SO WE END UP IN LIMBO
;6585 (4585)
BADCAS:	PUSH	BC		;SAVE BC REGISTER
	PUSH	AF		;SAVE MEMORY BYTE
	PUSH	DE		;SAVE TEST BYTE
	PUSH	HL		;SAVE MEMORY ADDRESS
	LD	HL,BADKYM-O	;BAD RAM IN KEYBOARD CASE
	CALL	DSPMSG-O	;DISPLAY THE ERROR MESSAGE
	XOR	D		;CLEAR CARRY FLAG
	LD	D,A		;GET MEMORY BYTE TO D
	RR	D		;ROTATE BIT TO CARRY
	LD	E,17H		;INIT FOR RAM CHIP Z17
	CALL	C,DISPIC-O	;DISPLAY IC NUMBER
	RR	D		;ROTATE BIT TO CARRY
	LD	E,16H		;INIT FOR RAM CHIP Z16
	CALL	C,DISPIC-O	;DISPLAY IC NUMBER
	RR	D		;ROTATE BIT TO CARRY
	LD	E,18H		;INIT FOR RAM CHIP Z18
	CALL	C,DISPIC-O	;DISPLAY IC NUMBER
	RR	D		;ROTATE BIT TO CARRY
	LD	E,19H		;INIT FOR RAM CHIP Z19
	CALL	C,DISPIC-O	;DISPLAY IC NUMBER
	RR	D		;ROTATE BIT TO CARRY
	LD	E,15H		;INIT FOR RAM CHIP Z15
	CALL	C,DISPIC-O	;DISPLAY IC NUMBER
	RR	D		;ROTATE BIT TO CARRY
	LD	E,20H		;INIT FOR RAM CHIP Z20
	CALL	C,DISPIC-O	;DISPLAY IC NUMBER
	RR	D		;ROTATE BIT TO CARRY
	LD	E,14H		;INIT FOR RAM CHIP Z14
	CALL	Z,DISPIC-O	;DISPLAY IC NUMBER
	RR	D		;ROTATE BIT TO CARRY
	LD	E,13H		;INIT FOR RAM CHIP Z13
	CALL	Z,DISPIC-O	;DISPLAY IC NUMBER
;
	If	PATCHG		;MY OWN PATCH
	 POP	HL		;RECOVER MEMORY ADDRESS
	 POP	DE		;RECOVER TEST BYTE
	 POP	AF		;RECOVER MEMORY BYTE
	 POP	BC		;RECOVER BC REGISTER
	EndIf			;END OF PATCH
;
	RET
;
;
; UPDATE IC NUMBER FOR LOCATION IN EXPANSION INTERFACE
; ENTRY:  B       - BIT COUNTER
;         D       - MEMORY BYTE
; EXIT:   B       - DECREMENTED
;         D       - ROTATED ONE BIT TO THE LEFT
;         E       - 10H
;65CA (45CA)
UPDAIC:	RL	D		;ROTATE BIT TO CARRY
	LD	E,09H		;INIT FOR RAM CHIP Z09
	CALL	C,DISPIC-O	;DISPLAY RAM CHIP NUMBER
	DEC	B		;DECREMENT CHIP COUNTER
	LD	E,10H		;INIT FOR RAM CHIP Z10
	RET
;
;
; CLEAR SCREEN AND TURN CURSOR ON
;65D5 (45D5)
CLRSCR:	LD	A,HO		;LOAD HOME
	CALL	VDCHAR		;MOVE DISPLAY CURSOR HOME
	LD	A,CE		;LOAD CLEAR TO SCREEN END
	CALL	VDCHAR		;CLEAR TO SCREEN END
	LD	A,ON		;LOAD CURSOR ON
	CALL	VDCHAR		;TURN THE CURSOR ON
	RET
;
;
; TEST MAIN AND EXPANSION INTERFACE RANDOM ACCESS MEMORY
;65E5 (45E5)
RAMTST:	LD	HL,0		;INIT RAM TEST ADDRESS
TOPGET:	DEC	HL		;BACKUP TEST ADDRESS
	LD	A,(HL)		;GET BYTE FROM THE RAM
	CPL			;COMPLEMENT THE BYTE
	LD	(HL),A		;STORE BYTE IN MEMORY
	XOR	(HL)		;FLIP ALL STORED BITS
	JR	NZ,TOPGET	;LOOP IF NO RAM THERE
	LD	(TESTAD-O),HL	;SAVE TOP OF RAM ADDRESS
	EXX			;SWAP TO ALTERNATE REGISTERS
	LD	A,33		;INITIALIZE LOOP COUNTER
	LD	B,A		;COPY LOOP COUNTER TO B
	EXX			;SWAP TO MAIN REGISTERS
	LD	SP,(TESTAD-O)	;GET RAM TEST ADDRESS TO SP
	INC	SP		;BUMP THE TEST ADDRESS
	XOR	A		;ZERO ACCUMULATOR
	LD	(TESTBT-O),A	;ZERO TEST BYTE TWO
	LD	BC,0		;ZERO BC REGISTER
	LD	E,C		;ZERO E REGISTER
NEWTBY:	LD	A,C		;GET TEST BYTE TO A
	LD	(TESTBY-O),A	;SAVE THE TEST BYTE
	EXX			;SWAP TO ALTERNATE REGISTERS
	DEC	B		;DECREMENT LOOP COUNTER
	JP	Z,RAMGUD-O	;TESTING DONE AND RAM IS GOOD
	EXX			;SWAP TO MAIN REGISTERS
	CALL	BINHEX-O	;DISPLAY BYTE IN HEXADECIMAL
TSTNXT:	LD	HL,(TESTAD-O)	;GET RAM TEST ADDRESS TO HL
	INC	HL		;BUMP THE TEST ADDRESS
BACKAD:	DEC	HL		;BACKUP RAM TEST ADDRESS
	LD	A,(TESTBY-O)	;GET TEST BYTE TO ACCUMULATOR
	XOR	L		;EXCLUSIVE OR WITH ADDRESS LSB
	XOR	H		;EXCLUSIVE OR WITH ADDRESS MSB
	LD	D,A		;COPY RESULT TO D REGISTER
	DEC	HL		;BACKUP MEMORY ADDRESS
	LD	A,(TESTBY-O)	;GET TEST BYTE TO ACCUMULATOR
	XOR	L		;EXCLUSIVE OR WITH ADDRESS LSB
	XOR	H		;EXCLUSIVE OR WITH ADDRESS MSB
	LD	E,A		;COPY RESULT TO E REGISTER
	PUSH	DE		;SAVE THE BYTE PAIR
	LD	A,(LOWADH-O)	;GET ADDRESS BYTE MSB
	CP	H		;TEST IF SAME AS CURRENT
	JR	NZ,BACKAD	;LOOP BACK IF NOT THE SAME
	LD	A,(LOWADL-O)	;GET ADDRESS BYTE LSB
	CP	L		;TEST IF SAME AS CURRENT
	JR	NZ,BACKAD	;LOOP BACK IF NOT THE SAME
	LD	HL,(LOWADR-O)	;GET THE ADDRESS TO HL
	DEC	HL		;BACKUP THE ADDRESS
NOTSAD:	INC	HL		;BUMP THE TEST ADDRESS
	LD	A,(TESTBY-O)	;GET TEST BYTE TO A
	XOR	L		;EXCLUSIVE OR WITH ADDRESS LSB
	XOR	H		;EXCLUSIVE OR WITH ADDRESS MSB
	LD	E,A		;COPY RESULT TO E REGISTER
	LD	(BYTEST-O),A	;SAVE THE TEST BYTE
	INC	HL		;BUMP MEMORY ADDRESS
	LD	A,(TESTBY-O)	;GET TEST BYTE TO A
	XOR	H		;EXCLUSIVE OR WITH ADDRESS MSB
	XOR	L		;EXCLUSIVE OR WITH ADDRESS LSB
	LD	D,A		;COPY RESULT TO D REGISTER
	LD	(TSTBYT-O),A	;SAVE THE TEST BYTE
	LD	(MEMADR-O),HL	;SAVE THE MEMORY ADDRESS
	EX	DE,HL		;SWAP TEST BYTES TO HL
	LD	A,L		;TEST FIRST TEST BYTE
	CPL			;COMPLEMENT THE BYTE
	LD	L,A		;UPDATE FIRST TEST BYTE
	LD	A,H		;GET SECOND TEST BYTE
	CPL			;COMPLEMENT THE BYTE
	LD	H,A		;UPDATE SECOND TEST BYTE
	INC	HL		;BUMP TEST BYTE WORD
	XOR	A		;CLEAR CARRY FLAG
	POP	DE		;RECOVER SAVED BYTE PAIR
	ADC	HL,DE		;TEST IF THE VALUES MATCH
	JR	NZ,NOMATC	;SKIP IF MISMATCHING VALUES
NXTEST:	LD	HL,(MEMADR-O)	;GET MEMORY ADDRESS TO HL
	LD	A,(TESTAH-O)	;RAM TEST ADDRESS MSB TO A
	CP	H		;TEST IF SAME ADDRESS
	JR	NZ,NOTSAD	;LOOP FOR NEXT IF NOT
	LD	A,(TESTAL-O)	;RAM TEST ADDRESS LSB TO A
	CP	L		;TEST IF SAME ADDRESS
	JR	NZ,NOTSAD	;LOOP FOR NEXT IF NOT
	LD	A,(TESTBY-O)	;GET TEST BYTE TO A
	CPL			;COMPLEMENT THE TEST BYTE
	LD	(TESTBY-O),A	;SAVE UPDATED TEST BYTE
	LD	A,(TESTBT-O)	;GET TEST BYTE TO A
	CPL			;COMPLEMENT THE TEST BYTE
	LD	(TESTBT-O),A	;SAVE UPDATED TEST BYTE
	AND	A		;TEST IF BYTE IS ZERO
	JR	Z,ISMATC	;THEN WE CONTINUE
	JR	TSTNXT		;ELSE LOOP FOR NEXT
ISMATC:	INC	BC		;BUMP THE TEST BYTE
	JR	NEWTBY		;LOOP FOR NEXT TEST
NOMATC:	DEC	SP		;BACKUP MEMORY ADDRESS
	DEC	SP		;BACKUP THE ADDRESS AGAIN
	LD	HL,(MEMADR-O)	;GET MEMORY ADDRESS TO HL
	DEC	HL		;BACKUP THE ADDRESS
	LD	A,(BYTEST-O)	;GET TEST BYTE TO A
	XOR	E		;TEST IF BYTE MATCH
	LD	A,(BYTEST-O)	;-GET TEST BYTE TO A-
	LD	A,D		;GET MEMORY BYTE TO A
	LD	(MEMBYT-O),A	;STORE AS MEMORY BYTE
	JR	NZ,MERONE	;REPORT ERROR IF MISMATCH
	LD	SP,(MEMADR-O)	;GET MEMORY ADDRESS TO SP
	DEC	SP		;BACKUP THE ADDRESS
	INC	HL		;BUMP THE MEMORY ADDRESS
	LD	A,(MEMBYT-O)	;GET MEMORY BYTE TO A
	LD	D,A		;COPY THE BYTE TO D
	LD	A,(TSTBYT-O)	;GET TEST BYTE TO A
	XOR	D		;TEST IF BYTES MATCH
	JR	NZ,MERTWO	;DISPLAY ERROR IF MISMATCH
TSTCNT:	LD	SP,(MEMADR-O)	;GET MEMORY ADDRESS TO SP
	INC	SP		;BACKUP THE ADDRESS
	JR	NXTEST		;THEN GO TO NEXT TEST
MERONE:	LD	SP,STKTWO	;POINT AT SECONDARY STACK
	LD	A,(BYTEST-O)	;GET TEST BYTE TO A
	LD	D,A		;COPY THE BYTE TO D
	LD	A,E		;GET MEMORY BYTE TO A
	CALL	RAMERR-O	;DISPLAY RAM ERROR MESSAGE
	JR	TSTCNT		;THEN CONTINUE TESTING
MERTWO:	LD	SP,STKTWO	;POINT AT SECONDARY STACK
	LD	A,(TSTBYT-O)	;GET TEST BYTE TO A
	LD	D,A		;COPY THE BYTE TO D
	LD	A,(MEMBYT-O)	;GET MEMORY BYTE TO A
	CALL	RAMERR-O	;DISPLAY RAM ERROR MESSAGE
	JR	TSTCNT		;THEN CONTINUE TESTING
;
;
; CHECKSUM ERROR IN BASIC ROM A - DISPLAY MESSAGE AND RE-BOOT
;66C4 (46C4)
CKERRA:	LD	HL,AERROM-O	;POINT AT ERROR STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	JR	HITENT		;WAIT FOR ENTER AND RE-BOOT
;
;
; CHECKSUM ERROR IN BASIC ROM B _ DISPLAY MESSAGE AND RE-BOOT
;66CC (46CC)
CKERRB:	LD	HL,BERROM-O	;POINT AT ERROR STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	JR	HITENT		;WAIT FOR ENTER AND RE-BOOT
;
;
; CHECKSUM ERROR IN BASIC ROM C _ DISPLAY MESSAGE AND RE-BOOT
;66D4 (46D4)
CKERRC:	LD	HL,CERROM-O	;POINT AT ERROR STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
	JR	HITENT		;WAIT FOR ENTER AND RE-BOOT
;
;
; RAM TEST PASSED - DISPLAY MESSAGE AND RE-BOOT
;66DC (46DC)
RAMGUD:	LD	HL,RAMPAS-O	;POINT AT PASSED STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
;
;
; PROMPT AND WAIT FOR 'ENTER' KEY PRESS, THEN RE-BOOT SYSTEM
;66E2 (46E2)
HITENT:	LD	HL,HITENM-O	;POINT AT PROMPT STRING
	CALL	MSGOUT-O	;DISPLAY THE MESSAGE
;
;
; WAIT FOR 'ENTER' KEY PRESS, THEN RE-BOOT SYSTEM
;66E8 (46E8)
WENTER:	LD	A,(KROSEV)	;LOAD CONTROL KEY ROW
	RRCA			;ROTATE 'ENTER' BIT TO CARRY
	JR	NC,WENTER	;LOOP UNTIL KEY IS PRESSED
	JP	RBASIC		;THEN RE-BOOT SYSTEM
;
;
; MESSAGES
;66F1 (46F1)
AERROM	Db	'ROM A ERROR',CR
BERROM	Db	'ROM B ERROR',CR
CERROM	Db	'ROM C ERROR',CR
ROMPAS	Db	'ROM TEST PASSED',CR
RAMPAS	Db	'RAM TEST PASSED',CR
HITENM	Db	'         HIT "ENTER" TO CONTINUE ',CR
MEMERM	Db	'MEMORY ERROR AT ',CC
SHOULM	Db	' SHOULD BE ',CC
WASERM	Db	' WAS ',CC
BADEXM	Db	'BAD RAM IN EXPANSION INTERFACE: ',CC
BADKYM	Db	'BAD RAM IN KEYBOARD CASE: ',CC
;
;
; STORAGE
;67B6 (47B6)
TESTAD	Dw	-1		;RAM TEST ADDRESS
TESTAL	Equ	$-2		;RAM TEST ADDRESS LSB
TESTAH	Equ	$-1		;RAM TEST ADDRESS MSB
TESTBT	Db	-1		;BYTE WRITTEN TO MEMORY
TESTBY	Db	-1		;BYTE WRITTEN TO MEMORY
LOWADR	Dw	ADRLOW		;LOWEST TEST ADDRESS
LOWADL	Equ	$-2		;LOWEST TEST ADDRESS LSB
LOWADH	Equ	$-1		;LOWEST TEST ADDRESS MSB
BYTEST	Db	-1		;BYTE WRITTEN TO MEMORY
TSTBYT	Db	-1		;BYTE WRITTEN TO MEMORY
MEMADR	Dw	-1		;MEMORY ADDRESS STORAGE
MEMBYT	Dw	-1		;BYTE READ FROM MEMORY
UNULOC	Db	-1		;UNUSED LOCATION
;
;
; FILLER BYTES ONLY NEEDED FOR CODE MATCH
;
	Db	-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
;
;
; DEFINE LENGTH OF CODE TO BE RELOCATED
;
CODLEN	Equ	$-MAINEN		;DEFINE THE LENGTH
;
;
; MORE FILLER BYTES ONLY NEEDED FOR CODE MATCH
;
	Db	-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
	Db	-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
;
	End	TEST1A
